nextcloud-libraries/nextcloud-vue

src/components/DatetimePicker/index.scss

Correction of background color in table header

bg color correction

---

LICENSE
packages/webpack4-template-simple/template/src/App.vue
packages/webpack4-template-simple/template/src/main.js
src/components/AppNavigation/AppNavigation.vue
src/components/AppNavigation/AppNavigationItem.vue
src/components/AppNavigation/index.js
src/components/DatetimePicker/index.js
src/components/Multiselect/index.js
src/components/PopoverMenu/PopoverMenu.vue
src/components/PopoverMenu/PopoverMenuItem.vue
src/components/PopoverMenu/index.js
src/components/index.js
src/index.js

Copyright typo fix

---

README.md
greenkeeper.json

Damn, I thought I was on my fork!!! :see_no_evil:

Revert "Greenkeeper/initial"

---

src/components/AppNavigation/AppNavigationItem.vue

Fixes: https://github.com/nextcloud/server/issues/11923

Add title attribute for app navigation items.

---

src/components/Action/Action.vue
src/components/Action/index.js
src/components/AppNavigation/AppNavigationItem.vue

Action component

---

src/components/Multiselect/Multiselect.vue

Fix check on single value. :man_facepalming: 
We do not want the slot on single selects.

Fix multiselect slot and title formatter

---

src/components/AppNavigation/AppNavigation.vue

Allow disabled state for the new button

---

src/components/AppNavigation/AppNavigationItem.vue

Ref https://docs.nextcloud.com/server/14/developer_manual/design/navigation.html#collapsible-entry
Ref https://github.com/nextcloud/mail/pull/1303

Add dedicated collapse button to app navigation items

---

src/components/DatetimePicker/index.scss

|![capture d ecran_2018-11-20_08-34-53](https://user-images.githubusercontent.com/14975046/48758685-305b9c00-eca1-11e8-83c5-74be5ea13796.png)|![capture d ecran_2018-11-20_08-34-59](https://user-images.githubusercontent.com/14975046/48758686-305b9c00-eca1-11e8-9dc8-160439fdd5b6.png)|

Fix flex order on datepicker headers arrow buttons

---

src/components/Avatar/Avatar.vue

The browser can perfectly figure out itself what avatar to show.
As a bonus if you now start zooming in the browser will fetch a higer
resolution avatar if needed.
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

Use srcset for avatars

---

.eslintrc.js
src/components/Action/Action.vue
src/components/AppNavigation/AppNavigation.vue
src/components/AppNavigation/AppNavigationItem.vue
src/components/Avatar/Avatar.vue
src/components/Multiselect/AvatarSelectOption.vue
src/components/Multiselect/Multiselect.vue
src/components/PopoverMenu/PopoverMenuItem.vue

Fix linting

---

src/components/PopoverMenu/PopoverMenuItem.vue

this allows to highlight the selected entry based on the active class if item.active === true
fixes #128
Signed-off-by: Jonas Sulzer <jonas@violoncello.ch>

"active" class to popover-menu action entries

---

src/components/Multiselect/Multiselect.vue

No need to register the scope if doesn't exists

Fixed scoped multiselect

---

src/components/Multiselect/index.scss

Allow above multiselect

---

src/components/Avatar/Avatar.vue

allow to overwrite the default avatar tooltip message

---

src/components/Multiselect/AvatarSelectOption.vue

allow to set isNoUser option for avatar in MultiSelect component

---

src/components/Multiselect/Multiselect.vue

Also make sure user-select layout is not requested

---

src/components/AppContent/AppContent.vue

As discussed in #227, I've added two new props for the component `AppContent` in order to set CSS classes for navigation and content.
Fixes #227.

add props for navigation class and content class

---

src/components/AppNavigationSettings/AppNavigationSettings.vue

See https://github.com/nextcloud/contacts/issues/903

Fix appsettings toggle

---

src/components/PopoverMenu/PopoverMenuItem.vue

* have no `action` specified but want to make the entry active doesn't work before this

Also allow active elments for non-buttons & show pointer on buttons

---

.travis.yml
Makefile
package-lock.json
package.json
src/components/PopoverMenu/PopoverMenuItem.vue
webpack.common.js

Make things ready for #273 
It seems to be an issue with stylelint. We might have to check on it later :thinking:

Cleanup unused deps and broken peers + bump webpack

---

package-lock.json
package.json
src/components/Modal/Modal.vue

Add modal touch events

---

src/components/Multiselect/index.scss

Hide limit on active

---

src/components/AppNavigationItem/AppNavigationItem.vue

Fix navigation menu with two or more actions

---

package-lock.json
package.json
src/components/Modal/Modal.vue

Use visibility instead of display for the modal clear view

---

src/components/Modal/Modal.vue

Allow to disable swipe events on modal

---

src/components/AppNavigationItem/AppNavigationItem.vue

let the comments reflect the changes from #291

fix comments

---

src/components/Modal/Modal.vue

Before & after, please review @nextcloud/designers

Darken modal mask background for better focus

---

package-lock.json
src/components/Modal/Modal.vue

| big | medium | normal |
|:---------:|:---------:|:------:|
|![dev skjnldsv com_apps_vueexample_](https://user-images.githubusercontent.com/14975046/54285519-6bf8d980-45a2-11e9-9423-223bf5609e99.png)|![dev skjnldsv com_apps_vueexample_ (1)](https://user-images.githubusercontent.com/14975046/54285520-6c917000-45a2-11e9-9227-b4e5f0c5254a.png)|![dev skjnldsv com_apps_vueexample_ (2)](https://user-images.githubusercontent.com/14975046/54285523-6d2a0680-45a2-11e9-99b5-a2af0639d032.png)|
I'm not convinced on the positions of the navigation. A bit of help @jancborchardt ? :wink:

Add modal sizes

---

src/components/Modal/Modal.vue

Enhancements on modal design slideshow

---

src/components/Modal/Modal.vue

Fix https://github.com/nextcloud/viewer/issues/50

Reset timer on manual next

---

src/components/AppNavigationNew/AppNavigationNew.vue

This allows for using also array or object syntax for CSS classes which is required, if the class has to be determined dynamically.

AppNavigationNew: fix type of buttonClass

---

src/components/Modal/Modal.vue

We might not need a close icon, we need to have an official way to disable it :)

Add canClose prop

---

src/mixins/index.js
src/mixins/isMobile.js
webpack.common.js

Add isMobile mixin

---

src/components/PopoverMenu/PopoverMenuItem.vue

Add download option on popovermenu link

---

src/mixins/isMobile/index.js

* Use a real method for data to have access to `this`
* Rename private methods with a _ prefix

Fix the isMobile mixin

---

src/components/AppSidebar/AppSidebar.vue
src/components/AppSidebar/index.js
src/components/index.js

Same motivation as https://github.com/nextcloud/nextcloud-vue/pull/337

Add a component for #app-sidebar

---

src/components/Modal/Modal.vue

Fix modal this.mc typo

---

.eslintrc.js
src/assets/iconfont/menu.svg
src/components/AppContent/AppContent.vue
src/components/AppNavigation/AppNavigation.vue
src/components/AppNavigationToggle/AppNavigationToggle.vue
src/components/AppNavigationToggle/index.js

There is one glitch when the menu nav is hidden again for the first time by clicking the icon: it shows blank space instead of moving the content to the right. @skjnldsv could you have a look and work your magic? :)

Add a navigation toggle and vue-slideout

---

src/components/AppNavigationSettings/AppNavigationSettings.vue

see #334.
For now without animation like in server. I had some problems in realizing the animation. Any help is appreciated, but we can add this later.

fix settings toggle

---

src/components/Avatar/Avatar.vue

Fix #134 
`<Avatar user="admin" status="negative" [status-color="0082c9"]></Avatar>`
| Positive | Neutral | Negative |
|:---------:|:------:|:------:|
|![dev skjnldsv com_apps_vueexample_ (1)](https://user-images.githubusercontent.com/14975046/56116082-41b18780-5f65-11e9-88e5-4d6c6338aabb.png)|![dev skjnldsv com_apps_vueexample_ (3)](https://user-images.githubusercontent.com/14975046/56116086-4413e180-5f65-11e9-8ed6-491f2a7a4230.png)|![dev skjnldsv com_apps_vueexample_ (2)](https://user-images.githubusercontent.com/14975046/56116093-45dda500-5f65-11e9-9af1-0eb689c65e9a.png)|

Add avatar status support

---

src/mixins/isFullScreen/index.js

Similar to #324 
@nextcloud/vue

Add isFullScreen mixin

---

Makefile

`make clean` should clean all generated files.
related to #346.

clean generated fonts

---

src/components/AppSidebar/AppSidebar.vue

Don't show the button if there are no actions!

AppSidebar: show actions only if slot is filled

---

src/components/AppContent/AppContent.vue

Removed will-change

---

src/mixins/isFullScreen/index.js
src/mixins/isMobile/index.js

Fix fullscreen and mobile mode detection

---

src/components/Modal/Modal.vue

Fix modal actions and header display

---

src/components/Avatar/Avatar.vue

Accessibility and show avatar menu indicator on hover

---

src/components/ActionLink/ActionLink.vue

Add back download and validate ActionLink props

---

src/components/ActionLink/ActionLink.vue

Also allow relative url

---

src/components/Modal/Modal.vue

Add tooltip title, accessibility & css cleanup

---

src/components/PopoverMenu/PopoverMenuItem.vue

Properly style disabled buttons on hover

---

src/directives/Tooltip/index.js
src/directives/Tooltip/index.scss

|![Kazam_screenshot_00002](https://user-images.githubusercontent.com/14975046/57715868-f976a980-7677-11e9-84d6-a2f1a53fb702.png)|![Kazam_screenshot_00004](https://user-images.githubusercontent.com/14975046/57715873-fa0f4000-7677-11e9-98c8-54be3d14cd5a.png)|
- Fix positionning
- Simplified css from official tooltip css

Fix tooltip design and scoping

---

src/components/Actions/Actions.vue
src/utils/IsOutOfViewport.js

Automatically shift popovermenu if out of window

---

src/components/Actions/Actions.vue

Shadow was a bit too strong and not enough contrasted on dark bg :)
| White | Dark |
|![Peek 16-05-2019 08-05](https://user-images.githubusercontent.com/14975046/57830270-e0721380-77b1-11e9-8143-ba5430d5c079.gif)|![Peek 16-05-2019 08-06](https://user-images.githubusercontent.com/14975046/57830272-e0721380-77b1-11e9-9f6f-071a436000f4.gif)|

Fix actions menu grey focus colour

---

src/components/ActionCheckbox/ActionCheckbox.vue
src/components/ActionInput/ActionInput.vue

Fix action input width and randomid

---

src/mixins/actionGlobal.js

Does anyone have a better solution?
@nextcloud/vue

Make action text reactive

---

src/components/Multiselect/EllipsisedOption.vue

Display Multiselect white spaces on first part too

---

package-lock.json
src/components/AppSidebar/AppSidebar.vue

Emit onFigureClick event and jsDoc bump

---

src/components/AppSidebarTab/AppSidebarTab.vue

Add AppSidebarTab component name

---

src/components/AppSidebar/AppSidebar.vue

Properly validate sidebar tabs and warn

---

src/components/AppNavigationToggle/AppNavigationToggle.vue

See https://github.com/nextcloud/server/pull/15913

Fix mobile toggle over app-content

---

src/components/AppNavigationCaption/AppNavigationCaption.vue
src/components/AppNavigationCaption/index.js
src/components/AppNavigationItem/AppNavigationItem.vue
src/components/index.js

see https://github.com/nextcloud/notes/pull/313#issuecomment-499928900

new component AppNavigationCaption

---

src/assets/variables.scss
src/components/Actions/Actions.vue
src/components/Modal/Modal.vue

Fix actions white background

---

src/components/AppNavigationItem/AppNavigationItem.vue

ref nextcloud/server#16076
>Apps with update should have the counter inside a primary color bubble for attention
@skjnldsv please check this out, @nickvergessen helped me to fix this bug.

Allow highlighted counter in app navigation

---

package-lock.json
src/assets/variables.scss
src/components/Actions/Actions.vue
src/components/AppNavigationItem/AppNavigationItem.vue
src/components/AppSidebar/AppSidebar.vue

Add AppSidebar compact mode

---

src/assets/action.scss
src/components/ActionButton/ActionButton.vue
src/components/ActionLink/ActionLink.vue
src/components/Actions/Actions.vue

Fix actions documentation

---

src/components/ActionCheckbox/ActionCheckbox.vue

Fix actioninput event and disabled styling

---

src/components/AppNavigationCounter/AppNavigationCounter.vue
src/components/AppNavigationCounter/index.js
src/components/AppNavigationItem/AppNavigationItem.vue

AppNavigationItem extensions necessary for talk.

---

src/components/ActionInput/ActionInput.vue
src/components/ActionTextEditable/ActionTextEditable.vue
styleguide/assets/additional.scss

Bind attrs to textarea and input as well and add actioninput docs

---

src/components/ActionInput/ActionInput.vue

|![Capture d’écran_2019-07-26_17-12-21](https://user-images.githubusercontent.com/14975046/61961851-8f0fad00-afc8-11e9-9c12-220f590d8c62.png)|![Capture d’écran_2019-07-26_17-11-41](https://user-images.githubusercontent.com/14975046/61961818-7901ec80-afc8-11e9-9048-57b9f7be526a.png)|

Add and edit placeholder docs for actionInput

---

src/components/Multiselect/AvatarSelectOption.vue
src/components/Multiselect/Multiselect.vue

Add docs to multiselect

---

src/directives/Tooltip/index.js

Signed-off-by: Julius Härtl <jus@bitgrid.net>

Set defaultHtml setting of v-tooltip to false

---

package-lock.json
package.json
src/components/Multiselect/AvatarSelectOption.vue

Automatically bold data from search in user-select template

---

package-lock.json
package.json

remove vuepress-jsdoc

---

src/components/Multiselect/Multiselect.vue

It was not possible prior to 2.6
Now it is https://stackoverflow.com/a/50892881

Forward all slots to multiselect

---

src/components/Multiselect/AvatarSelectOption.vue

Fix default icon size on user-select layout

---

.stylelintrc.js
src/components/Modal/Modal.vue
src/utils/Timer.js

Allow pausing ongoing modal slideshow

---

src/components/ActionInput/ActionInput.vue

That way the keyboard also focus the datepicker  input

Make datepicker focusable

---

src/components/Avatar/Avatar.vue

For https://github.com/nextcloud/text/issues/171

Allow properly settings avatars for guests as well

---

src/components/Modal/Modal.vue

Modal is broken :see_no_evil: 
We cannot clear something that is not yet a timer.
Initial data is null.

Fix modal timeout clear

---

src/directives/Tooltip/index.scss

|![Capture d’écran_2019-08-08_14-27-11](https://user-images.githubusercontent.com/14975046/62930999-d3b78880-bdbd-11e9-95fa-bba2a2bde1da.png)|![Capture d’écran_2019-08-08_14-27-02](https://user-images.githubusercontent.com/14975046/62930997-d3b78880-bdbd-11e9-95f6-758ab4810712.png)|

Fix tooltip positionning

---

src/components/Multiselect/EllipsisedOption.vue

Correctly show option by label if it's a tag

---

src/components/ActionButton/ActionButton.vue
src/components/ActionLink/ActionLink.vue
src/components/ActionRouter/ActionRouter.vue

Do not allow disabled links

---

src/components/DatetimePicker/DatetimePicker.vue

See https://github.com/nextcloud/nextcloud-vue/pull/395#issuecomment-518596537

Fix year/month select on the datepicker

---

src/components/Multiselect/AvatarSelectOption.vue
src/components/Multiselect/EllipsisedOption.vue
src/components/Multiselect/Multiselect.vue
src/mixins/highlightText.js

- cleans methods
- add highlight on EllipsisedOption

Fix highlight on multiselect slots

---

src/components/ActionLink/ActionLink.vue
src/components/ActionRouter/ActionRouter.vue

Remove unused isFocusable computed

---

src/components/Actions/Actions.vue

Fix actions focus querySelector

---

src/components/DatetimePicker/DatetimePicker.vue

Add datetime picker docs

---

src/components/ActionLink/ActionLink.vue
src/components/ActionRouter/ActionRouter.vue

Remove code disabled actions remnants

---

src/components/Actions/Actions.vue

Fix remnants of $children implementation

---

src/utils/ValidateSlot.js

Prevent vnode false positive

---

src/components/ActionRadio/ActionRadio.vue
src/components/ActionRadio/index.js
src/components/Actions/Actions.vue
src/components/index.js
src/utils/GetChildren.js
src/utils/GetParent.js

Add ActionRadio

---

src/components/Popover/Index.js
src/components/Popover/Popover.vue
src/components/Popover/index.js
src/components/index.js

Create Popover component

---

src/components/Popover/Popover.vue

Fix typo: plgin -> plugin

---

src/components/Multiselect/Multiselect.vue

Allow auto match from value if useing track-by

---

src/components/PopoverMenu/PopoverMenu.vue

Mark PopoverMenu component as deprecated

---

src/components/AppSidebar/AppSidebar.vue

Rough example:
|![dev skjnldsv com_apps_files__dir=_ (2)](https://user-images.githubusercontent.com/14975046/66318536-c7fac500-e91b-11e9-9fb2-5a3265dcd466.png)|![dev skjnldsv com_apps_files__dir=_ (1)](https://user-images.githubusercontent.com/14975046/66318535-c7fac500-e91b-11e9-9811-ea70e2fbcb99.png)|

Fix small issues with actions layout in sidebar in compact mode

---

src/components/ColorPicker/ColorPicker.vue

Fix colorpicker docs

---

src/components/Popover/Popover.vue

[V-Tooltip](https://github.com/Akryum/v-tooltip) offers plenty of events, so forward listeners

Forward listeners to V-Popover

---

src/components/DatetimePicker/DatetimePicker.vue

fixes #646 
Slot on the left side, standard icon on right side.

Forward slots to vue2-datepicker

---

package-lock.json
package.json

@nextcloud/vue

---

src/components/AppNavigationSpacer/AppNavigationSpacer.vue

Fix spacer order

---

src/components/AppNavigationItem/AppNavigationItem.vue

Fix icon sizing

---

README.md

Please check @ma12-co @skjnldsv @juliushaertl

Add documentation for development setup

---

src/components/AppNavigationSpacer/AppNavigationSpacer.vue

See https://github.com/nextcloud/nextcloud-vue/pull/656#issuecomment-543130728

Prevent app nav spaacer from shrinking

---

src/components/AppSidebar/AppSidebar.vue

Add appsidebar close button unique class

---

docs/directives.md
docs/index.md
styleguide.config.js

fix package rename in docs

---

package-lock.json
package.json
src/components/Actions/Actions.vue
src/components/AppNavigationItem/AppNavigationItem.vue
src/components/AppNavigationSettings/AppNavigationSettings.vue
src/components/Avatar/Avatar.vue

Backport of https://github.com/nextcloud/nextcloud-vue/pull/675

[stable0-12] Migrate to v-click-outside

---

package-lock.json
package.json

Backport of https://github.com/nextcloud/nextcloud-vue/pull/670

[stable0-12] Fix/@nextcloud/browserslist config

---

styleguide.config.js

- use dev build which makes it a lot faster when building locally
- update git repo url
- use one page per component section instead of one long page with all components

Enhance styleguide config

---

src/components/Actions/Actions.vue
src/components/AppNavigationItem/AppNavigationItem.vue

After https://github.com/nextcloud/nextcloud-vue/pull/675

Fix Actions click outside

---

src/components/ActionLink/ActionLink.vue

Fix ActionLink docs

---

README.md
docs/index.md

For https://www.netlify.com/legal/open-source-policy/
> In exchange for this free service, we request that you place a link to our service on your main page. We have premade badges for your convenience, or you may create your own link.

Add netlify logo

---

src/components/AppNavigationItem/AppNavigationItem.vue

Allow to replace default actions icon of appNavigationItem

---

src/assets/action.scss

fixes #575, see screenshot over there.

fix action's long-text style

---

src/components/AppNavigationItem/AppNavigationItem.vue

- add hint for event
- example: add event
- example: use title which is conform to [documentation](https://docs.nextcloud.com/server/stable/developer_manual/design/navigation.html#undo-entry)

improve docs for undo

---

docs/index.md

fix package rename

---

src/mixins/isMobile/index.js

🐛 FIX: adjust isMobile mixin to match the breakpoint variable

---

src/components/ActionText/ActionText.vue
src/mixins/actionText.js

Allow ActionText components with no icon

---

babel.config.js
package-lock.json
package.json
webpack.common.js

closes #692
Fixes #691
Tested on guests with this branch

Use babel env usage & corejs@3

---

src/utils/IsMobileState.js

fixes #577
uses the idea of @paulschwoerer (https://github.com/nextcloud/nextcloud-vue/issues/577#issuecomment-559399080) Thanks!!! :heart:

fix performance issue in isMobile

---

src/components/Modal/Modal.vue

As discussed in the design group: bring opacity back to .92!

Fix Modal backdrop

---

src/components/Avatar/Avatar.vue

Add ability to choose popovermenu alignment in avatar component

---

src/components/AppSidebar/AppSidebar.vue

fix #747
Allows v-if on appSidebarTabs components

Fix sidebar tabs children reactivity

---

src/components/Actions/Actions.vue

Allow actions to be forced into a menu

---

src/components/AppSidebar/AppSidebar.vue

Allow force actions menu into sidebar

---

package-lock.json
src/components/AppSidebar/AppSidebar.vue

Add missing button to the sidebar input and fix alignments

---

src/components/AppNavigationItem/AppNavigationItem.vue

Add proper hover/focus/active feedbacks to AppNavigationItem

---

.github/workflows/npm-publish.yml

Travis has been failing recently, Let's improve our script :)

Publish with github actions

---

.github/workflows/npm-test.yml
.gitignore
package-lock.json
package.json
src/components/Multiselect/Multiselect.vue
tests/.eslintrc.js
tests/setup.js
tests/unit/components/Multiselect/Multiselect.spec.js

This PR aims to fix the double call of the input callback for the Multiselect. I'd like to add a jest test for this as well.
Since jest is not configured yet for this repo, I wonder whether I should fix the Multiselect bug in a different issue and only set up jest here?
Locally, jest runs fine already, but it's not run by the Github actions yet.

Only fire Multiselect input function once

---

styleguide/global.requires.js

Fix missing OC.getLanguage() in docs

---

.github/workflows/npm-publish.yml

Update npm publish node version and syntax

---

src/components/Modal/Modal.vue

Fix modal slideshow translation import

---

src/components/AppNavigationItem/AppNavigationItem.vue

wip
For https://github.com/nextcloud/mail/pull/2686

Fix forceMenu for one action item

---

src/components/ActionButton/ActionButton.vue
src/components/ActionLink/ActionLink.vue
src/components/ActionRouter/ActionRouter.vue
src/components/Actions/Actions.vue
src/mixins/actionText.js

(This is strictly what I need for talk)

Add ability to set a custom aria-label value for the actions menu button

---

l10n/messages.pot
src/components/Actions/Actions.vue

Fix actions aria labels

---

src/components/Actions/Actions.vue

fix aria-controls

---

src/components/Actions/Actions.vue

Fix opening Actions menu

---

src/assets/iconfont/more.svg

Comply to server's more icon

---

src/components/Breadcrumb/Breadcrumb.vue
src/components/Breadcrumbs/Breadcrumbs.vue

@skjnldsv I thought about your comment to use the Breadcrumb component for the hidden actions menu, it seems this was easier than I thought.
I will enjoy my Sunday now 😉

Use breadcrumb component for hidden actions

---

src/components/Content/Content.vue
styleguide.config.js

The Content doesn't really display properly, because this is of course not meant to be used within a page.
Shall we leave this like that?

Better sections for app containers

---

.gitignore
src/components/DatetimePicker/DatetimePicker.vue
src/components/DatetimePicker/index.scss

We're back to how it was :rocket:

Fix datepicker design regressions

---

src/components/AppNavigation/AppNavigation.vue
src/components/AppNavigationToggle/AppNavigationToggle.vue
src/components/Breadcrumbs/Breadcrumbs.vue

This PR allows the breadcrumbs component to react on toggling the app-navigation.

Adjust breadcrumb size on app-navigation toggle

---

src/components/EmptyContent/EmptyContent.vue
src/components/EmptyContent/index.js

Add empty content component

---

package-lock.json
package.json
src/components/Avatar/Avatar.vue

See https://github.com/nextcloud/documentation/pull/1950

Fix deprecated OC globals

---

src/components/AppNavigation/AppNavigation.vue

Fix animation-quick fallback

---

src/components/Avatar/Avatar.vue

See https://github.com/nextcloud/nextcloud-vue/pull/1030#discussion_r411329088

Don't throw error when getCurrentUser() returns null

---

src/components/Modal/Modal.vue

Increasing only the large size doesnt do anything, since the wrapper for preview and next button stops the modal to extend. So i fixed also the modal wrapper.

Update large modal size

---

README.md

Since this was unclear and led to me being confused as to what the issue was. :)

Clarify that the app needs to be built after linking

---

src/components/Avatar/Avatar.vue

Fix https://github.com/nextcloud/nextcloud-vue/issues/910
Please review @ahstro @ChristophWurst @GretaD @ma12-co as this is most present in Mail and Talk. :)

Remove loading spinner from avatar as it makes everything seem slow, fix #910

---

src/components/Actions/Actions.vue

Add primary and title option to Actions

---

styleguide/assets/variables.css

Adjusting as per server pull request https://github.com/nextcloud/server/pull/20853

Fix color-text-maxcontrast not passing WCAG AA

---

src/directives/Tooltip/index.scss
styleguide.config.js
styleguide/assets/font.css
styleguide/assets/variables.css

Just cleaning up the old references. See https://github.com/nextcloud/server/pull/16055

Remove Nunito references, move to native font stack as in server

---

l10n/messages.pot

Update outdated messages.pot

---

styleguide/assets/variables.css

This is the companion pull request to https://github.com/nextcloud/server/pull/21117

Simplify text variables from 4 to 2, map -lighter to -maxcontrast

---

l10n/messages.pot

Update pot file

---

styleguide/global.requires.js

Missed that in #1137 
Otherwise browsing the styleguide fails

Fake OC.isUserAdmin global in styleguide

---

.github/workflows/l10n.yml

Just a small fix of a missing word. ;)

Fix l10n workflow

---

src/components/UserBubble/UserBubble.vue

- Cleaning up docs
- Added new slot to add whatever we want inside the bubble after the label
- Added docs for this new feature too
- Removed the use of the Popover component if the popover was empty, this avoid a weird unecessary complex html structure for such a simple user bubble
- Added a way to set size and avatar margin for the whole component

Fix/user bubble/slot size

---

src/components/UserBubble/UserBubble.vue
styleguide.config.js

Fix UserBubble documentation/click propagation & documentation config

---

package-lock.json
package.json

see https://github.com/nextcloud/nextcloud-vue/pull/1160#issuecomment-651849177

release 2.2.0

---

package-lock.json
src/components/ProgressBar/ProgressBar.vue
src/components/ProgressBar/index.js

Simple progress bar component :) 

Create ProgressBar Component

---

src/components/ProgressBar/ProgressBar.vue

Fix progressbar validators

---

src/components/PopoverMenu/PopoverMenuItem.vue

Fix missing icons in avatar popover menu

---

styleguide/global.requires.js

Needed by https://github.com/nextcloud/nextcloud-router/blob/40ee667eae2403b63783e88ec8093534c04dda91/lib/index.ts#L77
Found while reviewing https://github.com/nextcloud/nextcloud-vue/pull/1240

Add missing OC.config for @nextcloud-router

---

README.md

Signed-off-by: Joas Schilling <coding@schilljs.com>

Add release manual to readme

---

src/components/AppNavigation/AppNavigation.vue
tests/unit/components/AppNavigation/AppNavigation.spec.js

Make sure this keeps the nav closed
if it already was closed.
Includes tests.
Signed-off-by: Azul <azul@riseup.net>

fix: toggle-navigation, open: false

---

src/components/ActionButton/ActionButton.vue
src/components/ActionInput/ActionInput.vue
src/components/ActionLink/ActionLink.vue
src/components/ActionRouter/ActionRouter.vue
src/components/ActionText/ActionText.vue
src/components/Actions/Actions.vue

Actions: Introduce icon slots

---

l10n/messages.pot
src/assets/iconfont/user-status-away.svg
src/assets/iconfont/user-status-dnd.svg
src/assets/iconfont/user-status-invisible.svg
src/assets/iconfont/user-status-online.svg
src/components/Avatar/Avatar.vue

Update status icons

---

src/components/Avatar/Avatar.vue

Do not fetch user-status if user prop does not represent a user

---

src/components/Actions/Actions.vue

Fix default-boundarieselement

---

src/components/AppSidebar/AppSidebar.vue

Fix active tab prop

---

src/components/Avatar/Avatar.vue

Part | Bright | Dark
---|---|---
hover and active | ![Bildschirmfoto von 2020-09-11 14-07-40](https://user-images.githubusercontent.com/213943/92923902-80888d00-f438-11ea-8e98-c8dbe8689bbb.png) | ![Bildschirmfoto von 2020-09-11 14-08-29](https://user-images.githubusercontent.com/213943/92923905-81b9ba00-f438-11ea-9019-ea6c5775a40c.png)
transparent issue in avatar | ![Bildschirmfoto von 2020-09-11 14-07-55](https://user-images.githubusercontent.com/213943/92923908-82eae700-f438-11ea-99e4-edffeb238c73.png) | ![Bildschirmfoto von 2020-09-11 14-08-40](https://user-images.githubusercontent.com/213943/92923914-841c1400-f438-11ea-9a90-5f0a88a5fc9b.png)

Avatar and status fixes

---

src/components/Avatar/Avatar.vue

1. As Alice set yourself to invisible (so you have a status but no icon/message or online-status image)
2. As Bennet open Talk and check the participant list
Before | After
---|---

Only use the icon on the avatar when there is one

---

src/components/Avatar/Avatar.vue

Fix to https://github.com/nextcloud/nextcloud-vue/issues/1406
not tested though :-)
Signed-off-by: Cyrille Bollu <cyrpub@bollu.be>

Adds supports for unicode-encoded names when creating an avatar from a name's initial

---

src/components/RichContenteditable/MentionBubble.vue

Make mention inlined and ellipsised

---

src/components/RichContenteditable/RichContenteditable.vue

Per Jan's request
Fix shadow and number of results showed

Fix autocomplete popup size and shadow

---

package-lock.json
package.json

Bump resolve-url-loader to v3.1.2

---

README.md

Improve release instructions

---

src/components/AppSettingsDialog/AppSettingsDialog.vue

Don't show navigation of settings modal by default

---

package.json
styleguide.config.js
styleguide/global.requires.js

Make sure we always server avatar requests with a fixed image

Proxy avatar to fixed image in the documentation 

---

README.md

To make it a bit more obvious.
I was looking for this command but didn't think about looking for the terms "styleguide".

Add notes about styleguide command in README

---

.github/workflows/l10n.yml
build/extract-l10n.js
l10n/messages.pot

I'm sure we can survive without them

Do not check l10n comments

---

.github/workflows/cypress.yml

Bump cypress github-action to v2

---

src/components/Avatar/Avatar.vue

The disableMenu condition was inverted.

Fix avatar menu click handler

---

src/components/Modal/Modal.vue

Don't close modal on mouseup

---

src/components/ActionInput/ActionInput.vue

Ref https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/color
Fixes

Allow ActionInput type=color

---

package-lock.json
package.json
src/components/RichContenteditable/RichContenteditable.vue
src/mixins/richEditor/index.js

- Add link support on rendering
- Make sure we also decode &amp;
- Replaced badly used `value` variable
- Make sure regex are multilines and insensitive

Add link support to richcontenteditor and fix various issues

---

src/components/AppSettingsDialog/AppSettingsDialog.vue

Make settings navigation list scrollable

---

src/components/ActionButton/ActionButton.vue

|                            Before                            | After                                                        |
| :----------------------------------------------------------: | ------------------------------------------------------------ |
| ![Screenshot from 2021-03-05 15-02-50](https://user-images.githubusercontent.com/26852655/110133184-e8a2a500-7dc3-11eb-95b7-aad7dda0c2b9.png) | ![Screenshot from 2021-03-05 14-59-17](https://user-images.githubusercontent.com/26852655/110133197-edffef80-7dc3-11eb-8a3e-8cc4874bb58d.png) |

Fix ActionButton icon slot

---

src/components/Multiselect/Multiselect.vue

Fix formattedOptions var in multiselect docs

---

.github/workflows/dependabot-approve-merge.yml

Fixing dependabot autoapprove since GitHub changed the Token-permissions.

Fix AutoApprove Action

---

src/components/Multiselect/Multiselect.vue

Quick fix for the docs. Gives a bit more info

Fix multiselect listitemicon docs

---

src/components/AppNavigationCounter/AppNavigationCounter.vue

Update AppNavigationCounter styles

---

src/components/EmptyContent/EmptyContent.vue

Add icon slot to emptycontent

---

styleguide.config.js

|![nextcloud-vue-components netlify app_ (1)](https://user-images.githubusercontent.com/14975046/116221547-03532380-a74e-11eb-82b9-531e8afdfcaf.png)|![localhost_6060_ (2)](https://user-images.githubusercontent.com/14975046/116221543-0221f680-a74e-11eb-9e4a-c347b2fd475e.png)|

Improve documentation sections

---

src/components/AppNavigationItem/AppNavigationItem.vue

Reverts nextcloud/nextcloud-vue#1897

Revert "Fix appnavigationitem layout"

---

src/components/AppNavigationItem/AppNavigationItem.vue

Reverts nextcloud/nextcloud-vue#1902

Revert "[stable3] Fix appnavigationitem layout"

---

src/components/DatetimePicker/DatetimePicker.vue
src/components/DatetimePicker/index.scss

I thought I was being clever by backporting to the backport branch, it's not as easy xD

Allow to append datepicker to body

---

.npmignore
package.json

Replaces https://github.com/nextcloud/nextcloud-vue/pull/1951

Do not ship src files

---

src/components/AppSidebar/AppSidebar.vue

Closes nextcloud/photos#598
Related PR: nextcloud/server#27051

Add timestamp tooltip

---

src/components/AppContent/AppContent.vue
styleguide/global.requires.js

It compiles well, but fails to render
https://deploy-preview-2008--nextcloud-vue-components.netlify.app/

Fix documentation after #1759

---

README.md

Signed-off-by: Louis Chemineau <louis@chmn.me>

Fix release documentation

---

src/components/ListItem/ListItem.vue

Check slots on updated hook

---

src/components/AppContent/AppContent.vue

Do not use app-content-wrapper if no list is provided

---

styleguide/assets/additional.scss

see https://github.com/nextcloud/nextcloud-vue/pull/2007#issuecomment-856063640
Preview: https://deploy-preview-2030--nextcloud-vue-components.netlify.app/

set AppNavigation examples' width to 300px

---

src/components/AppSettingsDialog/AppSettingsDialog.vue

Fix settings navigation  layout

---

src/components/ActionCaption/ActionCaption.vue

| Before | After |   
|--------|-------|
|   ![before](https://user-images.githubusercontent.com/26852655/122434239-d45b7000-cf8e-11eb-9ce8-5bf558686297.PNG)  |  ![after](https://user-images.githubusercontent.com/26852655/122434262-da515100-cf8e-11eb-9899-3dd05ff97350.PNG) |

Fix ActionCaption layout

---

l10n/messages.pot
src/components/DatetimePicker/DatetimePicker.vue
src/components/TimezonePicker/TimezonePicker.vue

Fixes https://github.com/nextcloud/nextcloud-vue/issues/2096

Optionally make the DatetimePicker timezone-aware

---

src/components/Multiselect/index.scss

Before | After
------------ | -------------

Increase padding/margin for MultiSelect tag

---

src/components/Modal/Modal.vue

Follow up to #2126
| Size | Desktop |
|---|---|
| Prompt | ![image](https://user-images.githubusercontent.com/42591237/129776804-43054d8d-b16f-4842-8ca2-3c7515a8a06d.png) |
| Small | ![image](https://user-images.githubusercontent.com/42591237/129777241-bcd8cb96-3957-4a6b-9026-a2f2b7c5d60c.png) |

add an additional Modal size

---

src/components/ListItem/ListItem.vue

Fix backwards navigation for listitem component

---

src/components/index.js
src/directives/index.js
src/mixins/index.js

Export each module with a single line rather than two :)

Simplify exports

---

src/components/AppSettingsDialog/AppSettingsDialog.vue

Otherwise the normal size would be applied which would shrink the size.
Follow up to #2126

set the settings modal size to large

---

src/components/AppSettingsDialog/AppSettingsDialog.vue
src/components/Modal/Modal.vue

And fix some details of the initial implementation
Follow up to https://github.com/nextcloud/nextcloud-vue/pull/2126

Improve modal and appsettingsdialog docs

---

src/components/CounterBubble/CounterBubble.vue
src/components/ListItem/ListItem.vue

Required by talk in order to separate team mentions from direct mentions

Add outlined counter

---

src/components/Modal/Modal.vue

Addresses the feedback that I've got from @jancborchardt 

address feedback on modal sizes

---

src/components/PopoverMenu/PopoverMenuItem.vue

Fix https://github.com/nextcloud/spreed/issues/5834

Fix missing icon

---

src/components/AppSidebarTab/AppSidebarTab.vue

Set sidebar tab content height to be 100 percent

---

src/components/Avatar/Avatar.vue

Fix #2484 
Related server change:
https://github.com/nextcloud/server/pull/31010

Limit avatar request sizes to 64 and 512 pixel

---

CHANGELOG.md
package-lock.json
package.json

Signed-off-by: greta <gretadoci@gmail.com>

Bump version to v5.0.0

---

CHANGELOG.md
package-lock.json
package.json

Signed-off-by: Max <max@nextcloud.com>

Bump version to 5.1.0

---

src/components/Button/Button.vue

Disallow secondary buttons

---

src/components/Button/Button.vue

Pass in a boolean instead of a string in the 'wide' prop

---

src/components/Button/Button.vue

Signed-off-by: Joas Schilling <coding@schilljs.com>

Fix secondary button with old style as temporary solution

---

src/components/EmojiPicker/EmojiPicker.vue

Inherit attrs and forward listeners in the emojipicker's popover

---

src/components/Button/Button.vue

Fix tertiary no background button color

---

package-lock.json

This updates vulnerable dependencies by running `npm audit fix`.

Fix package issues by npm audit fix

---

src/components/AppSidebar/AppSidebar.vue

| --- | --- |
| ![tabs-before](https://user-images.githubusercontent.com/12123721/159885401-950d91fa-6464-4c6a-8b15-ade17115e2d7.png) | ![tabs-after](https://user-images.githubusercontent.com/12123721/159885420-65e91797-702d-459e-9219-f73f439b1d8c.png) |

Fix visual issue of the settings tab in the documentation

---

src/components/Actions/Actions.vue
src/components/Button/Button.vue

See individual commit messages for more explanation
Screenshot for first commit:

Action button vue class

---

package-lock.json
package.json
src/assets/action.scss
src/components/Actions/Actions.vue
src/components/AppNavigationCaption/AppNavigationCaption.vue
src/components/DatetimePicker/index.scss
src/components/Modal/Modal.vue

This update @nextcloud/stylelint-config to the latest version 2.1.2 and fixes lint issues introduced by the update.

Update @nextcloud/stylelint-config to 2.1.2

---

src/components/AppNavigationCaption/AppNavigationCaption.vue

Required for https://github.com/nextcloud/calendar/issues/3965

Extend AppNavigationCaption with slot for custom actions icon

---

src/components/Popover/Popover.vue

Fixes a small leftover from #2713.

Fix trailing comma

---

l10n/messages.pot
src/components/DashboardWidget/DashboardWidget.vue

Reported at Transifex.
Signed-off-by: rakekniven <2069590+rakekniven@users.noreply.github.com>

Change placeholder name to be more clear

---

package-lock.json

Reverts nextcloud/nextcloud-vue#2826

Revert "Bump vue-styleguidist from 4.45.2 to 4.46.1"

---

src/components/Modal/Modal.vue

Signed-off-by: Vanessa Pertsch <vanessa.pertsch@posteo.de>

add role & aria-labels for accessibility

---

package-lock.json

Reverts nextcloud/nextcloud-vue#2849

Revert "Bump vue-styleguidist from 4.45.2 to 4.47.0"

---

README.md

Signed-off-by: Joas Schilling <213943+nickvergessen@users.noreply.github.com>

Update sample diff for Nextcloud 25

---

src/components/AppNavigationCaption/AppNavigationCaption.vue

Fix https://github.com/nextcloud/spreed/issues/7103

Make captions real headings for improved a11y

---

src/components/CheckboxRadioSwitch/CheckboxRadioSwitch.vue

As per validator in the line below

Fix checkbox docs

---

package-lock.json

Reverts nextcloud/nextcloud-vue#2933

Revert "Bump vue-styleguidist from 4.48.0 to 4.50.0"

---

package-lock.json
package.json

Signed-off-by: Joas Schilling <coding@schilljs.com>

[stable5] Bump @nextcloud/logger dependency

---

src/components/Modal/Modal.vue

[stable5] add role & aria-labels for accessibility

---

README.md

Signed-off-by: Joas Schilling <213943+nickvergessen@users.noreply.github.com>

Update release instructions to also handle the milestones

---

src/components/AppSidebar/AppSidebar.vue

[stable5] Fix favorite icon 

---

src/components/Modal/Modal.vue

Make sure modal ids are unique

---

src/components/ListItem/ListItem.vue

Fixes https://github.com/nextcloud/mail/issues/6866

Add $emit 'update:menuOpen' for Actions on actions' menu handling

---

src/components/TextField/TextField.vue

Signed-off-by: Joas Schilling <213943+nickvergessen@users.noreply.github.com>

Remove invalid type from docs

---

webpack.dev.js

Fix local styleguide server run

Webpack config: Remove source-map

---

src/components/Multiselect/Multiselect.vue

Signed-off-by: julia.kirschenheuter <julia.kirschenheuter@nextcloud.com>

```aria-expanded``` was fixed for Multiselect.vue

---

src/components/AppSettingsDialog/AppSettingsDialog.vue

Add missing trailing comma

---

src/components/NcModal/NcModal.vue

See https://github.com/nextcloud/nextcloud-vue/pull/2695/files#r949428258

Fix Modal closing

---

src/components/NcAppNavigationCounter/NcAppNavigationCounter.vue

Fixes a little regression of #3058 in the docs.

Fix link in docs to NcCounterBubble

---

src/components/NcAppNavigationItem/NcAppNavigationItem.vue
src/components/NcListItem/NcListItem.vue

📰 Update AppNavigationItem design

---

CHANGELOG.md
package-lock.json
package.json

Signed-off-by: greta <gretadoci@gmail.com>

Release v6.0.0-beta.5

---

src/components/NcPopover/NcPopover.vue
tests/unit/components/NcActions/NcActions.spec.js

Fixes a small leftover from #3058.

Use correct Nc components prefix everywhere

---

src/components/NcModal/NcModal.vue

Add missing tab in NcModal CSS

---

src/components/NcActions/NcActions.vue

@nickvergessen Could you test whether this closes #3109 for you, please?

Ensure proper actions menu styling

---

src/components/NcInputField/NcInputField.vue
src/components/NcPasswordField/NcPasswordField.vue

- Fix fetch reason from password_policy api
- Pass error/success state correctly
- Better align icon in helper text

Polish password field component

---

CHANGELOG.md
package-lock.json
package.json

Signed-off-by: greta <gretadoci@gmail.com>

Release v6.0.0-beta.6

---

src/components/NcMultiselect/index.scss

Don't change size of the multiselect when clicking on it and make
padding consistent with all states

Make NcMultiselect pixel perfect

---

CHANGELOG.md
package-lock.json
package.json

ref https://github.com/nextcloud/mail/pull/7128#issuecomment-1235205305

Release v7.0.0-beta.1

---

src/components/NcAppNavigationItem/NcAppNavigationItem.vue

Follow-up to https://github.com/nextcloud/nextcloud-vue/pull/3165.
| Before | After
|---|---|
| ![Bildschirmfoto vom 2022-09-05 19-42-24](https://user-images.githubusercontent.com/1374172/188496881-871e867b-10e4-49c5-b4f8-6515d85747d6.png) | ![Bildschirmfoto vom 2022-09-05 19-39-01](https://user-images.githubusercontent.com/1374172/188496900-08a95fe1-dac7-4a65-bbd3-c78e6d6138dd.png) |

Right-align nav item utils

---

src/components/NcRichContenteditable/NcRichContenteditable.vue

For https://github.com/nextcloud/server/issues/33832
|---|---|
| ![image](https://user-images.githubusercontent.com/42591237/188478888-1296b71a-a004-4036-a5cd-84ffac43dedf.png) | ![image](https://user-images.githubusercontent.com/42591237/188478974-23eafd80-7127-4755-b94f-1bf9efcc18b0.png) |

fix comments border-radius

---

styleguide/assets/additional.css

Fix scrolling in styleguide

---

src/components/NcAvatar/NcAvatar.vue
webpack.config.js

Use asset/inline in webpack config and add an example to show that this works
Fix https://github.com/nextcloud/server/issues/33890

Fix loading avatar status

---

src/components/NcAppNavigation/NcAppNavigation.vue

Fixes https://github.com/nextcloud/nextcloud-vue/issues/3188

Fix app navigation backdrop blur

---

CHANGELOG.md
package-lock.json
package.json

Release v7.0.0-beta.2

---

CHANGELOG.md
package-lock.json
package.json

Signed-off-by: greta <gretadoci@gmail.com>

Release v7.0.0-beta.3

---

src/components/NcAvatar/NcAvatar.vue

Fix #3232
Before | After
---|---

Fix avatar border color

---

src/components/NcAppNavigationItem/NcAppNavigationItem.vue

Fixes regression introduced with [93dd3d1](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)

Add proper margin to the counter

---

src/components/NcAppNavigation/NcAppNavigation.vue

Add gap between nav entry

---

CHANGELOG.md
package-lock.json
package.json

Release v7.0.0-beta.4

---

src/components/NcRelatedResourcesPanel/NcResource.vue

Fix button styles in https://github.com/nextcloud/spreed/pull/7789

Mark resource button styles as important to fix styles in some contexts

---

CHANGELOG.md
package-lock.json
package.json

Still having some hope to use it in production. 😉

v6.0.0 beta.8

---

src/components/NcInputField/NcInputField.vue

Fix #3280 
Signed-off-by: Marco <marcoambrosini@icloud.com>

Fix unclickable text at the beginning of the inputfield

---

CHANGELOG.md

fixes #3203 
Christoph's :eye: pain free

Merge pre-releases changelog for v6

---

src/components/NcDateTimePickerNative/NcDateTimePickerNative.vue

This fixes some small linting errors that were reported by the lint in #2637.

Fix minor linting errors

---

src/components/NcModal/NcModal.vue

https://github.com/nextcloud/viewer/issues/1357

Make Viewer title h2

---

src/components/NcAvatar/NcAvatar.vue

|---|---|
| ![image](https://user-images.githubusercontent.com/42591237/193002057-50fdf12a-075f-4a42-ba01-38ac4c58ff1a.png) | ![image](https://user-images.githubusercontent.com/42591237/193002265-410c0666-1156-4aa3-99b2-0548792efe96.png) |

fix Avatar Size

---

package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud/nextcloud-vue/compare/v7.0.0-beta.[6](https://github.com/nextcloud/nextcloud-vue/actions/runs/3152995806/jobs/5128926175#step:7:7)...v[7](https://github.com/nextcloud/nextcloud-vue/actions/runs/3152995806/jobs/5128926175#step:7:8).0.0-beta.7)
- Enables ESM Modules [\#32[8](https://github.com/nextcloud/nextcloud-vue/actions/runs/3152995806/jobs/5128926175#step:7:9)3](https://github.com/nextcloud/nextcloud-vue/pull/3283) ([vinicius73](https://github.com/vinicius73))
- Fix NcMultiselect height [\#3312](https://github.com/nextcloud/nextcloud-vue/pull/3312) ([st3iny](https://github.com/st3iny))
- Fix: export missing NcProgressBar component  [\#3301](https://github.com/nextcloud/nextcloud-vue/pull/3301) ([vinicius73](https://github.com/vinicius73)) …

🔖 v7.0.0-beta.7

---

src/components/NcModal/NcModal.vue

Fix https://github.com/nextcloud/server/issues/33870
Approved by Jan for the breakpoint change

Increase modal title breakpoint and prevent overflow

---

src/components/NcColorPicker/NcColorPicker.vue

Before | After
--- | ---
Advanced fields

Expand color picker width only when using advanced fields

---

src/components/NcColorPicker/NcColorPicker.vue

Fix dark themed color picker and use button component

---

styleguide/assets/server.css

Auto-generated update of our locally cached css styling from
* https://nextcloud.github.io/server/apps/theming/css/default.css
* https://nextcloud.github.io/server/core/css/server.css
* https://nextcloud.github.io/server/dist/icons.css

Automated styling update from server

---

package-lock.json
package.json

https://github.com/nextcloud/eslint-config/releases/tag/v8.1.3

Bump @nextcloud/eslint-config from 8.1.2 to 8.1.3

---

src/components/NcPasswordField/NcPasswordField.vue

Signed-off-by: John Molakvoæ <skjnldsv@protonmail.com>

Move loadState to data for better mockability

---

src/components/NcEmojiPicker/NcEmojiPicker.vue
src/components/NcPopover/NcPopover.vue

After https://github.com/nextcloud/nextcloud-vue/pull/3490

Finish emoji focus cleaning

---

src/components/NcAppNavigationItem/NcAppNavigationItem.vue

Make gap in NcAppNavigation consistent in nested lists

---

README.md
package.json

- Add a npm run script to watch changes and build the es module
- Document how to watch during development

Add watch:module and document the module build

---

src/components/NcInputField/NcInputField.vue

| | Screenshot
--- | ---
**Before** | ![image](https://user-images.githubusercontent.com/24800714/206321049-7ace2f60-6048-46b8-8c17-ec213b76f8cc.png)
**After** | ![image](https://user-images.githubusercontent.com/24800714/206321059-25016791-cec2-4ce1-a591-83dfb81083be.png)

Increase input field border contrast

---

src/components/NcAppSidebar/NcAppSidebarTabs.vue

Fix https://github.com/nextcloud/nextcloud-vue/issues/3533
Reintroduce https://github.com/nextcloud/server/issues/34777
Signed-off-by: Simon L <szaimen@e.mail.de>

[stable7] revert "fix sidebar scrolling for small displays"

---

src/components/NcAppSidebar/NcAppSidebarTabs.vue

Reverts nextcloud/nextcloud-vue#3444

Revert "fix sidebar scrolling for small displays"

---

src/components/NcAppNavigationItem/NcAppNavigationItem.vue

For https://github.com/nextcloud/mail/issues/7769
i tested with mail and tasks

Add more space for unread counter so its aligned with action menu

---

l10n/messages.pot
src/components/NcAppNavigationItem/NcAppNavigationIconCollapsible.vue

Signed-off-by: John Molakvoæ <skjnldsv@protonmail.com>

Fix appNavigationItem collapse labels

---

src/components/NcActionInput/NcActionInput.vue

Fix action input styles

---

src/components/NcAppNavigationItem/NcAppNavigationItem.vue

Vue router does NOT support external href
```vue
<NcAppNavigationItem title="Files" href="/index.php/apps/files" />
<NcAppNavigationItem title="Nextcloud" href="https://nextcloud.com" />
```

feat(AppNavigationItem): Add href support

---

package-lock.json
package.json

Bump vue-select to 3.20.2

---

.github/workflows/command-l10n-update.yml

Signed-off-by: Simon L <szaimen@e.mail.de>
Signed-off-by: Simon L. <szaimen@e.mail.de>

add compile command for l10n

---

src/components/NcBreadcrumb/NcBreadcrumb.vue

- Add exact prop for vue router
- Fix styling
|![Capture d’écran_2023-01-13_16-31-35](https://user-images.githubusercontent.com/14975046/212357762-ddefda66-a0dd-4b96-8b7a-e79e7784e60f.png)|![Capture d’écran_2023-01-13_16-31-41](https://user-images.githubusercontent.com/14975046/212357774-e25169a3-befb-4731-bcd1-66628361a738.png)|

Breadcrumb: add exact prop and fix style

---

src/components/NcActions/NcActions.vue

This is just a small cleanup of the NcActions docs. No functional changes.

Small cleanup of the NcActions docs

---

package-lock.json
package.json

To support package exports for #3667

Update `@nextcloud/eslint-config` to 8.2.1

---

package-lock.json
package.json
src/components/NcSelect/NcSelect.vue

Switch to `@nextcloud/vue-select` from `vue-select` with accessibiity improvements and bug fixes, see https://github.com/nextcloud-deps/vue-select/releases

Use @nextcloud/vue-select

---

src/components/NcSelect/NcSelect.vue

Add keyboard focus border to select options

---

src/components/NcAppNavigationItem/NcAppNavigationItem.vue

Signed-off-by: Marco <marcoambrosini@icloud.com>

Allow inline actions for appnavigationitem

---

src/components/NcSelect/NcSelect.vue

Fix focused select border color with top placement

---

src/components/NcSelect/NcSelect.vue

Rounded select dropdown options

---

src/components/NcRichText/NcReferencePicker/NcCustomPickerElement.vue
src/components/NcRichText/NcReferencePicker/NcProviderList.vue
src/components/NcRichText/NcReferencePicker/NcRawLinkInput.vue
src/components/NcRichText/NcReferencePicker/NcReferencePicker.vue
src/components/NcRichText/NcReferencePicker/NcReferencePickerModal.vue
src/components/NcRichText/NcReferencePicker/NcSearch.vue

This PR adds the emits sections for the `NcRichText` components.

Add emits event sections for `NcRichText*` components

---

src/components/NcAppNavigation/NcAppNavigation.vue
src/components/NcAppNavigationItem/NcAppNavigationItem.vue
src/components/NcListItem/NcListItem.vue

Just a little cleanup for vue3.

Use single quotes in SCSS code

---

l10n/messages.pot
src/components/NcEmojiPicker/NcEmojiPicker.vue

Add accessible search field to emoji picker

---

src/components/NcAppNavigation/NcAppNavigation.vue
src/components/NcAppSidebar/NcAppSidebar.vue

Address https://github.com/nextcloud/server/pull/37692#issuecomment-1505633808

adjust sidebar to go full-screen earlier at 768px

---

CHANGELOG.md

For https://github.com/nextcloud/nextcloud-vue/pull/3981

Update CHANGELOG for 7.10.0

---

src/components/NcRichContenteditable/NcMentionBubble.vue

* Contributes to https://github.com/nextcloud/spreed/issues/9188#issuecomment-1520658853
Before | After
---|---

feat(NcRichContenteditable): Support iconUrl on mention bubbles

---

src/components/NcAvatar/NcAvatar.vue

Just a minor cleanup of `NcAvatar` and a follow-up to #4017 and https://github.com/nextcloud/nextcloud-vue/pull/4017#discussion_r1188910827.

Minor avatar cleanup

---

src/components/NcAppSidebar/NcAppSidebar.vue

Follow-up to https://github.com/nextcloud/nextcloud-vue/pull/3972

update sidebar to really take the whole space on mobile

---

src/components/NcAppNavigationItem/NcAppNavigationItem.vue

Address https://github.com/nextcloud/server/issues/38155

make navigation-collapsible always visible

---

src/components/NcInputField/NcInputField.vue

- For https://github.com/nextcloud/server/issues/36949
---|---

Increase input field helper text contrast

---

src/components/NcInputField/NcInputField.vue

- Revert https://github.com/nextcloud/nextcloud-vue/pull/4189 as `--color-error-text` and `--color-success-text` are added for master 28 only

Revert "Merge pull request #4189 from nextcloud/backport/4188/stable7"

---

src/components/NcSelect/NcSelect.vue

- Fix https://github.com/nextcloud/nextcloud-vue/issues/4208
---|---

enh(NcSelect): Keep dropdown open while loading

---

src/components/NcPopover/NcPopover.vue

Close https://github.com/nextcloud/nextcloud-vue/issues/4198
|---|---|
| ![image](https://github.com/nextcloud/nextcloud-vue/assets/42591237/8abd0a28-365f-4345-8aec-e18442455921) | ![image](https://github.com/nextcloud/nextcloud-vue/assets/42591237/e2ab4d85-51f3-4780-b0cf-1abb15595c9e) |

adjust border-radius of ncpopover

---

docs/index.md
styleguide.config.js

[stable7] Add links to documentation for other versions

---

CHANGELOG.md

Update CHANGELOG to reflect changes in new beta release.
---|---

Update Changelog to reflect 8.0.0-beta.2 changes

---

src/components/NcEmptyContent/NcEmptyContent.vue
src/components/NcIconSvgWrapper/NcIconSvgWrapper.vue

|![2023-07-07_12-42](https://github.com/nextcloud/nextcloud-vue/assets/14975046/7048a7f2-1ed2-4d00-a535-d4a9d846ac38)|![2023-07-07_12-41](https://github.com/nextcloud/nextcloud-vue/assets/14975046/aca0ee17-e352-42f3-a370-1735e4277272)|

fix: NcIconSvgWrapper size

---

package-lock.json
package.json
src/components/NcAppNavigation/NcAppNavigation.vue
src/components/NcButton/NcButton.vue

The update to the new stylelint config requires some manual changes to the code.

Update `@nextcloud/stylelint-config` and fix issues detected

---

.editorconfig
.github/workflows/lint-eslint-when-unrelated.yml

* Ref https://github.com/nextcloud/nextcloud-vue/pull/4340
* Ref #4326

chore(CI): Add a "eslint when unrelated" so the requirement can be kept

---

CHANGELOG.md
README.md
docs/index.md
package.json
styleguide.config.js

(need to do this from my personal fork as permissions to create new branches were lost while transfering)

chore: Fix URLs after package was transfered

---

.github/workflows/changelog-generate.yml

Fixes the changelog CI workflow
> The repository has moved, update your configuration

fix(ci): Set github user after project was moved

---

CHANGELOG.md

Somehow the auto generation failed

fix: v7.12.2 changelog

---

.tx/config

Reverts #4412 
Instead applied online

Delete invalid .tx config

---

src/components/NcHeaderMenu/NcHeaderMenu.vue

Close https://github.com/nextcloud/server/issues/39881
|---|---|
| ![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/42591237/783684cf-3adf-45b9-932f-6e1d4ce3ea96) | ![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/42591237/3ef42663-a126-4cb3-991b-e9b53e48169b) |

try to fix header size on mobile

---

src/components/NcHeaderMenu/NcHeaderMenu.vue

manual backport of https://github.com/nextcloud-libraries/nextcloud-vue/pull/4420

[stable7] try to fix header size on mobile

---

src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue

Close https://github.com/nextcloud-libraries/nextcloud-vue/issues/4345
|---|---|
| ![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/42591237/61de5bfd-68f6-4895-9aaa-7b4e4f050eb0) | ![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/42591237/99e21f84-bcf1-4446-8a25-5d07860508c7) |

NcCheckboxRadioSwitch - adjust border color

---

CHANGELOG.md
package-lock.json
package.json

v8.0.0-beta.3

---

src/components/NcActions/NcActions.vue

🔥 hotfix https://github.com/nextcloud-libraries/nextcloud-vue/pull/4450

[stable7] fix: Rename name → title

---

src/components/NcListItem/NcListItem.vue

[stable7] fix(`NcListItem`) don't force blur action menu on tab

---

CHANGELOG.md
package-lock.json
package.json

v8.0.0-beta.4

---

styleguide.config.js

This adds the link to the vue 3 docs.

chore[docs]: link to docs for vue3

---

.eslintrc.js
jest.config.js
src/components/NcHighlight/NcHighlight.vue
src/components/index.js
styleguide.config.js
tests/unit/components/NcHighlight/NcHighlight.spec.js

This migrates the `NcHighlight` component to vue 3.

chore(vue3): Migrate NcHighlight

---

.eslintrc.js
src/components/NcDatetime/NcDatetime.vue
src/components/index.js
styleguide.config.js
tests/unit/components/NcDatetime/NcDatetime.spec.js

This migrates the `NcDatetime` component to vue 3.

chore(vue3): Migrate NcDatetime

---

package-lock.json
package.json
styleguide.config.js
vite.config.mts
webpack.config.js

"Backport" of https://github.com/nextcloud-libraries/nextcloud-vue/pull/4386

[vue3] Use vite for all entry points

---

package-lock.json
package.json

* Fix #4592 
The update contains a workaround for the minify issue (vite replaces a require after it was minified and chained with the comma operator, so the following assignment is invalid).

chore(deps): Update `@nextcloud/vite-config` as a workaround for minify issue

---

src/components/NcDateTimePicker/chevron-double-left-light.svg
src/components/NcDateTimePicker/chevron-double-right-light.svg
src/components/NcDateTimePicker/chevron-left-light.svg
src/components/NcDateTimePicker/chevron-right-light.svg
src/components/NcDateTimePicker/index.scss

fix: invert datepicker buttons on dark mode

---

src/components/NcDatetimePicker/chevron-double-left-light.svg
src/components/NcDatetimePicker/chevron-double-right-light.svg
src/components/NcDatetimePicker/chevron-left-light.svg
src/components/NcDatetimePicker/chevron-right-light.svg
src/components/NcDatetimePicker/index.scss

[stable7] fix: invert datepicker buttons on dark mode

---

src/components/NcActionInput/NcActionInput.vue
src/components/NcPasswordField/NcPasswordField.vue

Backport https://github.com/nextcloud-libraries/nextcloud-vue/pull/4632

[stable7] fix(NcActionInput): Set default trailing button label

---

src/components/NcRelatedResourcesPanel/NcRelatedResourcesPanel.vue

* Fix #https://github.com/nextcloud/related_resources/pull/303
---|---
B | A

Add the resource type on RelatedResourcesPanel

---

src/components/NcDialog/NcDialog.vue

* Fix: suggestions from this review were required https://github.com/nextcloud-libraries/nextcloud-vue/pull/4682

fix(dialog): fix component registration

---

package-lock.json
package.json

This updates the dependencies of the `next` branch.

[next] chore(deps): update dependencies

---

.github/workflows/command-l10n-update.yml
.github/workflows/cypress.yml
.github/workflows/l10n.yml
.github/workflows/lint-eslint.yml
.github/workflows/lint-stylelint.yml
.github/workflows/node.yml
.github/workflows/npm-publish.yml
.github/workflows/npm-test.yml
src/components/NcEmptyContent/NcEmptyContent.vue
src/components/NcRelatedResourcesPanel/NcRelatedResourcesPanel.vue

This merges the recent changes from `master` into the `next` branch before the PR gets too large again.

[next] chore(master): merge `master` into `next`

---

src/components/NcTextArea/NcTextArea.vue

* Adds a missing trailing comma

fix(NcTextArea): add missing trailing comma

---

src/components/NcInputField/NcInputField.vue

Fix input field trailing button alignment

---

src/components/NcSelectTags/NcSelectTags.vue

- Fix console errors when passing object value

fix(NcSelectTags): Allow object type value

---

l10n/messages.pot
src/components/NcModal/NcModal.vue

* Fix nextcloud/server#40703
See this for details: https://github.com/nextcloud/server/issues/40703#issuecomment-1781569649

fix(NcModal): Adjust `aria-label` of close button

---

.eslintrc.js
src/components/NcUserBubble/NcUserBubble.vue
src/components/index.js
styleguide.config.js

* This migrates `NcUserBubble` to vue 3.

[next] feat(NcUserBubble): migrate to vue 3

---

src/components/NcSelect/NcSelect.vue

Fix https://github.com/nextcloud-libraries/nextcloud-vue/issues/4816
|---|---|
| ![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/42591237/c3337b09-9856-42a6-b720-21805937d79f) | ![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/42591237/a0920983-61bf-4c33-aaf9-7ad9418d3aad) |

fix single-select design

---

src/components/NcAppSidebar/NcAppSidebarTabs.vue

Follow-up to https://github.com/nextcloud-libraries/nextcloud-vue/pull/4823

Use the correct text color in NcAppSidebarTabs.vue

---

src/components/NcAppSidebar/NcAppSidebarTabs.vue

Reverts nextcloud-libraries/nextcloud-vue#4834

Revert "Use the correct text color in NcAppSidebarTabs.vue"

---

src/components/NcUserBubble/NcUserBubble.vue

* Fixes importing `warn` in `NcUserBubble`.

[next] fix(NcUserBubble): import warn correctly

---

package.json

chore(ci): make Jest output colorful

---

src/index.js

* Small cleanup after everything got migrated.

fix: export functions again

---

src/components/NcActionButtonGroup/NcActionButtonGroup.vue

- Fixes ESLint warning (methods/computed order)
- Replace computed with constant in setup to avoid creating unneeded reactive effect

refactor(NcActionButtonGroup): replace computed of constant with constant

---

package-lock.json
package.json

* Since dependabot only works against `master`, I updated a few dependencies of `next` manually here.

[next] chore(deps): bump various dependencies

---

l10n/de.pot
src/components/NcDateTime/NcDateTime.vue
src/components/NcDateTimePicker/NcDateTimePicker.vue
src/composables/index.js
src/composables/useFormatDateTime.js
tests/unit/components/NcDateTime/NcDateTime.spec.js
tests/unit/composables/useFormatDateTime.spec.js

* Merges `master` into `next`.
You know how it goes.

[next] chore(master): merge `master` into `next` again

---

package-lock.json
package.json
vite.config.ts
vitest.config.ts

[next] chore(deps): bump vitest to 1.1.3

---

package-lock.json
package.json

[next] chore(deps): bump `vue` to `3.4.13`

---

src/components/NcRelatedResourcesPanel/NcRelatedResourcesPanel.vue

- Fix https://github.com/nextcloud/related_resources/issues/337
Set the correct default query params https://github.com/nextcloud/related_resources/blob/dd5cc9bcb88d309bcf992de856d3095f7fa7d42b/lib/Controller/ApiController.php#L94-L95

fix(NcRelatedResourcesPanel): Fix invalid URL query params

---

CHANGELOG.md

GitHub bot 🤖 didn't count this one before

chore: Fix missing PR from changelog

---

CHANGELOG.md

chore(CHANGELOG): Add missing entry for 8.6.0 release

---

src/components/NcActionButton/NcActionButton.vue

Make it a bit more semantic correct.

fix(NcActionButton): Forward `disabled` state to native button element

---

src/components/NcDateTimePicker/NcDateTimePicker.vue

- Fix  https://github.com/nextcloud/mail/issues/9339
- fixes https://github.com/nextcloud/calendar/issues/5767
---|---
B | A

Fix timezone dropdown

---

CHANGELOG.md
src/components/NcListItem/NcListItem.vue

Merge master into next to prepare next alpha release.

[next] Merge master into next

---

CHANGELOG.md
package-lock.json
package.json

We just released a new 8.x version, time to also release the matching 9.x preview release.

[next] Prepare 9.0.0-alpha.2 release

---

src/components/NcActions/NcActions.vue

Manual backport of https://github.com/nextcloud-libraries/nextcloud-vue/pull/5308

[next] fix(NcActions): provide a label in dialog role

---

src/components/NcSelect/NcSelect.vue

Enh: handle text overflow in NcSelect

---

CHANGELOG.md
package-lock.json
package.json

* fix: Revert "fix(NcAppNavigation): Wrap app navigation default slot with scrollable container" by @Pytal in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5355
**Full Changelog**: https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.9.0...v8.9.1

chore: Release v8.9.1

---

src/components/NcAppNavigationItem/NcAppNavigationItem.vue

- Fix https://github.com/nextcloud/server/issues/42059
---|---

fix(NcAppNavigationItem): Fix uncollapsible entry

---

.github/workflows/update_timezones.yml
resources/timezones/update-zones.py
resources/timezones/zones.json

Workflow and python script were taken from https://github.com/nextcloud/calendar-js.
- Fix _none_
---|---
B | A

fix: update timezone data and automate future updates

---

src/components/NcAppSidebar/NcAppSidebar.vue

- For https://github.com/nextcloud-libraries/nextcloud-vue/pull/5584#pullrequestreview-2062086553

feat(NcAppSidebar): add CSS variables for toggle button offset

---

CHANGELOG.md
package-lock.json
package.json

chore: Prepare v9.0.0-alpha.3 release

---

package-lock.json
package.json

- Backport of https://github.com/nextcloud-libraries/nextcloud-vue/pull/5612

[next] fix: Adjust license in package.json

---

styleguide/assets/dark.css
styleguide/assets/default.css

fix(REUSE): add SPDX header to a new file

---

CHANGELOG.md
package-lock.json
package.json

chore: Prepare 9.0.0-alpha.4

---

src/components/NcInputField/NcInputField.vue

Vertically center label in the middle of the input field

Fix input field label alignment

---

REUSE.toml

Use correct date in header

---

README.md

Add reuse status badge

---

src/components/NcAppNavigationSettings/NcAppNavigationSettings.vue

- Fix https://github.com/nextcloud-libraries/nextcloud-vue/issues/5764
---|---

fix(NcAppNavigationSettings): border radius of toggle button

---

CHANGELOG.md
l10n/ar.pot
l10n/ast.pot
l10n/da.pot
l10n/de.pot
l10n/de_DE.pot
l10n/en_GB.pot
l10n/ga.pot
l10n/gl.pot
l10n/ja_JP.pot
l10n/nl.pot
l10n/pl.pot
l10n/pt_BR.pot
l10n/sr.pot
l10n/sv.pot
l10n/tr.pot
l10n/uk.pot
package-lock.json
package.json

Companion for the 8.14.0 release with updated translations.

Prepare v9.0.0-alpha.5 release

---

src/components/NcAppNavigationSettings/NcAppNavigationSettings.vue

- Fix https://github.com/nextcloud/calendar/issues/6141
|---|---|
| ![Bildschirmfoto_20240717_134412](https://github.com/user-attachments/assets/4e2ba8a8-d763-45aa-a2a0-0a66669dd205) | ![Bildschirmfoto_20240717_134113](https://github.com/user-attachments/assets/b9999dfa-35a1-44c4-beec-27d560e48696) ![Bildschirmfoto_20240717_134125](https://github.com/user-attachments/assets/cd83bb19-fa89-49ec-80ee-172fe31b8f75) |

fix(NcAppNavigationSettings): use tertiary styling for the toggle button

---

src/components/NcAppNavigationCaption/NcAppNavigationCaption.vue

- Fix https://github.com/nextcloud/mail/issues/9835
---|---

style(NcAppNavigationCaption): remove margin-bottom

---

src/components/NcSelect/NcSelect.vue

- Fix the issue commented on https://github.com/nextcloud/server/pull/46591#issuecomment-2243400428
---|---
B | A

fix(NcSelect): increase avatar size to show subname

---

src/components/NcAvatar/NcAvatar.vue

- Follow-up to #5898 
- I was just about to push...
- This fixes NcActions radius as well
---|---

style(NcAvatar): make border-radius consistent

---

.github/workflows/npm-audit-fix.yml

chore: add npm-audit-fix workflow

---

package-lock.json

This audit fix resolves 36 of the total 40 vulnerabilities found in your project.
* [@nextcloud/l10n](#user-content-\@nextcloud\/l10n)
* [anymatch](#user-content-anymatch)
* [bonjour](#user-content-bonjour)
* [braces](#user-content-braces)
* [chokidar](#user-content-chokidar)
* [cookie](#user-content-cookie)
* [css-loader](#user-content-css-loader)
* [dns-packet](#user-content-dns-packet)
* [express](#user-content-express)
* [http-proxy-middleware](#user-content-http-proxy-middleware)
* [icss-utils](#user-content-icss-utils)
* [ip](#user-content-ip)
* [micromatch](#user-content-micromatch)
* [multicast-dns](#user-content-multicast-dns)
* [node-forge](#user-content-node-forge)
* [node-gettext](#user-content-node-gettext)
* [postcss](#user-content-postcss)
* …

[next] Fix npm audit

---

src/components/NcAppSidebar/NcAppSidebar.vue

- Manual backport of https://github.com/nextcloud-libraries/nextcloud-vue/pull/5720/

[next] fix(NcAppSidebar): apply toggle offset transition only on sidebar transition

---

src/components/NcAppContent/NcAppDetailsToggle.vue

- part of https://github.com/nextcloud/mail/issues/10227
---|---
B | A

fix(NcAppDetailsToggle): Rtl support

---

src/components/NcDateTimePickerNative/NcDateTimePickerNative.vue

- Useful for https://github.com/nextcloud/calendar/pull/6423

docs(NcDateTimePickerNative): add time picker example

---

src/components/NcAvatar/NcAvatar.vue

- Fix attributes order in `next` branch.

[next] fix(NcAvatar): attributes order

---

package-lock.json
package.json

- Update `@babel` deps for `next` branch

[next] chore(deps): update babel deps

---

package-lock.json
package.json

- Update `vue` deps of the `next` branch

[next] chore(deps): update vue deps

---

CHANGELOG.md
README.md
package-lock.json
package.json

* For https://github.com/nextcloud-libraries/nextcloud-vue/issues/6106
- Contributors
- @ShGKme 
- @susnux 
- @raimund-schluessler 
- @skjnldsv 
- @st3iny 
- @ShGKme 
- @susnux 
- @hamza221

chore: Prepare release of v9.0.0-alpha.6

---

src/components/NcAvatar/NcAvatar.vue
src/components/NcRichText/NcReferenceWidget.vue

fix(bidi): NcAvatar status and interactivity toggle button

---

.github/workflows/block-unconventional-commits.yml

We somehow missed this workflow here.

ci: block unconventional commits

---

l10n/ar.pot
l10n/cs.pot
l10n/da.pot
l10n/de.pot
l10n/de_DE.pot
l10n/en_GB.pot
l10n/es_AR.pot
l10n/es_MX.pot
l10n/fa.pot
l10n/fi.pot
l10n/fr.pot
l10n/ga.pot
l10n/gl.pot
l10n/ja.pot
l10n/ko.pot
l10n/nb.pot
l10n/nl.pot
l10n/pl.pot
l10n/pt_BR.pot
l10n/ru.pot
l10n/sk.pot
l10n/sr.pot
l10n/sv.pot
l10n/tr.pot
l10n/uk.pot
l10n/zh_CN.pot
l10n/zh_HK.pot

Update translation on vue3 branch.

[next] chore: Update translations

---

CHANGELOG.md
package-lock.json
package.json

Prepare a new pre-release.
---

chore: prepare v9.0.0-alpha.7

---

l10n/el.pot
l10n/et_EE.pot
l10n/is.pot
l10n/pt_BR.pot
l10n/pt_PT.pot
l10n/sk.pot
l10n/uz.pot

- Sync translations from master to next

[next] chore: sync translations from master

---

src/components/NcDateTimePicker/NcDateTimePicker.vue

- Prevent scrollbars where not needed.
---|---

fix(NcDateTimePicker): adjust padding to prevent horizontal scrolling

---

src/components/NcDateTimePicker/NcDateTimePicker.vue

- no functional changes
- document every prop we provide
- add some developer docs on what some computed properties do
- also resort the props in consistent order

docs(NcDateTimePicker): add prop documentation for all props

---

package-lock.json

No fixable problems found (4 unfixable, 42 only fixable manually using --force)

[stable8] Fix npm audit

---

src/components/NcSelectUsers/NcSelectUsers.vue
tests/component/components/NcSelectUsers/NcSelectUsers.spec.ts
tests/component/components/NcSelectUsers/UserSelect.story.vue

* resolves https://github.com/nextcloud-libraries/nextcloud-vue/issues/6921

fix(NcSelectUsers): use correct type for model and add tests for model-value handling

---

src/components/NcInputField/NcInputField.vue

Regression of #4512 
Fix the unresolved components issue and unify state color handling.

fix(NcInputField): unresolved component and state color

---

src/components/NcAppContent/NcAppContent.vue

[stable8] fix(NcAppContent): incorrect page title from a different core.apps format in Nextcloud 30

---

src/components/NcAvatar/NcAvatar.vue

- Fix component render from `user_status:status.updated` event
- hasStatus should be computed?
---|---

fix(NcAvatar): update 'hasStatus' flag if changed

---

src/components/NcButton/NcButton.vue

- Fix cursor issue on button contents

refactor(NcButton): remove redundant style

---

.github/workflows/command-l10n-update.yml
.github/workflows/command-playwright-update.yml
.github/workflows/npm-publish.yml

update workflows from organization including some fixes for workflow linting.

ci: update workflows from organization

---

package-lock.json
src/components/NcInputField/NcInputField.vue
tests/unit/components/NcActions/NcActionButton.spec.ts

Recreate the package lock to also update nested development dependencies.
This also uncovered two issues:
- Wrong test expectation due to DOM mock (missing quotation marks in style)
- Wrong event casing we missed in #7059

chore(dev-deps): update nested development dependencies

---

src/components/NcInputField/NcInputField.vue
src/components/NcTextArea/NcTextArea.vue
src/globals.d.ts
src/utils/legacy.ts
tests/OC.js
tests/unit/components/NcField/NcField.spec.ts
tests/unit/components/NcTextArea/NcTextArea.spec.ts

- Resolves https://github.com/nextcloud-libraries/nextcloud-vue/issues/7281

fix(NcInputField, NcTextareaField): remove placeholder on Nextcloud 32+

---

src/components/NcInputField/NcInputField.vue
src/components/NcTextArea/NcTextArea.vue
src/globals.d.ts
src/utils/legacy.ts
styleguide/global.requires.js
tests/OC.js

* manual backport of https://github.com/nextcloud-libraries/nextcloud-vue/pull/7283

[stable8] fix(NcInputField, NcTextareaField): remove placeholder on Nextcloud 32+

---

styleguide/assets/default.css

Auto-generated update of our locally cached css styling from
* https://nextcloud.github.io/server/apps/theming/css/default.css
* https://nextcloud.github.io/server/core/css/server.css
* https://nextcloud.github.io/server/dist/icons.css

[main] Automated styling update from server

---

src/components/NcHeaderMenu/NcHeaderMenu.vue

Manual backport of #7370
Had to move some thing around

[stable8] fix(NcHeaderMenu): pause trap stack on opening

---

src/assets/status-icons/user-status-away.svg
src/assets/status-icons/user-status-busy.svg
src/assets/status-icons/user-status-dnd.svg
src/assets/status-icons/user-status-invisible.svg
src/assets/status-icons/user-status-online.svg
src/components/NcUserStatusIcon/NcUserStatusIcon.vue

- Follow-up to #7392
```diff
- --color-icon-online
+ --user-status-color-online
```

fix(NcUserStatusIcon): adjust scoped names for style variables

---

package-lock.json
package.json
src/functions/usernameToColor/index.ts
tests/unit/functions/usernameToColor/__snapshots__/usernameToColor.spec.ts.snap

- Revert changes from dropping md5 library in #6657
---|---

fix(usernameToColor): restore original color algorithm

---

l10n/messages.pot
src/components/NcColorPicker/NcColorPicker.vue
src/utils/colors.ts

- Resolves https://github.com/nextcloud-libraries/nextcloud-vue/issues/4037
Allow to clear the selected color:
- palette can be unchecked
- custom color can be cleared

feat(NcColorPicker): allow to clear selected value

---

.github/workflows/server-styling-update.yml

- use scoped branch name to prevent conflicts if both branches are updates
- use correct committer and author for DCO
- add source of the app styles

ci: fix server styling update

---

src/components/NcAvatar/NcAvatar.vue

- Forward port of https://github.com/nextcloud-libraries/nextcloud-vue/pull/7561
---|---
n/a | n/a

fix(NcAvatar): log the error object

---

styleguide/assets/default.css

Auto-generated update of our locally cached css styling from
* https://nextcloud.github.io/server/apps/theming/css/default.css
* https://nextcloud.github.io/server/core/css/server.css
* https://nextcloud.github.io/server/core/css/apps.css
* https://nextcloud.github.io/server/dist/icons.css

[main] chore(docs): Automated styling update from server

---

styleguide/assets/default.css

Auto-generated update of our locally cached css styling from
* https://nextcloud.github.io/server/apps/theming/css/default.css
* https://nextcloud.github.io/server/core/css/server.css
* https://nextcloud.github.io/server/core/css/apps.css
* https://nextcloud.github.io/server/dist/icons.css

[stable8] chore(docs): Automated styling update from server

---

CHANGELOG.md
package-lock.json
package.json

Align with #7620 to get the fixes also for v9

chore: prepare release of v9.0.1

---

CHANGELOG.md

[stable8] chore: adjust heading in changelog to match version
