src/components/NcModal/NcModal.vue
|![2023-07-27_21-30_1](https://github.com/nextcloud/nextcloud-vue/assets/14975046/b0c719c4-0fcd-4119-981f-39cc71e1c2fa)|![2023-07-27_21-30](https://github.com/nextcloud/nextcloud-vue/assets/14975046/5b85c12c-ad84-47f3-b657-47a060a9e39d)|
=> fix(NcModal): prev/next color and sizing fix

l10n/messages.pot, src/components/NcEmojiPicker/NcEmojiPicker.vue
Backport of #4381.
In collectives pages optionally have an emoji set. Once this is set there is currently no way to remove it.
Enhance the emoji picker to show the currently selected emoji and enable unselecting it to clear the previous selection.
See also:
* https://github.com/nextcloud/collectives/issues/422
* https://github.com/serebrov/emoji-mart-vue/issues/253#issuecomment-1585978632
=> [stable7] enh(emoji-picker): allow unselecting set emoji

src/components/NcButton/NcButton.vue
We sometimes need to change the alignment of icon and text of the button, currently this is dirty-hacked by using `:deep` selectors. Examples are the column headers on tables (file list, logreader, file picker).
=> NcButton: Add alignment property to change icon and text ordering

src/components/NcButton/NcButton.vue
Continuation of the discussion of #4366 
This adds the example from @ShGKme which is more complete for showing all supported property values.
So do we want to show all supported types or only the default ones?
From my point of view there is no benefit in hiding, but we should rather have a line in the style guide when to use which button type. (Because even before this feature was available users of the library simply hacked this behavior).
=> fix(NcButton): Improve alignment documentation to show all variants.

cypress/component/modal.cy.ts, src/components/NcModal/NcModal.vue
* Fix #3118
Ensures that the close button of the modal is always visible, even if the content overflows the container and is scrolled.
:test_tube: Cypress test included.
=> fix(NcModal): Close button should be visible even if modal content is scrolled

l10n/messages.pot, src/components/NcRichText/NcReferencePicker/NcSearch.vue
=> fix(l10n): Remove quoting character 

styleguide.config.js
The `NcMultiselect` component was removed from the library, this PR removes its leftover from the styleguide config.
=> fix: remove NcMultiselect from styleguide config

package.json
This adds a build step to build the module in development mode. Before, `npm run dev` would not build the module, preventing the library from being used, e.g. via `npm link` while developing.
=> fix: build module on dev

src/components/NcRichContenteditable/NcRichContenteditable.vue, tests/unit/components/NcRichContenteditable/NcRichContenteditable.spec.js
* Fix https://github.com/nextcloud/server/issues/37087
**The solution in this PR is different from the suggestion in the linked issue.**
Using `aria-describedby` requires a layout update, adding a wrapper element for `NcRichContenteditable` with the `div[contenteditable]` itself and a new visually hidden describing element. Though the layout of the element is not a part of its public interface, I think developers expect the component to be a directly `contenteditable` element and I prefer to keep current simple layout as long as it's possible.
A good and very simple alternative solution IMO is [`aria-placeholder`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-placeholder).
---|---
=> fix(NcRichContenteditable): add aria-placeholder

src/components/NcModal/NcModal.vue
* Fix https://github.com/nextcloud/server/issues/39415
Two problems with focus trap break navigation with modal.
**Problem 1:** When Viewer is opened with sidebar, focus on the sidebar is not possible
Source: `additionalTrapElements` are not used on init but only on change. 
**Problem 2:** `NcModal` intercept arrow navigation for slider (next/prev)
https://github.com/nextcloud-libraries/nextcloud-vue/assets/25978914/abd9cf42-73bc-4cae-be4f-ebd49bb2b656
https://github.com/nextcloud-libraries/nextcloud-vue/assets/25978914/cae07f32-b44b-42c6-bb40-ee3dac0e59a5
https://github.com/nextcloud-libraries/nextcloud-vue/assets/25978914/7bea1fb3-4618-486a-ab83-6bca3374ad2c
- If there is an element and it's outside the modal, then it is
- either element from `additionalTrapElements`
- or some pop over …
=> Fix modal focus trap with additional elements and arrow navigation

vite.config.mts
* Fix https://github.com/nextcloud-libraries/nextcloud-vue/pull/4428#issuecomment-1681039520
Without this the `SCOPE_VERSION` is interpreted as octal number (because the md5 hash generated from version `8.0.0-beta.3` starts with 0.
=> fix(build): Replaced `SCOPE_VERSION` variable need to be stringified

src/components/NcSelect/NcSelect.vue
* Fixes part of https://github.com/nextcloud/server/issues/36980 regarding "the keyboard focus in the list is not noticeable.", see https://github.com/nextcloud/server/issues/36980#issuecomment-1669768669
---|---
=> Fix contrast for selected item

src/components/NcListItem/NcListItem.vue
* Fix #nextcloud/spreed#10210
* Before component:
* ...creates an empty `<span>` wrapper and fill it with children conditionally;
* ...removes wrapper on hover (or if menu actions are forced) - look at bold text jumping;
* After component:
* ...creates wrapper only if children should be there, otherwise skips;
* ... hides wrapper with `display: none` on hover
---|---
=> fix(`NcListItem`) - remove empty wrapper for additional elements from DOM if not needed

package.json
Fixes eslint issues of libraries using the package like:
> "@nextcloud/vue/dist/Components/NcButton.js" is not found        n/no-missing-import
Using directory exports is deprecated since Node 14, instead wildcard exports should be used.
This causes eslint-plugin-n to fail because it does not support the deprecated syntax.
See server PR as example of failing lint: https://github.com/nextcloud/server/actions/runs/5908640226/job/16028330790?pr=39970
=> fix: `exports` field of package used deprecated syntax

src/components/NcListItem/NcListItem.vue
=> [stable7] fix(NcListItem) - remove empty wrapper for additional elements from DOM if not needed

src/components/NcActionTextEditable/NcActionTextEditable.vue
Replace `strong` with `label`
The text is now not bolded which is consistent with the action input visible label
---|---
=> Add accessible label to textarea

src/components/NcAppSidebar/NcAppSidebarTabs.vue, src/components/NcCounterBubble/NcCounterBubble.vue, src/components/NcListItem/NcListItem.vue
* Fix [#4034](https://github.com/nextcloud-libraries/nextcloud-vue/issues/4034)
---|---
|
=> Remove border from sidebar tabs

src/components/NcActions/NcActions.vue
Backport https://github.com/nextcloud-libraries/nextcloud-vue/pull/4447
=> [stable7] Prevent accessible name conflicts on action menu

src/components/NcActionLink/NcActionLink.vue
- For https://github.com/nextcloud/server/issues/37093
=> Add menuitem role to action link

package-lock.json, package.json, src/components/NcBreadcrumbs/NcBreadcrumbs.vue
* This PR fixes an issue with the breadcrumbs component where the `getWidth` function errors because it uses `.elm` on a `vnode` which might not be defined. The PR is basically a backport of the changes I did for the `NcBreadcrumbs` component in the `vue3` branch. The PR still needs some cleanup and fine-tuning, but it seems to fix the error.
@susnux The hidden breadcumbs in the action menu currently don't work as they should. The breadcrumbs component might need to be adjusted, but I still need to figure out what's the problem.
=> fix: adjust breadcrumbs component

src/components/NcSelect/NcSelect.vue
> TypeError: _nextcloud_vue_select__WEBPACK_IMPORTED_MODULE_4__.props is undefined
With mixed exports the default is not imported but the whole exports object, can be tested with a simple script.
Just name this script `some-name.mjs` and run `node ./some-name.mjs` (of cause in that directory must be a node_modules with `@nextcloud/vue-select` installed).
```js
import VueSelect from '@nextcloud/vue-select'
console.warn(VueSelect)
```
=> fix(NcSelect): Use named export of VueSelect to prevent issues when imported in ESM projects

package-lock.json, package.json, src/components/NcBreadcrumbs/NcBreadcrumbs.vue
Manual backport of #4416 since as far as I know the new vue filepicker in 27.1. still has to rely on stable7 of nextcloud/vue.
=> [stable7] fix(NcBreadcrumbs): adjust component for vue filepicker

src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
We use the NcCheckboxRadioSwitch also for e.g. the files list in the FilePicker and the files app, on the table no text is used.
But even if the text is empty the element is still displayed, resulting in an oval shape of the hover state and focus visible outline.
Moreover we use 24x24px icons for checkboxes and radio, so the padding was incorrectly set as if we use 20x20px icons.
---|---
=> fix(NcCheckboxRadioSwitch): If no text is provided the element should be a circle

src/components/NcModal/NcModal.vue, tests/unit/components/NcModal/modal.spec.js
Currently the modal is closed if `canClose` is `true` and the user clicked outside the modal on the backdrop. This can now be configured with the `closeOnClickOutside` property (defaults to `true` for backwards compatibility).
This is especially helpful for implementing the dialogs.
=> feat(NcModal): Allow to configure if the modal is closed when clicked outside

src/components/NcRichText/NcRichText.vue
* Markdown eats newlines (`Enter`, `Shift+Enter`), because rendered `<span/>` element doesn't contain symbols, so it's `height === 0`
* For newline (several `\n\n` in a row) - we paste no-break space (unicode `\u00A0`) between to fill the line
* Also replaced ~~strikethrough~~ with `inline code`, as we don't support it yet
🏚️ Before
[Screencast from 24.08.2023 14:27:11.webm](https://github.com/nextcloud-libraries/nextcloud-vue/assets/93392545/8fa83492-da04-4abe-91a7-c644cedff4fe)
🏡 After
[Screencast from 24.08.2023 14:26:17.webm](https://github.com/nextcloud-libraries/nextcloud-vue/assets/93392545/cb12c42c-6b0e-4071-bd42-ed1c40118249)
=> fix(`NcRichText`) - keep newlines in rendered Markdown 

src/components/NcRichText/NcRichText.vue
=> [stable7] fix(`NcRichText`) - keep newlines in rendered Markdown 

CHANGELOG.md, src/components/NcActionInput/NcActionInput.vue, src/components/NcInputField/NcInputField.vue, src/components/NcPasswordField/NcPasswordField.vue, src/components/NcTextField/NcTextField.vue
Alternative to #4287 as requested by @marcoambrosini 
https://github.com/nextcloud-libraries/nextcloud-vue/assets/1855448/20b1cb4e-9f5a-4e27-98c5-b3cc4a9e2124
=> Feature: Add visible inner label for `NcInputField` on border

cypress/component/richtext.cy.ts, src/components/NcRichText/NcRichText.vue
=> [stable7] fix(`NcRichText`) - don't populate a first newline to properly parse blockqoute tags

cypress/component/richtext.cy.ts, src/components/NcRichText/NcRichText.vue
* Regression from  #4461
* Condition for `<blockqoute/>` was broken, as at least one line after it should be empty
* Added Cypress tests based on https://www.markdownguide.org/basic-syntax and https://github.com/nextcloud-deps/CDMarkdownKit/tree/master/CDMarkdownKitTests
---|---
=> fix(`NcRichText`) - don't populate a first newline to properly parse blockqoute tags

src/components/NcAppSidebar/NcAppSidebarTabs.vue, src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue, tests/unit/components/NcAppSidebar/NcAppSidebarTabs.spec.js
- For https://github.com/nextcloud/server/issues/37107
- Remove redundant `nav` for element with tablist role
> MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav
- Remove radios in favour of input with `type="button"`
> MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/button
> In theory, this could lead to issues.
> —michaelnissenbaum
Ref: https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-automatic/#sc1_label
=> fix(a11y): Remove nav and radios in sidebar tabs

src/components/NcSelect/NcSelect.vue
Followup https://github.com/nextcloud-libraries/nextcloud-vue/pull/4434
---|---
=> fix(NcSelect): Do not add border to single select option

src/components/NcActionInput/NcActionInput.vue
https://github.com/nextcloud-libraries/nextcloud-vue/pull/4394 introduced a change that having the label outside of the input is no longer possible with NcActionItem
In previous versions the label was shown above the input which gives the
text more space which might be better than the inline label from
https://github.com/nextcloud-libraries/nextcloud-vue/pull/4394 in some
scenarios.
This is a breaking change as it renames the previous labelVisible
property to a labelOutside property. The label should always be visible
with the new NcInputField, however we can optionally decide to have the
label outside.
Found in https://github.com/nextcloud/text/pull/4663
=> Bring back label outside of the input for NcActionInput

src/components/NcRichContenteditable/NcRichContenteditable.vue
* Raise awareness how the component handles and transfers strings
* May help to identify some issues before they reach release
* Cover frequent usecases:
* render as a simple message 
* send to server with `JSON.stringify()`
* interact with `<NcRichText />` (with markdown enabled)
---|---
=> feat(`NcRichContenteditable`) - add different output appearance in examples 

src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
|![2023-08-31_08-41](https://github.com/nextcloud-libraries/nextcloud-vue/assets/14975046/c981154f-e5cf-4927-9e24-f446cf4d12f7)|![2023-08-31_08-40](https://github.com/nextcloud-libraries/nextcloud-vue/assets/14975046/e1eb43c6-1545-4791-8e79-0a853abbe93c)|
|![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/14975046/878e2391-5c4c-4a63-bf90-951258dba2b0)|![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/14975046/696ca45e-1f87-4944-8567-d04639b2f419)|
=> feat and fix: `NcCheckboxRadioSwitch` `required` prop and input position fix

src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
---|---
I did not align the label of `NcCheckboxRadioSwitch` `type="switch"`, because it has a wider icon and aligning it does not really work well.
=> Align NcCheckboxRadioSwitch labels

src/components/NcEmptyContent/NcEmptyContent.vue
|![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/14975046/17993bbe-da58-4eb2-9139-0b321006e44d)|![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/14975046/336173c6-738c-45e9-9899-0997896d9288)|
There is a conflict when used with the `NcIconSvgWrapper`
=> fix(EmptyContent): svg max size

styleguide.config.js
=> feat: add `v8.x (Nextcloud 28)` as latest docs title

src/components/NcAppNavigationCaption/NcAppNavigationCaption.vue
Forward listeners to NcActions
=> enh(NcAppNavigationCaption): Forward listeners

src/components/NcRichContenteditable/NcRichContenteditable.vue
(cherry picked from commit 31db00d409bbd4ff02bb7ec020cda215350c57f7)
Backport of #4485
=> [stable7] feat(NcRichContenteditable) - add different output appearance in examples

l10n/messages.pot, src/components/NcRichContenteditable/NcRichContenteditable.vue
* A part of fixing https://github.com/nextcloud/server/issues/37087
* Used in https://github.com/nextcloud/server/pull/40294
* Alternative to https://github.com/nextcloud-libraries/nextcloud-vue/pull/4482
The default placeholder is very long, because it is not a placeholder, but a description with instructions of using the input.
This PR proposes to remove the instruction from the default placeholder.
In case of merging this PR we need to find a way to explain users what they can do with the input at least with user documentation.
See discussion in the issue.
---|---
=> fix(NcRichContenteditable): make the default placeholder short

src/components/NcDashboardWidget/NcDashboardWidget.vue, src/components/NcEmptyContent/NcEmptyContent.vue, src/components/NcRichText/NcReferencePicker/NcProviderList.vue, src/components/NcRichText/NcReferencePicker/NcRawLinkInput.vue, src/components/NcRichText/NcReferencePicker/NcSearch.vue
By default `NcEmptyContent` displays the content with fixed 20vh top margin. This doesn't look good sometimes. I think that could be useful to have centered `NcEmptyContent`.
For example, by default, it looks bad in comments, where the default margin is overridden now with `!important`. 
Current `!important` override | Default styles | New `centered`
---|---|---
Or in Talk.
Large screen (almost centered, but not) | Small screen (cut, but there is space)
---|---
---|---
Also still works:
NcAppSidebar | ReferencePicker
---|---
- `NcHeaderMenu`, `NcDashboardWidget` - custom styles, nothing breaking
- `NcAppSidebar` - works fine by default because of flex
- `NcReferencePicker`: `NcProviderList`, `NcRawLinkInput`, `NcSearch` - remove unnecessary `margin: 0`, works fine now …
=> feat(NcEmptyContent)!: make empty content centered by default instead of 20vh margin

src/directives/Focus/index.js, src/index.js, styleguide.config.js, styleguide/preview.js, webpack.config.js
This migrates the `Focus` directive to vue 3.
=> chore(vue3): Migrate Focus directive, globally import Tooltip in docs

src/utils/isSlotPopulated.js, tests/unit/utils/isSlotPopulated.spec.js
This adds a unit test for the `isSlotPopulated` util. This util is made to check whether a slot actually contains content. I also slightly changed it to check whether there is only an empty Text node.
In vue 3 the usual way used in vue 2 does not work anymore.
Both `!!this.$slots.default` and `!!this.$slots.default?.()` will basically always be `true`.
=> chore(vue3): add unit test for isSlotPopulated

package-lock.json, package.json, styleguide.config.js, vite.config.mts, webpack.config.js
With this PR all dist files will be built using Vite, see todo for rest of webpack.
* Final step for building with Vite.
* Follow up on #4329 and #4276 
*(previously this PR was breaking, but this is changed):*
<details>
:warning:  This is a breaking change!
This simply adds more entry points, which is good as now code can be shared between the entry points which allows for smaller app bundles. But as this also introduces ESM entry points for all components it changes the file extensions from `.js` to `.cjs` and `.mjs` respective.
Because of this I think we should take the opportunity and move from `/dist/Components/...` to simply `/components/...`.
This will also make it easier when we decide to provide Typescript definitions as then the same layout of *dist* as of *src* is used.
So this …
=> Migrate build of single entry points from webpack to vite

src/components/NcHeaderMenu/NcHeaderMenu.vue
- For https://github.com/nextcloud/server/issues/37095
- Add opt-in `nav`
- Remove role semantics, ref: https://inclusive-components.design/menus-menu-buttons/#themenuandmenuitemroles
=> enh(a11y): Add nav to header menu

src/components/NcRichContenteditable/NcRichContenteditable.vue, src/components/NcRichText/NcRichText.vue
* Extend docs (follow-ups from https://github.com/nextcloud-libraries/nextcloud-vue/pull/4485):
* NcRichContenteditable - render mentions in NcRichText
* NcRichText - add example with NcRichContenteditable usage
Commits were separated from #4486 
---|---
"-" | NcRichContenteditable docs
"-" | NcRichText docs
=> feat(docs) - add cross-examples for rich components in docs, add mention support

CHANGELOG.md, package-lock.json, package.json
* feat(NcEmptyContent)!: make empty content centered by default instead of 20vh margin by @ShGKme in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4506
* Bring back label outside of the input for NcActionInput by @juliushaertl in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4484
* feat(`NcRichContenteditable`) - add different output appearance in examples  by @Antreesy in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4485
* perf(NcEmojiPicker): decrease mounting time and memory by moving large constants initialization and storing out from instance's reactive data by @ShGKme in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4479
* enh(NcAppNavigationCaption): Forward listeners by @Pytal in …
=> v8.0.0-beta.6

package-lock.json, package.json
* Fix https://github.com/nextcloud/server/pull/40451#issuecomment-1722091298
=> chore(deps): Update `@nextcloud/vite-config` to fix styles included in `.mjs` files

package.json
* Fix _none_
We use `npm run watch` in most apps so it would be nice to keep the standard. I don't see any downsides to this other than one more line of json.
=> chore(pkgjson): alias dev:watch to watch

src/components/NcAppNavigation/NcAppNavigation.vue
* Fix #4433
Make only the content of the navigation inert when closed but not the wrapper which includes the toggle
https://github.com/nextcloud-libraries/nextcloud-vue/assets/1855448/d0fabf66-49db-4963-94ff-f7a3374420ca
=> fix(NcAppNavigation): Make the navigation toggle accessible again when closed

src/components/NcDatetimePickerNative/NcDatetimePickerNative.vue, src/components/NcDatetimePickerNative/index.js, src/components/index.js, styleguide.config.js
This migrates `NcDatetimePickerNative` to vue 3.
I also renamed `NcDateTimePickerNative` to `NcDatetimePickerNative`, because it always bothered me, that we have a `NcDatetimePicker` and a `NcDateTimePicker*`.
=> feat(vue3): Migrate NcDatetimePickerNative

src/components/NcInputField/NcInputField.vue, src/components/NcPasswordField/NcPasswordField.vue, src/components/NcTextField/NcTextField.vue
@ShGKme What do you think of this approach:
We rename the `default` slot of `NcInputField` to `icon` and then simply use `!!$slots.icon` as you proposed. This way, one anyway has to wrap the content for the `icon` slot in a `template` tag and it is easier to explain that one has to use `v-if` on the `template` when toggling the existence of an icon.
This then makes everything reactive without the need for an overkill solution, no?
And I think renaming to `icon` anyway makes sense, since it makes it clearer that it's, well, for an icon.
=> chore(vue3): Nc*Field rename default to icon slot

package-lock.json, package.json, src/components/NcSettingsSelectGroup/NcSettingsSelectGroup.vue
* Fix https://github.com/nextcloud-libraries/nextcloud-dialogs/issues/885
If there is a loading error, then we can simply add a error info text below the component.
This was the only place where we used the dialogs library, so by changing the error handling here we can drop the dependency and prevent a circular dependency issue.
=> fix(NcSettingsSelectGroup): Prevent circular dependency with `@nextcloud/dialogs`

src/components/NcEmojiPicker/NcEmojiPicker.vue
The "hacked" padding into the label broke when we introduced the internal label, so remove the custom styles on the label.
Focus on the search input label:
---|---
=> fix(NcEmojiPicker): Do not set padding for the search input label

src/components/NcEmojiPicker/NcEmojiPicker.vue
The default is to display the emoji from a remote data source, which we don't want (and is prohibitted by our CSP anyway).
I tested this while implementing https://github.com/nextcloud/collectives/issues/422.
=> fix(NcEmojiPicker): Set type to `native` for selected emoji

src/components/NcEmojiPicker/NcEmojiPicker.vue
The default is to display the emoji from a remote data source, which we don't want (and is prohibitted by our CSP anyway).
Manual backport of https://github.com/nextcloud-libraries/nextcloud-vue/pull/4575
=> [stable7] fix(NcEmojiPicker): Set type to `native` for selected emoji

src/components/NcDateTimePickerNative/NcDateTimePickerNative.vue, src/components/NcDateTimePickerNative/index.js, src/components/index.js, styleguide.config.js
Rename `NcDatetimePickerNative` to `NcDateTimePickerNative`.
=> fix(vue3): Rename `NcDatetimePickerNative` to `NcDateTimePickerNative`

src/components/NcPopover/NcPopover.vue
This fixes the `$attrs` inheritance for `NcPopover`. in #4511 I forgot to re-enable the automatic inheritance, that was explicitly disabled before. This fixes it.
=> fix(vue3): Inherit `$attrs` to `Dropdown` in `NcPopover`

CHANGELOG.md, package-lock.json, package.json
* chore!: Rename `Datetime` to `DateTime` in component names by @susnux in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4560
* fix(NcAppNavigation): Make the navigation toggle accessible again when closed by @susnux in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4546
* fix: Replace sanitize-svg with dompurify by @raimund-schluessler in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4557
* fix(NcEmojiPicker): Do not set padding for the search input label by @susnux in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4577
* fix(NcEmojiPicker): Set type to `native` for selected emoji by @mejo- in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4575
* fix: also export NcSettings* components by @raimund-schluessler in …
=> v8.0.0-beta.7

jest.config.js, src/components/NcEmojiPicker/NcEmojiPicker.vue, src/components/index.js, styleguide.config.js
This migrates `NcEmojiPicker` to vue 3 and pulls in two commits from `master`.
=> chore(vue3): Migrate NcEmojiPicker

src/components/NcEmptyContent/NcEmptyContent.vue, src/components/index.js, styleguide.config.js
This migrates `NcEmptyContent` to vue 3.
=> chore(vue3): Migrate NcEmptyContent

src/components/NcSettingsSection/NcSettingsSection.vue
* Fix https://github.com/nextcloud/server/issues/40704
Before | After
---|---
`heading level 2` | `External documentation for Two-Factor Authentication visited link heading level 2`
=> fix(NcSettingsSection): remove incorrect role=note on doc link

src/utils/IsMobileState.js
Currently it otherwise will always be imported because the treeshake algorithm can not decide if running the Vue constructor has any sideeffects.
(saves a few bytes on projects not using it)
=> fix(utils): Make `isMobileState` PURE so it can be treeshaken if not used

src/components/NcAppNavigationNew/NcAppNavigationNew.vue
* Fix #4551
* Fix https://github.com/nextcloud/polls/issues/3082
---|---
=> allow type property for NcAppNavigationNew

src/components/NcEmptyContent/NcEmptyContent.vue
Since we had to explicitly set the icon size of `NcIconSvgWrapper` in #4557 to make it work on iOS, we now have to overwrite it here to not rely on the order of the files bundling.
=> fix(EmptyContent): ensure proper custom icon size

src/assets/variables.scss, src/components/NcAppContent/NcAppContent.vue, src/components/NcAppNavigation/NcAppNavigation.vue, src/components/NcAppNavigationToggle/NcAppNavigationToggle.vue
Currently the toggle is set at `4px` while the app navigation items are placed at `8px` (using that variable), this looks slightly displaced.
So this PR moves the padding calculation into a variable and uses the variable for the toggle (besides the navigation items).
**Before / Currently:**
**After / This PR:**
=> Properly align AppNavigationToggle with first navigation item

src/components/NcHeaderMenu/NcHeaderMenu.vue
Remove id from header menu trigger button when unused
=> fix: Remove unused id from trigger

src/components/NcSelect/NcSelect.vue
* Fix https://github.com/nextcloud/server/issues/37098 (Page files)
VueSelect generates unique IDs for some elements. But it is just [auto-increment id](https://github.com/sagalbot/vue-select/blob/857753655adbebae612518aab072ed7f4a8deaa0/src/utility/uniqueId.js). For example, `#vs1-compobox`.
It works fine while only one copy of VueSelect (`@nextcloud/vue`) is used. Otherwise, there are several VueSelects with their own uid sequence. Then there are many `#vs1-compobox` elements on the page.
This PR defines a default value for [VueSelect.uid](https://vue-select.org/api/props.html#uid) with a random string.
Now nc-selects have IDs like `#vs-wxtrv-compobox`
=> fix(NcSelect): make id truly uniqual

src/components/NcIconSvgWrapper/NcIconSvgWrapper.vue, tests/unit/components/NcIconSvgWrapper/NcIconSvgWrapper.spec.js
* Fix https://github.com/nextcloud/server/issues/37098 (many pages)
All material design icons from [`@mdi`](https://github.com/Templarian/MaterialDesign-SVG) have ID attribute. It seems to be used by material design icons for web-font generation, but not needed in our apps and creates multiple duplicated IDs.
This PR removes the ID using DOM parser.
=> feat(NcIconSvgWrapper)!: remove ID from svg

src/components/NcDateTimePickerNative/NcDateTimePickerNative.vue
* Fix _none_
The native date time picker doesn't handle empty values gracefully. Currently, there will be errors in the console due to a failing type check.
The style guide now renders the currently selected value. Have a look at it on the preview:
https://deploy-preview-4540--nextcloud-vue-components.netlify.app/#/Components/NcPickers?id=ncdatetimepickernative
_Links are apparently broken. You may need to scroll to the NcDateTimePickerNative manually._
It should render a date if one is selected and null otherwise.
---|---
B | A
=> fix: handling of empty values in NcDateTimePickerNative

src/components/NcIconSvgWrapper/NcIconSvgWrapper.vue, tests/unit/components/NcIconSvgWrapper/NcIconSvgWrapper.spec.js
* Fix https://github.com/nextcloud-libraries/nextcloud-vue/pull/4607#discussion_r1346379815
This prop should not be needed because no code should use ID on SVG, they are not unique
=> fix(NcIconSvgWrapper): remove new keepId prop

src/components/NcInputField/NcInputField.vue
From today's design review call:
* Add note that the internal label is only recommended when the background matches
* Make border of the internal label rounded (needed to adjust the padding as well)
* Perfect pixel align label, placeholder and content
(added background color to make the border more visible, e.g. like on the login)
---|---
=> fix(NcInputField): Adjust styling of the internal label

src/components/NcDateTimePickerNative/NcDateTimePickerNative.vue
=> [stable7] fix: handling of empty values in NcDateTimePickerNative

package-lock.json, package.json
Don't explicitly install `vue-template-compiler`.
=> fix: remove unused vue-template-compiler

package-lock.json, package.json
- Fixes Cypress + CalDavSettings CI errors in https://github.com/nextcloud/server/pull/40692
=> chore: Bump @nextcloud/vite-config to fix cjs require default

CHANGELOG.md, package-lock.json, package.json
* feat(NcIconSvgWrapper)!: remove ID from svg by @ShGKme in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4607
* fix(NcSettingsSection): remove incorrect role=note on doc link by @ShGKme in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4594
* fix(utils): Make `isMobileState` PURE so it can be treeshaken if not used by @susnux in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4595
* allow type property for NcAppNavigationNew by @dartcafe in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4555
* fix(EmptyContent): ensure proper custom icon size by @raimund-schluessler in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4584
* Properly align AppNavigationToggle with first navigation item by @susnux in …
=> v8.0.0-beta.8

cypress.config.ts
This migrates the cypress tests from `webpack` to `vite`. The only component left that still uses the `webpack` config is the `styleguide` now.
~@susnux I wanted to migrate `cypress` from `webpack` to `vite`, but I cannot seem to import the `vite.config.mts` file, no matter how I try (with or w/o extension, all extensions possible). Do you have any hint?~ Nevermind, it turns out one does not even need to explicitly import the `vite` config.
=> [next] feat(cypress): use vite instead of webpack

src/components/NcListItem/NcListItem.vue
* Fix #4625 
* NcListItem now has correct colors for hover states when active or not
* Padding was adjusted for content to be inscribed in a circle and even horizontal-vertical visual paddings
Top to bottom: `.active`, `.active:hover`, `.active:focus`, `.active:focus-visible`
---|---
=> fix(NcListItem): adjust paddings and hover styles for list items

src/components/NcActionInput/NcActionInput.vue, src/components/NcPasswordField/NcPasswordField.vue
- Set default trailing button label to match click handler `"$refs.form.requestSubmit()"` behaviour
- Remove redundant NcPasswordField props
=> fix(NcActionInput): Set default trailing button label

src/components/NcEmojiPicker/NcEmojiPicker.vue, src/components/NcInputField/NcInputField.vue, src/components/NcPasswordField/NcPasswordField.vue, src/components/NcTextField/NcTextField.vue
This migrates the `Nc*Field` components to use `modelValue` instead of `value`. This allows to simply use `v-model="text"` instead of `v-model:value="text"`. 
Depending on what gets merged first, either this PR or #4646 need to be adjusted.
=> [next] feat(Nc*Field): migrate from `value` to `model-value`

package-lock.json, package.json, src/components/NcIconSvgWrapper/NcIconSvgWrapper.vue
This allows to render raw SVG paths which prevents the overhead of having to sanitize the SVG icon for use in `v-html`.
=> feat(NcIconSvgWrapper): allow to render raw svg paths

src/components/NcRichText/NcRichText.vue
Fixes a missing trailing comma. Honestly, I am not really convinced there should be a comma, but it makes `eslint` happy :man_shrugging:
=> fix: missing trailing comma

src/components/NcModal/NcModal.vue
* Fix #4627 
* Fix https://github.com/nextcloud-libraries/nextcloud-vue/issues/3117
1. Revert hack to make unused buttons invisible instead of setting `display: none`
The buttons are placed absolute, therefor they do not interact with the modal container and content.
Meaning even if only on button is shown the modal is centered correctly.
2. Ensure the modal header does not overflow the modal content
The modal height is max. 90%, but if the window is not that tall or the modal is tall, then the header might overlap the content. So fix this by setting the modal max. height to 100% - 2*modal-header (because of the centered placement).
3. Ensure the close button is always clickable and not covert by content. (simply setting a z-index on it).
You can see the header no longer overflows the …
=> fix(NcModal): Some modal improvments

src/components/NcAppSettingsDialog/NcAppSettingsDialog.vue, src/components/NcDialog/NcDialog.vue, src/components/NcDialog/index.js, src/components/NcDialogButton/NcDialogButton.vue, src/components/NcDialogButton/index.js, src/components/index.js, styleguide.config.js
* Fix #631 
* Fix #4348 (fixed by migrating AppSettingsDialog to NcDialog base)
* Replace https://github.com/nextcloud-libraries/nextcloud-vue/pull/4415 (without Typescript and fancy `<script setup>`).
Introduces NcDialog as a generic base Dialog component, while NcModal is simply a base for modals like the viewer, NcDialog provides a convenient interface to define dialogs (see example).
The new FilePicker of the `@nextcloud/dialogs` package is based on top of it.
One example dialog:
=> feat(NcDialog): New component (moved from `@nextcloud/dialogs`)

src/assets/action.scss, src/components/NcActionButton/NcActionButton.vue, src/components/NcActionLink/NcActionLink.vue, src/components/NcActionRouter/NcActionRouter.vue, src/components/NcActionText/NcActionText.vue, src/components/NcActions/NcActions.vue, src/mixins/actionText.js
- For https://github.com/nextcloud/server/issues/37130
- Remove aria-expanded when closed, https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/examples/menu-button-actions-active-descendant/
- Use span for long text
- Remove button presentation role
- Remove empty aria-label attr
=> fix(NcActions): Various accessibility improvements

cypress/component/NcSelect.cy.ts, src/components/NcListItemIcon/NcListItemIcon.vue, src/components/NcSelect/NcSelect.vue, tests/unit/components/NcListItemIcon/list-item-icon.spec.ts
* Fix #4491 
Allows to filter by the email notation like `Jane <j.doe@example.com>`
=> feat(NcSelect): Allow to filter users by email notation

src/components/NcBreadcrumbs/NcBreadcrumbs.vue
* Part of https://github.com/nextcloud/server/issues/36965
* Fixes "Add" button is far away
| ![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/6078378/e01ae8db-5881-4c4d-b2bd-aa5baf0c619d) | ![Screenshot from 2023-10-18 16-15-54](https://github.com/nextcloud-libraries/nextcloud-vue/assets/6078378/c992734a-3a58-4591-b31b-cddc0e7ada95)
=> Fix NcBreadcrumbs styles to wrap buttons

src/components/NcDashboardWidgetItem/NcDashboardWidgetItem.vue
When `NcDashboardWidgetItem` has empty `targetUrl`, it is rendered as `div`, but still has `href=""` which is not a valid HTML
=> fix(NcDashboardWidgetItem): do not assign href="" with empty link

src/components/NcActions/NcActions.vue
Currently for some reason all props of `NcActions` are passed twice to `NcPopover`: as props and as attrs
https://github.com/nextcloud-libraries/nextcloud-vue/blob/d93993902c86fdc78403479b377242a17910cc50/src/components/NcActions/NcActions.vue#L1080-L1105
But `popoverBaseClass` is not a `NcPopover` prop but `NcActions` own prop. It should not be passed as an attribute. It results with an invalid `popoverbaseclass` attribute on an HTML element.
=> fix(NcActions): do not pass popoverBaseClass as an attr to NcPopover

src/components/NcActions/NcActions.vue, tests/unit/components/NcActions/NcActions.spec.ts
Currently inline action do not receive the attributes set on them, this PR allows to set e.g. `data-test-id` to buttons for integration tests.
=> fix(NcActions): Allow to set attributes to inline actions

src/components/NcAppSidebar/NcAppSidebarTabs.vue, src/components/NcAppSidebarTab/NcAppSidebarTab.vue, src/components/NcCheckboxRadioSwitch/NcCheckboxContent.vue, src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue, tests/unit/components/NcAppSidebar/NcAppSidebarTabs.spec.js
- For https://github.com/nextcloud/server/issues/37107
---|---
- Fix glitchy <kbd>Tab</kbd> + <kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd> navigation, now only <kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd> will change tab focus
- Fix tabpanel association
- Test on server
- Test with NVDA
- Update tests
> No visual changes
=> enh(NcAppSidebarTabs): Make tab navigation accessible

src/components/NcAvatar/NcAvatar.vue
It is required to allow using avatar as a phrasing content, for example, as a button content.
> **Error: Element [`div`](https://html.spec.whatwg.org/multipage/#the-div-element) not allowed as child of element [`button`](https://html.spec.whatwg.org/multipage/#the-button-element) in this context. (Suppressing further errors from this subtree.)**
Sometimes we use `NcAvatar` as a button content, for example, as a Popover trigger on the main UserMenu.
HTML does not allow this. Button should have only so-called phrasing (aca inline text) content.
This PR makes `NcAvatar` a `span` instead of a `div`. 
For some places it doesn't change anything in the layout, because it has `display: inline-block`, or `position: absolute`. In other …
=> fix(NcAvatar): make it a span phrasing element

src/components/NcModal/NcModal.vue
Do not close all modals if escape is pressed while multiple layered modals are open, e.g. viewer and help dialog or filepicker from text
Steps to reprocuce:
- Open a markdown file in viewer
- Open the formatting help through the menu bar
- Press Escape
=> fix: Avoid closing all modals on escape if multiple are present

src/components/NcActions/NcActions.vue
Signed-off-by: Julius Härtl <jus@bitgrid.net>
Fixes https://github.com/nextcloud/text/issues/3864
I checked and it seems we cannot easily or nicely change the initial focus of the NcActions entires. (unless we consider using setTimeout an option) within text. Now we don't have a real active state in the NcAction* components which we could use to pick the initial focus element, however since this initial focus handling is mostly bound to accessibility I decided to make a change of the initial focus depending on if any NcAction* entry is indicating a selected state with `aria-selected`.
=> fix: If a aria-selected button is present we focus on this one instead of the first entry

src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
- Restore breaking prop removal 🙈
=> fix(NcCheckboxRadioSwitch): Restore wrapper element prop

src/components/NcPasswordField/NcPasswordField.vue, src/components/NcTextField/NcTextField.vue
HTML Validation issue.
Currently `NcTextField` passes both `$attrs` and `$props` to the `NcInputField`.
```html
<NcInputField v-bind="{ ...$attrs, ...$props }">
```
While passing `$attrs` makes sense, passing `$props` is valid only when both components have **exactly** the same props. But they don't. `NcTextField` has its own prop `trailingButtonIcon` and may have more props in the future.
**Proposal:** same as `NcSelect`.
Filter props to proxy only original `NcInputField` props.
**Alternative solution:** do not use props for proxying.
See: https://github.com/nextcloud-libraries/nextcloud-vue/pull/4665
`trailingbuttonicon` is not a valid `<input>` attribute.
=> fix(Nc*Field): do not pass all props to InputField BY filtering $props

src/components/NcDialog/NcDialog.vue
- Fix https://github.com/nextcloud/server/issues/41025
=> fix(NcDialog): NcModal registration

src/components/NcTextArea/NcTextArea.vue, src/components/NcTextArea/index.js, src/components/index.js, styleguide.config.js
* Fix _none_
* Required for https://github.com/nextcloud/server/pull/40767
_None_
=> feat(NcTextArea): implement new textarea component

src/components/NcAppNavigationItem/NcAppNavigationItem.vue, src/components/NcModal/NcModal.vue, src/components/NcNoteCard/NcNoteCard.vue, src/components/NcUserBubble/NcUserBubble.vue
> **Error: Bad value `' '` for attribute `target` on element [`a`](https://html.spec.whatwg.org/multipage/#the-a-element): Browsing context name must be at least one character long.**
=> fix: remove empty attributes values

src/components/NcCheckboxRadioSwitch/NcCheckboxContent.vue, src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
* Fix #4689
This fixes the circular import of `NcCheckboxRadioSwitch` and `NcCheckboxContent`. No visual changes.
=> fix(NcCheckboxRadioSwitch): fix circular import

src/components/NcCheckboxRadioSwitch/NcCheckboxContent.vue, src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
=> fix(NcCheckboxRadioSwitch): forward indeterminate prop

src/components/NcListItemIcon/NcListItemIcon.vue
* This brings back the icons in the `NcListItemIcon` examples. I couldn't really figure out why it doesn't work when simply using `<template>`. It only works when not wrapping the default slot content, or when using `<template #default>`.
---|---
=> [next] fix(NcListItemIcon): correctly use default slot in examples

src/components/NcEmptyContent/NcEmptyContent.vue
* Fix https://github.com/nextcloud-libraries/nextcloud-vue/issues/4338 
=> Change heading in EmptyContent to `span`

src/components/NcRelatedResourcesPanel/NcRelatedResourcesPanel.vue
* Needed for https://github.com/nextcloud/contacts/issues/3364
---|---
B | A
=> Add header prop to NcRelatedResourcesPanel

src/components/NcRelatedResourcesPanel/NcRelatedResourcesPanel.vue
* Follow-up to #4703, fixes a `ReferenceError: t is not defined` error in the docs.
=> fix(NcRelatedResourcesPanel): t is not defined

src/components/NcAppNavigationItem/NcAppNavigationItem.vue
If there are no children it can not be expanded and as such the attribute should be removed.
=> fix(NcAppNavigationItem): Do not include `aria-expanded` attribute if there are no children

src/components/NcDialogButton/NcDialogButton.vue
* Fix https://github.com/nextcloud-libraries/nextcloud-vue/issues/4723
=> fix(NcDialog): register components in NcDialogButton

.eslintrc.js, cypress.config.ts, cypress/component/modal.cy.ts, src/components/NcModal/NcModal.vue, styleguide.config.js, vite.config.mts
* This migrates `NcModal` to vue 3.
=> [next] feat(NcModal): migrate to vue 3

src/assets/action.scss, src/components/NcActionButton/NcActionButton.vue
- Only for the ActionButton (see [context](https://github.com/nextcloud/server/pull/41010))
- Cleaned the [documentation](https://github.com/nextcloud-libraries/nextcloud-vue/pull/3030/#discussion_r1377287691)
- Also fix regression from [here](https://github.com/nextcloud-libraries/nextcloud-vue/pull/4648#issuecomment-1786843212)
=> feat(NcActionButton): support menu styling 

src/components/NcActions/NcActions.vue
- For https://github.com/nextcloud-libraries/nextcloud-vue/issues/4681
- Fix detection of navigation menu links with relative hrefs
- Exclude anchor links
=> fix(NcActions): Detect navigation menu links correctly

.eslintrc.js, src/components/NcAvatar/NcAvatar.vue, src/components/NcListItemIcon/NcListItemIcon.vue, src/components/index.js, styleguide.config.js, tests/unit/components/NcAvatar/NcAvatar.spec.ts, vite.config.mts
* This migrates `NcAvatar` to vue 3.
=> [next] feat(NcAvatar): migrate to vue 3

.eslintrc.js, src/components/NcHeaderMenu/NcHeaderMenu.vue, src/components/index.js, styleguide.config.js
* This migrates `NcHeaderMenu` to vue 3.
=> [next] feat(NcHeaderMenu): migrate to vue 3

src/components/NcListItem/NcListItem.vue, src/components/NcVNodes/NcVNodes.vue, src/components/index.js, styleguide.config.js
* This migrates `NcListItem` to vue 3.
=> [next] feat(NcListItem): migrate to vue 3

src/components/NcRelatedResourcesPanel/NcRelatedResourcesPanel.vue
* ref https://github.com/nextcloud/contacts/pull/3670
---|---
=> Made description dynamic on related resources

src/components/NcSelect/NcSelect.vue
* Part of https://github.com/nextcloud/server/issues/40697
Make sure the currently active option has still enough contrast when the menu is opened, by dropping the opacity property but using max contrast color.
---|---
=> fix(NcSelect): Ensure selected option has enough contrast when the menu is opened

src/components/NcEmptyContent/NcEmptyContent.vue
=> fix(NcEmptyContent): Fix regression that changed the color of the description text

src/components/NcTimezonePicker/NcTimezonePicker.vue
* Required for https://github.com/nextcloud/server/issues/40697
Allows to the the ID of the inner select so it can be referenced by labels.
=> fix(NcTimezonePicker): Allow to set ID of inner select component

src/components/NcRichContenteditable/NcRichContenteditable.vue
When getting a picker result, emit an event so parent components can prevent it to be inserted in the content and add some custom processing.
This could be useful in Talk when getting an OpenStreetMap link. A location rich object could be shared instead of inserting the link.
=> Allow preventing link insertion in RichContentEditable

src/components/NcAppContent/NcAppContent.vue
When `NcAppContentList` is resizeable, a thin scrollbar is hard to catch with the mouse. Set scrollbar width to auto in this case.
* Fixes: #4706
| Before (hover `NcAppContentList`) in Firefox/Linux | After (hover `NcAppContentList`) in Firefox/Linux |
|---|---|
| ![2023-10-31T09:32:32,543502737+01:00](https://github.com/nextcloud-libraries/nextcloud-vue/assets/3582805/fb70c2c1-b2e0-445a-9df8-82afac1bc45f) |![2023-10-31T09:31:27,365873640+01:00](https://github.com/nextcloud-libraries/nextcloud-vue/assets/3582805/514204ff-3574-45c5-92ab-1bde28a1d5b5) |
| Before (hover scrollbar of `NcAppContentList`) in Firefox/Linux | After (hover scrollbar of `NcAppContentList`) in Firefox/Linux |
|---|---|
| ![2023-10-31T09:32:38,423200946+01:00](https://github.com/nextcloud-libraries/nextcloud-vue/asset …
=> fix(NcAppContent): Set normal scrollbar width on resizeable NcAppContentList

src/components/NcAvatar/NcAvatar.vue
* Fixes showing `false` as tooltip when the tooltip was disabled with `disable-tooltip`.
---|---
=> [next] fix(NcAvatar): don't show `false` for disabled tooltip

src/components/NcAvatar/NcAvatar.vue, tests/unit/components/NcAvatar/NcAvatar.spec.ts, tsconfig.json
* Fix https://github.com/nextcloud-libraries/nextcloud-vue/issues/2044
1. Filter user names to only use real characters (for all languages) to generate initials and not using special characters like e.g. `(`.
2. Use first & last name for initials instead of second name (e.g. `First Second Last` should be `FL` and not `FS`).
---|---
=> fix(NcAvatar): Improve initials generation to filter out special characters

src/components/NcAppContent/NcAppContent.vue
Manual backport of #4710 
When `NcAppContentList` is resizeable, a thin scrollbar is hard to catch with the mouse. Set scrollbar width to auto in this case.
Fixes: #4706
=> [stable7] fix(NcAppContent): Set normal scrollbar width on resizeable NcAppContentList

src/components/NcAvatar/NcAvatar.vue
> **Error**: Attribute `alt` not allowed on element [`span`](https://html.spec.whatwg.org/multipage/#the-span-element) at this point.
Also, there is a description with `aria-label`.
=> fix(NcAvatar): remove alt attr from span[role=img]

src/components/NcAppSidebar/NcAppSidebarTabs.vue, src/components/NcAppSidebarTab/NcAppSidebarTab.vue
* Fix https://github.com/nextcloud-libraries/nextcloud-vue/issues/3032
If only one sidebar tab is shown, the tab header is missing. Thus we can not reference it for `aria-labelledby` and have to use `aria-label` instead.
=> fix(NcSidebarTab): Ensure there is an `aria-label` if the `aria-labelledby` element does not exist

src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
* Fix https://github.com/nextcloud/server/issues/40706
| ![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/6078378/cd3e7894-c001-48cb-9d60-d60146d56e02) | ![Screenshot from 2023-10-26 13-28-29](https://github.com/nextcloud-libraries/nextcloud-vue/assets/6078378/6d87cae4-4876-4311-a5e2-f86136720aee) |-------------|---------------------------------------------------------------|
| ![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/6078378/319eb332-dc5e-4304-aa09-22ad2fa55887) | ![Screenshot from 2023-10-26 13-26-04](https://github.com/nextcloud-libraries/nextcloud-vue/assets/6078378/dac48b08-0a05-418c …
=> Create outline for `focus-within` on RadioSwitch

l10n/messages.pot, package-lock.json, package.json, src/components/NcSelect/NcSelect.vue
* Required for https://github.com/nextcloud/server/issues/40697 to allow adjusting the `aria-label`
Also add translated variants of the default `aria-label`s
=> fix(NcSelect): Update `@nextcloud/vue-select` and add translated options for `aria-labels`

CHANGELOG.md
* Add header prop to NcRelatedResourcesPanel by @GretaD in 
https://github.com/nextcloud-libraries/nextcloud-vue/pull/4703
* feat(NcAppNavigationItem): Add `active` property to set active state & use `aria-current` by @susnux in 
https://github.com/nextcloud-libraries/nextcloud-vue/pull/4716
* feat(NcActionButton): support menu styling  by @skjnldsv in 
https://github.com/nextcloud-libraries/nextcloud-vue/pull/4724
* Made description dynamic on related resources by @GretaD in 
https://github.com/nextcloud-libraries/nextcloud-vue/pull/4729
* fix(NcTimezonePicker): Allow to set ID of inner select component by @susnux in 
https://github.com/nextcloud-libraries/nextcloud-vue/pull/4734
* Allow preventing link insertion in 
RichContentEditable by @julien-nc in …
=> 8.0.0-beta.10

src/components/NcUserBubble/NcUserBubble.vue, src/globals.d.ts
* Fix #792 
1. Make `displayName` not required
We already have a fallback so it is not required.
But we should show a warning when user and display name are not set.
2. Fix URL prop validator to allow relative URLs
3. Fix examples
* Examples does not need to pass computed property
* `alert` is not defined in templates for Vue 2 (same with console)
=> fix: NcUserBubble properties

src/components/NcUserBubble/NcUserBubble.vue
* This adjusts `NcUserBubble` to only forward props to `NcAvatar` that are actually used by it. E.g. the `primary` prop is currently also forwarded and lands in the markup, although `NcAvatar` makes no use of it.
=> fix(NcUserBubble): only forward necessary props

src/components/NcSelect/NcSelect.vue
* Fix https://github.com/nextcloud/server/issues/41217
🏚️ Before 
🏡 After
=> Change styles for focused Select

src/components/NcAppSettingsDialog/NcAppSettingsDialog.vue, src/components/NcAppSettingsSection/NcAppSettingsSection.vue
* Part of https://github.com/nextcloud-libraries/nextcloud-vue/issues/1441
This consists of 2 commits, the first one changes the way the sections are registered and the second on provides icon support.
Previously the default slot content was iterated and the props of every vNode were used. This had two downsides:
1. `$slots` is not reactive -> changes will not propagate
2. We can not easily access slots of a section (like for the icon) because the slot will only be available when the vNode is mounted
So instead we now provide to functions to children:
`registerSection` and `unregisterSection` with that functions children (the sections) can register themself and update on change. Solving both issues: the reactivity and the ability to inject icons (as the registration is done after mount). …
=> [NcAppSettingsDialog] Allow to add icons to the navigation sections

src/components/NcButton/NcButton.vue
Allow us to format the text of a button without dirty hacks like `:deep` selectors, I added the example why this is useful and where we should use this: Table headers.
Places where we have this and can remove all custom hacks are: all file tables in the files app, the logreader app, the file picker.
:warning: this is chained on #4366  (see first commit), should be reviewed and merged first
=> NcButton: Allow to format text of button

src/components/NcInputField/NcInputField.vue, src/components/NcSelect/NcSelect.vue
* Resolves https://github.com/nextcloud-libraries/nextcloud-vue/issues/3376
https://github.com/nextcloud-libraries/nextcloud-vue/assets/26852655/cdbdd6ee-f6c2-4eea-985c-beb39d447a99
=> fix(NcInputField): Bring input field height to 44px and fixes its focus feedback

l10n/messages.pot, src/components/NcTimezonePicker/NcTimezonePicker.vue
* Fix https://github.com/nextcloud/server/issues/40697
Change `aria-label` to reflect that you select time zones.
=> fix(NcTimezonePicker): Add correct `aria-label`

src/components/NcAppNavigation/NcAppNavigation.vue
Fix regression of #4730 
We can not use scoped here because it will set a different scope than on the NcAppContent and thus the css variable will not be injected into it.
(One of the reasons I do not like scoped but prefer `module`).
=> fix(NcAppNavigation): Ensure `--app-navigation-padding` is set also on app-content

src/components/NcAppNavigation/NcAppNavigation.vue, tests/unit/components/NcAppNavigation/NcAppNavigation.spec.js
* A part of https://github.com/nextcloud/server/issues/36964
---|---
=> fix(NcAppNavigation): add focus trap on mobile and improve a11y

src/components/NcAppNavigation/NcAppNavigation.vue, src/components/NcAppNavigationToggle/NcAppNavigationToggle.vue
* Fix https://github.com/nextcloud/server/issues/40954
* Chained on https://github.com/nextcloud-libraries/nextcloud-vue/pull/4633
There are 2 issues with a small screen:
1. On a very small screen (320px) the 300px navigation is too wide, the toggle button is out of viewport
2. The toggle button doesn't look good on top of content
---|---
Toggle button on a different background:
=> fix(NcAppNavifation): small screen support

src/components/NcActions/NcActions.vue
From https://github.com/nextcloud/server/pull/41010#pullrequestreview-1717797692
```vue
<template>
<NcActions>
<template v-if="!showMenu">
<NcActionButton @click="showMessage('Edit')">Edit</NcActionButton>
<NcActionButton :is-menu="true" @click="showMenu = true">Show menu</NcActionButton>
</template>
<template v-else>
<NcActionButton key="menu-1" @click="showMenu = false">< Back</NcActionButton>
<NcActionButton key="menu-2" @click="showMessage('Edit')">Second entries</NcActionButton>
<NcActionButton key="menu-3" @click="showMessage('Delete')">Second entries</NcActionButton>
</template>
</NcActions>
</template>
<script>
data() {
return {
showMenu: false,
}
},
methods: {
showMessage(msg) {
alert(msg)
},
},
}
</script>
```
=> feat(NcActions): focus the first action again if no action have a focus after render

src/components/NcAppNavigation/NcAppNavigation.vue, src/components/NcAppNavigationToggle/NcAppNavigationToggle.vue
See: https://github.com/nextcloud-libraries/nextcloud-vue/pull/4767#issuecomment-1801812704
Returns transparency between the app navigation and the toggle. Only the toggle button has a background.
Before (no text between nav and toggle) | After (text is visible, only toggle has background)
---|---
=> fix(NcAppNavigation): remove background square connecting toggle and navigation

package-lock.json, package.json, vite.config.mts
We should not require any not compiled vue files as this breaks unit tests in apps, as you require the users to compile vue files first.
We had this discussion with @skjnldsv on dialogs before and decided there to bundle the vue-material-design-icons, so I would like to do the same here.
=> fix: Do not depend on uncompiled vue files as dependencies

CHANGELOG.md, package-lock.json, package.json
We need to create the stable release before Thursday so apps can update for the feature freeze of Nextcloud 28.
Currently still open feature pull requests:
Pull requests we can also merge for the first patch release:
=> chore: Prepare release of stable version 8.0.0

src/components/NcTimezonePicker/NcTimezonePicker.vue
https://github.com/nextcloud/server/pull/41348#issuecomment-1803538694
=> fix(NcTimezonePicker): add missing `t` method

CHANGELOG.md, package-lock.json, package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.0.0...v8.0.1)
* fix(NcModal): Adjust `aria-label` of close button by @susnux in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4778
* fix(NcCounterBubble): Fix color of highlighted/outlined items when no… by @nickvergessen in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4781
* fix(NcTimezonePicker): add missing `t` method by @ShGKme in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4790
* fix(NcCheckboxRadioSwitch): Fix contrast of Radio switches using butt… by @nickvergessen in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4791
* Updates for project Nextcloud vue library by @transifex-integration in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4780 …
=> Release v8.0.1

l10n/messages.pot, src/components/NcTextField/NcTextField.vue
The `aria-label` property defaults to "Clear text" which makes no sense when the icon is undo, so instead if there is no explicit value set default to one that most likely matches the icon used.
=> fix(NcTextField): Align default label for trailing button with used icon

src/components/NcAppSidebar/NcAppSidebarTabs.vue
=> Fix tabs appearance

CHANGELOG.md, package-lock.json, package.json
Prepare next release, due to #4761 this is already a minor release from semver.
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.0.1...v8.1.0)
* feat: introduce `useIsMobile` and `useIsFullscreen` composables [\#4761](https://github.com/nextcloud-libraries/nextcloud-vue/pull/4761) [\(@ShGKme\)](https://github.com/@ShGKme)
* Fix tabs appearance [\#4815](https://github.com/nextcloud-libraries/nextcloud-vue/pull/4815) [\(@marcoambrosini\)](https://github.com/@marcoambrosini)
* fix(NcTextField): Align default label for trailing button with used icon [\#4805](https://github.com/nextcloud-libraries/nextcloud-vue/pull/4805) [\(@susnux\)](https://github.com/@susnux)
* fix single-select design [\#4817](https://github.com/nextcloud-libraries/nextcloud-vue/pull/4817) …
=> chore: Prepare 8.1.0 release

src/components/NcAppSidebar/NcAppSidebarTabs.vue
=> fix(NcAppSidebarTabs): override checkbox radio switch only in navigation

src/composables/index.js, src/composables/useIsFullscreen/index.js, src/index.js
* This exports the composables added in #4761 and ensures the correct license and copyright.
=> fix: export composables

src/components/NcDateTime/NcDateTime.vue, tests/unit/components/NcDateTime/NcDateTime.spec.js
- 
---|---
See activity from "50 hours ago" and start dying as you are bad in math instead of knowing when a colleague did something | "2 days ago" helpfully obvious
In stable27 Moment was used by the activity app, the breaking points are here:
https://github.com/moment/moment/blob/000ac1800e620f770f4eb31b5ae908f6167b0ab2/src/lib/duration/humanize.js#L4-L11
We could also go for those, but at least the 72 hours need to go.
=> Improve relative time handling

src/components/NcActionButton/NcActionButton.vue, src/components/NcActionButtonGroup/NcActionButtonGroup.vue, src/components/NcActionCaption/NcActionCaption.vue, src/components/NcActionCheckbox/NcActionCheckbox.vue, src/components/NcActionInput/NcActionInput.vue, src/components/NcActionLink/NcActionLink.vue, src/components/NcActionRadio/NcActionRadio.vue, src/components/NcActionRouter/NcActionRouter.vue, src/components/NcActionSeparator/NcActionSeparator.vue, src/components/NcActionText/NcActionText.vue, src/components/NcActions/NcActions.vue, src/components/NcButton/NcButton.vue, src/mixins/actionText.js
* Fix https://github.com/nextcloud/server/issues/37099
`NcActions` and `NcAction*` items should have correct menu roles only when it represents a menu.
See detailed requirement in the comment here: https://github.com/nextcloud/server/issues/37099#issuecomment-1803927925
Example | Before | After
---|---|---
**Application menus** | | +group, +presentation, +label, +checkbox/radio
**Navigation** | ✅ | No changes
**Popovers** | | no wrong roles
- Always set `aria-hidden="true"` on `span.icon` in default `#icon`
- ⚠️ **Deprecate `ariaHidden` props. Developers don't need to set it manually, it is always needed by default** ⚠️
- Change rule to determine when actions has `role="menu"`
- Provide `NcActions:inSemanticMenu`, to `NcAction*` may know if they are in `role="menu"`
- Only in a menu:
- …
=> fix(NcActions): fix role and aria attributes

src/components/NcAppSettingsDialog/NcAppSettingsDialog.vue, tests/unit/components/NcAppSettingsDialog/NcAppSettingsDialog.spec.ts, tests/unit/components/NcAppSettingsDialog/register-unregister.spec.ts
There was a logic error where unregister removed all but the unregistered section.
Also fix some minor issues and only warn on duplicated name instead of error.
=> fix(NcAppSettingsDialog): `unregisterSection` should remove the section instead of remove all other

src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
* Fix `[Vue warn]: v-on with no argument expects an object value. ` for `NcCheckboxRadioSwitch`.
=> [next] fix(NcCheckboxRadioSwitch): fix v-on with no argument expects an object value

src/components/NcRichContenteditable/NcRichContenteditable.vue, tests/unit/components/NcRichContenteditable/NcRichContenteditable.spec.js
* A part of: https://github.com/nextcloud/server/issues/37092
This attribute is not valid on `div[richcontenteditable]` and was used only to pass value to css.
=> fix(NcRichcontenteditable): remove placeholder attr

src/components/NcDateTime/NcDateTime.vue, tests/unit/components/NcDateTime/NcDateTime.spec.js
=> fix(NcDateTime): Also use months for relative date time

src/components/NcActions/NcActions.vue
* Fix https://github.com/nextcloud/server/issues/41012
* https://www.w3.org/WAI/ARIA/apg/patterns/menubar/
* Briefly, **a primary keyboard navigation convention common across all platforms is:**
* <kbd>TAB</kbd> and <kbd>SHIFT + TAB</kbd> should move focus between **components**
* <kbd>Arrows ⬆️⬇️</kbd> should move focus between **elements inside a component**
See also: https://www.w3.org/WAI/ARIA/apg/practices/keyboard-interface/
- <kbd>ESC</kbd> closes actions
---|---
**Arrow** |
Don't loop | Loop
**TAB in Menu / Navigation** | 
Between elements | Between components
**TAB in Popover-like** |
Submit is not focusable | Classic popover with focus trap
=> fix(NcActions): adjust keyboard navigation

src/components/NcCheckboxRadioSwitch/NcCheckboxContent.vue
Fix https://github.com/nextcloud/server/issues/41262
|---|---|
| ![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/42591237/1ac55320-7bf7-46e9-b3cf-64d38c985530) | ![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/42591237/f89dc0db-664e-4ccc-94c8-0750851648f7) |
=> fix checkbox sizing

src/components/NcActions/NcActions.vue
* Fix #4539
When a mouse is moved over `NcActions` it searches for a `NcAction<item>` under the cursor by searching for the **closest** `li` element.
The `closest` searches up to the document root.
So when the cursor is not on an actual `NcAction-<item>` (on `UL` itself between actions) and `NcActions` is rendered in a `container`, it finds just any `li` ancestor. In Talk, it is a message element. It results in focusing the first focusable action in this container.
---|---
=> fix(NcActions): only search for items to focus on in the current menu

src/components/NcAppSettingsDialog/NcAppSettingsDialog.vue
Create scrollable content via `min-height` over sidebar and settings dialog on small screens
* Fix https://github.com/nextcloud/server/issues/41542
🏚️ Before 
🏡 After
=> Create scrollable content via `min-height` over sidebar and settings dialog on small screens

src/components/NcTextArea/NcTextArea.vue
make same styles for focused, hovered and active NcTextArea as https://github.com/nextcloud-libraries/nextcloud-vue/pull/4718
---|---
=> Correct styles for focused NcTextArea

CHANGELOG.md, package-lock.json, package.json
* feat(NcColorPicker): palette now can have color names [\#4611](https://github.com/nextcloud-libraries/nextcloud-vue/pull/4611) [\(ShGKme\)](https://github.com/ShGKme)
* fix: export composables [\#4829](https://github.com/nextcloud-libraries/nextcloud-vue/pull/4829) [\(raimund-schluessler\)](https://github.com/raimund-schluessler)
* fix(NcAppSidebarTabs): override tabs styles only tablist navigation [\#4823](https://github.com/nextcloud-libraries/nextcloud-vue/pull/4823) [\(ShGKme\)](https://github.com/ShGKme)
* Improve relative time handling [\#4832](https://github.com/nextcloud-libraries/nextcloud-vue/pull/4832) [\(nickvergessen\)](https://github.com/nickvergessen)
* fix(cypress): delete unused files [\#4837](https://github.com/nextcloud-libraries/nextcloud-vue/pull/4837) …
=> chore: Release 8.2.0

src/components/NcCheckboxRadioSwitch/NcCheckboxContent.vue
Ensure the text of the checkbox label does not overflow the label.
---|---
=> fix(NcCheckboxContent): Make sure text can wrap

src/components/NcAppNavigation/NcAppNavigation.vue
* Move `NcAppNavigationToggle` down the list
* Possible effect: when isMobile is active (from #4633), focus-trap grabs the first available element.
* Before fix: toggle button
* After fix: first element in navigation
From Talk usecase of component:
---|---
=> fix(NcAppNavigation): make toggle button not the first element for focus-trap

src/components/NcAppNavigation/NcAppNavigation.vue, tests/unit/components/NcAppNavigation/NcAppNavigation.spec.js
When a window is resized to a mobile size, the app navigation closes. However, when the page was initially open on mobile, the navigation is open. It could be annoying because a user needs to close it to see the content.
See also discussion from: https://github.com/nextcloud/spreed/issues/10908#issuecomment-1822460276
=> fix(NcAppNavigation): closed on mobile initially

src/components/NcAppSettingsDialog/NcAppSettingsDialog.vue, src/components/NcDialog/NcDialog.vue
Instead of hiding the navigation on small devices, remove it (and clean up the styles as they are not needed anymore).
Also fix dialog styles (content & navigation) which need to have the `deep` selector to be applied.
Fixed the padding which is now already (partly) included by NcDialog.
---|---
=> fix(NcAppSettingsDialog): Remove navigation instead of hiding and fix styles

src/components/NcActionButton/NcActionButton.vue
=> Remove server styles from action menu

src/components/NcInputField/NcInputField.vue
* Feature for https://github.com/nextcloud/spreed/issues/7850
=> feat(NcInputField): add optional pill form appearance to the component

src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
* Fix https://github.com/nextcloud-libraries/nextcloud-vue/issues/4802
`<input>` in `<NcCheckboxRadioSwitch>` is visually hidden with `position: absolute`.
But when it is used in a scrollable container in another `position: relative` container, positioning is broken and is not relative to the `<NcCheckboxRadioSwitch>` position.
As a result:
- It doesn't work for accessibility having the wrong position
- Click on the input puts focus on it and scroll the container to the wrong position
=> fix(NcCheckboxRadioSwitch): visually hidden input position

src/components/NcDialog/NcDialog.vue
On the OCDialogs.confirm and everywhere else we use
left: secondary action
right: primary action
So I adjusted the example for this.
And also add slightly more padding on the bottom in case there is only text shown, so that the padding on the left / right and bottom is the same.
---|---
=> fix(NcDialog): Add slighly more padding on the bottom and fix example button order

src/components/NcAppNavigationToggle/NcAppNavigationToggle.vue
* Continues: https://github.com/nextcloud-libraries/nextcloud-vue/issues/2503
* Fix https://github.com/nextcloud/server/issues/41862
---|---
=> fix(NcAppNavigation): replace custom `v-tooltip` with native `title`

src/components/NcAppNavigationCaption/NcAppNavigationCaption.vue
Currently the text is not readable, especially on dark mode. So lets move to main text color instead.
---|---
=> fix(NcAppNavigationCaption): Make color `main-text` for accessibility

src/components/NcActions/NcActions.vue
* Fix https://github.com/nextcloud/server/issues/41890
* Fix https://github.com/nextcloud/server/issues/41889
* Fix https://github.com/nextcloud/server/issues/41906
* Fix https://github.com/nextcloud/server/issues/41888
There was a typo, then/else is misplaced in a ternary operator.
=> fix(NcActions): typo in aria-haspopup

src/components/NcDialog/NcDialog.vue, src/components/NcDialogButton/NcDialogButton.vue
`@values` is not valid in JSDoc by out ESLint rules.
`@type` with literal type union works in the `styleguidist` as well
=> chore(lint): use valid JSDoc for literal type union

CHANGELOG.md, package-lock.json, package.json
Again a feature was merged...
---
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.3.0...v8.2.0)
* feat(NcInputField): add optional pill form appearance to the component [\#4876](https://github.com/nextcloud-libraries/nextcloud-vue/pull/4876) \([Antreesy](https://github.com/Antreesy)\)
* fix(NcCheckboxContent): Make sure text can wrap [\#4862](https://github.com/nextcloud-libraries/nextcloud-vue/pull/4862) \([susnux](https://github.com/susnux)\)
* fix(NcAppNavigation): make toggle button not the first element for focus-trap [\#4864](https://github.com/nextcloud-libraries/nextcloud-vue/pull/4864) \([Antreesy](https://github.com/Antreesy)\)
* fix(NcAppNavigation): closed on mobile initially [\#4869](https://github.com/nextcloud-libraries/nextcloud-vue/pull/486 …
=> chore: Prepare new release 8.3.0

src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
If no text should be shown currently you have to provide the label as a `span` with `hidden-visually`, because the `aria-label` would not be forwarded correctly.
=> enh(NcCheckboxRadioSwitch): Allow to set `aria-label`

src/components/NcRichContenteditable/NcRichContenteditable.vue, tests/unit/components/NcRichContenteditable/NcRichContenteditable.spec.ts
For consistent look of Nextcloud components this adds the same label as NcTextField / NcInputField / NcTextArea.
https://github.com/nextcloud-libraries/nextcloud-vue/assets/1855448/a07e6492-003a-4c50-8226-07aa55d7436e
=> enh(NcRichContenteditable): Add optional visual label for content editable

src/components/NcBreadcrumbs/NcBreadcrumbs.vue
- For https://github.com/nextcloud/server/issues/41865
=> enh(NcBreadcrumbs): Allow setting aria-label on nav

jest.config.js, l10n/messages.pot, package-lock.json, package.json, src/assets/status-icons/user-status-away.svg, src/assets/status-icons/user-status-dnd.svg, src/assets/status-icons/user-status-online.svg, src/components/NcAvatar/NcAvatar.vue, src/components/NcRichContenteditable/NcAutoCompleteResult.vue, src/globals.d.ts, src/utils/UserStatus.ts
- For https://github.com/nextcloud/server/issues/41856
---|---
=> fix(NcAvatar): Increase contrast of avatar status icon

src/assets/variables.scss, src/components/NcAppSidebar/NcAppSidebar.vue, src/components/NcDialog/NcDialog.vue, src/components/NcHeaderMenu/NcHeaderMenu.vue, src/components/NcModal/NcModal.vue, src/composables/useIsMobile/index.js
Used in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4909
This repo has several components with `math.div($breakpoint-mobile, 2)` media query. Similar to `breakpoint-mobile` it seems to be useful to have a SCSS variable for it and a composable to handle aka media-query change.
I called it `small-mobile`, but discussable for me.
=> feat: add small mobile breakpoint

src/components/NcListItem/NcListItem.vue
The component user should have full control over what tab they want the link to open in, if any.
* Fixes : https://github.com/nextcloud-libraries/nextcloud-vue/issues/4880
=> Add target prop for NcListItem

src/components/NcDialog/NcDialog.vue
- For https://github.com/nextcloud/server/issues/41865
=> enh(NcDialog): Label dialog nav

l10n/messages.pot, src/components/NcColorPicker/NcColorPicker.vue, src/functions/usernameToColor/usernameToColor.js, src/utils/GenColors.js
Lets provide a fully labelled color palette for the color picker by default.
When users provide a different palette its their task but for the default we can provide some color names (yes that are real color names for that colors).
=> enh: Add a full labelled color palette to be used as the default for the color picker

src/components/NcAppNavigationToggle/NcAppNavigationToggle.vue, src/components/NcAppSidebar/NcAppSidebar.vue
* Fix https://github.com/nextcloud/server/issues/41839
On mobile view, the sidebar is full-screen. But it doesn't have a focus trap. So the focus may fall into the main content below the sidebar.
---|---
Focus is lost on the main content | It's a trap
=> fix(NcAppSidebar): add focus trap on mobile

src/components/NcRichContenteditable/NcRichContenteditable.vue
* Put caret to the end of inputted text when focus it, instead of start
Casted some tests (with mouse clicks, range selections, keyboard tabbing)
[Screencast - focus tests](https://github.com/nextcloud-libraries/nextcloud-vue/assets/93392545/88b89afe-b91c-4aeb-aa7b-29a144155bc3)
https://github.com/nextcloud-libraries/nextcloud-vue/blob/9dcd33b3810293a23e9dd964d60814f97639c8e2/src/components/NcRichContenteditable/NcRichContenteditable.vue#L700-L705
=> feat(NcRichContenteditable): put caret in the end when focus input

package.json
* See: https://github.com/nextcloud/spreed/issues/10927
=> fix(package): specify exports for composables

src/components/NcActions/NcActions.vue
* Fix https://github.com/nextcloud/server/issues/41897
Example on [w3c patterns](https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/examples/menu-button-actions/) says "The aria-expanded attribute is removed when the menu is closed.".
However there is an ongoing discussion about it.
For example, PR 2829 on https://github.com/w3c/aria-practices/pull/. Or another example https://www.w3.org/WAI/ARIA/apg/patterns/accordion/examples/accordion/
So actually it is recommended to add `aria-expanded="false"`, not remove the attribute.
=> fix(NcActions): provide `aria-expanded="false"` when menu is closed instead of removing it

src/components/NcListItem/NcListItem.vue
`width` is set to 100% but if `box-sizing` is not set to `border-box` it will not include the border and the padding.
This causes the list item to overflow its parents in some cases, you can for example see this in the new unified search of Nextcloud 28 (there are even more places).
To fix this simply set `box-sizing` to `border-box` of the list item.
---|---
=> fix(NcListItem): Ensure list item does not overflow wrapper

src/mixins/actionText.js, tests/unit/components/NcActions/NcActionButton.spec.ts
Most API returns relative icon URLs so we should also support them for NcActionXXX
=> fix(NcActionX): Allow relative icon URL

src/components/NcAppSettingsDialog/NcAppSettingsDialog.vue, tests/unit/components/NcAppNavigation/NcAppNavigation.spec.js, tests/unit/components/NcAppSettingsDialog/NcAppSettingsDialog.spec.ts, tests/unit/composables/useIsMobile.spec.js, tests/unit/testing-utils.ts
* Fix #4941
With `:show-navigation="false"`
---|---
=> fix(NcAppSettingsDialog): respect showNavigation prop

src/assets/NcAppNavigationItem.scss
Bring back the hover state for active app navigation elements.
=> fix(NcAppNavigation): Bring back hover state for active element

src/components/NcColorPicker/NcColorPicker.vue
---|---
Changes the check color depending on the background color chosen to either be white or black to achieve the 3:1 contrast ratio for ARIA - radio input button still has white border, so up to reviewers to decide if that should change
=> enh(aria): changed check color to adhere to 3:1 ratio

src/components/NcHeaderMenu/NcHeaderMenu.vue
The current styles used in NcHeaderMenu makes it hard to make NextCloud work fine in RTL mode automatically. In order to be able to add bidirectional text support to NextCloud (server), we need to use logical styles here, so the if the layout of the dashboard is RTL, the menu automatically moved to the right.
These changes shouldn't have any visible impact in the current state of NextCloud server. To test the impact, manually set the body to use `dir="RTL"`.
There will be another PR on NextCloud server. It will depend on this PR to get merged. It will be linked to this PR as soon as it is opened.
---|---
Nothing remained
=> Use logical style for NcHeaderMenu

src/components/NcActions/NcActions.vue
* Don't use the `sync` modifier which was removed for vue 3. This must have slipped when merging `master` into `next`.
=> [next] fix(docs): use v-model instead of sync

src/components/NcTextArea/NcTextArea.vue
* Fix https://github.com/nextcloud/server/issues/42243
* Relied on https://github.com/nextcloud-libraries/nextcloud-vue/pull/4718
| ![Screenshot from 2023-12-18 16-44-20](https://github.com/nextcloud-libraries/nextcloud-vue/assets/6078378/aa62d617-078f-450e-bc36-4620e033bec3) | ![Screenshot from 2023-12-18 16-25-40](https://github.com/nextcloud-libraries/nextcloud-vue/assets/6078378/98591f26-00fa-48d0-adac-fbb0fd105de1) |-------------|---------------------------------------------------------------|
| ![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/6078378/c4c2d6f9-5fbe-4c67-aa83-dd9304fb476e) | ![Screenshot from …
=> Equalize `TextArea` styles with `TextField` styles

src/components/NcRichContenteditable/NcRichContenteditable.vue
* For https://github.com/nextcloud/server/issues/41879
---|---
=> Increase contrast on input field for `NcRichContenteditable`

src/components/NcBreadcrumb/NcBreadcrumb.vue
---|---
Changed components aria label to better represent the content of the span for screen readers
=> enh(breadcrumbs): changed aria label for voice control on a-tag

src/components/NcDateTimePickerNative/NcDateTimePickerNative.vue
* Fix https://github.com/nextcloud/server/issues/42392
No changes for the light theme.
---|---
=> Differentiate between dark and light theme for NcDateTimePickerNative

src/components/NcActionTextEditable/NcActionTextEditable.vue, src/components/NcAppNavigationItem/NcInputConfirmCancel.vue, src/components/NcSettingsInputText/NcSettingsInputText.vue, src/components/NcSettingsSelectGroup/NcSettingsSelectGroup.vue
* This unifies the usage of `value / modelValue`. Every `value` prop got renamed to `modelValue` to align with the new usage by vue 3. For some components we did this already, so here I migrated the rest to have it consistent.
=> [next] fix: unify `modelValue` naming

src/components/NcActionCheckbox/NcActionCheckbox.vue, src/components/NcActionRadio/NcActionRadio.vue, src/components/NcAppSidebar/NcAppSidebar.vue, src/components/NcAppSidebar/NcAppSidebarTabs.vue, src/components/NcButton/NcButton.vue, src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue, src/components/NcRichText/NcRichText.vue, src/components/NcSavingIndicatorIcon/NcSavingIndicatorIcon.vue
* This PR makes use of the `v-model` capabilities new to vue 3. The `checked` prop of `NcActionCheckbox`, `NcActionRadio` and `NcCheckboxRadioSwitch` was renamed to `modelValue` so the component can be used easier by simply providing `v-model="isChecked"` instead of `v-model:checked="isChecked"`.
Companion PR to #4990.
=> [next] feat!: rename `checked` prop to `modelValue`

CHANGELOG.md, package-lock.json, package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.4.0...v8.3.0)
* NcRichContenteditable: new visual label feature might break layout if you have custom contenteditable styles
* `isMobile` and `isFullscreen` mixins are now deprecated, use `useIsMobile` and `useIsFullscreen` composables instead
* enh: Split translations by components to only include needed strings in app bundles by @susnux in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4861
* enh(NcCheckboxRadioSwitch): Allow to set `aria-label` by @susnux in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4903
* enh(NcRichContenteditable): Add optional visual label for content editable by @susnux in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4907
* enh(NcBreadcrumbs): …
=> chore: Release 8.4.0

src/components/NcActionCheckbox/NcActionCheckbox.vue, src/components/NcActions/NcActions.vue, src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
* Correctly declare `update:modelValue` in `NcCheckboxRadioSwitch`. Fixup of a problem I introduced in #4994 when renaming `checked` to `modelValue`.
=> [next] fix(NcCheckboxRadioSwitch): correctly declare update:modelValue

tests/unit/components/NcModal/modal.spec.js
* Fixes the way we provide props to the `mount` function in `modal.spec.js` for vue 3. 
@susnux Since the tests passed even though we didn't provide the props correctly, I assume the tests don't really test anything. I didn't change it here though, since it is the same in `master` and should probably be fixed there, I think.
=> [next] fix(test): correctly provide props in test

src/components/NcCheckboxRadioSwitch/NcCheckboxContent.vue, src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
Fix https://github.com/nextcloud/server/issues/42202
Ref https://bugzilla.mozilla.org/show_bug.cgi?id=559506
I'm not sure, if anyone else have a better idea, please suggest it! :pray: :smiling_face_with_tear:
=> fix(NcCheckboxRadioSwitch): fix shift+click on firefox

package-lock.json, package.json
* This PR bumps `vite-plugin-node-polyfills` from `0.15.0` to `0.19.0` and a few other dependencies to the latest version as well. `vite-plugin-node-polyfills@0.19.0` conflicts with `0.15.0` which gives an error when trying to build with https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/18. This PR fixes this issue.
=> [next] fix: bump vite-plugin-node-polyfills from 0.15.0 to 0.19.0

src/components/NcCheckboxRadioSwitch/NcCheckboxContent.vue
Having a comment directly in a template may cause issues in `@vue/test-utils` and other tools that consider such a component to have two root nodes in a fragment: a comment node and a `span` node.
Also, replaced `null` with `undefined` to remove minor typing issue.
No visual changes.
=> refactor(NcCheckboxRadioSwitch): move comment to have a single root node

src/components/NcBreadcrumb/NcBreadcrumb.vue
* Fix setting `class` on the root element of `NcBreadcrumb`. This is necessary to correctly set the `dropdown` class for the breadcrumb containing the hidden crumbs. This fixes a visual issue with the alignment of the three-dots icon.
---|---
=> [next] fix(NcBreadcrumb): fix setting class on root element

src/components/NcCheckboxRadioSwitch/NcCheckboxContent.vue, src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
* Fix #5008.
This adjusts the left/right padding of the label to the correct / better value of `10px`. The value of `14px` calculated before does not work here, as the element is not an icon with a width of `16px` but a label with a width of `24px`.
---|---
=> fix(NcCheckboxRadioSwitch): use correct padding

src/components/NcCheckboxRadioSwitch/NcCheckboxContent.vue
- Make the icon inert
- Do not render the content text if undefined
=> fix(NcCheckboxRadioSwitch): improve rendering and prevent unecessary elements

l10n/messages.pot, src/components/NcSelect/NcSelect.vue, src/components/NcSelectTags/NcSelectTags.vue
- For https://github.com/nextcloud/server/issues/41902
- Adds built-in visible input label which should be preferred over non-visible `ariaLabelCombobox`
=> enh(NcSelect): Add visible input label

src/components/NcAppNavigationCaption/NcAppNavigationCaption.vue
* Fix nextcloud/server#42554
---|---
Change the h2 element in NcAppNavigationCaption to span, as the former h2 element broke the hierarchy of headings within the user page.
=> fix(NcAppNavigation): change h2 to span

src/components/NcModal/NcModal.vue
- For https://github.com/nextcloud/server/issues/41878
Allow setting the return focus element
=> feat(NcModal): Set return focus element on focus trap deactivation

src/assets/NcAppNavigationItem.scss
* For https://github.com/nextcloud/server/issues/41699
**Before 
Vue-navigation** 
**Unchanged non-vue navigation**
**After
Vue-navigation** 
Vue-navigation | Unchanged non-vue navigation
---|---
=> Harmonize focus-visible styles for vue-navigation item with none-vue navigation item

src/components/NcActionInput/NcActionInput.vue
* This allows to append the `NcSelect` in `NcActionInput` to body. This prevents clipping the select by the action menu.
Code-wise it would be simpler to just remove `:append-to-body="false"`, but this would introduce a breaking change, as it would set `append-to-body` to `true` by default for `NcSelect`. So I decided to add a prop instead.
Also, for vue 3 this is not necessary, since `v-bind="$attrs"` overwrites the props already set on the component.
---|---
=> feat(NcActionInput): allow to append `NcSelect` to body

cypress.config.ts, cypress/visual/AppNavigationItem.cy.ts
* Brings back the cypress tests for `NcAppNavigationItem`.
=> [next] fix(NcAppNavigationItem): run cypress tests

src/components/NcBreadcrumb/NcBreadcrumb.vue, src/components/NcBreadcrumbs/NcBreadcrumbs.vue
* Fixes opening the hidden breadcrumbs menu when dragging and hovering over the menu. The `dragenter` and `dragleave` events where not emitted, so the listener in `NcBreadcrumbs` was never called, hence, the hidden crumb menu not opened. Emitting the events fixes the issue.
=> [next] fix(NcBreadcrumb): correctly emit drag events

l10n/messages.pot, package-lock.json, package.json, src/components/NcSelect/NcSelect.vue
- For https://github.com/nextcloud/server/issues/41902
- Bump vue-select to v3.25.0 with a11y fixes
- Add ariaLabelListbox
- Minor fixes
=> enh(NcSelect): Improve accessibility

CHANGELOG.md
* Adds a short guide for the migration from `8.4.0` to `9.0.0`.
Closes #5030.
=> [next] chore: add a migration guide for `9.0.0`

src/components/NcDateTime/NcDateTime.vue, src/composables/index.js, src/composables/useFormatDateTime.js, tests/unit/components/NcDateTime/NcDateTime.spec.js, tests/unit/composables/useFormatDateTime.spec.js
I need the formatting logic in an application so instead of copy-paste lets externalize it into a composable.
=> enh: Make the date time formatting reusable for applications

src/components/NcDateTimePicker/NcDateTimePicker.vue
* Fix #5044 
Use ISO week numbers by default, but still allow users to override it using the `formatter`  prop.
---|---
=> fix(NcDateTimePicker): Use ISO week numbers if `showWeekNumber` is set

src/components/NcActions/NcActions.vue, src/mixins/actionText.js, tests/unit/components/NcActions/NcActions.spec.ts
* Follow up on #4955 
* Resolves https://github.com/nextcloud-libraries/nextcloud-vue/issues/2315
The actions support the `icon` prop with class and URL, but if they are rendered as inline actions the URL was not used currently as the icon but set as class.
---|---
=> fix(NcActions): In case of inline actions make sure to support icon as URL

src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
* Fixes the detection whether `NcCheckboxContent` has text. Before, it would always be `true` leading to a wrong padding right.
---|---
=> [next] fix(NcCheckboxContent): correctly check default slot

src/components/NcAppSettingsDialog/NcAppSettingsDialog.vue, src/components/NcDialog/NcDialog.vue
* Follow-up from #4550
* It feels counter-intuitive now for some dialogs (ex-modals) to not be closed with outside click. That doesn't apply to small confirmation popups, but some general things should be reverted to old behavior with this:
* NcAppSettingsDialog
* FilePicker
* e.t.c.
=> fix(NcDialog): allow to close NcDialog on click outside

src/components/NcBreadcrumbs/NcBreadcrumbs.vue
* Fix #5063.
In vue 3, the `props` also contains the `ref`s. If we forward them to the hidden crumbs, `ref` will be `null` once the hidden crumbs are destroyed (after the action menu is closed). This will lead to the `ref`s of the original crumbs being `null` too, causing the resize to fail.
=> [next] fix(NcBreadcrumbs): do not forward refs to hidden crumbs

src/components/NcHeaderMenu/NcHeaderMenu.vue
- For https://github.com/nextcloud/server/issues/41875
- Close the menu automatically on focusout
- Alternative way using keydown is not sufficient as users may switch focus to an external element by targetting it directly via e.g. mouse or screen reader
=> enh(NcHeaderMenu): Close navigation header menu on focusout

src/components/NcCheckboxRadioSwitch/NcCheckboxContent.vue, src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
* Fix #4661
Vue-Styleguidist tries to parse the values list from `validator`, but crashes when it is an array of not values itself but constants.
---|---
=> chore(docs): correct list types values for styleguidist in NcCheckboxRadioSwitch

src/components/NcSettingsSection/NcSettingsSection.vue
Once the nextcloud/vue8.5.0 releases a,d the server repository gets the new library update, then the servers issue will be properly fixed!
Adds an aria label to all sections that use NcSettings Section
Example ^ This now has an aria label. Since the icon has no text, it needs a label AND a title for accessibility
=> enh(a11y): added aria-label that matches title attr on icon

.eslintrc.js, l10n/messages.pot, src/assets/status-icons/user-status-away.svg, src/assets/status-icons/user-status-dnd.svg, src/assets/status-icons/user-status-invisible.svg, src/assets/status-icons/user-status-online.svg, src/components/NcAvatar/NcAvatar.vue, src/components/NcRichContenteditable/NcAutoCompleteResult.vue, src/components/NcUserStatusIcon/NcUserStatusIcon.vue, src/components/NcUserStatusIcon/index.js, src/components/index.js, src/utils/UserStatus.ts
- For https://github.com/nextcloud/server/issues/42644
Add new NcUserStatusIcon component for accessibility
> No visual changes
=> feat: Add NcUserStatusIcon

src/components/NcBreadcrumb/NcBreadcrumb.vue
This fixes the semantic problems when no redirection link is provided to the NcBreadcrumb component, so it renders our own NcButton. To fix the problem references, nextcloud/server#42624, we would have to update NcDialog's library version for vue
---|---
=> enh(breadcrumb): conditionally renders button when no redirection link given

l10n/messages.pot, src/components/NcActions/NcActions.vue, src/components/NcButton/NcButton.vue, src/components/NcColorPicker/NcColorPicker.vue, src/components/NcDateTimePicker/NcDateTimePicker.vue, src/components/NcEmojiPicker/NcEmojiPicker.vue, src/components/NcPopover/NcPopover.vue, src/components/NcPopover/NcPopoverTriggerProvider.vue, src/components/NcUserBubble/NcUserBubble.vue, styleguide.config.js, styleguide/global.requires.js, tests/OC.js
* Fix https://github.com/nextcloud/server/issues/41904
* In the issue there is only 1 place, but we have this issue in literally all `NcPopover` usages except `NcActions`...
1. `NcPopover` trigger button should have a11y attributes
- `aria-haspopup="<role>"`
- `aria-expanded="<is shown>"`
3. Trigger button is provided via slot in place, we don't control it
```html
<NcPopover>
<template #trigger>
Any button here should have attrs
</template>
</NcPopover>
```
3. We don't want to control all the places where `NcPopover` is used to make sure its trigger button has attributes.
This implementation might look a bit complex, but it helps to make a lot of popovers more accessible.
So any component used as a trigger may receive the attrs, required to be on the trigger
A small component …
=> feat(NcPopover): provide a11y attributes to the trigger

src/components/NcInputField/NcInputField.vue
* Fix https://github.com/nextcloud/server/issues/42498
@nextcloud-libraries/designers
=> fix input disabled appearance

src/components/NcButton/NcButton.vue
* This PR adjusts `NcButton` to render an `a` if the `to` prop is provided instead of a `button` as before. This is the expected behaviour (for me) and fixes #5089.
=> fix(NcButton): use `a` as tag for router-link

src/components/NcSelect/NcSelect.vue
* Fix https://github.com/nextcloud-libraries/nextcloud-vue/issues/4943
`outline` shows a border on all the sides, including the top, which looks like a gap.
Using `box-shadow` allows adding outline only on 3 sides, except the top.
---|---
=> fix(NcSelect): remove visual gap on top of the list

src/components/NcAppSettingsDialog/NcAppSettingsDialog.vue, tests/unit/components/NcAppSettingsDialog/NcAppSettingsDialog.spec.ts
* For https://github.com/nextcloud/server/issues/42599
* See https://github.com/nextcloud/server/issues/42599#issuecomment-1879050422
* Navigation example: https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/navigation.html
No visual changes. Result: no errors through automatically a11y tests.
=> Remove unneeded `tab`, `tablist` and `aria-selected` roles from navigation

src/components/NcAppSettingsDialog/NcAppSettingsDialog.vue, src/components/NcDialog/NcDialog.vue
Allows labeling navigation in dialogs when the name doesn't work well as a navigation label.
For example, "Select location for attachments" doesn't work well as a navigation for "All files", "Recent", Favorites".
Also, updated labeling in `NcAppSettingsDialog` using this new prop
Before | After
---|---
=> feat(NcDialog): add navigationAriaLabel and navigationAriaLabelledBy props

src/components/NcInputField/NcInputField.vue, tests/unit/components/NcInputField/NcInputField.spec.ts
If the type is set to number and a number is passed as value also emit a number instead of a string.
It always bugs me that you have to write wrappers otherwise, example:
```vue
<template>
<NcInputField type="number" :value="someObject.number" @update:value="(v) => someObject.number = Number(v)" />
</template>
```
vs with this:
```vue
<template>
<NcInputField type="number" :value.sync="someObject.number" />
</template>
```
=> enh(NcInputField): Support numeric values - if numeric also emit numeric

src/components/NcProgressBar/NcProgressBar.vue
* Implement the option to have a circular progress bar for `NcProgressBar`. For this I added the `type` prop to switch between `linear`  and `circular` with `linear` being the default. I also added a `color` prop, to give it a custom color.
* Required for https://github.com/nextcloud/tasks/pull/2464
No visual changes to existing components, no breaking changes.
Used in the Tasks app it looks like this:
=> feat(NcProgressBar): add circular progress bar

src/components/NcSettingsSection/NcSettingsSection.vue
* For https://github.com/nextcloud/server/issues/42941
Opacity is a bad choice for a11y in general. Let's remove it.
---|---
=> Remove inaccessible opacity from SettingsSection

src/components/NcPopover/NcPopover.vue
Fixes a typo in the `NcPopover` docs. Not critical for vue 2, but breaks the example for vue 3.
=> fix(NcPopover): fix docs example

src/components/NcPopover/NcPopover.vue, src/components/NcPopover/NcPopoverTriggerProvider.vue
* Fix https://github.com/nextcloud-libraries/nextcloud-vue/issues/5108
* Alternative to https://github.com/nextcloud-libraries/nextcloud-vue/pull/5104 to keep check in Vue 3
Popover content is usually only the trigger. So no need to check content in a slot component.
Trigger's parent DOM node is accessible by `$refs` of Floating-Vue.
For Vue 3 only requires to change `refs` from Floating-Vue.
=> fix(NcPopover): check trigger a11y compatible with Vue 3

src/components/NcHeaderMenu/NcHeaderMenu.vue
🏡 After
---
- make sure the the pointer is cursor on all elements that can be input into the #icon slot
=> fix(NcHeaderMenu): mouse in now pointer

src/components/NcRichText/NcReferenceList.vue
Allow to render a fallback widget if no other reference widget loads.
=> feat(NcReferenceList): Add support for a fallback reference widget

src/mixins/actionGlobal.js
- Since Vue 2.6 with new slots api, it is guaranteed that `$scopedSlots` has render function for all slots passed any way, while `$slots` only has value when using deprecated API or short-hand syntax
- It also closer to Vue 3 API
- `before` method is removed, there is no such lifecycle hook
It allows dynamically defining text content of the component in template without the need to rewrite the component to render-function.
See: https://v2.vuejs.org/v2/api/#vm-scopedSlots
When using non-deprecated slots api:
---|---
=> fix(NcActions): use new slots api

src/assets/action.scss, src/components/NcActionButton/NcActionButton.vue, src/components/NcActionButtonGroup/NcActionButtonGroup.vue, src/components/NcActions/NcActions.vue, tests/unit/components/NcActions/NcActions.spec.ts
* Fix https://github.com/nextcloud-libraries/nextcloud-vue/issues/425
NcButton already allows a checked state so this introduces this for the NcActionButton.
In checked state the `aria-pressed` attribute will be added and a primary border will indicate it visually.
https://github.com/nextcloud-libraries/nextcloud-vue/assets/1855448/c90a7c12-e663-4cd6-8abd-5d3848088de1
=> feat(NcActionButton): Allow pressed state on NcActionButton - similar to NcButton

src/components/NcDialog/NcDialog.vue
* Fix https://github.com/nextcloud/mail/pull/9144#issuecomment-1900748293
---|---
B | A
=> Fix additionalTrapElements to accept HTMLelements as well

cypress/component/richtext.cy.ts, jest.config.js, package-lock.json, package.json, src/components/NcRichText/NcRichText.vue, src/components/NcRichText/autolink.js, src/components/NcRichText/richtext.scss, tests/unit/components/NcRichText/NcRichText.spec.js
* Add package [remark-gfm](https://github.com/remarkjs/remark-gfm) for further support of:
* autolink literals
* footnotes ??
* strikethrough `~~`
* tables ` -- | -- `
* tasklists ` - [ ]` `- [x]`
* parsed text was hacked to insert non-breaking space between each two new lines. Thus span which rendered for a new line, have both width and height parameters, and is visible in the window
[markdown-checkboxes.webm](https://github.com/nextcloud-libraries/nextcloud-vue/assets/93392545/a842bfb8-1e56-4777-9971-cb0c847694ab)
In Talk messages:
=> feat(`NcRichText`) add support of GFM (extended markdown)

CHANGELOG.md, package-lock.json, package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.5.0...v8.4.0)
* enh(NcSelect): Add visible input label by @Pytal in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4963
* feat(NcModal): Set return focus element on focus trap deactivation by @Pytal in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5025
* Harmonize focus-visible styles for vue-navigation item with none-vue navigation item by @JuliaKirschenheuter in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5022
* feat(NcActionInput): allow to append `NcSelect` to body by @raimund-schluessler in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5017
* enh(NcSelect): Improve accessibility by @Pytal in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5036
* …
=> chore(release): v8.5.0

CHANGELOG.md
---
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v9.0.0...v8.4.0)
* The package now uses Vue 3 instead of Vue 2.7
* The package is now a native ESM package
* The `checked` prop was renamed to `modelValue`, the `update:checked` event was renamed to `update:modelValue`. This affects the following components.
- `NcActionCheckbox`
- `NcActionRadio`
- `NcCheckboxRadioSwitch`
* The `value` prop was renamed to `modelValue`, the `update:value` or `input` events were renamed to `update:modelValue`. This affects the following components.
- `NcActionInput`
- `NcActionTextEditable`
- `NcColorPicker`
- `NcDateTimePicker`
- `NcDateTimePickerNative`
- `NcInputField`
- `NcPasswordField`
- `NcRichContenteditable`
- `NcSelect`
- `NcSelectTags`
- `NcSettingsInputText`
- …
=> chore: Prepare 9.0.0-alpha.0

src/components/NcTimezonePicker/NcTimezonePicker.vue
---|---
1.  Removes the styling issue presented in the before picture (contrast ratio for the heading of the grouping not being correct. This is due to NcSelect marking the header as a non-selectable element due to us passing in the header as an object)
2. Now leaves us (for later!) to decide how to better organize the groupings better visually, as right now, I personally do not like the presentation of the areas. But that is me, personally, and we can always work on a better design later :)
=> fix: removed groupings in timezone picker

src/components/NcInputField/NcInputField.vue, src/components/NcRichContenteditable/NcRichContenteditable.vue, src/components/NcTextArea/NcTextArea.vue
Before, it had the same line-height in docs, but server has different styles.
See: https://github.com/nextcloud-libraries/nextcloud-vue/pull/5132
Manually set the same line-height, which is the minimum allowed for a11y and was supposed to be set during development.
* Fix https://github.com/nextcloud-libraries/nextcloud-vue/issues/5128
---|---
=> fix(fields): adjust label line-height

src/components/NcHeaderMenu/NcHeaderMenu.vue
=> fix(header): width regression fixed

src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
The checkbox sets are currently broken as the click even does not set the checked state anymore thus the wrong value is emitted (tab + space works).
=> fix(NcCheckboxRadioSwitch): Make sure to include current value in cheched array

src/components/NcAppSettingsDialog/NcAppSettingsDialog.vue, src/components/NcDialog/NcDialog.vue, src/components/NcModal/NcModal.vue
* Fix https://github.com/nextcloud/server/issues/42938
* NcDialog:
* Adjust styles to prevent two scrollbars on small screens
This also fixes some design issues, we do not want padding or margin on the bottom and right of the content in case of a scrollbar. When scrolling the scrollbar should be on the very left (not floating in the middle) and the scrolled content should be clipped by the modal container.
* Also ensure the dialog name is not overflown by the close button.
* NcModal:
* Use more height for a modal when window height is small, not only when window width is small.
* NcAppNavigationSettings
* Apply padding also for dialog name on small sizes where the name is not centered
**Note the double scrollbars**
---|---
=> fix: Ensure no double scrollbars for NcDialog and NcAppNavigationSettings

src/components/NcCheckboxRadioSwitch/NcCheckboxContent.vue
The text was not correctly centered, see below
---|---
=> fix(NcCheckboxRadioSwitch): On button style align the text vertically

src/components/NcActionButton/NcActionButton.vue
Allows to have checkbox-like usage for developers having radio semantics for users.
Currently `NcActionButton[type="radio"]` supports only string `modelValue` based on `value` value. For example, if we have alignment, we can use the button with one string variable with `left | center | right` value.
```html
<NcActionButton :model-value.sync="align" value="left"   type="radio" />
<NcActionButton :model-value.sync="align" value="center" type="radio" />
<NcActionButton :model-value.sync="align" value="right"  type="radio" />
align = left | center | right
```
It is great in a general case. But sometimes it is more convenient to define `boolean` check value for each button. For example, in `text`, where the value is more complex like `['heading', { level: 1 }]` and is managed by `Tiptop`. …
=> feat(NcActionButton): support boolean value for radio type

src/components/NcButton/NcButton.vue, src/components/NcPopover/NcPopover.vue, src/components/NcPopover/NcPopoverTriggerProvider.vue
Though it must be fine in Vue 3.3+, for some reason, sometimes `computed` in `provide/inject` is not reactive.
It works in `docs`, in `server`, in `Talk`. But it doesn't work in `Text`...
We had a similar issue with provide/inject in `NcSidebarTabs` in past.
@raimund-schluessler I also included a small fix with `internalShown` based on your comment somewhere
=> fix(NcPopover): a11y attrs provide-inject reactivity

l10n/messages.pot, src/components/NcActions/NcActions.vue, src/components/NcAvatar/NcAvatar.vue, tests/unit/components/NcAvatar/NcAvatar.spec.ts
- For https://github.com/nextcloud/server/issues/42957
<details>
<summary>Previous iteration</summary>
- Previously the tab sequence would go from wrapper span[role="button"] -> action menu button -> next element on page. Only the span focus would show visual focus while the action menu button had none so there would appear to be a gap in the tab sequence.
- W3 states that "a button element allows phrasing content as descendants, and does not allow interactive content or descendants with a tabindex attribute. Therefore, any elements specified with a role=button would follow the same descendant restrictions, and not allow any interactive content descendants, elements with a tabindex specified, or any elements with role values that are in the interactive content category" …
=> fix(NcAvatar): Remove span wrapper button semantics in favour of internal button components

CHANGELOG.md, package-lock.json, package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.5.0...v8.5.1)
* fix(NcPopover): a11y attrs provide-inject reactivity [\#5142](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5142) \([ShGKme](https://github.com/ShGKme)\)
* fix(NcCheckboxRadioSwitch): On button style align the text vertically [\#5151](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5151) \([susnux](https://github.com/susnux)\)
* fix: removed groupings in timezone picker [\#5130](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5130) \([emoral435](https://github.com/emoral435)\)
* fix(fields): adjust label line-height [\#5133](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5133) \([ShGKme](https://github.com/ShGKme)\)
* fix(header): width regression …
=> chore: Prepare 8.5.1

src/components/NcRichText/NcReferenceList.vue, src/components/NcRichText/widgets.js
* Fix #5090 
Allow apps that display link previews to pass in if they want to request interactive link previews or not. We default to false to not have any breaking behaviour for apps. When apps register a preview render function with `registerWidget` they can then handle either the non-interactive or interactive view based on that flag. Apps not handling this will just fallback to the existing preview rendering that is currently in place already.
Just pass in the interactive property to the NcReferenceList component
```
<NcReferenceList :text="'https://nextcloud.com/f/1234'" :interactive="true" />
```
```
registerWidget('deck-board', (el, { richObjectType, richObject, accessible, interactive }) => {
if (interactive) {
// render interactive component to el
return
}
// existing custom …
```
=> feat: Implement widget flag for requesting interactive view

src/components/NcActions/NcActions.vue
* Fix - see comment https://github.com/nextcloud-libraries/nextcloud-vue/pull/4953#pullrequestreview-1845179797
Fixes keyboard navigation in two cases:
1. When a menu type is determined incorrect because **inline actions** were taken into account
- E.g. where is an inline button and we thought, it is in the menu
2. Correctly handle <kbd>Tab</kbd> blur, when there is no focusable element in the actions
There are quite a lot of changes.
Separated with 💙 into small commits to be easier to review.
---|---
=> fix(NcActions): keyboard navigation

package-lock.json, package.json
* Follow up on #5103 to make the selector reactive
=> fix: Update emoji-mart-vue-fast to make skin tone selector reactive

src/components/NcListItem/NcListItem.vue
* Provide an option to use slot (for embedding icon / custom template) instead of prop string
=> feat(`NcListItem`): introduce 'details' slot

src/components/NcSelect/NcSelect.vue
By default Vue-Select takes width for content list on element insert.
But if select is resized after opening (for example, on page scale), that width is not actual anymore.
Manually set width according to the toggle element on update.
The current solution is a bit glitchy when select has flexible width. Not sure, how to fix better.
* Fix #4943
---|---
=> fix(NcSelect): list width on page scaling

package-lock.json, package.json
Full changelog: https://github.com/nextcloud-libraries/nextcloud-vite-config/compare/v1.2.0...v1.2.1
* fix(css-plugin): Use `generateBundle` hook to prevent CSS imports from being lost [\#112](https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/112) \([susnux](https://github.com/susnux)\)
=> chore(deps): bump nextcloud-vite-config library from 1.2.0 to 1.2.1

src/components/NcNoteCard/NcNoteCard.vue
* Allows to replace default icon with a custom one
* If no custom icon is provided, default is used as a fallback for a slot
* Reduce efforts for implementing a workarounds and extra wrappers, if custom icon is needed
| 🏡 After
|---
| ![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/93392545/cbd0c314-a9d3-466e-9631-a27d536d8f42)
=> feat(NcNoteCard): provide a slot for inserting a custom icon instead of default

CHANGELOG.md
Added to GitHub release but missed in version controlled CHANGELOG.md 😵
=> chore: Fix missing PR from changelog

src/components/NcAppNavigationToggle/NcAppNavigationToggle.vue
---|---
This has the same changes from nextcloud/photos#2285
- When the viewport got small in the photos app, the app-navigation-button overflowed to the right of the screen, becoming inaccessible
- To fix this, since the button is positioned relative to the header, I removed some of the negative right positioning on the button
This allows the button to still be in view, while a little tight, and also still allows it to be found with keyboard navigation 👍
Any styling choices can be commented on !
=> fix: app-navigation-toggle remains on screen on small viewports

src/components/NcActions/NcActions.vue
* Resolves: #4910
When the component has its own focus trap, then it is managed by global trap stack by focus-trap.
However if the component has no focus trap and is used inside another focus trap - there is an issue. By default popover content is rendered in body or other container, which is likely outside the current focus trap containers. It results in broken behavior from focus-trap.
We need to pause all the focus traps for opening popover and then unpause them back after closing.
---|---
Header Menu | .
Sidebar multi-level | .
Focus trap still works.
Supports multi-level focus traps (header menu focus trap inside sidebar trap):
=> fix(NcActions): intercept into current focus trap stack

src/components/NcAppSidebar/NcAppSidebar.vue
* This PR fixes the animation class names of `NcAppSidebar`. The names were changed with vue 3, see here https://v3-migration.vuejs.org/breaking-changes/transition.html
=> [next] fix(NcAppSidebar): adjust animation class names

CHANGELOG.md, src/components/NcActions/NcActions.vue, src/components/NcAppNavigationToggle/NcAppNavigationToggle.vue, src/components/NcSelect/NcSelect.vue
* Merges `master` into `next`.
#4953 had some conflicts, so here is the manual merge / backport.
=> [next] chore(master): merge `master` into `next`

src/components/NcContent/NcContent.vue
* This brings back the `NcAppSidebar` example in the docs and adjusts the style to actually show `NcContent`.
* It also fixes an issue in the styleguide with `Teleport` as the `#skip-actions` element was not present.
=> [next] fix(docs): bring back NcAppSidebar in docs

src/components/NcActions/NcActions.vue
* Hotfix for https://github.com/nextcloud-libraries/nextcloud-vue/issues/5171
* Particularly a regression of https://github.com/nextcloud-libraries/nextcloud-vue/pull/5153
In `NcActions` we check what `NcAction*` components were passed as direct children. But some apps (Text, Mail) pass `NcAction*` not as direct children of `NcActions`, but as a sub-child.
```html
<NcActions>
<MyUserActionsList /> // renders <NcActionButton />
</NcActions>
```
The current `NcActions` implementation doesn't fully support this.
- In past it resulted in ignoring `inline` prop and incorrect render of single actions
- After mentioned PR it was completely broken:
1. Menu is rendered
2. There are no direct `NcAction*` interactive children (they are sub-children)
3. Menu is considered a tooltip
4. It should close …
=> fix(NcActions): hotfix for custom children

src/components/NcDateTimePickerNative/NcDateTimePickerNative.vue
Create possibility to change a color theme for native datetime picker on system default theme
* Fix https://github.com/nextcloud/server/issues/42392
---|---
=> Create possibility to change a color theme for native datetime picker on system default theme

CHANGELOG.md, package-lock.json, package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.5.1...v8.6.0)
* feat: Implement widget flag for requesting interactive view by @juliushaertl in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5144
* feat(NcListItem): introduce 'details' slot by @Antreesy in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5146
* feat(NcNoteCard): provide a slot for inserting a custom icon instead of default by @Antreesy in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4894
* fix(NcActions): keyboard navigation by @ShGKme in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5153
* fix(NcSelect): list width on page scaling by @ShGKme in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5162
* fix(NcColorPicker): define a …
=> chore: prepare 8.6.0 release

.github/workflows/npm-publish.yml
This did not work since we migrated from `nextcloud` to `nextcloud-libraries`.
=> fix(CI): Adjust npm-publish to work with GPR

src/assets/NcAppNavigationItem.scss
* Fixes a regression with `NcAppNavigationNewItem` that I introduced in #4989. Closes #5159.
---|---
=> fix(NcAppNavigationNewItem): bring back correct CSS class

CHANGELOG.md, package-lock.json, package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.5.0...v9.0.0-alpha.1)
* fix(NcAppSidebar): adjust animation class names by @raimund-schluessler in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5168
* fix(docs): bring back NcAppSidebar in docs by @raimund-schluessler in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5167
=> chore: prepare v9.0.0 alpha.1

src/mixins/actionGlobal.js
* Fix https://github.com/nextcloud/mail/issues/9282
* Reverts: https://github.com/nextcloud-libraries/nextcloud-vue/pull/5118
`$scopedSlots` cannot be used in `beforeUpdated` hook.
- On re-rendering, when `vnode` is reused, on beforeUpdated state `$scopedSlots` still returns an old value and breaks rendering.
- Officially, `$slots/$scopedSlots` should be used only during the rendering and not supposed to be used in `data`, `computed` or life cycle hooks.
This commit returns `$slots` to have an old behavior and resolve a regression
TODO: find a better solution to support both slots API. Use method in template and always call it, like we do in Vue 3?
=> revert: fix(NcActions): use new slots api

CHANGELOG.md, package-lock.json, package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.6.0...v8.6.1)
* fix(NcAppNavigationNewItem): bring back correct CSS class [\#5194](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5194) \([raimund-schluessler](https://github.com/raimund-schluessler)\)
* revert: fix(NcActions): use new slots api [\#5196](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5196) \([ShGKme](https://github.com/ShGKme)\)
* Updated translations
* fix(CI): Adjust npm-publish to work with GPR [\#5183](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5183) \([susnux](https://github.com/susnux)\)
* chore(CHANGELOG): Add missing entry for 8.6.0 release [\#5192](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5192) …
=> chore: Release 8.6.1

src/components/NcHeaderMenu/NcHeaderMenu.vue
---|---
Regression for the aforementioned PR
- On small viewports, the button nested inside the wrapper for NcHeaderMenu stayed 50x50 px. This change ensures that the trigger button is the same size as the wrapper component on small viewports, which is 44x50 px. This now keeps the styling on the server consistent and working!
=> fix: button size regression on small viewports fixed

src/components/NcListItem/NcListItem.vue
* Fix https://github.com/nextcloud/server/issues/43237
It is not valid to put `button` inside `a` thus we need to refactor the NcListItem:
1. Unify the *actions* location within the source to be outside the main wrapper
2. Replace wrapper `a` with `div`
3. Make only the main content an `a` , this is required so users can right click + copy link or middle click -> native browser behavior.
4. Not related but fix *focus-visible* to have consistent style across all components.
*Hint: Hide white space changes when review*
Could not spot visual changes except from focus visible.
https://github.com/nextcloud-libraries/nextcloud-vue/assets/1855448/de196e16-541e-4f5e-9517-23119fa4ceed
=> fix(NcListItem): Remove actions from within `a` which caused invalid HTML output

src/components/NcSelect/NcSelect.vue
- Mention `labelOutside` for developers
=> chore(NcSelect): Mention labelOutside for external label use

src/components/NcRichContenteditable/NcAutoCompleteResult.vue, src/components/NcRichContenteditable/NcRichContenteditable.vue
* Fix https://github.com/nextcloud/server/issues/41896
Adds a contrast outline border for keyboard navigation only.
Also, unifies styles in different autocompletes with NcActions and NcSelect components.
Previously, there were no "general" styles for the tribute container and items. Different autocompletes had a bit different styles on always individual classes. Now:
- There are common classes and structure is always:
```
div.tribute-container (+ additional custom .tribute-container-NAME)
ul
li.tribute-container__item (+ .highlight + .tribute-container-NAME__item)
div.tribute-item
<custom content>
```
- An autocomplete item now:
- Always has padding
- Always has border radius
- Always has `hover` background color same as `NcSelect` or `NcActions`
---|---
=> fix(NcRichContenteditable):  unify styles and add contrast border on keyboard navigation

src/components/NcRichContenteditable/NcAutoCompleteResult.vue, src/components/NcRichContenteditable/NcMentionBubble.vue, src/components/NcRichContenteditable/NcRichContenteditable.vue, src/components/NcRichText/NcRichText.vue, tests/unit/mixins/richEditor.spec.js
* Kind of a regression of https://github.com/nextcloud-libraries/nextcloud-vue/pull/4222/
`NcAutoComplete` used in `NcRichContenteditable` had props that were in line with server API response for mentions.
In that PR `label` was renamed to `title`. not it is not possible to use mentions API resopnse without data mapping.
For example, in Talk https://github.com/nextcloud/spreed/pull/10626/commits/ea667ff6e1b9ae8515bd55b8d499a316b6dfe25f a work around was added:
https://github.com/nextcloud/spreed/blob/ea667ff6e1b9ae8515bd55b8d499a316b6dfe25f/src/components/NewMessage/NewMessage.vue#L709-L712
```js
// TODO fix backend for userMention
if (!possibleMention.title && possibleMention.label) {
possibleMention.title = possibleMention.label
}
```
While in server it was forgotten: 
This PR brings …
=> fix(NcRichContenteditable): bring back label for autocomplete

src/components/NcActions/NcActions.vue, src/components/NcAppSidebar/NcAppSidebar.vue, src/components/NcAppSidebarTab/NcAppSidebarTab.vue
* Fix for https://github.com/nextcloud/server/issues/41877
* Can be tested with https://github.com/nextcloud/server/pull/42444
See description in commits.
1. Open sidebar
2. Focus is moved to the sidebar
3. Close sidebar
4. Focus is moved to the trigger button
5. For menu - special case, return to the menu trigger
https://github.com/nextcloud-libraries/nextcloud-vue/assets/25978914/a286b6a2-5a55-4d70-bd39-674016000bc4
https://github.com/nextcloud-libraries/nextcloud-vue/assets/25978914/2dd59a40-0587-4c64-8e96-ebd0e70df85a
https://github.com/nextcloud-libraries/nextcloud-vue/assets/25978914/6698351a-883b-4162-850f-6c250081f11d
https://github.com/nextcloud-libraries/nextcloud-vue/assets/25978914/7d940181-8ee8-43c0-88bd-50d42f7aa60e …
=> feat(NcAppSidebar): move focus to sidebar on open and auto return focus on close

CHANGELOG.md, package-lock.json, package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.6.1...v8.6.2)
* In `NcRichContenteditable` properties `autoComplete.title`/`userData.title` were renamed back to `label` to be in line with server API. The `title` property is still working as a fallback, but deprecated. See https://github.com/nextcloud-libraries/nextcloud-vue/pull/5215
* fix(NcHeaderMenu): button size regression on small viewports fixed by @emoral435 in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5149
* fix(NcListItem): Remove actions from within `a` which caused invalid HTML output by @susnux in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5198
* fix(NcRichContenteditable): make autocomplete accessible by @ShGKme in …
=> release: v8.6.2

src/components/NcRichContenteditable/NcRichContenteditable.vue, stylelint.config.js, webpack.config.js
* Fix https://github.com/nextcloud/mail/issues/9310
* Fix https://github.com/nextcloud/server/issues/43478
`NcRichContenteditable` has global CSS styles to style Tribute autocomplete. It works fine, until there are more than one version of those styles on the page. Styles should be scoped.
@szaimen @hamza221 @JuliaKirschenheuter Could you please check it in your apps? The bug was not reproducible for me...
Note, there is no `data-v-<hash>` attrs in both cases.
Before | After
---|---
- Some issues were not noticeable before, because of other global styles
=> fix(NcRichContenteditable): adjust styles and use CSS Modules to avoid global styles leak

src/components/NcSelect/NcSelect.vue
- Part of https://github.com/nextcloud/server/issues/43383
- Add native form validation by setting the required attribute conditionally
=> feat(NcSelect): Add `required` attribute for native form validation

.github/pull_request_template.md
@raimund-schluessler Would it be a good alternative for merging `master` into `next`?
=> chore: add backport to `next` (Vue 3) in the PR checklist

src/components/NcModal/NcModal.vue
=> fix(NcModal): scope modal-container size to current modal, don't propagate it on nested

src/components/NcRichText/NcReferenceWidget.vue
* `new ResizeObserver(...)` is not available in some contexts. `useResizeObserver` handles these gracefully.
* `useResizeObserver` also takes care of the cleanup. See https://v5-3-0.vueuse.org/core/useresizeobserver/#usage .
- Fix `"ReferenceError: ResizeObserver is not defined"` in [jest tests](https://github.com/nextcloud/text/actions/runs/7862298422/job/21451607906#step:7:13)
---|---
=> fix(NcReferenceWidget): `useResizeObserver`

src/components/NcRichText/NcReferenceWidget.vue, src/components/NcRichText/NcRichText.vue, src/components/NcRichText/autolink.js
- Ref https://github.com/nextcloud/spreed/issues/10565
- Ref https://github.com/nextcloud/spreed/issues/8855
Tested against Talk:
- link to app root `/apps/spreed`
- links between different conversation `/call/{token}`
- links between specific messages `/call/{token}#message_id`
- both inline links and previews in NcReferenceWidget
Cursor is missing, but browser address bar is visible
https://github.com/nextcloud-libraries/nextcloud-vue/assets/93392545/9706a0d3-1e88-4dda-b897-4e6e28d7e7c2
=> feat(NcRichText): handle internal links with Vue Router

src/components/NcBreadcrumb/NcBreadcrumb.vue
For nextcloud/server#43604
🏡 After
-
-
* To prevent a breaking change, I decided to add a prop that user configures to enable the nationality to add text to accompany a icon breadcrumb that is a NcButton, and not an NcAction.
* Since default for iconText is false, all previous library users of NcBreadcrumb will not have breaking changes
* Library now allows user to have NcButton with just text, just icon, and now icon and text
=> enh: added option to render icon and text for breadcrumb

src/components/NcActionInput/NcActionInput.vue, src/components/NcColorPicker/NcColorPicker.vue
* This PR fixes `NcActionInput` to listen to the correct events of its child components. Before, the events of its childcomponents would not trigger an update of the model value.
* Fix #5229
=> [next] fix(NcActionInput): listen to correct events

package-lock.json, package.json
- This regenerates `package-lock.json` to get the latest version of various dependencies. Dependabot does not run for `next`, so we need to do it manually from time to time.
=> [next] chore: bump various dependencies

src/components/NcRichContenteditable/NcRichContenteditable.vue
- Fix regression from #4904 
- documentation on https://github.com/zurb/tribute#a-collection claims props such as `allowSpaces` and `menuContainer` to be a part of `Collection`, although they should be registered globally, if there are a collections array
- modify initial styles for root element, so it will be rendered outside of viewport and won't break layout
---|---
🏚️ Before 
[Screencast from 20.02.2024 12:35:34.webm](https://github.com/nextcloud-libraries/nextcloud-vue/assets/93392545/12e27b36-a933-4389-a427-0d5e8578ee37)
🏡 After
[Screencast from 20.02.2024 12:59:51.webm](https://github.com/nextcloud-libraries/nextcloud-vue/assets/93392545/b066da53-dd8b-49c7-905d-b27e4f03afe2)
=> fix(NcRichContenteditable): register props globally for new Tribute

src/components/NcDashboardWidgetItem/NcDashboardWidgetItem.vue
If we have no subtext the title shall be centered to the image
---|---
=> fix: Center dashboard list items when there is no subtext

cypress/component/NcAppNavigationSpacer.cy.ts, package-lock.json, package.json, src/components/NcAppNavigationSpacer/NcAppNavigationSpacer.vue
- Fix #5210
Remove the order as it is only used to pin items to the bottom but when using spacers between elements, the spacer and the element need the same order.
Also added a test case.
=> fix(NcAppNavigationSpacer): Adjust order to make the spacer work again

src/components/NcRelatedResourcesPanel/NcResource.vue
- Reuse logic introduced in #5246 for Resource panel
- Allows to navigate between shared sources within one app (Talk on example)
- As logic is alreasy presented (`getRoute()` + `NcButton::to`), not considering it as breaking / feature for minor release
[Screencast from 21.02.2024 17:44:23.webm](https://github.com/nextcloud-libraries/nextcloud-vue/assets/93392545/5345d971-6289-4e87-8e61-464b8ad2decd)
=> fix(NcResource): use RouterLink where possible for internal shared resources

src/components/NcRichText/NcReferenceList.vue
This reverts https://github.com/nextcloud-libraries/nextcloud-vue/pull/5272
Unfortunately it caused issues with Talk.
See the discussion in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5290 and https://github.com/nextcloud-libraries/nextcloud-vue/pull/5272.
=> Revert "fix(NcReferenceList): Resolve relative URLs before fetching references"

src/components/NcActions/NcActions.vue, src/components/NcPopover/NcPopover.vue
- Resolves:  "More apps" action button have two unneeded attrs: `aria-haspopup` and `aria-controls`. It is enough to have only `aria-expanded` in this case.
Every navigation "menu" which contains only links should not have additional attributes `aria-haspopup` and `aria-controls`.
---|---
=> Remove `aria-haspopup` and `aria-controls` from navigation menu

src/components/NcPopover/NcPopover.vue, src/components/NcPopover/NcPopoverTriggerProvider.vue
- A small regression from https://github.com/nextcloud-libraries/nextcloud-vue/pull/5300
- `popupRole` was made non-required in `NcPopover` but then it should also be non-required in `NcPopoverTriggerProvider`
- And because `aria-haspopup` is not required now, it should not be checked when checking for required attrs
=> fix(NcPopover): make popupRole non-required

src/components/NcActions/NcActions.vue
1. <kbd>Arrow</kbd> and <kbd>Tab</kbd> keyboard navigation should not be used at the same time
- Either menu is an atomic UI element, and <kbd>Arrow</kbd> select menu items, <kbd>Tab</kbd> moves to the next UI element
- Or the menu is an expanded list of UI elements
2. When `actions` are used for navigation, it should work as just an expanded list with classic "native-like" <kbd>Tab</kbd> navigation without focus trap
- <kbd>Tab</kbd> on the last element closes the list and moves focus to the trigger
- <kbd>SHIFT + Tab</kbd> on the first element - the same
Also, I've put all the config that changes the behavior of the component in one place, so it's clearer what can be different and in which case.
Before Navigation worked as a Menu:
- Arrows - navigate between items
- Tab - navigate to …
=> fix(NcActions): put in order tab and arrow navigation

src/components/NcActions/NcActions.vue
`role="dialog"` must have a label. Labelling by the menu trigger button.
=> fix(NcActions): provide a label in dialog role

src/components/NcActions/NcActions.vue
- Brings back https://github.com/nextcloud-libraries/nextcloud-vue/pull/4678 after changes in the component
- `aria-selected` should be `aria-checked`
- `aria-checked` should not only present, but be `'true'`
- `aria-checked` must be on the focusable element itself (otherwise there is an a11y issue)
- New possibility — check only radio buttons
IMO, this should happen only when ALL the buttons are one radio button group. But it is required even for heading in Text, where we have "Show outline" button together with heading radio buttons.
The solution is still not reliable, but I don't see any other simple solution...
=> fix(NcActions): focus first checked item on open

src/components/NcRichContenteditable/NcRichContenteditable.vue
- Fix regression from #5268
- tributejs library doesn't support allowSpaces as a collection option, only as a global one. As we need it only for mentions ('@' trigger), the best option for now is to disable it completely
>[!IMPORTANT]
> Mentions couldn't be searched with spaces in uid or as a `name surname`
---|---
=> fix(NcRichContenteditable): disable global allowSpaces tribute option

src/components/NcActions/NcActions.vue, src/components/NcColorPicker/NcColorPicker.vue, src/components/NcEmojiPicker/NcEmojiPicker.vue, src/components/NcPopover/NcPopover.vue
- Our dialogs should be considered modal because they have `focus-trap` and click outside closes the dialog
=> fix(NcPopover): add aria-modal to some popover-based dialog components

vite.config.mts
- Regression from https://github.com/nextcloud-libraries/nextcloud-vue/pull/5328
=> fix: scope component breaking NcModal and NcDateTimePickers

CHANGELOG.md, package-lock.json, package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.8.0...v8.8.1)
* fix(NcSelect): handle text overflow in NcSelect by @hamza221 in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5325
* fix: scope component breaking NcModal and NcDateTimePickers by @ShGKme in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5331
=> release: v8.8.1

src/components/NcActions/NcActions.vue
- Regression from #5219
- Fix #5292 
- Also fix issues like https://github.com/nextcloud/spreed/issues/9725
There are couple of places, where triggering an action in NcActions (by click, for example) leads to unmounting / breaking re-rendering of NcActions immediately. (Examples in Talk: stop the screensharing (stable28), end the call (main)). In such cases, after `nextTick` ref elements (popover, menuButton) are no longer present in the DOM (`undefined`), thus attempt to call methods on them lead to an error (see issues).
Popover has `clearFocusTrap` in beforeDestroy hook, so changes should be safe to apply (regarding previous PR)
No behaviour change, just clean console :broom:
=> fix(NcActions): clear focus trap and move focus only if elements are existing in the DOM

l10n/messages.pot, src/components/NcRelatedResourcesPanel/NcRelatedResourcesPanel.vue, src/components/NcRelatedResourcesPanel/NcTeamResources.vue
- Resolve https://github.com/nextcloud/related_resources/issues/360
=> feat: List team resources in related resources panel

src/components/NcAppNavigation/NcAppNavigation.vue, src/components/NcAppNavigationList/NcAppNavigationList.vue
- Fix https://github.com/nextcloud/server/pull/43804#issuecomment-1977005782
- To fix the unscrollable content in NcAppNavigationList we wrap the entire default slot with a container
- The `div.app-navigation__body` now fills the height with `height: 100%`
- Remove the redundant `&:nth-last-of-type(2)` fill styles
- NcAppNavigationList now has `height: fit-content` in all contexts and is itself not scrollable now that scrolling is delegated to the container similar to the `ul.app-navigation__list` list slot behaviour
---|---
=> fix(NcAppNavigation): Wrap app navigation default slot with scrollable container

CHANGELOG.md, package-lock.json, package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.8.1...v8.9.0)
* feat(reference): Add opt-in for interactive mode and render widgets lazy once in view by @juliushaertl in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5257
* feat: List team resources in related resources panel by @juliushaertl in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5316
* fix(NcAppNavigation): Wrap app navigation default slot with scrollable container by @Pytal in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5347
* Updates for project Nextcloud vue library by @transifex-integration in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5333
* Updates for project Nextcloud vue library by @transifex-integration in …
=> chore: Release 8.9.0

src/components/NcAppNavigation/NcAppNavigation.vue, src/components/NcAppNavigationList/NcAppNavigationList.vue
- Revert https://github.com/nextcloud-libraries/nextcloud-vue/pull/5347
=> fix: Revert "fix(NcAppNavigation): Wrap app navigation default slot with scrollable container"

src/components/NcAppNavigation/NcAppNavigation.vue, src/components/NcAppNavigationList/NcAppNavigationList.vue
- Alternative for reverted https://github.com/nextcloud-libraries/nextcloud-vue/pull/5347
- Users tested with https://github.com/nextcloud/server/pull/43804, where no #list slot is used
Files | Users | Talk | Mail | Contacts
---|---|---|---|---
<details>
</details>
=> fix(NcAppNavigation): stretch the main content when there is no list slot

.github/workflows/npm-publish.yml
- Fix publish CI failures https://github.com/nextcloud-libraries/nextcloud-vue/actions/workflows/npm-publish.yml
=> chore: Remove GitHub Package Registry from publish workflow

src/components/NcRichContenteditable/NcRichContenteditable.vue
- Fix #5352
Tested against Talk (we handle Esc keyup depending whether tribute state is open or not 
Before (event isn't emitted -> blur input)
[Screencast from 06.03.2024 12:57:48.webm](https://github.com/nextcloud-libraries/nextcloud-vue/assets/93392545/b388d058-63a8-4931-a902-509675c8fe31)
After (Esc doesn't blur the input)
[Screencast from 06.03.2024 12:53:54.webm](https://github.com/nextcloud-libraries/nextcloud-vue/assets/93392545/7bff85ed-83e2-4571-af53-28398e72829d)
=> fix(NcRichContenteditable): capture and stop `Esc` keydown event when closing tribute

src/components/NcRelatedResourcesPanel/NcTeamResources.vue
Limit images provided by the backend in size, otherwise they might just overflow the list items
---|---
=> fix: Adjust styling of team resource images

src/components/NcAppContent/NcAppContent.vue, src/components/NcAppContent/NcAppDetailsToggle.vue, src/components/NcListItem/NcListItem.vue
* Ref https://github.com/nextcloud/mail/issues/8811
Having the possibility to switch to a full-width message/thread list. The three column design (nav + list + content) becomes two columns: nav + list or nav + content. The user will see the list. When they navigate to a message/thread, the content shows.
Adding a prop layoutMode to switch between views on NcAppContent and changing a bit the NcListItem, instead of putting the details inside the "line one" / "line two" we should split main content and details.
This allows to switch from flex-direction column to row for one-line layout without adjusting the DOM. This way we have the possibility to show the list in one line on mail, without breaking the other apps. 
When we are on list mode(oneLine) and content view is shown(aka thread on …
=> feat(NcAppContent): Support full width lists

README.md
- Fix https://github.com/nextcloud-libraries/nextcloud-vue/issues/5340
=> chore(README): remove build:module and watch:module

src/components/NcRichContenteditable/NcRichContenteditable.vue
=> fix(NcRichContentEditable): require leading space to open tributes

src/components/NcListItem/NcListItem.vue
I don't understand what that line is intended to do.
1. It prevents `target=_blank` above from working at all
2. You can't call `preventDefault` on the event anymore
~~This just makes zero sense to me.~~
My guess is, this is for the keyboard event? (even then, enter always triggers click if `href` is present, which should always be)
~Regardless, switched that to a explicit trigger.~
=> fix(NcListItem): open _blank link by Enter and allow prevent

src/components/NcRichText/NcReferenceWidget.vue, src/components/NcRichText/NcRichText.vue
In Talk we need to pass the interactive widget property over from NcRichText to be able to toggle it.
=> fix(NcRichText): Allow to pass interactive widget toggle

src/components/NcActions/NcActions.vue
- In `dialog`, `role="dialog"` should be not a replacement of `UL`
---|---
- So now almost everything that changes a11y stuff depending on a11y semantic role is moved to one place
- `role`, `aria-labelledby`, `aria-modal` and `id` to connect with `aria-controls`
=> fix(NcActions): correct dialog a11y attrs place

src/assets/status-icons/user-status-away.svg, src/assets/status-icons/user-status-dnd.svg, src/assets/status-icons/user-status-invisible.svg, src/assets/status-icons/user-status-online.svg
- Fix #5386
- As SVG is inserted as plain HTML into DOM, all styles should be provided from parent elements (Vue component) or by SVG itself
- Turns out Safari doesn't adjust SVG element sizes to fit content inside of it
- P.S Screenshots are mocked, but output is the same
---|---
=> fix(NcUserStatusicon): set status icons size explicitly

src/components/NcActions/NcActions.vue, styleguide.config.js, tests/unit/components/NcActions/NcActions.spec.ts
So we can make use of `NcActions` even when wrapping common groups of actions in components.
=> feat(NcActions): Allow to manually specify the semantic menu type

src/components/NcListItem/NcListItem.vue
- Ref https://github.com/nextcloud/mail/pull/9285
---|---
=> NcListItem - change padding for one-line layout

CHANGELOG.md, package-lock.json, package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.9.1...v8.10.0)
* feat(NcAppContent): add no-split layout by @GretaD in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5209
* feat(NcListItem): add one-line layout by @GretaD in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5209
* feat(NcActions): Allow to manually specify the semantic menu type by @susnux in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5336
* fix(NcAppNavigation): stretch the main content when there is no list slot by @ShGKme in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5360
* fix(NcRichContenteditable): capture and stop `Esc` keydown event when closing tribute by @Antreesy in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5353
* …
=> release: v8.10.0

src/components/NcListItem/NcListItem.vue
- Fix regression from #5209
🏡 Old Before | 🏚️ Before | 🏡 After
---|---|---
>[!TIP]
>As name is bold in one-line, you might have to use `:deep` selector to overwrite this or use a name slot (#5388)
=> fix(NcListItem): bring back old styling for two-line list items

src/components/NcListItem/NcListItem.vue
* For nextcloud/server#44109
To extend component flexibility, allow component to be able to render content to the side of name. For instance, in my case, I need to be able to add content to the side of the name for a customer request feature. However, the current implementation keeps the whole line one bolded, and for design reasons, it would be better to allow users of the library to manually style their side content.
Any input on how to better name the slot is appreciate as well :) I did not have any good naming convention to describe `content that aligns right to the name of line one`
🏡 New extension
---|
=> feat: add title slot for NcItemList component

src/components/NcAppContent/NcAppContent.vue
- Ref https://github.com/nextcloud/mail/issues/8309
---|---
B | A
=> Feat(NcAppContent) Add horizontal split for appcontent

src/components/NcListItem/NcListItem.vue
- Fix small regression from  #5400
- fix issues, when details are not provided
---|---
=> fix(NcListItem): align indicators at the element bottom

src/components/NcRichText/NcReferenceWidget.vue
- Fix flickering widgets moving in an out of viewport (Talk chat)
- When widget is out if view, a timer is set for 3 minutes (in case user scrolls back to it). If after timeout widget is still not visible, we destroy it, and it has to be rendered again
- If widget is already rendered, we don't trigger the render method
Sorry for bad sccreencast:
🏚️ Before - re-rendered each time
[before.webm](https://github.com/nextcloud-libraries/nextcloud-vue/assets/93392545/953f2e05-ad68-43f2-99d9-1e6e928cb80e)
🏡 After - re-rendered only if new or after 3 minutes
[after.webm](https://github.com/nextcloud-libraries/nextcloud-vue/assets/93392545/86758813-056d-4333-8dcc-bc75e1b0d15d)
=> fix(NcReferenceWidget): set timeout to destroy idle widgets outside of viewports

src/components/NcAvatar/NcAvatar.vue
- Fix https://github.com/nextcloud/talk-desktop/issues/548#issuecomment-1999608706
- Emoji status in NcAvatar's menu didn't work:
- URL was not correct, quotes were missing in `background-image: url()` which is required for data URL
- Emoji status was inverted in dark mode because NcAction's url icons are inverted if dark
To test - add icon to the `icon` property.
---|---
=> fix(NcAvatar): rendering user status emoji in the menu

src/components/NcAvatar/NcAvatar.vue
=> fix(NcAvatar): handle regex error on initials match

CHANGELOG.md, package-lock.json, package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.10.0...v8.11.0)
* feat(NcListItem): add title slot by @emoral435 in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5388
* feat(NcAppContent): add horizontal split layout by @GretaD in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5401
* fix(NcListItem): bring back old styling for two-line list items by @Antreesy in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5400
* fix(NcListItem): align indicators at the element bottom by @Antreesy in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5408
* fix(NcReferenceWidget): set timeout to destroy idle widgets outside of viewports by @Antreesy in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5411
* fix(NcAvatar): …
=> release: v8.11.0

src/components/NcAvatar/NcAvatar.vue, src/components/NcRichContenteditable/NcAutoCompleteResult.vue, src/components/NcRichContenteditable/NcMentionBubble.vue, src/utils/getAvatarUrl.ts, tests/unit/utils/getAvatarUrl.spec.ts
- Fix wrong user avatar colors in dark mode for autocomplete rendered components
---|---
=> fix(tribute): provide avatar url correctly when in dark mode

src/components/NcListItem/NcListItem.vue
- Fix regression from recent component rework (subname color was `max-contrast`)
- Decrease font-weight from bold `700` to medium `500`
- Numeric value is used because linter complained about it (see https://developer.mozilla.org/en-US/docs/web/css/font-weight#common_weight_name_mapping)
---|---
Talk | --
=> fix(NcListItem): decrease font-weight, restore contrast color for subname

src/components/NcAppNavigation/NcAppNavigation.vue
Signed-off-by: RayBB <RayBB@users.noreply.github.com>
- Fix https://github.com/nextcloud/server/issues/43969
~~Apologies, I cannot test this outside of the browser devtools because of https://github.com/nextcloud-libraries/nextcloud-vue/issues/5339 but it is a simple enough change I hope someone else can help test/verify until I can get a local instance working. Thanks!~~
Edit: Finally I was able to test in a local instance and it worked great, looks the same as the video I put below.
The "after" video shows before/after
---|---
=> fix(NcAppSidebar): animation glitch on toggle

src/components/NcActionInput/NcActionInput.vue
Before https://nextcloud-vue-components.netlify.app/#/Components/NcActions?id=ncactioninput yields an error in the console and leads to bad examples:
=> fix(NcActionInput): Add label to sample

CHANGELOG.md, package-lock.json, package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.11.0...v8.11.1)
* fix(tribute): provide avatar url correctly for dark mode by @Antreesy in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5420
* fix(NcListItem): decrease font-weight, restore contrast color for subname by @Antreesy in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5421
* fix(NcAppSidebar): fix animation glitch on toggle by @RayBB in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5389
* fix(NcAppSidebar): remove always hover styles from actions in non-compact mode by @ShGKme in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5367
* fix(NcActionInput): Add label to docs by @nickvergessen in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5432 …
=> release: v8.11.1

src/components/NcBreadcrumbs/NcBreadcrumbs.vue
- Fix https://github.com/nextcloud/server/issues/44005
- When some breadcrumbs are hidden and the user tries to navigate to a breadcrumb that comes before the hidden one the component attempts to render a no longer existing crumb so we filter out the indices are no longer present before rendering
=> fix(NcBreadcrumbs): Only render existing hidden breadcrumbs

src/components/NcRichText/NcRichText.vue, src/components/NcRichText/richtext.scss, tests/unit/components/NcRichText/NcRichText.spec.js
event `'interact:todo'` now returns a string (id of the affected checkbox) instead of an object.
- Fix https://github.com/nextcloud/spreed/issues/12009
* Checkbox includes different elements in its label
* Added explicit indentation for nested lists
* Interactivity: used the DOM to calculate the position of the element and then use it in the string
---|---
Interactivity: 
https://github.com/nextcloud-libraries/nextcloud-vue/assets/84044328/130eee3e-5532-4b1b-92b3-8efa1a702a72
=> fix(NcRichText): include all label items

src/components/NcAppSidebar/NcAppSidebar.vue
Someone else might want to handle that event
https://github.com/pulsejet/memories/issues/1115
=> fix(sidebar): propagate keydown unless mobile

src/components/NcActions/NcActions.vue
- Resolves https://github.com/nextcloud/server/issues/44463
1. Fix wrong event name - the event is named `apply-show` and not `after-show`
2. If the popover content is too large and will be capped (max-height) make sure the last element is shown only partially, so users can discover there is more to scroll.
See that before you can not see any hint of the overflow:
---|---
=> fix(NcActions): Show last action entry only partial to make it discoverable

src/components/NcDialog/NcDialog.vue
- Fix Dialog compatibility with NC30
---|---
=> fix(NcDialog): Set font size to make dialog compatible with Nextcloud 30

src/components/NcRichText/autolink.js, tests/unit/components/NcRichText/autoLink.spec.js
Currently `route.regex.source.slice(1, -1)` is used to resolve URL.
Without `^` and `$` URL matching is too wide. For example, routes like `/` matches any absolute URL and any pathname.
This PR uses `route.resolve` for get the route and also supports more edge cases:
- Having and not having `index.php` in the path
- Having and not having `index.php` in the router (some apps add it, some don't)
- Different base path
- Support for relative links (to be in line with `next`, cc @susnux)
```
http://cloud.ltd /nextcloud /index.php/app/files /favorites?fileid=2#fragment
|_____origin____|__________router-base__________|_________router-path________|
|__________base____________|
|___root___|
```
Before | After
---|---
=> fix(NcRichText): more strictly resolve vue router's path

src/components/NcAvatar/NcAvatar.vue
- Support `RouterLink` for `NcAvatar` contact's menu, same as for links in `NcRichText`
- Also, do not render user status as a link
For this place in Talk:
---|---
=> fix(NcAvatar): support in-app router links for contact menu

CHANGELOG.md, package-lock.json, package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.11.1...v8.11.2)
* fix(NcBreadcrumbs): Only render existing hidden breadcrumbs by @Pytal in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5441
* fix(NcAppNavigationItem): Fix uncollapsible entry by @Pytal in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5456
* fix(NcRichText): include all label items by @DorraJaouad in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5455
* fix(sidebar): propagate keydown unless mobile by @pulsejet in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5451
* fix(NcActions): Show last action entry only partial to make it discoverable by @susnux in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5448
* fix(NcDialog): Set font …
=> release: v8.11.2

src/functions/reference/widgets.ts
`!!expression` returns boolean and cannot return `undefined`/`null` anyway. And if it is `falsy`, then it is `false` already.
```
[plugin:vite:esbuild] [plugin vite:esbuild] src/functions/reference/widgets.ts: The "??" operator here will always return the left operand
42 |  
43 |  export const hasFullWidth = (id: string) => {
44 |    return !!window._vue_richtext_widgets[id]?.fullWidth ?? false
|                                                        ^
45 |  }
46 | 
```
=> chore(widgets): remove unneeded nullish coalescing

src/components/NcRichText/NcReferenceWidget.vue
`NcReferenceWidget` always tries to render the widget into `ref="customWidget"`, but `ref="customWidget"` exists only when there is a custom widget (`reference && hasCustomWidget`), for example, if the widget is not registered yet there is no div to render the widget.
It doesn't look like a bug for the end user, but spams with errors on the console.
=> fix(NcReferenceWidget): do not try to render widget when there is no widget

src/components/NcDialog/NcDialog.vue
- Fix https://github.com/nextcloud/forms/issues/2064
---|---
=> fix(NcDialog): Actions should not overflow the action container

src/components/NcColorPicker/NcColorPicker.vue
Also show the `Choose` button for the simple select view to allow triggering the `submit` event.
=> fix(NcColorPicker): Allow to submit selected color in simple-view

src/components/NcRichText/autolink.js, tests/unit/components/NcRichText/autoLink.spec.js
- Continue of https://github.com/nextcloud-libraries/nextcloud-vue/pull/5419
I just realized that relative links should be considered relative to the Nextcloud instance, not origins.
For example, for the page `http://cloud.ltd/nextcloud/index.php/apps/files/favorites`, the relative link should be `/apps/files/favorites`, not `/nextcloud/index.php/apps/files/favorites`.
- Adjusted relative links generation tests
- Added one specific test for this case
- Changed `getRoute`
Tests for all the cases looks a bit messy, but I don't know how to make it better.
=> fix(autolink): correctly handle relative links without webroot

src/components/NcDateTime/NcDateTime.vue, src/composables/index.js, src/composables/useFormatDateTime.ts, tests/unit/composables/useFormatDateTime.spec.js, vite.config.mts
The `.value` call was missing in case of disabled relative time. This causes the string to be quoted (because of stringification of the computed value). To prevent similar issues the file is now migrated to Typescript, also fixed some other issues discovered by type checking.
=> fix(NcDateTime): When relative time is disabled return a string and not the reference to it

src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue, tests/unit/components/NcCheckboxRadioSwitch/checkbox.spec.js
I would expect the attrs on the input element to allow any aria attributes.
So if not button type, pass the attrs to the input element to allow setting aria tags like `aria-invalid` and `aria-errormessage`
=> fix(NcCheckboxRadioSwitch): Pass attrs to `input` if available

src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
* Resolves: https://github.com/nextcloud/forms/issues/2089
On forms we use the button style for the views-toggle (view edit results), we noticed the background is not set to it will leak the background e.g. when scrolling.
---|---
=> fix(NcCheckboxRadioSwitch): Add background color for button style

src/composables/useFormatDateTime.ts, tests/unit/components/NcDateTime/NcDateTime.spec.js
- Fix https://github.com/nextcloud/server/issues/15457
---|---
=> fix(NcDateTime): Respect language

src/components/NcCheckboxRadioSwitch/NcCheckboxContent.vue, src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue, src/components/NcRichText/NcRichText.vue
At least for checkboxes in `RichText`, it makes sense to have inline display. 
---|---
=> fix(NcRichText): adjust display so long texts in checkboxes can be shown correctly

src/functions/emoji/emoji.ts
- Index emoji 'database' only when first time calling a function (like `emojiSearch()`)
- Apply method similar to what is used in EmojiPicker
Tested with:
```js
console.time('emoji')
for (let i = 0; i < N; i ++) {
const em1 = emojiSearch(text, 10)
}
console.timeEnd('emoji')
```
🏚️ Before (N = 10) | 🏚️ Before (N = 1000) | 🏡 After (N = 1000)
---|---|---
=> fix(emoji): index emoji data once for search functions

CHANGELOG.md, package-lock.json, package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.11.2...v8.11.3)
* fix(NcReferenceWidget): do not try to render widget when there is no widget by @ShGKme in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5485
* fix(NcDialog): Actions should not overflow the action container by @susnux in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5495
* fix(NcColorPicker): Allow to submit selected color in simple-view by @susnux in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5499
* fix(autolink): correctly handle relative links without webroot by @ShGKme in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5487
* fix(NcDateTime): When relative time is disabled return a string and not the reference to it by @susnux in …
=> release: v8.11.3

src/components/NcRichText/NcReferenceWidget.vue
Without `requestAnimationFrame` resize observer causes cypress to crash.
Also use a ref for the width and a computed for the resulting number of lines.
- Fixes cypress failures such as https://github.com/nextcloud/text/actions/runs/8976130504/job/24652414376?pr=5772
=> fix(NcReferenceWidget): use requestAnimationFrame in observers

package-lock.json, package.json
I checked all usages for breaking changes and we are good.
- Fix _none_
---|---
B | A
=> chore(deps): bump @nextcloud/calendar-js to ^7.0.0

src/components/NcAppNavigationCaption/NcAppNavigationCaption.vue, tests/unit/components/NcAppNavigation/NcAppNavigationCaption.spec.ts
Allow to adjust the heading level if needed.
=> feat(NcAppNavigationCaption): Allow to set heading level

src/components/NcAppNavigationCaption/NcAppNavigationCaption.vue
- Regression from https://github.com/nextcloud/server/pull/43640
---|---
=> fix(NcAppNavigationCaption): Fix margin

src/components/NcAppNavigationCaption/NcAppNavigationCaption.vue, tests/unit/components/NcAppNavigation/NcAppNavigation.spec.js, tests/unit/components/NcAppNavigation/NcAppNavigationCaption.spec.ts
Add a prop to set caption id to the caption, needed for linking list and caption.
=> feat(NcAppNavigationCaption): Add `heading-id` prop to allow setting the ID on the caption itself

src/components/NcAppNavigationCaption/NcAppNavigationCaption.vue, tests/unit/components/NcAppNavigation/NcAppNavigation.spec.js, tests/unit/components/NcAppNavigation/NcAppNavigationCaption.spec.ts
Manual backport of https://github.com/nextcloud-libraries/nextcloud-vue/pull/5565
=> [next] feat(NcAppNavigationCaption): Add `heading-id` prop

src/components/NcRichText/NcReferenceWidget.vue
It does exactly what we want.
- Superseeds #5582.
=> fix(NcReferenceWidget): useElementSize

cypress/tsconfig.json, package.json, src/components/NcButton/NcButton.vue, tests/tsconfig.json, tsconfig.json, vite.config.ts
Make sure Typescript definitions are correctly exported. Also export them from the package.
---|---
=> fix: Adjust Typescript definition export

src/components/NcActionButton/NcActionButton.vue, src/components/NcActionLink/NcActionLink.vue, src/components/NcActions/NcActions.vue, src/components/NcAppNavigationItem/NcAppNavigationItem.vue, src/components/NcAppSidebar/NcAppSidebar.vue, src/components/NcAvatar/NcAvatar.vue, src/components/NcButton/NcButton.vue, src/components/NcEmptyContent/NcEmptyContent.vue, src/components/NcListItemIcon/NcListItemIcon.vue
Fix missing file extensions on imports.
=> fix(docs): Add missing file extensions to vue-material-design-icons imports

src/components/NcSettingsSection/NcSettingsSection.vue
Remove custom heading, remove full width option and other minor fixes
=> Update NcSettingSection design

src/components/NcIconSvgWrapper/NcIconSvgWrapper.vue
Use CSS variable with `style` binding instead, as the `v-bind` generated an undefined CSS variable. (Yet for the next branch, Vue 3, it seems to work).
---|---
=> fix(NcIconSvgWrapper): Fix icon size variable being undefined

src/components/NcAppNavigation/NcAppNavigation.vue
Follow-up to https://github.com/nextcloud-libraries/nextcloud-vue/pull/2747
|---|---|
| ![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/42591237/dd28fcf7-30ec-4939-b1bd-a0c121948675) | ![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/42591237/08ec8628-401e-405f-ac2e-8e3642564d74) |
=> feat(mobile): restore hiding the appnavigation on mobile

src/components/NcSettingsSection/NcSettingsSection.vue
#5514 is breaking and should **not** have been merged for this major version, because it also breaks server on Nextcloud 28 and 29 when updating the library!
Instead deprecate the prop and force overwrite on Nextcloud 30+ so you can fix your app or server on Nextcloud 30+, but keep working on Nextcloud 29 and lower.
=> fix: Revert #5514 and only force width limit on Nextcloud 30+

CHANGELOG.md, package-lock.json, package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.11.2...v8.12.0)
* feat(NcAppNavigationCaption): Allow to set heading level [\#5567](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5567) \([susnux](https://github.com/susnux)\)
* feat(NcAppNavigationCaption): Add `heading-id` prop to allow setting the ID on the caption itself [\#5565](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5565) \([susnux](https://github.com/susnux)\)
* fix(NcReferenceWidget): use requestAnimationFrame in observers [\#5561](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5561) \([max-nextcloud](https://github.com/max-nextcloud)\)
* fix(NcAppNavigationCaption): Fix margin [\#5576](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5576) …
=> release: v8.12.0

package.json, vite.config.ts
* Resolves #4899
There is very little need for the CJS built anymore as any modern bundler can handle ESM (webpack, vite).
This not only reduces the package size and prevents tree-shaking issues if the CJS entry is used, but also reduces potential pitfalls with maintaining two module formats.
=> [next] refactor!: Drop CJS entry points, only provide ESM

src/components/NcAppSidebar/NcAppSidebar.vue
- Regression from https://github.com/nextcloud-libraries/nextcloud-vue/pull/5603
- App navigation toggle was visible "intentionally" and also was a part of keyboard navigation. Now it is hidden, but still a part of keyboard navigation in the focus trap on mobile.
---|---
B | A
=> fix(NcAppSidebar): remove hidden navigation toggle from focus trap

CHANGELOG.md
- Move `feat` to new features `Enhancements`
- Rename `feat` of `appnavigation` to `fix` with conventional commits style
=> chore(CHANGELOG): correct 8.12.0

src/assets/NcAppNavigationItem.scss, src/components/NcButton/NcButton.vue, src/components/NcListItem/NcListItem.vue
Use border radius large for NcAppNavigationItem, NcListItem and NcButton
=> Reduce border radius of components

src/assets/NcAppNavigationItem.scss, src/components/NcButton/NcButton.vue, src/components/NcListItem/NcListItem.vue
Ref: https://github.com/nextcloud/server/pull/45295
=> Update temporary border radius variable

package-lock.json, package.json
We are using AGPL-3.0 or later, so adjust the package.json to reflect this
=> fix: Adjust license in `package.json`

tests/.eslintrc.js, tests/unit/components/NcHighlight/NcHighlight.spec.js, tests/unit/components/NcRichText/NcRichText.spec.js, tests/unit/utils/FindRanges.spec.js
- Some files in the *tests* directory had no correct formatting, this is fixed now.
=> refactor: Fix linter issues on test case files

src/components/NcInputField/NcInputField.vue, src/components/NcSelect/NcSelect.vue, src/components/NcTextArea/NcTextArea.vue
https://github.com/nextcloud-libraries/nextcloud-vue/assets/26852655/a2c1e554-3488-4d99-8b82-a3c377f768ab
=> Use variables for input border width

src/components/NcEllipsisedOption/NcEllipsisedOption.vue
- For: https://github.com/nextcloud-libraries/nextcloud-vue/issues/5662
- cc @DaphneMuller
---|---
=> chore(NcEllipsisedOption): add docs

package-lock.json, package.json, src/components/NcRichText/NcRichText.vue
- Talk is broken when there is a link to another chat in the chat
- Fix warnings and errors
To test:
1. Checkout https://github.com/nextcloud/spreed/tree/vue3
2. Before linking `nextcloud-vue` - remove `rm -rf node_modules/vue-router` from nextcloud-vue repo (or use `npm pack` instead of `npm link`)
3. Send a link to another chat in a chat
---|---
Fixes:
Fixes:
=> [next] fix(NcRichText): crash on router links rendering

src/components/index.ts
- Manual backport of https://github.com/nextcloud-libraries/nextcloud-vue/pull/5666/
=> [next] fix: re-export `NcEllipsisedOption` and `NcInputField` in root export 

src/components/NcDialogButton/NcDialogButton.vue
While it is already possible to pass the disabled prop (`v-bind` of props in NcDialog), we should make this prop official to document it.
=> feat(NcDialogButton): Allow to pass `disabled` prop

src/components/NcRichContenteditable/NcRichContenteditable.vue
- Required for #https://github.com/nextcloud/spreed/issues/12250
- The added methods will be used to programmatically show slash commands by clicking on a button.
=> feat(NcRichContenteditable): programmatically show tributes

src/components/NcAppSidebar/NcAppSidebar.vue
- In Talk when we are in the call, we need the top bar to be **dark-themed**.
In the past, we had a custom toggle button in the top bar with `data-dark-theme` on the top bar to archive that. Now with the built-in toggle button, it is not possible...
- Add `toggleAttrs` similar to `toggleClasses` prop to pass attributes on the toggle button
- Allows to set `data-them-dark` manually from Talk
- Alternative: 
1. Add `hideToggle` prop to hide the default toggle button
2. Add `NcAppToggleButton` to allow users to place it anywhere
3. Connect this `NcAppToggleButton` with `NcAppSidebar` inside `@nextcloud/vue`
4. Do not forget about slide animations for the custom toggle button
---|---
=> feat(NcAppSidebar): add `toggleAttrs` prop to pass attributes on the toggle button

src/components/NcRichText/autolink.js, tests/unit/components/NcRichText/autoLink.spec.js
- Fix https://github.com/nextcloud/spreed/issues/12516
- `autolink` supports relative URLs, for example, `/call/ab34cd` is resolved as a Talk route.
- It considers a link as relative if it doesn't start with `https?://`.
- However, `call/abc` or `mailto:email@nextcloud.ltd` also doesn't start with HTTP.
- The best is to only allow relative URLs with leading slashes `/`.
- Even the check for leading `/` is enough for explicitly adding a check for non-http schemes. 
VueRouter handles such URLs according to the URL RFC, for example, being on `/call/abc` page, a link `def` is resolved as `/call/def` relative to `/call/`. We don't want to support such links anyway, so relative URL MUST start with a slash.
**Alternative solution:** add a leading slash `/` to relative links.
=> fix(richText): do not handle relative links without leading slash as router links

src/components/NcAppSidebar/NcAppSidebar.vue
- Allows to use `open` state (which is the only way to hide sidebar with `v-show`) without the built-in toggle button
---|---
=> feat(NcAppSidebar): add noToggle prop to hide the built-in toggle button

docs/directives.md, docs/directives/focus.md, docs/directives/linkify.md, docs/directives/tooltip.md, styleguide.config.js, styleguide/global.requires.js
- For: https://github.com/nextcloud-libraries/nextcloud-vue/issues/5662
---|---
=> chore(directives): add docs

src/components/NcAppSidebar/NcAppSidebar.vue
- There is a transition for the sidebar toggle button
- It makes sense when the sidebar is opening/closing
- It looks like a glitch initially when it appears
Slowed down to be more visible on gifs
---|---
=> fix(NcAppSidebar): apply toggle offset transition only on sidebar transition

src/components/NcUserStatusIcon/NcUserStatusIcon.vue
- Removes a warning error from server
- This could also be fixed on server side by using `v-if` on component node.
But actually, this component already has `v-if="activeStatus"` on root and works completely normal without status being set.
=> chore(NcUserStatusIcon): remove warn if status is not set

l10n/ja.pot
=> fix: japanese system tags translation

CHANGELOG.md, package-lock.json, package.json
---
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.12.0...v8.13.0)
* feat(NcDialogButton): Allow to pass `disabled` prop [\#5679](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5679) \([susnux](https://github.com/susnux)\)
* feat(NcRichContenteditable): programmatically show tributes [\#5674](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5674) \([DorraJaouad](https://github.com/DorraJaouad)\)
* feat: Add NcChip component [\#5686](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5686) \([susnux](https://github.com/susnux)\)
* feat(NcAppSidebar): add `toggleAttrs` prop to pass attributes on the toggle button [\#5695](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5695) \([ShGKme](https://github.com/ShGKme)\)
* …
=> chore: Prepare v8.13.0

src/components/NcAppSidebar/NcAppSidebar.vue, src/components/NcAppSidebar/NcAppSidebarTabs.vue
- Allows to show a tab navigation if there is only one tab available
- Should be non-interactive, act as a visual header
---|---
=> feat(NcAppSidebar): force show navigation for a single tab

src/components/NcRichContenteditable/NcRichContenteditable.vue
=> fix(NcRichContentEditable): remove overlapping placeholder with tribute trigger

src/components/NcUserStatusIcon/NcUserStatusIcon.vue
- Manual backport of https://github.com/nextcloud-libraries/nextcloud-vue/pull/5715
=> [next] chore(NcUserStatusIcon): remove warn if status is not set

src/components/NcRichContenteditable/NcMentionBubble.vue
- Fix visible userid from mention bubble on widescreens (21:9, zoomed out)
🏚️ Before
🏡 After
=> fix(NcMentionBubble): hide selectable mention id from widescreens

src/components/NcRichText/NcReferenceWidget.vue
* Regression from https://github.com/nextcloud-libraries/nextcloud-vue/pull/5561
Intersection observer has observed elements as output
=> fix(NcReferenceWidget): pass elements to intersection observer

src/components/NcHeaderMenu/NcHeaderMenu.vue
- Fix https://github.com/nextcloud/notifications/issues/1962
---|---
=> style(NcHeaderMenu): pass text-on-background color for header menu

src/components/NcButton/NcButton.vue, src/components/NcHeaderMenu/NcHeaderMenu.vue
With our new 3 different clickable area sizes we have some places, like the header menu, where we still want to use "large" buttons. So this gives the ability to set the button size to either `normal` which is the default, `large` for main actions or `small`.
[Bildschirmaufnahme_20240703_133223.webm](https://github.com/nextcloud-libraries/nextcloud-vue/assets/1855448/993f701f-c65c-42e8-b918-87f93c064abb)
=> feat(NcButton): Add `size` prop to allow setting the button size to `small`, `normal`, `large`

.reuse/dep5, cypress/commands.d.ts, cypress/component/NcCheckboxRadioSwitch.cy.ts, cypress/support/commands.ts, cypress/support/component.ts, src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue, tests/unit/components/NcCheckboxRadioSwitch/checkbox.spec.js
Fix regression from https://github.com/nextcloud-libraries/nextcloud-vue/pull/5507
Needed for:
- https://github.com/nextcloud/server/pull/46239
- https://github.com/nextcloud/server/pull/46237
- https://github.com/nextcloud/server/pull/46283
- https://github.com/nextcloud/server/pull/46292
=> fix(NcCheckboxRadioSwitch): only bind aria attributes to the input

CHANGELOG.md, package-lock.json, package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.13.0...v8.14.0)
* feat(NcAppSidebar): force show navigation for a single tab [\#5740](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5740) \([Antreesy](https://github.com/Antreesy)\)
* feat(NcButton): Add `size` prop to allow setting the button size to `small`, `normal`, `large` [\#5767](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5767) \([susnux](https://github.com/susnux)\)
* feat: migrate `NcCollectionList` component from `nextcloud-vue-collections` [\#5757](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5757) \([Antreesy](https://github.com/Antreesy)\)
* fix(NcDialog): Ensure the dialog is correctly labelled by its name …
=> chore: Prepare release of 8.14.0

src/components/NcAppNavigationCaption/NcAppNavigationCaption.vue, tests/unit/components/NcAppNavigation/NcAppNavigationCaption.spec.ts
Only forward the real props and not all attributes, for Vue3 this fixes the forwarding of `class` and `style`.
=> [next] fix(NcAppNavigationCaption): Only pass needed props to NcActions

src/components/NcAppNavigationCaption/NcAppNavigationCaption.vue
Make NcAppNavigationCaption properly align with NcAppNavigationItem
- Fix https://github.com/nextcloud/calendar/pull/6129#issuecomment-2225327507
---|---
=> fix(NcAppNavigationCaption ): properly align with NcAppNavigationItem

src/components/NcActions/NcActions.vue, styleguide.config.js, styleguide/assets/styleguide.css
- Fix https://github.com/nextcloud-libraries/nextcloud-vue/issues/3920
Calculate the space on the window based on the trigger location.
---|---
=> fix(NcActions): Use full window height

src/mixins/actionGlobal.js, src/mixins/clickOutsideOptions/index.js
- Fix https://github.com/nextcloud-libraries/nextcloud-vue/issues/5808
When there is nothing else in a mixin, styleguidist uses SPDX header as mixin's JSDoc and adds it to the component docs.
```js
/**
* SPDX-FileCopyrightText: 2020 Nextcloud GmbH and Nextcloud contributors
* SPDX-License-Identifier: AGPL-3.0-or-later
*/
// Mixin
```
Affected components:
- `NcHeaderMenu`
- `NcAppNavigationSettings`
- `NcActionCheckbox`
- `NcActionInput`
- `NcActionLink`
- `NcActionRouter`
- `NcActionRadio`
- `NcActionText`
- `NcActionTextEditable`
This can be disabled via [validExtends](https://vue-styleguidist.github.io/Configuration.html#validextends) config, but that would also remove `props` docs defined in mixins.
A solution - add a fake empty JSDoc in a mixin.
Get rid of mixins
🏚️ …
=> chore(docs): remove SPDX header from component docs

src/components/NcAppNavigationCaption/NcAppNavigationCaption.vue
We need to use the real `NcAppNavigation` component as this is injecting other styles. Otherwise the styleguide will look very different to the real result.
See especially the padding
---|---
=> docs: Fix `NcAppNavigationCaption` examples

src/components/NcInputField/NcInputField.vue, src/components/NcTextField/NcTextField.vue
The helper text should be aligned with the input, at least the inline padding should match the input (without icons).
Also the helper text without any state (error / success) should be maxcontrast color.
---|---
=> fix(NcInputField): Make helper text aligned and maxcontrast color

src/components/NcInputField/NcInputField.vue
Rework layout logic to ensure the label is not jumping on focus. This was caused as our border width changes when focusing.
[vokoscreenNG-2024-07-18_02-44-45.webm](https://github.com/user-attachments/assets/a3666632-6ae2-4969-8e81-bc07ac3a251e)
[vokoscreenNG-2024-07-18_02-42-29.webm](https://github.com/user-attachments/assets/d6698d4d-3ba2-43b2-ac3f-19b11424d790)
=> fix(NcInputField): Make sure label and placeholder is not jumping

src/components/NcListItem/NcListItem.vue
* The anchor height is in reality not default-clickable-area but 2 lines of text
* Fix visual regressions on Nextcloud 30 by making the padding dependent of the border radius
* The margin for the focus-visual needs only to account for the box shadow on the first and last element, all other can just have a margin for the border.
@marcoambrosini this is a bug fix for invalid height which causes some errors, but maybe it also fixes visual regression good enough for Nextcloud 30, what do you think?
See screencase for Nextcloud 30 and 29 behavior below
[Bildschirmaufnahme_20240704_175824.webm](https://github.com/nextcloud-libraries/nextcloud-vue/assets/1855448/cac20181-c08e-4014-af98-2fb181dbff34)
=> fix(NcListItem): Anchor height was set not to content but random area

src/components/NcListItem/NcListItem.vue
- Fix empty container, if counter has been passed as falsy value, but not 0 (null)
---|---
=> fix(NcListItem): do not render counter on falsy values

src/components/NcAppSettingsSection/NcAppSettingsSection.vue
- Fix https://github.com/nextcloud/mail/pull/9879
---|---
Not sure why their size was limited in the first place
=> NcAppSettingsSection: make titles normal h3 size

src/components/NcAppSidebar/NcAppSidebar.vue
- Fix https://github.com/nextcloud/spreed/issues/12747
When NcAppSidebar appears, two things happen:
1. Transition animation with margin
2. Focus is moved to the sidebar
Moving focus scrolls container (`NcContent`) to the sidebar which is out of the container (in the process of moving from the right side). It results in weird animation when the margin changes the width + scroll of the container instead of the position of the sidebar.
P.S. `overflow: hidden` only hides the scrollbar and content, but the container is still scrollable.
`overflow: clip` is used to actually remove scrolling.
Slowed animation 1000 times to see the effect: sidebar moves left and right by 1 pixel.
---|---
- Both return focus and focus trap
Use `overflow: clip` on `NcContent` to remove …
=> fix(NcAppSidebar): manage focus only after transition has finished

src/components/NcActions/NcActions.vue
- Fix regression from https://github.com/nextcloud-libraries/nextcloud-vue/pull/5806#discussion_r1685505657
- default boundaries is NcAppContent `<main />`, so NcAppNavigation and NcAppSidebar stays out of it
- Didn't notice any drawbacks yet, so @susnux please check if that suffice previous PR results 
---|---
=> fix(NcActions): assign NcContent as NcActions > NcPopover default boundaries

src/components/NcColorPicker/NcColorPicker.vue
- For https://github.com/nextcloud/calendar/issues/6145
The size of the circles is hard coded but the grid size depends on the clickable area. So I made the size dependent as well. I've tested this with a clickable area of 34. It works with the old 44 as well:
---|---
=> fix(NcColorPicker): Make the color circle size depend on clickable area

src/components/NcAppContent/NcAppContent.vue
The CSS selectors used for the splitter were no functional, so we were using the default ones from splitpane here.
Use our variables for colors to unbreak styling in dark mode.
🏚️ Light mode before | 🏡 Light mode after
---|---
🏚️ Dark mode before | 🏡 Dark mode after
---|---
=> fix(NcAppContent): splitpane splitter styles with dark theme

src/components/NcAppNavigationSearch/NcAppNavigationSearch.vue
Merged too fast :see_no_evil: 
Now that the ref is pointing to a plain HTML element, there is no `$el`...
=> fix(NcAppNavigationSearch): Fix focus button when clearing search

CHANGELOG.md, package-lock.json, package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.14.0...v8.14.1)
* fix(NcAppNavigationItem): Fix popper boundary element [\#5632](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5632) \([ChristophWurst](https://github.com/ChristophWurst)\)
* Use correct date in header [\#5793](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5793) \([AndyScherzinger](https://github.com/AndyScherzinger)\)
* fix(NcAppNavigationSettings): border radius of toggle button [\#5765](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5765) \([st3iny](https://github.com/st3iny)\)
* fix(NcAppNavigationCaption): properly align with NcAppNavigationItem [\#5804](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5804) …
=> chore: prepare release 8.15.0

src/components/NcListItem/NcListItem.vue
=> fix: alignement of listitem name for one line layout

src/components/NcListItem/NcListItem.vue
- Helps https://github.com/nextcloud/calendar/pull/6169#issuecomment-2236754615
---|---
@miaulalala
=> NcListItem: remove max width

src/components/NcAppNavigation/NcAppNavigation.vue
- Follow-up to #5831 and #5783
---|---
=> fix(NcAppNavigation): update docs example with NcAppNavigationSearch component

src/components/NcActionCheckbox/NcActionCheckbox.vue
- Fix https://github.com/nextcloud/mail/issues/9892
---|---
=> NcActionCheckbox: align with NcActionText

src/components/NcInputField/NcInputField.vue, src/components/NcSelect/NcSelect.vue
- Fix https://github.com/nextcloud/calendar/issues/6155
---|---
=> NcSelect: make same height and color as NcTextField

src/components/NcChip/NcChip.vue
If there is no icon then there should be no empty space.
---|---
=> fix(NcChip): Ensure chips without icon do not reserve empty space for icon

src/components/NcListItem/NcListItem.vue
Add a `legacy` class so that we can keep stylings for Nextcloud 29 and older but still can style the component properly on Nextcloud 30 (smaller border radius = we can use smaller paddings)
---|---
=> fix(NcListItem): Make paddings smaller again on Nextcloud 30

CHANGELOG.md, package-lock.json, package.json
* fix(NcListItem): Make paddings smaller again on Nextcloud 30 [\#5879](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5879) \([susnux](https://github.com/susnux)\) 
* fix(NcChip): Ensure chips without icon do not reserve empty space for icon [\#5859](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5859) \([susnux](https://github.com/susnux)\)
* fix: alignment of listitem name for one line layout [\#5853](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5853) \([GretaD](https://github.com/GretaD)\)
* NcActionCheckbox: align with NcActionText [\#5839](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5839) \([GVodyanov](https://github.com/GVodyanov)\)
* NcSelect: make same height and color as NcTextField …
=> chore: Prepare v8.15.1

src/components/NcListItemIcon/NcListItemIcon.vue, src/components/NcSelect/NcSelect.vue
Currently the element was 36px instead of 34px which looks weird if using multiple input elements side by side (caused by search input being 34px + 2px border).
Also there was jumping because there are two different border width, so we need to adjust the input height based on the outer border width and the margin of the selected options.
=> fix(NcSelect): Ensure component height is same as input element

src/components/NcInputField/NcInputField.vue, src/components/NcListItem/NcListItem.vue
- Based on https://github.com/nextcloud-libraries/nextcloud-vue/pull/5887
- unitless line-height cannot be used as a unit value in calculations
- Replaced with `lh`
---|---
=> fix(style): adjust elements styles to unit-less line-height

src/components/NcSettingsSection/NcSettingsSection.vue
- `NcSettingsSection` header has unneeded top margin from global styles
- `NcSettingsSection` should only has its own padding around the content
---|---
=> fix(NcSettingsSection): remove default h2 margin-top

src/components/NcNoteCard/NcNoteCard.vue
We should allow a simple text prop instead of requiring passing through a slot.
=> feat(NcNoteCard): Add `text` prop to pass the content of the note card

src/components/NcPasswordField/NcPasswordField.vue
- Sometimes we need to show secret but editable value, for example, a secret token
- To hide we should use password field
- But it is not a password. Neither creating a new password, nor authentication. It should not be saved, generated or autocompleted.
- The problem - browsers have save/generate prompts for password fields. This behavior cannot be disabled with `autocomplete="off"`, browsers ignore it.
Proposal: add a new `as-text` prop that forces using `type="text"` and emulates password field view.
Note: `-webkit-text-security` is not a standard feature, but well supported.
=> feat(NcPasswordField): add as-text prop to remove autocomplete

src/components/NcListItem/NcListItem.vue
- Ref https://github.com/nextcloud/spreed/issues/12800
- Allows more specific customization of NcActions component's icon 
- Allows additional elements inside NcListItem
=> feat(NcListItem): provide additional slots for NcActions / extra actions customization

src/components/NcCounterBubble/NcCounterBubble.vue
- Fixes: with small numbers like `1` NcCounterBubble is narrower than a circle
- Makes `min-width` equal to `height`
Note: it is a but not centered vertically, because actually digits in fonts are smaller than line height. It will be fixed in a separate PR.
---|---
=> fix(NcCounterButton): adjust min-width to make it a right circle

src/components/NcUserBubble/NcUserBubble.vue
- Show interactive cursor `pointer` if an element has click event
---|---
=> feat(NcUserBubble): add RouterLink support

src/components/NcAvatar/NcAvatar.vue
- Fix focus-visible state appearance
- `parent > children` syntax to avoid leaking to NcActionsButtons
---|---
=> style(NcAvatar): make button element round as avatar itself

src/components/NcUserBubble/NcUserBubble.vue
- Fix bug introduced in #5708
- splitted with if/else block to redefine 'div' tag and condition later
=> fix(NcUserBubble): fix tag assignment if no url but to provided

src/components/NcDashboardWidgetItem/NcDashboardWidgetItem.vue
=> fix: Fix alignment of dashboard list items

src/components/NcNoteCard/NcNoteCard.vue
- Fix https://github.com/nextcloud-libraries/nextcloud-vue/issues/5886
Adjust the padding and margin to be a bit more condensed. Also fixed the documentation as the text was incomplete.
=> fix(NcNoteCard): Adjust padding and margin

CHANGELOG.md, package-lock.json, package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.15.1...v8.16.0)
* feat(NcNoteCard): Add `text` prop to pass the content of the note card [\#5894](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5894) \([susnux](https://github.com/susnux)\)
* feat(NcPasswordField): Add `as-text` prop to remove autocomplete [\#5896](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5896) \([ShGKme](https://github.com/ShGKme)\)
* feat(NcListItem): Provide additional slots for NcActions / extra actions customization [\#5870](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5870) \([Antreesy](https://github.com/Antreesy)\)
* feat(NcUserBubble): Add RouterLink support [\#5708](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5708) …
=> chore: release v8.16.0

styleguide.config.js
=> chore(docs): specify more Nextcloud versions in styleguidist

src/components/NcButton/NcButton.vue
Required to allow opening links in `_blank` target via `NcButton`.
=> feat(NcButton): Allow to specify `target` attribute for buttons with href

src/components/NcActions/NcActions.vue
See https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/menu_role
The `menu` needs a label set, so lets add it similar to dialog role. In general we could consider always add it to the `ul` as this is pretty valid and has good browser support.
=> fix(NcActions): Role `menu` needs a label assigned so label by trigger

src/components/NcListItem/NcListItem.vue
- Fix https://github.com/nextcloud/forms/issues/2240
---|---
=> fix(NcListItem): Adjust icon color when the list item is active

src/components/NcDialog/NcDialog.vue, src/components/NcDialogButton/NcDialogButton.vue, src/components/NcInputField/NcInputField.vue
This allows us to make simple small dialogs like asking for a password, asking for a filename or similar while having proper HTML semantics and native form validation.
[Bildschirmaufnahme_20240806_195309.webm](https://github.com/user-attachments/assets/e3655a45-b135-4746-a603-5dad4b177eb1)
=> feat(NcDialog): Allow to make the dialog a form

src/components/NcCounterBubble/NcCounterBubble.vue
- With 1 digit in `NcUserBubble` the digit is not exactly in the middle
- The problem is that `1em` line height is bigger than actual digit height
- Usually it is not a problem, but with a circle it looks better than it's perfectly in the middle
- Using `cap` fixes the problem
- `cap` is not well supported, so using `1em` as a fallback
---|---
Top padding is bigger than the bottom | Padding is almost equal
=> fix(NcUserBubble): make it perfectly aligned circle

src/components/NcAvatar/NcAvatar.vue
- Fix overlapping of status icons on small-sized avatars
🏠 Before | 🏡 After
--- | ---
=> fix(NcAvatar): extend variable size of status icons

src/components/NcActionCheckbox/NcActionCheckbox.vue, src/components/NcActionRadio/NcActionRadio.vue
=> fix(NcActions): NcActionCheckbox and NcActionRadio icon alignment

src/components/NcCheckboxRadioSwitch/NcCheckboxContent.vue, src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
* Closes https://github.com/nextcloud-libraries/nextcloud-vue/pull/5923
- adjust `NcCheckboxRadioSwitch` to new border radius
---|---
=> fix(NcCheckboxRadioSwitch): adjust to new border radius

src/assets/variables.scss, src/components/NcContent/NcContent.vue, src/components/NcHeaderMenu/NcHeaderMenu.vue, src/components/NcModal/NcModal.vue
- Use `--header-height` instead of `50px` constant to allow changing the height (used in Talk Desktop)
- NcModal
- NcHeaderMenu
- NcContent
No visual changes without custom theming
=> fix: use `--header-height` instead of `50px` constant

src/components/NcAppSettingsDialog/NcAppSettingsDialog.vue
Ensure correct border radius and padding is used.
---|---
=> fix(NcAppSettingsDialog): Adjust navigation entries to match Nextcloud 30 design

src/components/NcAppNavigationCaption/NcAppNavigationCaption.vue
- Fix https://github.com/nextcloud/mail/issues/7171#issuecomment-2296411043
I removed `padding-right` in order for the text to not ellipsize too early
---|---
=> fix(NcAppNavigationCaption): make name ellipsize

src/components/NcListItem/NcListItem.vue
- Related to https://github.com/nextcloud/spreed/issues/12921
The other general solution is to use `actionsProps` prop. It can be a better solution if we often want to customize `NcActions` in `NcListItem` in depth
There is one action
---|---
=> fix(NcListItem): allow to control the display of a three dot menu

src/components/NcModal/NcModal.vue
- Fix https://github.com/nextcloud-libraries/nextcloud-vue/pull/5978#discussion_r1722061777
=> refactor(NcModal): get rid of unneeded calc()

src/components/NcCounterBubble/NcCounterBubble.vue, tests/unit/components/NcCounterBubble/NcCounterBubble.spec.js
- Fix https://github.com/nextcloud-libraries/nextcloud-vue/issues/5486
Currently, the maximal number is limited via ... ellipsis. It doesn't make sense for numbers. And it is broken on Nextcloud 30 styles.
In general, having a slot doesn't make much sense for me. As the component is supposed to show a count, it is better to work with it as a number, not any content.
Instead, add an explicit `count` humanize output using:
- Added `count` prop for the value
- Humanize output with localization by default
- Even humanized output from the default slot content, if a plain number is passed
- Mark default slot as deprecated in flavor of `count` or `NcChip`
- Added `raw` prop to disable this behavior
- Improved docs
- Added tests
English | Chinese
---|---
=> feat(NcCounterBubble): add count and limit props instead of slot

src/mixins/richEditor/index.js
Fixes RichText causes errors on WebKit | Invalid regex #5589
This regex performs the same function as the one used before, but does not make use of negative lookbehinds and therefore should work on older MobileSafari versions.
To test, I looked first at the original mentioned regex from nextcloud server to get an idea of what the intended valid and invalid captures were. I tested both the original and modified regexes for both the server one and the one used in this component to verify that the matching groups were the same. The overall match 1 (blue highlight) is slightly different however the capture group 1 (green highlight) has the same content across both so this should be compatible.
- Fix #5589 
- Fix https://github.com/nextcloud/forms/issues/2163
---|---
=> fix(NcRichText): modify MENTION_START regex to work on older MobileSafari versions

src/components/NcCounterBubble/NcCounterBubble.vue
- ⚠️ On top of https://github.com/nextcloud-libraries/nextcloud-vue/pull/5863/files
- See only the last commit
- Padding around looks to small
- Increase padding to `1.5 * grid` (**applies only to large numbers**)
- Height is a bit small
- Increases to 22px (~ 1cap + padding)
- Centering with `1cap` was not very well supported from https://github.com/nextcloud-libraries/nextcloud-vue/pull/5948 
- Use `line-height` to expand height and center text instead of `1cap`
---|---
=> fix(NcCounterBubble): increase size

src/components/NcRichContenteditable/NcAutoCompleteResult.vue, src/components/NcRichContenteditable/NcRichContenteditable.vue
- Fix https://github.com/nextcloud-libraries/nextcloud-vue/issues/5975
- Paddings adjustments also applies for 28+29 intentionally (previously there were double paddings)
- Also applies for 28 + 29, but not a visible change
Note, it has some copy-paste from `NcAvatar` and `NcListItem`. We can look at reuse in a follow-up
🏚️ Before 30 | 🏡 After 30
---|---
🏚️ Before 28 | 🏡 After 28
---|---
=> fix(NcRichContenteditable): adjust to new design

docs/composables.md, docs/composables/useHotKey.md, src/composables/index.js, src/composables/useHotKey/index.js, styleguide.config.js
Moved from [nextcloud/spreed#12698](https://github.com/nextcloud/spreed/pull/12698/commits/91ab5f7204bc670aab2cc6169ce1bc2295bdbdbc)
Add a new `useHotKey` composable with respect Nextcloud Accessibility setting
Available modifiers:
- ctrl: Ctrl key is required
- alt: Alt key is required
- shift: Shift key is required
- prevent: Prevent default action
- stop: Stop propagation
- push: Trigger on keydown and keyup
=> feat(useHotKey): add composable for keyboard shortcuts

src/components/NcCounterBubble/NcCounterBubble.vue, tests/unit/components/NcCounterBubble/NcCounterBubble.spec.js
=> [next] feat(NcCounterBubble)!: remove default slot and make `count` prop required

CHANGELOG.md, package-lock.json, package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.16.0...v8.17.0)
* feat(NcButton): Allow to specify `target` attribute for buttons with href [\#5938](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5938) \([mejo-](https://github.com/mejo-)\)
* feat(NcDialog): Allow to make the dialog a form [\#5932](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5932) \([susnux](https://github.com/susnux)\)
* fix(NcListItem): allow to control the display of a three dot menu [\#5980](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5980) \([DorraJaouad](https://github.com/DorraJaouad)\)
* feat(NcCounterBubble): add count and limit props instead of slot [\#5863](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5863) …
=> chore: Prepare v8.17.0

src/components/NcAppNavigationItem/NcAppNavigationItem.vue, src/components/NcListItem/NcListItem.vue
- Regressions from https://github.com/nextcloud-libraries/nextcloud-vue/pull/5997
=> [next] fix(NcListItem): correctly use NcCounterBubble after slot removal

src/components/NcRichText/NcReferenceList.vue
- Fix reference widgets recalculating in case of rich text change
---|---
=> fix(NcRichText): discard reference widgets on text update

src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
… a link
In rich text > tasks list, check boxes can have links
---|---
=> fix(NcCheckBoxRadioSwitch): do not toggle on a click on a link inside

src/components/NcActions/NcActions.vue
Manual backport of https://github.com/nextcloud-libraries/nextcloud-vue/pull/5933
=> [next] fix(NcActions): Role `menu` needs a label assigned so label by trigger

src/components/NcHeaderMenu/NcHeaderMenu.vue
* From @jancborchardt comment (3rd one): https://github.com/nextcloud/server/pull/47568#pullrequestreview-2268099943
There should be no padding within the popover menu. The popover container is not style-able (at least not without hacking the (not exposed-)CSS classes), so users can not remove the padding themself.
The padding is a problem if the content is scroll-able, because the scrollbar should be on the very end of the container and not floating around.
[Bildschirmaufnahme_20240830_002829.webm](https://github.com/user-attachments/assets/65f03a35-5c8e-46df-b818-f84c86888d4b)
[Bildschirmaufnahme_20240830_002718.webm](https://github.com/user-attachments/assets/356a6b8f-8391-4244-a87d-a0b8017eb6f5)
=> fix(NcHeaderMenu): Remove padding from popover menu

docs/composables/useHotKey.md, src/composables/useHotKey/index.js
- Fix https://github.com/nextcloud/spreed/issues/13155
- Regression from #5899
=> fix(useHotKey): respect press of MacOS Cmd key as Ctrl key

CHANGELOG.md, package-lock.json, package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.17.0...v8.17.1)
* fix(NcAppNavigation): keep border only on mobile [\#6008](https://github.com/nextcloud-libraries/nextcloud-vue/pull/6008) \([ShGKme](https://github.com/ShGKme)\)
* fix(NcRichText): discard reference widgets on text update [\#6011](https://github.com/nextcloud-libraries/nextcloud-vue/pull/6011) \([Antreesy](https://github.com/Antreesy)\)
* fix(NcCheckBoxRadioSwitch): do not toggle on a click on a link inside [\#6013](https://github.com/nextcloud-libraries/nextcloud-vue/pull/6013) \([DorraJaouad](https://github.com/DorraJaouad)\)
* fix: Adjust time intervals for relative time [\#6017](https://github.com/nextcloud-libraries/nextcloud-vue/pull/6017) \([susnux](https://github.com/susnux)\)
* …
=> chore: Prepare v8.17.1

l10n/messages.pot, src/components/NcAppNavigationItem/NcAppNavigationItem.vue, src/components/NcDialog/NcDialog.vue, src/components/NcDialogButton/NcDialogButton.vue, styleguide.config.js
If the callback returns `false` then the click event will not be forwarded. This could be useful if the click triggers a validation that fails and the user should be able to fix the issue.
=> feat(NcDialogButton): Allow to return `false` from callback to keep dialog open

src/components/NcActions/NcActions.vue
1. Opening actions, then e.g. right-click for context menu.
2. Now press escape -> context menu closes
3. Press escape again -> nothing happens
4. (with this commit): Pressing it a second time will close the actions as expected
=> fix(NcActions): Pressing escape should always close the actions

src/components/NcListItem/NcListItem.vue
- Fix https://github.com/nextcloud/mail/issues/10086
---|---
=> NcListItem: make the max width of the NcListItem in oneline mode apply only to the content name

src/components/NcHeaderMenu/NcHeaderMenu.vue
* First step for https://github.com/nextcloud/server/issues/46997
Make sure the header button is correctly resized on small screen.
Before only the outer container was resized but the inner button was larger than the container -> scroll bars were shown.
=> fix(NcHeaderMenu): Ensure trigger button is has same width as wrapper

src/components/NcCheckboxRadioSwitch/NcCheckboxContent.vue
- Fix issues caused by wrong stylesheet import order for NcCheckboxRadioSwitch
---|---
Signed-off-by: Antreesy <antreesy.web@gmail.com>
=> fix(NcCheckboxRadioSwitch): switch may always have checked-like background

src/components/NcEmojiPicker/NcEmojiPicker.vue
- Fix hover effects on emoji buttons
- Added fallback for Nextcloud <= v29
---|---
=> fix(NcEmojiPicker): adjust hover effects to new design

CHANGELOG.md, package-lock.json, package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.17.1...v8.18.0)
* feat(NcDialogButton): Allow to return `false` from callback to keep dialog open [\#6005](https://github.com/nextcloud-libraries/nextcloud-vue/pull/6005) \([susnux](https://github.com/susnux)\)
* feat(NcHeaderButton): Add a button-only alternative for the header menu [\#6048](https://github.com/nextcloud-libraries/nextcloud-vue/pull/6048) \([susnux](https://github.com/susnux)\)
* fix(NcActions): Pressing `Escape` should always close the actions [\#6037](https://github.com/nextcloud-libraries/nextcloud-vue/pull/6037) \([susnux](https://github.com/susnux)\)
* fix(NcListItem): make the max width in `oneline` mode apply only to the content name …
=> chore: release v8.18.0

src/assets/NcAppNavigationItem.scss
- Calendar sidebar alignment, no issue
---|---
=> fix(NcAppNavigationItem): align utils with actions and other components

src/components/NcModal/NcModal.vue
Required to fix regression with Text in Viewer in Nextcloud 30, where we still want a white viewer header.
=> fix(NcModal): make dark header configurable

package-lock.json
This audit fix resolves 40 of the total 43 vulnerabilities found in your project.
* [@nextcloud/l10n](#user-content-\@nextcloud\/l10n)
* [anymatch](#user-content-anymatch)
* [axios](#user-content-axios)
* [body-parser](#user-content-body-parser)
* [bonjour](#user-content-bonjour)
* [braces](#user-content-braces)
* [chokidar](#user-content-chokidar)
* [css-loader](#user-content-css-loader)
* [dns-packet](#user-content-dns-packet)
* [elliptic](#user-content-elliptic)
* [express](#user-content-express)
* [fast-xml-parser](#user-content-fast-xml-parser)
* [http-proxy-middleware](#user-content-http-proxy-middleware)
* [icss-utils](#user-content-icss-utils)
* [ip](#user-content-ip)
* [micromatch](#user-content-micromatch)
* [multicast-dns](#user-content-multicast-dns)
* …
=> [next] Fix npm audit

src/components/NcActions/NcActions.vue
The flow is like:
1. Close the actions
2. `update:open` with `false` is emitted
3. Actions popover closes (transition)
4. `close` is emitted
Fixes flashing changes in the menu if you have conditionals like submenus.
=> feat(NcActions): Emit `closed` event only when the actions are fully closed

src/components/NcColorPicker/NcColorPicker.vue
- Fix styling. Nothing more
- Rules are mostly a copy-paste from NcInputFIeld
---|---
=> style(NcColorPicker): adjust styles of advanced fields to match NcInputField

CHANGELOG.md, package-lock.json, package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.18.0...v8.19.0)
* feat(NcModal): make dark header configurable [\#6083](https://github.com/nextcloud-libraries/nextcloud-vue/pull/6083) \([mejo-](https://github.com/mejo-)\)
* feat(NcActions): Emit `closed` event only when the actions are fully closed [\#6065](https://github.com/nextcloud-libraries/nextcloud-vue/pull/6065) \([susnux](https://github.com/susnux)\)
* fix(NcAppNavigationItem): align utils with actions and other components [\#6054](https://github.com/nextcloud-libraries/nextcloud-vue/pull/6054) \([GVodyanov](https://github.com/GVodyanov)\)
* fix(NcAvatar): add a fallback for missing CSS variable [\#6090](https://github.com/nextcloud-libraries/nextcloud-vue/pull/6090) …
=> chore: release v8.19.0

src/components/NcListItem/NcListItem.vue
The previous condition was always showing the counter number because the `counter-number` prop has `0` as default value.
This can be seen in a few examples in https://next--nextcloud-vue-components.netlify.app/#/Components/NcListItems?id=nclistitem
``` vue
<NcListItem compact
name="Name of the element">
<template #icon>
<IconNoteText :size="20" />
</template>
</NcListItem>
```
=> fix(NcListItem): change condition to display the counter number 

src/components/NcRichText/NcReferencePicker/NcReferencePicker.vue, src/components/NcRichText/NcReferenceWidget.vue
Mounting in Vue 3 does not replace the mount point but sets its innerHTML. So the mount point needs to be styled to take all the space in its container.
This does not affect custom elements mounted with Vue 2 because the mount point is replaced so it disappears.
It will only fix custom elements mounted with Vue 3.
This can be forward-ported to next.
=> [NcRichText] Add style to mount point for custom picker and custom widget elements

src/components/NcRichText/NcReferencePicker/NcReferencePickerModal.vue
- Fix https://github.com/nextcloud-libraries/nextcloud-vue/issues/4328
Fix possibility to close dialog via `Esc` if focus stays on "close" button
🏚️ Before
🏡 After
=> fix(reference-picker): allow closing modal dialog on NcReferencePicker

src/components/NcRichText/NcReferenceList.vue, src/components/NcRichText/NcReferenceWidget.vue, src/components/NcRichText/NcRichText.vue
- Do not load widget integration by default (if embedded e.g. in Talk)
- Fix min-height of list (test 'before' -> when loading is done, list shrinks)
- Make toggle button present (remove opacity, move to corner)
🏚️ Before
https://github.com/user-attachments/assets/15384f8a-9f78-4770-adc4-75d256149806
🏡 After
https://github.com/user-attachments/assets/14f260ac-7538-49d3-9d14-efe554d1a832
=> feat(NcRichText): make interactive widgets opt-in

src/assets/action.scss
- Fix https://github.com/nextcloud/mail/issues/10225
---|---
=> fix(NcActions): RTL support

src/components/NcAppNavigation/NcAppNavigation.vue, src/components/NcAppNavigationToggle/NcAppNavigationToggle.vue
- part of https://github.com/nextcloud/mail/issues/10227
---|---
1. Change nextcloud to an Rtl language (arabic here) 
2. the toggle disappears 
3. the navigation doesn't disappear once the toggle pressed
=> fix(NcAppNavigation): RTL support

src/components/NcDateTimePicker/NcDateTimePicker.vue, src/components/NcDateTimePicker/index.scss
- Fix # https://github.com/nextcloud/calendar/pull/6322
after
=> fix(NcDateTimePicker): change styling to look more like the native picker

src/components/NcActionCheckbox/NcActionCheckbox.vue, src/components/NcActionInput/NcActionInput.vue, src/components/NcActionRadio/NcActionRadio.vue, src/components/NcActionTextEditable/NcActionTextEditable.vue, src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue, src/components/NcInputField/NcInputField.vue, src/components/NcPasswordField/NcPasswordField.vue, src/components/NcRichContenteditable/NcRichContenteditable.vue, src/components/NcSettingsInputText/NcSettingsInputText.vue, src/components/NcTextArea/NcTextArea.vue, src/components/NcTextField/NcTextField.vue
Can we get this in nc/vue 8.x or does it not matter since it was added in vue9 recently (#4994)? Would be a nice QOL improvement still.
=> feat: add v-model support for input-like components

src/components/NcAppNavigationItem/NcAppNavigationItem.vue
- Fix https://github.com/nextcloud/mail/issues/10270
> Used to programmatically access [scoped slots](https://v2.vuejs.org/v2/guide/components#Scoped-Slots). For each slot, including the default one, the object contains a corresponding function that returns VNodes.
Ref https://v2.vuejs.org/v2/api/#vm-scopedSlots
[Bildschirmaufnahme_20241022_194043.webm](https://github.com/user-attachments/assets/15a03f9e-1df2-48d6-9cb2-fc35527c8125)
[Bildschirmaufnahme_20241022_193652.webm](https://github.com/user-attachments/assets/ec91c380-b66d-4028-a987-e2f35657e177)
=> fix(NcAppNavigationItem): use $scopedSlots instead of $slots

src/components/NcModal/NcModal.vue
- Part of https://github.com/nextcloud/mail/issues/10224
---|---
=> fix(NcModal): rtl support

src/components/NcAppSidebar/NcAppSidebarTabs.vue
- Continuation of #6055
- Both rules have same specificity (0.4.0):
- `.checkbox-radio-switch--button-variant:not(.checkbox-radio-switch--checked) .checkbox-radio-switch__icon > *` in NcChevkboxRadioSwitch 
- `.checkbox-content--button-variant .checkbox-content__icon:not(.checkbox-content__icon--checked) > *` in NcCheckboxContent
- so it might come up again sooner or later (noticed when linked new lib to spreed app, but not noifications app)
- since we have styles overriden for NcAppSidebarTabs specifically, they should force cover both checked and default icon
---|---
=> fix: force color-main-text for icons in NcAppSidebarTabs

src/components/NcDateTimePicker/NcDateTimePicker.vue
- Fix leaking styles to all NcSelects
Not sure, if `left` rule should be applied, see it's [broken on master](https://nextcloud-vue-components.netlify.app/#/Components/NcPickers?id=ncdatetimepicker), but at least scoped to timezone:
Current | Expected
-- | --
```vue
<template>
<span>
<NcDateTimePicker
v-model="time"
type="datetime"
:show-timezone-select="true"
:timezone-id.sync="tz" /><br>
{{ time }} | {{ tz }}
<br>
<NcSelect v-model="tz"/>
</span>
</template>
```
---|---
=> fix: scope css styles for TimeZonePicker

src/components/NcActionCheckbox/NcActionCheckbox.vue, src/components/NcActionInput/NcActionInput.vue, src/components/NcActionRadio/NcActionRadio.vue, src/components/NcActionTextEditable/NcActionTextEditable.vue, src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue, src/components/NcColorPicker/NcColorPicker.vue, src/components/NcDateTimePicker/NcDateTimePicker.vue, src/components/NcDateTimePickerNative/NcDateTimePickerNative.vue, src/components/NcInputField/NcInputField.vue, src/components/NcPasswordField/NcPasswordField.vue, src/components/NcRichContenteditable/NcRichContenteditable.vue, src/components/NcSelect/NcSelect.vue, src/components/NcSelectTags/NcSelectTags.vue, src/components/NcSettingsInputText/NcSettingsInputText.vue, src/components/NcSettingsSelectGroup/NcSettingsSelectGroup.vue, src/components/NcTextArea/NcTextArea.vue, src/components/NcTextField/NcTextField.vue, src/components/NcTimezonePicker/NcTimezonePicker.vue, src/composables/useModelMigration.ts
This PR adds **forward compatibility** with `next` (`v9`) on `v-model` props/events
- `modelValue` prop fallbacks to an old prop
- `update:modelValue` is emitted together with an old event
- `update:model-value` is emitted as well to use the new Vue 3 recommended event style in template compatible with Vue 2
Implementation details:
- Added `useModelMigration` to create migration proxy that:
- Returns a new model prop if an old one is not defined
- Triggers a new event together with an old one on set
- Checks if either old or new prop is provided for required model
- Use `model` proxy instead of old prop to get value
- Assign to `model` instead of `$emit` an old event
- Define new `prop` and `event` as well as define/update `model` option
- Update docs:
- Mark the old interfaces as …
=> feat: forward compatibility with v9 on `v-model` props/events

src/components/NcAppSidebar/NcAppSidebar.vue
- Fix https://github.com/nextcloud/calendar/issues/6400
---|---
=> fix(NcAppSidebar): RTL support

docs/functions/spawnDialog.md, src/functions/dialog/index.ts, src/functions/index.ts, src/index.js, styleguide.config.js, styleguide/global.requires.js
This allows to spawn a Vue dialog without the need of mounting the component.
So it is possible to spawn a dialog directly from any JS code outside of components (e.g. callback functions).
This method was originally taken from `@nextcloud/dialogs`, but I think it should belong to this Vue components library.
=> feat: Add `spawnDialog` function

CHANGELOG.md, package-lock.json, package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.19.0...v8.20.0)
Now you can use `v-model` directive, `:model-value` prop, and `@update:model-value` (`@update:modelValue`) event in all data input components to have **compatibility with v9** in the future.
```html
<NcTextField :value.sync="username" />
<NcTextField v-model="username" />
<NcTextField :model-value="username" @update:model-value="username = $event" />
```
If you already use `v-model` with a custom writable computed on `:value.sync` components before, it might not work as expected anymore. Make sure to remove or adjust it before update.
See the full list in [v9 breaking changes](https://github.com/nextcloud-libraries/nextcloud-vue/blob/next/CHANGELOG.md#-breaking-changes).
* feat: add `v-model` …
=> chore: prepare v8.20.0 release

styleguide/global.requires.js
- Fix https://github.com/nextcloud-libraries/nextcloud-vue/issues/6214
=> docs: add missing `useIsDarkTheme` import

src/components/NcChip/NcChip.vue
`--color-primary-element-text` should be used over `--color-primary-element` and not `--color-primary-text`
=> fix(NcChip): wrong color-primary-text variable used

src/composables/useModelMigration.ts
- Regression from: https://github.com/nextcloud-libraries/nextcloud-vue/pull/6172
- Fixes: https://github.com/nextcloud/server/issues/49335/
- https://github.com/nextcloud/server/pull/49343/
`v-model` event was fired later than the original like `input` or `update:value`. As a result - old event handlers were executed before the model value is actually updated
Solution: trigger the event defined in the `model` option first. Also, `update:modelValue` should be before `update:model-value`, but it was correct
To test: log model value from value update event from any component with `v-model`
```vue
<NcSelect
v-model="value"
@input="log('input', value)"
@update:model-value="log('model-value', value)"
@update:modelValue="log('modelValue', value)"
/>
<NcInputField
v-model="value" …
```
=> fix: make sure model event in `v-model` is the first to avoid regression

src/components/NcTextField/NcTextField.vue
- Events are fired twice:
- Once in `@input="handleInput"` which results in `$emit('update:value', $event.target.value)`
- Once in `v-on="$listeners"` which equivalent to `@update:value="$emit('update:value', $event)"`
- Before `v-model` compatibility it was only for `update:value` event. Now also for all the `modelValue` events
Handling input manually is not needed, it's handled by `NcInputField`
---|---
=> fix(NcTextField): don't fire value updating events twice

src/mixins/richEditor/index.js, tests/unit/mixins/richEditor.spec.js
- Follow-up to https://github.com/nextcloud/server/pull/48760
---|---
B | A
=> fix(NcRichContenteditable): support email mentions

src/components/NcAppContent/NcAppContent.vue
In dark Mode the background-color of the splitter are not correctly adjusted.
This PR adds the missing css for the horizontal splitter.
=> fix(NcAppContent): white splitter in dark mode when using split-horizontal mode

src/mixins/richEditor/index.js, tests/unit/mixins/richEditor.spec.js
- when injecting HTML template, newlines, tabs and consecutive whitespaces should be stripped
- when parsing innerHTML (reverse process), collapsing of whitespacing also affecting two adjacent HTML templates
- parsed ids without whitespace will be joined and won't be rendered next time
---|---
=> fix(NcRichContenteditable): do not break adjacent mentions

jest.config.js, package-lock.json, package.json, src/components/NcRichText/NcRichText.vue, src/components/NcRichText/highlight.scss, src/components/NcRichText/richtext.scss, tests/unit/components/NcRichText/NcRichText.spec.js
- Fix https://github.com/nextcloud/spreed/issues/13687
- install rehype-highlight lib v7.0.1
- use when render markdown
- apply colors from github light/dark theming
Supported languages: https://github.com/wooorm/lowlight/blob/main/lib/common.js
---|---
- We don't support language syntax before, so `use-extended-markdown` without providing lang prefix would work as before
- I haven't found a better way to do it (see PR). Suggestions are welcome
=> feat(NcRichText): highlight code syntax if language provided

src/components/NcRichContenteditable/NcRichContenteditable.vue
=> fix(NcRichContenteditable): fix pasted text handling

src/components/NcAppNavigationItem/NcAppNavigationItem.vue
- Fix #6225
menuButton was renamed to triggerButton in e817174f4
```
@@ -1883,7 +1900,7 @@ export default {
disabled: this.disabled,
},
slot: 'trigger',
-                                               ref: 'menuButton',
+                                               ref: 'triggerButton',
attrs: {
id: this.triggerRandomId,
'aria-label': this.menuName ? null : this.ariaLabel,
```
=> fix(NcAppNavigationItem): TypeError: this.$refs.actions.$refs.menuButton is undefined

src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
- set default cursor to content of disable component
- unless there is a nested clickable link (like interactive todo lists in NcRichtext)
---|---
=> style(NcCheckboxRadioSwitch): fix styles in disabled state

src/components/NcModal/NcModal.vue
- Fix https://github.com/nextcloud/spreed/issues/13867
- Button is mounted before content slot, therefor it's the first element to get into focus trap
---|---
=> fix(NcModal): make 'Close' button the last element for the focus-trap

src/components/NcAppNavigation/NcAppNavigation.vue
- Fix #6217 
So, in RTL mode, the sidebar slides from the right not the left like in LTR mode.
Now, we have to adjust apps headers margins and padding for RTL mode to accomedate the toggle button that'll be displayed on the right.
---|---
Best
=> fix(NcAppNavigation): Fix sidebar position in RTL and mobile mode.

src/components/NcAppContent/NcAppContent.vue
- Fix https://github.com/nextcloud/mail/issues/10497
=> fix(NcAppContent): add RTL support

src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
- partof https://github.com/nextcloud/mail/issues/10226
---|---
=> fix(NcCheckboxRadioSwitch): RTL support

src/components/NcDashboardWidgetItem/NcDashboardWidgetItem.vue
- #6291 
---|---
🏚️ Before | 🏡 After (icon moved `up and left` a few pixels)
---|---
Best
=> Fix(NcDashboardWidgetItem): Add RTL support to NcDashboardWidgetItem

src/components/NcRichContenteditable/NcRichContenteditable.vue
- Fix overflowing of content with long label/placeholder
---|---
=> fix(NcRichContenteditable): prevent content from overflowing

CHANGELOG.md, package-lock.json, package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.21.0...v8.22.0)
* feat(NcAvatar): implement custom javascript hook action for the contacts menu [\#6238](https://github.com/nextcloud-libraries/nextcloud-vue/pull/6238) \([st3iny](https://github.com/st3iny)\)
* feat(NcAppNavigation): add `n` hotkey to toggle navigation [\#6311](https://github.com/nextcloud-libraries/nextcloud-vue/pull/6311) \([skjnldsv](https://github.com/skjnldsv)\)
* fix(NcAppNavigationItem): TypeError: this.$refs.actions.$refs.menuButton is undefined [\#6226](https://github.com/nextcloud-libraries/nextcloud-vue/pull/6226) \([wofferl](https://github.com/wofferl)\)
* fix(NcListItem): Don't require name prop by @artonge in [\#6128](https://github.com/nextcloud-libraries/nextcloud-vue/pull/6128 …
=> chore: release v8.22.0

src/components/NcRichText/NcRichText.vue, tests/unit/components/NcRichText/NcRichText.spec.js
- Fix #6246
- `remark-gfm` is 39.5 kB in dev build, which is 30% of rehype-highlight library size (111kB which we're also importing async)
- `rehype-highlight` won't be imported for code blocks without language provided/recognised
- ⚠️ if all conditions are met, that would cause two re-renders of the first component
Signed-off-by: Maksim Sukharev <antreesy.web@gmail.com>
=> fix(NcRichText): async import remark-gfm library

src/components/NcAvatar/NcAvatar.vue
Right now `title` not visible if `NcAvatar` used without menu. This PR fixes that by moving `title` to parent `span` element.
<details><summary>:mag: Preview after fix</summary>
<p>
</p>
</details>
=> fix: Fix avatar title not shown when component used without menu

src/components/NcCounterBubble/NcCounterBubble.vue
- Fixes a small typo in the `NcCounterBubble` docs.
=> [next] fix(NcCounterBubble): small typo in docs

src/components/NcActionButton/NcActionButton.vue
- Fix the `vue/order-in-components` lint warning
=> [next] fix(NcActionButton): order in components

src/components/NcColorPicker/NcColorPicker.vue, src/components/NcPopover/NcPopover.vue
- Fix stale button (`submit` should close Popover by the code, but it's not)
- Whitespaces hidden: https://github.com/nextcloud-libraries/nextcloud-vue/pull/6336/files?w=1
---|---
=> fix(NcColorPicker): close popover on submit event

CHANGELOG.md, docs/composables.md, docs/composables/useHotKey.md, docs/composables/useIsDarkTheme.md, docs/directives.md, docs/directives/focus.md, docs/directives/linkify.md, docs/directives/tooltip.md, docs/functions/a11y.md, docs/functions/emoji.md, docs/functions/isDarkTheme.md, docs/functions/spawnDialog.md, docs/functions/usernameToColor.md, docs/index.md, package.json
The individual import path of components, composables, directives, and functions was changed.
The type of import is (e.g. `components`) is now lowercase and the `dist` will be omitted.
For example to import the `NcButton` component the path has changed:
- from  `@nextcloud/vue/dist/Components/NcButton.js`.
- to `@nextcloud/vue/components/NcButton.js`
The old import paths are still valid, but deprecated and will be removed in version 9.
=> feat: Allow to import without `dist`

CHANGELOG.md, src/assets/NcAppNavigationItem.scss, src/components/NcAppNavigation/NcAppNavigation.vue, src/components/NcAppNavigationList/NcAppNavigationList.vue, src/components/NcAppNavigationSettings/NcAppNavigationSettings.vue, src/components/NcAppSettingsDialog/NcAppSettingsDialog.vue, src/components/NcColorPicker/NcColorPicker.vue, src/components/NcContent/NcContent.vue, src/components/NcDialog/NcDialog.vue, src/components/NcModal/NcModal.vue, src/components/NcPopover/NcPopover.vue
- Ref #6384
Apart from NcPopover, there should be no visual changes from this PR
=> [next] fix!: make 'box-sizing: border-box' a default behaviour for all containers

CHANGELOG.md, docs/composables.md, docs/composables/useHotKey.md, docs/composables/useIsDarkTheme.md, docs/directives.md, docs/directives/focus.md, docs/directives/linkify.md, docs/directives/tooltip.md, docs/functions/a11y.md, docs/functions/emoji.md, docs/functions/isDarkTheme.md, docs/functions/spawnDialog.md, docs/functions/usernameToColor.md, docs/index.md, package.json, vite.config.ts
* v9 version of https://github.com/nextcloud-libraries/nextcloud-vue/pull/6385
The individual import path of components, composables, directives, and functions was changed. The type of import is (e.g. `components`) is now lowercase and the `dist` part on the path, as well as the `.js` extension, will be omitted.
This also has the benefit that types and js assets are placed next to each other (not relevant but cleaner structure).
=> [next] feat!: Change module import paths - drop `dist` and `.js`-extension

src/components/NcCounterBubble/NcCounterBubble.vue, tests/unit/components/NcCounterBubble/NcCounterBubble.spec.js
- Fix https://github.com/nextcloud-libraries/nextcloud-vue/issues/6394
- Show original raw value in title, when displayed value is shortened (humanized)
- No title for raw/unchanged value
=> fix(NcCounterBubble): show original count in title when shortened

src/components/NcInputField/NcInputField.vue, src/components/NcPasswordField/NcPasswordField.vue, src/components/NcTextField/NcTextField.vue
- https://github.com/nextcloud-libraries/nextcloud-vue/issues/6384
- in v9 `#default` slot for the leading icon has been replaced with `#icon` in `Nc*Field`
- Adding `#icon` slot for forward compatibility, fallbacks to the default slot.
- Adding a deprecation note
=> feat(Nc*Field): add `#icon` slot for forward compatibility with v9, `#default` slot is deprecated

src/components/NcListItem/NcListItem.vue
=> fix(NcListItem): Fix padding in RTL mode.

package.json
This fixes warning of npm when releasing the package, as well as apply consistent ordering.
=> [next] chore: restructure `package.json`

src/components/NcAvatar/NcAvatar.vue, styleguide.config.js
The output directory needs to be different from the input, otherwise the assets are overwritten and we can not use them (e.g. for the avatar).
This needs adjustments in Netlify to use `styleguide/build` for deployment instead of just `styleguide`. @juliusknorr
=> doc: Do not override assets while building the styleguide

src/components/NcDateTimePickerNative/NcDateTimePickerNative.vue
- Fix setting `this.model` twice from `@input` events (invalid, 'month')
---|---
Docs:
=> fix(NcDateTimePickerNative): do not set invalid value

package-lock.json, package.json, stylelint.config.js
- Check for using non-logical properties on CI
- Only a warning for now
- Auto-fixable, but each auto-fix should be checked manually
- Alternative: https://github.com/nextcloud-libraries/stylelint-config/pull/121
=> chore(stylelint): `csstools/use-logical`

.github/workflows/command-l10n-update.yml, .github/workflows/dependabot-approve-merge.yml, .github/workflows/l10n.yml, .github/workflows/lint-eslint.yml, .github/workflows/lint-stylelint.yml, .github/workflows/node-test.yml, .github/workflows/npm-audit-fix.yml, .github/workflows/npm-publish.yml, .github/workflows/reuse.yml, .github/workflows/server-styling-update.yml, .github/workflows/transifex-approve-merge.yml
Update workflows for hardening
=> ci(deps): Update workflows from organization

src/components/NcSelect/NcSelect.vue
- Fix https://github.com/nextcloud-libraries/nextcloud-vue/issues/6121
=> [next] fix(NcSelect): `required` doesn't work

CHANGELOG.md, src/components/NcActionRadio/NcActionRadio.vue
- `v-model: Boolean` is quite unusable for radio-buttons, as it should store selected value (one from many options)
- Should be changed by developers when migrate from `checked` to `v-model`, apart from that works as before
---|---
- `this.model = this.$refs.radio.checked` is kept for backward compatibility
=> fix(NcActionRadio): change modelValue to behave like NcCheckboxRadioSwitch

src/assets/action.scss, src/components/NcActions/NcActions.vue
* Resolves #6386 
1. This causes issues with the native datetime picker on Safari as the mouse move is also considered outside when hovering a picker popover that overlays other actions.
2. In general this is very unexpected behavior, e.g. click on a text input, type something, move the mouse and keep typing. You expect to write to the same input but the focus is changed to a different while typing.
=> fix(NcActions): Remove on `mousemove` listener for auto focus elements

src/assets/NcAppNavigationItem.scss, src/components/NcAppNavigationCaption/NcAppNavigationCaption.vue, src/components/NcAppNavigationItem/NcAppNavigationIconCollapsible.vue, src/components/NcAppNavigationNewItem/NcAppNavigationNewItem.vue, src/components/NcAppNavigationSettings/NcAppNavigationSettings.vue, src/components/NcRichContenteditable/NcAutoCompleteResult.vue, src/components/NcRichContenteditable/NcMentionBubble.vue, src/components/NcUserBubble/NcUserBubble.vue
- Many other components will need to be adjusted as well later.
Another issue to keep in mind: `NcRichContenteditable` is used with dir="auto" in Talk and is attached to the div with `"_input"` class. While we need to make a space for the emoji picker, the spacing is not adjusted to the RTL direction and it remains on the left side. We probably need to take the padding logic (and others) out of the `_input` class and put it in the wrapper class `rich-contenteditable` to follow the implemented language direction.
---|---
=> fix(NcAppNavigation + NcUserBubble + NcRichContenteditable): RTL support

src/components/NcDateTimePicker/index.scss
- Fix https://github.com/nextcloud-libraries/nextcloud-vue/issues/6491
---|---
=> fix(NcDateTimePicker): selected and hover time is not readable

cypress/component/richtext.cy.ts, src/components/NcRichText/NcRichText.vue, src/components/NcRichText/remarkUnescape.js
- Fix broken parsing caused by early/late escaping of special characters
- should be done after `remarkParse`, so it's not stripped
- should be done before `remarkGfm`, so it's correctly parsed
---|---
=> fix: extract un-escaping of text/code nodes with XML-like content

cypress/component/richtext.cy.ts, src/components/NcRichText/NcRichText.vue, src/components/NcRichText/remarkUnescape.js
=> fix(NcRichText): unlock tests, patch component

src/components/NcRichText/NcRichText.vue, tests/unit/components/NcRichText/NcRichText.spec.js
- This reverts commit 49ce673235268a63e765859caeabec6800dba136. (#6259)
After some testing, I'm not happy with the results. async load of ~40kB comes with side effect of resizing of components, which doesn't look good in long lists (Talk)
🏚️ Before
https://github.com/user-attachments/assets/13d6f094-169e-4be4-b34b-f8adafa82ad9
🏡 After
https://github.com/user-attachments/assets/8816a340-d674-41f4-a513-808cf86fc2c3
=> revert: import remark-gfm library in NcRichText as module, not async

CHANGELOG.md, src/components/NcAppContent/NcAppContent.vue, src/components/NcModal/NcModal.vue
Provide `disableSwipe` instead of `allowSwipeNavigation` (`NcAppContent`) and `enableSwipe` (`NcModal`).
Boolean prop should always - when possible - have a default value of `false` to allow shorthand prop assignment in the template. Similar to native HTML boolean attributes:
```html
<button disabled>
<NcModal disable-swipe>
```
=> refactor: Use boolean props with default value false

src/components/NcPopover/NcPopover.vue
- Fix https://github.com/nextcloud-libraries/nextcloud-vue/issues/6341
`after-show` was triggered before the end of init, including focusing on the elements using `focus-trap`.
This broke `focus-trap` auto return focus when `NcPopover` content focused an element on `after-show`, making it the element to return focus to.
Same for `after-hide`.
Additionally, fixed types of related `setReturnFocus`, which allows function
---|---
focus moves to `body` | focus returns to the trigger
=> fix(NcPopover): emit `after-show` after `focus-trap` init to correctly return focus when content set focus initially (e.g. `NcEmojiPicker`)

src/components/NcModal/NcModal.vue, src/utils/ValidateSlot.js
* Resolves https://github.com/nextcloud-libraries/nextcloud-vue/issues/6431
If there is anything directly rendered on the backdrop we need to ensure that it has enough contrast. This means we need the opaque backdrop always if:
- `dark` prop is set
- Any button is rendered
- Actions are rendered
- A modal header is rendered
Also fixed on doc example as that really bugged me...
=> fix(NcModal): Enforce opaque backdrop if needed

src/mixins/richEditor/index.js, tests/unit/mixins/richEditor.spec.js
NcRichContenteditable has a hidden feature: when a content is set outside (not inputted ⚠️), it's linkified.
- Origin is https://github.com/nextcloud-libraries/nextcloud-vue/pull/1669/
- But it doesn't specify motivation
@juliusknorr @mejo- Could you confirm you don't rely on this behavior in text/collectives?
---|---
=> fix(NcRichContenteditable): remove value linkify

src/components/NcActionCaption/NcActionCaption.vue, src/components/NcActionCheckbox/NcActionCheckbox.vue, src/components/NcActionInput/NcActionInput.vue, src/components/NcActionRadio/NcActionRadio.vue, src/components/NcActionTextEditable/NcActionTextEditable.vue, src/components/NcActions/NcActions.vue, src/components/NcButton/NcButton.vue, src/components/NcColorPicker/NcColorPicker.vue, src/components/NcHeaderButton/NcHeaderButton.vue, src/components/NcHeaderMenu/NcHeaderMenu.vue, src/components/NcPasswordField/NcPasswordField.vue, src/components/NcTextField/NcTextField.vue
- Fix support for RTL languages in NcActions and nested items
⚠️ `left: -10000px;` was replaced with different handling, as it might affect scrolling (although we don't have a horizontal one, it seems better to keep native elements within the component area, not outside of screen)
- Additionaly fix stylelint logical rules in docs examples (to not come back to them later)
No visual changes (for LTR)
=> fix(NcAction*): complete BiDi support

CHANGELOG.md, package-lock.json, package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.22.0...v8.23.0)
* The individual import path of components, composables, directives, and functions was changed.
The type of import is (e.g. `components`) is now lowercase and the `dist` will be omitted.
For example to import the `NcButton` component the path has changed:
```ts
// Old import
import NcButton from '@nextcloud/vue/dist/Components/NcButton.js'
// New way to import
import NcButton from '@nextcloud/vue/components/NcButton'
```
The old import paths are still valid, but deprecated and will be removed in version 9.
* `NcActionRadio` is now expecting String|Number in `v-model` directive (to compare with passed `value`) instead of Boolean. Consider it for migration.
* Some boolean props have been …
=> chore: prepare v8.23.0 release

src/components/NcDialog/NcDialog.vue, src/components/NcDialogButton/NcDialogButton.vue, tests/setup.js, tests/unit/components/NcDialogButton/NcDialogButton.spec.ts
* Depends on https://github.com/nextcloud-libraries/nextcloud-vue/pull/6005
Sometimes it is useful to also have a reset button, we already support the native type `reset` so this allows to catch the `reset` event.
=> feat(NcDialog): Allow to catch `reset` event

src/components/NcColorPicker/NcColorPicker.vue
- Fix https://github.com/nextcloud-libraries/nextcloud-vue/issues/6510
The styles are unused because they are invalid and overwritten, so we can just drop them.
=> fix(NcColorPicker): remove unused invalid styles

src/components/NcAppContent/NcAppContent.vue, tests/unit/components/NcAppContent/NcAppContent.spec.ts
Sometimes - e.g. when you have multiple view - you want to adjust the page title, that is shown as the browsers tab name. This adds a property to set that value.
=> feat(NcAppContent): Allow to set the page title

src/components/NcActions/NcActions.vue, src/components/NcButton/NcButton.vue, src/components/NcChip/NcChip.vue, src/components/NcDialogButton/NcDialogButton.vue
- Fix https://github.com/nextcloud-libraries/nextcloud-vue/pull/6472#discussion_r1993071083
=> docs: adjust version number for `variant` props

src/components/NcInputField/NcInputField.vue
Prevent error state when "required" but no user interaction yet.
=> fix(NcInputField): Only show error state border if user interacted with the input

src/components/NcEmojiPicker/NcEmojiPicker.vue
Like in a `focus-trap`, we should only return focus on close if the closing action didn't add the focus already, for example, when the emoji picker was closed by clicking on an input field.
=> fix(NcEmojiPicker): return focus steals actual focus

CHANGELOG.md, src/components/NcAvatar/NcAvatar.vue, src/components/NcDialog/NcDialog.vue, src/components/NcModal/NcModal.vue
- master PR of https://github.com/nextcloud-libraries/nextcloud-vue/pull/6653
=> feat: add boolean prop alternatives with false as default value

package-lock.json, package.json
- Ref: https://github.com/nextcloud/server/issues/51506
- Fixing the problem on `@nextcloud/vue` part without the need to override
=> fix(deps): fix version and bundle `mdast-util-gfm-autolink-literal`

src/components/NcEllipsisedOption/NcEllipsisedOption.vue, src/components/NcHighlight/NcHighlight.vue, src/utils/findRanges.ts, tests/unit/utils/createElementId.spec.ts, tests/unit/utils/findRanges.spec.ts, webpack.config.cjs
* For #841 
- For a consistent code base
=> refactor: migrate `findRanges` to Typescript

src/components/NcPopover/NcPopover.vue
The Focus-Trap library will throw an error if a trap does not have any elements it can focus. Therefore we need something to set focus on if there's nothing else to use. In the documentation it is recommended to give the container a tab-index of -1 to make it focusable but not appear in the tab flow, and then set that as the fallBack to focus on when theres nothing else in the container.
=> add fallBackFocus to NcPopover

src/components/NcAvatar/NcAvatar.vue
- Fix unnecessary scrolling, if NcAvatar is in the list
- There might be an invisible symbol rendered, which causes DOM element to be larger than its actual size
- If there is no image, but only initials - line-height centers them in the circle, and scroll-height is correct
---|---
=> fix(NcAvatar): keep line-height only for 'initials' avatars

src/components/NcActionButton/NcActionButton.vue, src/components/NcActions/NcActions.vue, src/components/NcAppNavigationNew/NcAppNavigationNew.vue, src/components/NcAvatar/NcAvatar.vue, src/components/NcPopover/NcPopover.vue
Following https://github.com/nextcloud-libraries/nextcloud-vue/pull/6065
The evets are `after-hide` and `after-show`, not `apply-hide` and `apply-show`
https://github.com/nextcloud/nextcloud-vue/blob/ae77137aee5097dcbe8cef6c53eb1ce3bc81c7ee/src/components/NcPopover/NcPopover.vue#L230-L237
The vue-floating lib does not properly compute how long it needs to wait to know the popup have been shown/hidden.
I investigated and it's [only using `requestAnimationFrame`](https://github.com/Akryum/floating-vue/blob/19857764c4f73dea7ed44a7d970adb968ee7ad90/packages/floating-vue/src/components/Popper.ts#L728-L782) which in that case _isn't_ enough to ensure its completion.
Because we have our own custom animation variables, we need to manually check for it ourselves.
Tested on Server with log entries …
=> feat(NcActions): fix listening to wrong event names and add `opened` event / [NcPopover] animation wait

src/components/NcPopover/NcPopover.vue
Following https://github.com/nextcloud-libraries/nextcloud-vue/pull/6683
Backport to `[next]` in https://github.com/nextcloud-libraries/nextcloud-vue/pull/6685
=> fix(NcPopover): use `transitionend` to wait for popover show/hide animation end

CHANGELOG.md, package-lock.json, package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.23.1...v8.24.0)
Some boolean props have been deprecated in favor of alternatives with default value `false`.
This allows to use shorthand notation on the template, as a prop with a default value of `false`
will be set to `true` if it is set (without any value) in the template,
similar to native HTML boolean attributes.
Following components have been adjusted:
|     Component |         Deprecated prop | New alternative |
|---------------|-------------------------|-----------------|
|    `NcAvatar` |        `showUserStatus` |    `hideStatus` |
|    `NcAvatar` | `showUserStatusCompact` | `verboseStatus` |
|     `NcModal` |              `canClose` |       `noClose` |
|    `NcDialog` |              `canClose` | …
=> release: v8.24.0

src/components/NcPopover/NcPopover.vue
Tiny nitpick from https://github.com/nextcloud-libraries/nextcloud-vue/pull/6687
=> [next] fix(NcPopover): add `passive: true` to `transitionend` event listener

.github/dependabot.yml, .github/pull_request_template.md, README.md, docs/index.md, styleguide.config.cjs
- Adjust documentation and templates for changed default branch
=> chore: default branch is `main` and Vue 2 branch is `stable8`

src/mixins/actionText.js, src/utils/getParent.ts, tests/unit/utils/getParent.spec.ts
- For #841 
- Also added tests - only used by NcActions
=> chore: migrate `GetParent` to Typescript

src/components/NcActions/NcActions.vue
- Regression from: https://github.com/nextcloud-libraries/nextcloud-vue/pull/6685/
- `onOpen` is not defined
- `closed` is not triggered
---|---
=> fix(NcActions): trigger forgotten closed event and correctly handle open

src/components/NcDateTimePicker/NcDateTimePicker.vue
- add more documentation on when and how to use the `NcDateTimePicker`.
- also fix wrong mention of old library
=> docs: improve examples and documentation for `NcDateTimePicker`

CHANGELOG.md, package-lock.json, package.json
- Release a (hopefully) last alpha for testing
Things we have in v8 but missing in v9
* [next] refactor: replace boolean properties with `default: true` with `default: false` by @susnux in https://github.com/nextcloud-libraries/nextcloud-vue/pull/6653
* [next] feat(NcAppContent): Allow to set the page title by @backportbot in https://github.com/nextcloud-libraries/nextcloud-vue/pull/6596
* [next] feat: Add consistent `variant` prop for design variant of buttons / chips by @backportbot in https://github.com/nextcloud-libraries/nextcloud-vue/pull/6595
* [next] feat(NcActions): add `opened` and `closed` events to handle closing/opening end | fix(NcPopover): correctly wait for animation end in `after-show`/`after-hide` events by @backportbot in …
=> chore: prepare release of v9.0.0-alpha.8

src/components/NcDateTimePicker/NcDateTimePicker.vue, tests/component/components/NcDateTimePicker.spec.ts
- Should fix the problem mentioned in #6720 by providing localized formatting by default
Instead of using some default format like ISO or US layout, we should use a format that works for all users.
So this migrates the default formatting to `Intl.DateTimeFormat`.
Before | After :us:  | After :de: 
---|---|--
=> fix(NcDateTimePicker): localize the default formatting

src/functions/dialog/index.ts
- `onClose` in `spawnDialog` doesn't work
- In Vue 3 event handler must be passed as `on{Event}`
More improvements are coming soon for:
- Instance access and unmounting
- Typings
- Correcting Params
---|---
=> fix(dialogs/spawnDialog): dialog cannot be closed

src/components/NcDateTimePicker/NcDateTimePicker.vue
We should not use partial ranges (meaning after selecting the start `[Date, null]` will be emitted). If this is needed someday we can enable it,
but its not covered by our component interface (props / events) documentation so just disabled for now.
=> fix(NcDateTimePicker): prevent emitting `[Date, null]`

CHANGELOG.md, src/components/NcDateTimePicker/NcDateTimePicker.vue, tests/component/components/NcDateTimePicker.spec.ts
1. Add a time range picker mode
2. Align type names to `TYPE(-range)?`
3. Fix some issues related to time mode (also without range)
=> feat(NcDateTimePicker): add time range picker and align naming

.github/workflows/command-l10n-update.yml, .github/workflows/command-playwright-update.yml, .github/workflows/l10n.yml, .github/workflows/lint-eslint.yml, .github/workflows/lint-stylelint.yml, .github/workflows/node-test.yml, .github/workflows/npm-audit-fix.yml, .github/workflows/npm-publish.yml, .github/workflows/playwright.yml, package-lock.json, package.json
This package does not even target Node.JS so we could even drop the `node` dependency for `engines.
But lets at least allow the current LTS version (22) along side with LTS 20.
=> chore: adjust package engines versions

docs/functions/spawnDialog.md, src/functions/dialog/index.ts
- Doing small changes from: https://github.com/nextcloud-libraries/nextcloud-vue/issues/6731
- Allows debugging dialog content with `vue-devtools`
- Also, `getCurrentInstance` only works when the dialog is spawned in the setup context, so doesn't even work in a click handler
This looses `appContext`.
Workarounds:
- Always use locally imported components
- When possible - provide data via props
- For `provide/inject` - provide directly from the root dialog component
- For Pinia - should work via `activePinia`, or via provide in the root dialog component
Alternative:
- Pass app/appContext via options and then do hacks - re-provide every provider
=> fix(dialogs/spawnDialog)!: support vue-devtool but loose appContext

CHANGELOG.md, src/components/NcDateTimePicker/NcDateTimePicker.vue
- For #6651
- three new types added
- deprecated `range`
- deprecated `formatter`
- add documentation about deprecation and transparent wrappers
=> [stable8] feat(NcDateTimePicker): add new types as alternative for `range` property

src/functions/dialog/index.ts
- Chained on https://github.com/nextcloud-libraries/nextcloud-vue/pull/6757
- For: https://github.com/nextcloud-libraries/nextcloud-vue/issues/6731
- Do not `toRaw` the result
`toRaw` is only actual for libraries like `@nextcloud/dialogs` where the library can `toRaw` the result before emitting the event.
=> feat(dialogs/spawnDialogs)!: do not toRaw the result 

CHANGELOG.md, src/components/NcAppContent/NcAppDetailsToggle.vue, src/components/NcModal/NcModal.vue, src/components/NcRichContenteditable/NcRichContenteditable.vue, src/directives/Tooltip/index.js
- port all usage within this library to native `title` attribute
- deprecate `Tooltip` directive, its recommended to use the browser native tooltips using `title`.
=> refactor: deprecate `Tooltip` directive for accessibility

src/components/NcIconSvgWrapper/NcIconSvgWrapper.vue, src/components/NcModal/NcModal.vue, src/components/NcPopover/NcPopover.vue, src/directives/Tooltip/index.scss, stylelint.config.cjs
Adjusted all styles for RTL support and increased severity to error if there are new incompatible changes.
=> Adjust all styles for RTL support and add `directional` prop to NcIconSvgWrapper

docs/functions/spawnDialog.md, src/functions/dialog/index.ts
- For: https://github.com/nextcloud-libraries/nextcloud-vue/issues/6731
- Non braking alternative for: https://github.com/nextcloud-libraries/nextcloud-vue/pull/6759
- Not only call the `onClose` callback, but also return a promise
=> feat(dialogs/spawnDialog): return promise with the result

docs/functions/spawnDialog.md, src/functions/dialog/index.ts
- Breaking alternative for https://github.com/nextcloud-libraries/nextcloud-vue/pull/6758
- For: https://github.com/nextcloud-libraries/nextcloud-vue/issues/6731
- Return promise **instead of** `onClose` callback
=> feat(dialogs/spawnDialog)!: replace onClose callback with Promise

CHANGELOG.md, src/components/NcModal/NcModal.vue, tests/component/components/NcModal.spec.ts
- for https://github.com/nextcloud-libraries/nextcloud-vue/issues/6384
Replace `closeButtonContained` with `closeButtonOutside`.
=> refactor!(NcModal): adjust to boolean props with default `false`

package-lock.json, package.json, src/components/NcRichContenteditable/NcRichContenteditable.vue
Remove useless dependencies where we can just use native ES alternatives.
=> refactor: drop `string-length` dependency and replace with native solution

src/functions/dialog/index.ts
- A next iteration of https://github.com/nextcloud-libraries/nextcloud-vue/pull/6770 that improves `spawnDialog` types:
- Now only components with a declared `@close` event can be passed to `spawnDialog`, otherwise an error is thrown on a type level suggesting what went wrong
- Autocompletion for props
- Return type is automatically inferred based on a `@close` event's payload
The implementation passes all the test cases from https://github.com/nextcloud-libraries/nextcloud-vue/pull/6770#issuecomment-2804453176
---|---
B | A
=> fix(dialogs/spawnDialog): enhance `spawnDialog` types

l10n/messages.pot, src/components/NcRichContenteditable/NcRichContenteditable.vue
regression of the migration from Tooltip directive to native tooltips. It needs to be a string not an object.
Also use `n` as you never can know how plurals are translated (there are possible more than two plural forms).
=> fix(NcRichContenteditable): add correct tooltip

.github/workflows/lint-typescript.yml, package-lock.json, package.json, src/components/NcButton/NcButton.vue, src/components/NcDateTimePicker/NcDateTimePicker.vue, src/components/NcDialog/NcDialog.vue, tsconfig.json
- built on top of https://github.com/nextcloud-libraries/nextcloud-vue/pull/6735
1. enforce project to be typescript compliant
2. fix found issues
- Missing type import in NcButton
- Wrong types in NcDateTimePicker (less strict types only)
- Missing event in NcDialog
=> chore: type check project on CI

src/components/NcRichContenteditable/NcRichContenteditable.vue
- some time ago the error state style was lost and only the class was set.
- bring back the error style on overflow.
=> fix(NcRichContenteditable): bring back error style on overflow

CHANGELOG.md, package-lock.json, package.json
* feat(NcDateTimePicker): add new types as alternative for `range` property [#6738](https://github.com/nextcloud-libraries/nextcloud-vue/pull/6738) ([susnux](https://github.com/susnux))
* feat: provide `NcSelectUsers` as replacement of `user-select` prop for `NcSelect` [#6791](https://github.com/nextcloud-libraries/nextcloud-vue/pull/6791)
* Adjust all styles for RTL support and add `directional` prop to NcIconSvgWrapper [#6766](https://github.com/nextcloud-libraries/nextcloud-vue/pull/6766)
* fix(NcRichContenteditable): add correct tooltip [#6782](https://github.com/nextcloud-libraries/nextcloud-vue/pull/6782)
* fix(NcRichContenteditable): bring back error style on overflow [#6789](https://github.com/nextcloud-libraries/nextcloud-vue/pull/6789)
* fix(NcAvatar): skip user status request …
=> chore: prepare release of v8.25.0

CHANGELOG.md, package-lock.json, package.json
* fix(NcPopover): regression with incorrect size on RTL [#6797](https://github.com/nextcloud-libraries/nextcloud-vue/pull/6797)
**Full Changelog**: https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.25.0...v8.25.1
=> chore: release 8.25.1

src/components/NcRichText/NcReferenceList.vue, src/components/NcRichText/NcRichText.vue
The references prop is passed to `NcReferenceList` and is processed as a list, not an object. This prevents Vue warnings and fixes the docs.
=> fix(NcRichText): `references` prop type

src/components/NcAppContent/NcAppContent.vue
- Fix #6204
As mentioned in #6204 the change in 8.10.0 causes the item list to rebuild every time the details of an item are shown.
With a dynamic list like in the news app, where read items are removed from the list when refreshing it, this means that the selected item you looked at the details are gone immediately when you close the details.
It also affects the performance, because of the rebuilding when closing the details, which is notable on mobile devices.
I think there is no technical reason to delete it, so it is better to just hide the list.
=> fix(NcAppContent): don't remove list when showing details in mobile or no-split mode

CHANGELOG.md, src/components/NcPopover/NcPopover.vue
* Split from #6802 
* for #6384 
Replacing the `focusTrap` prop to have prop with default of `false` allowing to use HTML short cut attributes `<NcPopover no-focus-trap />`.
=> feat(NcPopover): add new `noFocusTrap` prop

.github/workflows/command-l10n-update.yml, .github/workflows/command-playwright-update.yml
- Adjust our CI commands to use conventional commits
=> ci: use conventional commits in `/*-update` commands

build/docs-plugin.ts, playwright.config.ts, vite.config.ts
Explicitly do not generate source maps to prevent warnings about missing souremaps. This especially happens when running Playwright tests.
Not a big problem as the docs are not used, but at least we get rid of those warnings in the logs.
=> chore: adjust vite plugin for vue `<docs>`

src/components/NcAvatar/NcAvatar.vue, tests/unit/components/NcAvatar/NcAvatar.spec.ts
- Fix loading of faulty avatars (for non-users) from NcUserBubble
---|---
=> fix(NcAvatar): do not load avatar from server, if iconClass was provided

src/components/NcRichContenteditable/NcMentionBubble.vue
- Fix subelements positioning
- Even if it's off the viewport, should be in line with wrapper
- To reproduce:
- have scrollable chat and new message form in Talk
- use autocomplete with `@` to mention someone
- hit `Enter`
- see third scrollbar
---|---
B | A
=> fix(NcMentionBubble): position selectable text aligned with the component

src/components/NcSelectUsers/NcSelectUsers.vue, tests/unit/components/NcInputField/NcInputField.spec.ts, tests/unit/components/NcSelectUsers/search-event.spec.ts
The `search` event is commonly used to search for more users instead of preload all.
So we need to add this event as well.
Reported by @Chartman123
=> fix(NcSelectUsers): add missing `search` event

CHANGELOG.md, src/components/NcPopover/NcPopover.vue, tests/unit/components/NcPopover/logical-placement.spec.ts
* Resolves #6384 
1. Document all properties used by Nextcloud apps (I checked for all usage in the nextcloud GitHub organization)
2. Remove mention of the wrapped library
3. Add feature to use logical direction in the `placement` prop
=> feat(NcPopover): document all properties and remove transparent `floating-vue` wrapper

CHANGELOG.md, package-lock.json, package.json
This release will (hopefully) be the last release of the v9 series with breaking changes.
* feat(NcDateTimePicker): add time range picker and align naming by @susnux in https://github.com/nextcloud-libraries/nextcloud-vue/pull/6728
* feat(dialogs/spawnDialog): separate spawning options from dialog props and allow Element as a container by @ShGKme in https://github.com/nextcloud-libraries/nextcloud-vue/pull/6756
* feat(dialogs/spawnDialogs)!: do not toRaw the result  by @ShGKme in https://github.com/nextcloud-libraries/nextcloud-vue/pull/6760
* Adjust all styles for RTL support and add `directional` prop to NcIconSvgWrapper by @susnux in https://github.com/nextcloud-libraries/nextcloud-vue/pull/6733
* feat(dialogs/spawnDialog): return promise with the result by @ShGKme in …
=> chore: prepare release of v9.0.0-rc.0

src/components/NcAppSidebar/NcAppSidebar.vue, src/components/NcAppSidebarHeader/NcAppSidebarHeader.vue, src/components/NcAppSidebarHeader/index.ts, src/components/index.ts, styleguide.config.cjs
- Allows to put custom content with `info` slot
- Expose `var(--app-sidebar-close-button-offset)` for custom content positioning (respecting the space taken by close button)
- Introduce `NcAppSidebarHeader` for a11y navigation
See https://github.com/nextcloud-libraries/nextcloud-vue/pull/6666/files?w=1 for non-whitespace changes
See https://github.com/nextcloud-libraries/nextcloud-vue/tree/feat/noid/appsidebar-header-empty-slot-vue2 for Vue2 branch to test with apps
Quick prototype for Talk:
Clean | WIth explanation
-- | --
https://github.com/user-attachments/assets/8815ee43-7b35-4453-a1ef-852bb7cac181
=> feat(NcAppSidebar): add `info` slot

CHANGELOG.md, package-lock.json, package.json
Due to a "bug" in our release workflow the v9 was published on the latest tag.
This will cause all users of `@nextcloud/vue` to receive that as a dependabot update.
So to prevent this we need to release a new v8 version.
To prevent this in the future the release workflow is fixed in:
https://github.com/nextcloud-libraries/nextcloud-vue/pull/6841
---
The `info` slot was introduced to allow customization of sidebar header content.
This will replace original main name of the sidebar and `header`, `subname`, `secondary-actions`, `tertiary-actions` slots.
It it recommended to use slot together with `NcAppSidebarHeader` component to support accessibility features.
The `focusTrap` property is now deprecated and will be replaced with `noFocusTrap`,
the reason behind this is to only have boolean …
=> chore: prepare release of v8.26.0

.github/workflows/block-unconventional-commits.yml, .github/workflows/command-l10n-update.yml, .github/workflows/command-playwright-update.yml, .github/workflows/dependabot-approve-merge.yml, .github/workflows/fixup.yml, .github/workflows/lint-eslint.yml, .github/workflows/lint-stylelint.yml, .github/workflows/node-test.yml, .github/workflows/npm-audit-fix.yml, .github/workflows/npm-publish.yml, .github/workflows/playwright.yml, .github/workflows/reuse.yml
Fixes some workflows like the "publish" one.
=> chore: update workflows from organization

src/components/NcIconSvgWrapper/NcIconSvgWrapper.vue
Parent is flex, but not the intermediate span
See the folder icon:
=> fix(NcIconSvgWrapper): center svg span wrapper

src/components/NcChip/NcChip.vue
* split from #6133  
* related to #841
=> refactor(NcChip): properly document and type slots and emits

package.json
So, we use `watch` everywhere, literally for over 7 years.
I see some repos that are slowly usig this new `dev:watch` syntax. Can we please stick to the one we used for years ? :see_no_evil: 
- https://github.com/nextcloud-libraries/nextcloud-vue/blob/f27d675871a16916e944cfbb5e1af196fd26524b/package.json#L17
- https://github.com/nextcloud/server/blob/2e7cbc5e1b5caed31cef9fc39c3dbc838478e03a/package.json#L13
=> chore: move from `dev:watch` to `watch`

CHANGELOG.md, package-lock.json, package.json
* fix(NcIconSvgWrapper): center svg span wrapper [#6880](https://github.com/nextcloud-libraries/nextcloud-vue/pull/6880) ([skjnldsv](https://github.com/skjnldsv))
=> chore: prepare v8.26.1

src/components/NcChip/NcChip.vue
- Fix https://github.com/nextcloud-libraries/nextcloud-vue/pull/6812/files#r2082255104
=> fix(NcChip): do not rerender slots to check if they are available

src/functions/dialog/index.ts
- Fix: https://github.com/nextcloud-libraries/nextcloud-vue/issues/6902
- Looks dirty, but I didn't find a better solution
=> fix(dialog/spawnDialog): incorrect return type for optional result

src/components/NcAppSidebar/NcAppSidebar.vue, src/directives/Focus/index.ts, src/directives/index.ts
=> refactor(Focus): migrate directive to Typescript

CHANGELOG.md, package-lock.json, package.json
* feat(NcAppSidebar): add `info` slot by @Antreesy in https://github.com/nextcloud-libraries/nextcloud-vue/pull/6666
* fix(NcIconSvgWrapper): center svg span wrapper by @skjnldsv in https://github.com/nextcloud-libraries/nextcloud-vue/pull/6869
* fix(NcChip): do not rerender slots to check if they are available by @susnux in https://github.com/nextcloud-libraries/nextcloud-vue/pull/6903
* fix(dialog/spawnDialog): incorrect return type for optional result by @ShGKme in https://github.com/nextcloud-libraries/nextcloud-vue/pull/6905
* Updates for project Nextcloud vue library by @transifex-integration in https://github.com/nextcloud-libraries/nextcloud-vue/pull/6844
* chore: update workflows from organization by @susnux in https://github.com/nextcloud-libraries/nextcloud-vue/pull/6841
* …
=> chore: prepare v9.0.0-rc.1

src/composables/index.js, src/composables/useIsFullscreen/index.ts, src/mixins/isFullscreen/index.js
- Backport of https://github.com/nextcloud-libraries/nextcloud-vue/pull/6659
=> [stable8] refactor(useIsFullscreen): migrate to Typescript

src/components/NcAppContent/NcAppDetailsToggle.vue
* for #841 
- migrate to `script setup` SFC
- migrate to Typescript
- use directional arrow icon
=> refactor(NcAppDetailsToggle): migrate to Typescript

src/components/NcAppContent/NcAppContent.vue
- Fix #6931
From [Splitpanes Release Notes](https://antoniandre.github.io/splitpanes/#release-notes)
Version 4.0.0
> Refactored all the emitted events to always return a single object containing as much information as possible. E.g. event, index, pane, prevPane, nextPane, panes.
=> fix(NcAppContent): adapt to new emitted event object with splitpanes ^4.0.0

tests/unit/functions/usernameToColor/usernameToColor.spec.ts
this just spams the test output.
=> test: drop useless console output

src/components/NcChip/NcChip.vue
- split from #6133 
If the component is used within a container this allow to also limit the actions popover to that container.
=> feat(NcChip): allow to define the actions container

src/components/NcSelect/NcSelect.vue
Going through our TODOs I noticed this stale TODO.
It makes no sense to provide a default as the label to be used varies to much depending on the use case. Its better to let the developer decide.
=> chore: remove `todo` from NcSelect

CHANGELOG.md, src/components/NcActionButton/NcActionButton.vue, src/components/NcActionInput/NcActionInput.vue, src/components/NcActionLink/NcActionLink.vue, src/components/NcActions/NcActions.vue, src/mixins/actionText.js
> To be removed in @nextcloud/vue 9.
This was deprecated in v8 and we should remove with v9.
Also added the check as written in the TODO.
=> chore: remove deprecated `aria-hidden` prop from `NcAction*`

CHANGELOG.md, src/components/NcRichContenteditable/NcAutoCompleteResult.vue, src/components/NcRichContenteditable/NcMentionBubble.vue
Was deprecated in v8 and need to be removed in v9. Affects:
- `NcAutoCompleteResult`
- `NcMentionBubble`
title only was added by accident, the backend provides `label` so only semantically breaking, but should not affect users.
=> chore!(NcRichContenteditable): remove `title` prop in favor of `label`

package-lock.json, package.json, src/components/NcRichText/NcRichText.vue, tests/component/components/NcRichText/markown-rendering.spec.ts
Only allow links to specific protocols.
---|---
=> fix(NcRichText): filter links based on protocol

src/assets/action.scss, src/components/NcActionButton/NcActionButton.vue
- There might be a need to use a button as 'action name' + 'description'
- Current solution: `name` prop + `default` slot is a bit bulky
- Alternative with this PR:  `default` slot + `subline` prop
Documentation screenshot:
Same content comparison:
=> feat(NcActionButton): introduce `description` prop

src/components/NcActionButton/NcActionButton.vue, src/components/NcActionTextEditable/NcActionTextEditable.vue
Simplify RTL handling for icons a bit.
=> refactor: use `NcIconSvgWrapper` with `directional` property where needed

CHANGELOG.md, package-lock.json, package.json
Open bugfix PRs:
Other PRs:
---
* fix(NcEmptyContent): description styling for mobile by @Plesin in https://github.com/nextcloud-libraries/nextcloud-vue/pull/6936
* style(NcAppSidebar): remove custom styles from close button by @Antreesy in https://github.com/nextcloud-libraries/nextcloud-vue/pull/6944
* fix: add missing `NcSelectUsers` export by @susnux in https://github.com/nextcloud-libraries/nextcloud-vue/pull/6947
* fix(NcAppContent): adapt to new emitted event object with splitpanes ^4.0.0 by @wofferl in https://github.com/nextcloud-libraries/nextcloud-vue/pull/6950
* fix(NcActionInput): register used NcColorPicker component by @susnux in https://github.com/nextcloud-libraries/nextcloud-vue/pull/6956
* refactor(NcUserStatusIcon): migrate component to Typescript by @susnux in …
=> chore: prepare v9.0.0-rc.2

CHANGELOG.md, package-lock.json, package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.26.1...v8.27.0)
A padding was added to the empty content wrapper. It is recommended to check in-app styles for possible overrides.
* feat(NcChip): allow to define the actions container [#6964](https://github.com/nextcloud-libraries/nextcloud-vue/pull/6964)
* feat(NcActionButton): introduce `description` prop [#6975](https://github.com/nextcloud-libraries/nextcloud-vue/pull/6975)
* fix(NcEmptyContent): description styling for mobile [#6943](https://github.com/nextcloud-libraries/nextcloud-vue/pull/6943)
* style(NcAppSidebar): remove custom styles from close button [#6945](https://github.com/nextcloud-libraries/nextcloud-vue/pull/6945)
* refactor(useIsFullscreen): migrate to Typescript …
=> chore: prepare v8.27.0 release

src/components/NcAppNavigationToggle/NcAppNavigationToggle.vue
* Resolves https://github.com/nextcloud-libraries/nextcloud-vue/issues/6930#issuecomment-2920520832
The backport to `next` was incomplete as this was a conflict of the (still) missing backport of https://github.com/nextcloud-libraries/nextcloud-vue/pull/6322
Meaning we need to restore the correct behavior and remove the shortcuts stuff until #6322 is merged.
=> fix(NcAppNavigationToggle): restore button design and remove wrong attribute

src/assets/NcAppNavigationItem.scss
- Fix https://github.com/nextcloud/mail/issues/11037
---|---
Check with them so they are aware this is fixed here.
=> fix(NcAppNavigationItem): multi level padding

src/components/NcAppNavigationSettings/NcAppNavigationSettings.vue
- Fix #6998
Unfortunately, the settings button and the navigation entries are not nicely aligned yet. But since I didn't know which one should be adjusted, I left it as it was.
Regression from #6429.
---|---
=> fix(NcAppNavigationSettings): button left full width

src/components/NcAppContent/NcAppContent.vue
Main issue: The `core -> apps` initial state is treated like an object in NcAppContent but [it is an array](https://github.com/nextcloud/server/blob/master/lib/private/TemplateLayout.php#L73).
So in the page title, instead of the current app's name, the `core -> active-app` initial state is used. In the case of the Files app, this value is not what we want, it's "Nextcloud" which leads to page titles like
`CURRENT_DIR - All files - Nextcloud - THEMING_INSTANCE_NAME`
instead of the expected
`CURRENT_DIR - All files - Files - THEMING_INSTANCE_NAME`
=> fix(NcAppContent): incorrect page title from a different `core.apps` format in Nextcloud 30

src/components/NcButton/NcButton.vue
This correctly applies the padding for reverse buttons.
- Fix #7005
Regression from #6033.
---|---
Comparison to `stable8`:
=> fix(NcButton): correctly apply reverse padding

src/components/NcSelectUsers/NcSelectUsers.vue
- Fix `v-model` usage in Vue 2 (for backward compatibility with main branch)
- Noticed while testing unreleased eslint config
---|---
[Try stable8--nextcloud-vue](https://stable8--nextcloud-vue-components.netlify.app/#/Components/NcSelect?id=ncselect-1) | [Try deploy-preview](https://deploy-preview-7032--nextcloud-vue-components.netlify.app/)
=> [stable8] fix(NcSelectUsers): fix using of v-model in Vue 2

src/components/NcCheckboxRadioSwitch/NcCheckboxContent.vue, src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
- Fix https://github.com/nextcloud/spreed/issues/15288
>[!WARNING]
> this reduces 'switch' icon height to `16px`
> this reduces 'switch' component height to `34px`
>
> - [ ] Qualify as breaking change or bugfix?
---|---
=> fix(NcCheckboxRadioSwitch): align icons with the first row of label

src/components/NcRichText/NcRichText.vue
- Upstreaming https://github.com/nextcloud/spreed/pull/15363
---|---
=> fix(NcRichText): always render code blocks in LTR direction

src/components/NcRichText/richtext.scss
Backport of #7056 
Styles have been moved from .scss file to the component
=> [stable8] fix(NcRichText): always render code blocks in LTR direction

src/components/NcHeaderMenu/NcHeaderMenu.vue
Regression from refactoring.
---|---
=> fix(NcHeaderMenu): bring caret back

src/components/NcPopover/NcPopover.vue
`getPopoverContentElement()` can be undefined, so it should not fail when trying to add a listener
=> fix(NcPopover): component crash when unmounted shown

src/components/NcListItem/NcListItem.vue
- If we pass `:active="false` and current item has an active path, it will bypass the explicit prop. This is also needed as vue-router 4 active [changing behavior](https://router.vuejs.org/guide/migration/#Removal-of-the-exact-prop-in-router-link-) where there is a wider range of paths considered active -> we rely more on prop to better maintain the previous behavior.
=> fix(NcListItem): let `active` prop take higher priority

src/components/NcActions/NcActions.vue, src/components/NcEmojiPicker/NcEmojiPicker.vue
- Alternative to: https://github.com/nextcloud-libraries/nextcloud-vue/pull/7090
- Regression from https://github.com/nextcloud-libraries/nextcloud-vue/pull/6807/
- Migration was missing
=> fix(NcActions + NcEmojiPicker): no focus-trap when needed, extra focus-trap when not

src/components/NcRichText/NcRichText.vue
- top children of .rich-text--wrapper-markdown is now a fragment instead of div in Vue 2
---|---
=> fix(NcRichText): adjust markdown styles after migration

src/components/NcNoteCard/NcNoteCard.vue
=> fix(NcNoteCard): too large icon padding

CHANGELOG.md, src/composables/index.ts, src/composables/useFormatDateTime/index.ts, tests/unit/composables/useFormatDateTime.spec.js
We now have `useFormatTime` and `useFormatRelativeTime` instead. This was never exported¹ thus its not breaking.
¹ because our exports pattern requires a subfolder e.g. `composables/NAME/index.ts` and not just the file itself like `composables/NAME.ts`.
**EDIT** It was not exported as entry point but it was exported in the default entry point, thus it is breaking and thus v9 only.
=> refactor!: remove `useFormatDateTime`

.eslintrc.json, CHANGELOG.md, src/components/NcAppContent/NcAppContent.vue, src/components/NcAppNavigationNewItem/NcAppNavigationNewItem.vue, src/components/NcAppSidebar/NcAppSidebar.vue, src/components/NcAppSidebarTab/NcAppSidebarTab.vue, src/components/NcCollectionList/NcCollectionListItem.vue, src/components/NcContent/NcContent.vue, src/components/NcEmojiPicker/NcEmojiPicker.vue, src/components/NcRelatedResourcesPanel/NcRelatedResourcesPanel.vue, src/components/NcRichContenteditable/NcRichContenteditable.vue, src/components/NcRichText/NcReferencePicker/NcProviderList.vue, src/components/NcRichText/NcReferencePicker/NcReferencePicker.vue, src/components/NcRichText/NcRichText.vue, tests/unit/components/NcRichText/NcRichText.spec.js
- :warning: chained on https://github.com/nextcloud-libraries/nextcloud-vue/pull/7058
Make all events camel case instead of kebab case. For Vue 3 this is the recommended way of naming.
With Vue 3 this is compatible as `@event-name` will be triggered for `emit('eventName')`.
The breaking part is only removal of the deprecated two events where a scope like `resize:list` was used.
=> refactor!: make all events camelcase and drop deprecated events

package-lock.json
silence the warnings when building.
=> chore(deps): update `caniuse-lite` to silence warnings

src/components/NcAppContent/NcAppContent.vue, tests/unit/components/NcAppContent/NcAppContent.spec.ts
We do not use the product name but the instance name, so this clarifies it.
Also the docs of the size props was a bit confusing - adjusted it.
=> refactor(NcAppContent): clarify props documentation and use capabilities over initial state

build/l10n-plugin.mts, package-lock.json, package.json, playwright.config.ts, tests/component/components/NcRichContenteditable.spec.ts, tests/unit/components/NcDateTime/NcDateTime.spec.js, tests/unit/utils/l10n.spec.ts
- Requires https://github.com/nextcloud-libraries/nextcloud-l10n/pull/953
This fixes some components not being translated correctly.
Also the gettext wrapper is only created once (performance).
=> fix(l10n): adjust for `@nextcloud/l10n` v3.4.0

src/components/NcDateTimePicker/NcDateTimePicker.vue, src/components/NcIconSvgWrapper/NcIconSvgWrapper.vue, webpack.config.cjs
This adjusts the CSS import of the `NcDateTimePicker` vendor styles to not be scoped. I don't know if this is the proper way to handle this issue, so plead advise if not.
- Fixes https://github.com/nextcloud-libraries/nextcloud-vue/issues/7050#issuecomment-2978166946.
---|---
=> fix(NcDateTimePicker): correctly import library CSS

src/components/NcListItem/NcListItem.vue
- Similar to #7077 
- When component is unmonted, `$refs.name` is null and therefore can no longer be used
---|---
=> fix(NcListItem): correctly handle unmounting

src/components/NcAvatar/NcAvatar.vue
- Performance regression from: https://github.com/nextcloud-libraries/nextcloud-vue/pull/6749/
- It adds a mutation observer for every single NcAvatar to support theme change
- It is not a part of the PR "ensure only 64px or 512px avatars are loaded"
- It can be handled by NcThemeProvider for context theme change
=> perf(NcAvatar): ensure avatar does not add mutation observer

AUTHORS.md, CHANGELOG.md
=> chore: copy diff from stable8 changelog

src/components/NcInputField/NcInputField.vue
- Fix https://github.com/nextcloud-libraries/nextcloud-vue/issues/7133
Ensure that **all** browsers show **our** clear button instead of some non-themed clear button of the browser implementation. This only happened for search boxes.
🏚️ Before (firefox) | 🏚️ Before (chrome) | 🏡 After (all!)
---|---|---
=> fix(NcInputField): remove browser injected clear button

netlify.toml, package-lock.json, package.json
We already did this on the main branch and should also do it in the stable8 branch as it is still the supported branch.
- Consistent sorting
- Add author according to our contributors and consistent with other libraries
- Adjust supported node versions
=> [stable8] chore: align sorting of package.json

src/components/NcModal/NcModal.vue
- resolves https://github.com/nextcloud-libraries/nextcloud-vue/issues/7175
> Currently, the border radius is quite low and eg. the close button doesn't nest nicely within it.
> If I see it correctly, with 4px of padding around it, the outer radius should be 12px (8+4).
before | after
---|---
=> fix(NcModal): use `--border-radius-container`

src/composables/useIsDarkTheme/constants.ts, src/composables/useIsDarkTheme/index.ts
- Fix https://github.com/nextcloud-libraries/nextcloud-vue/pull/6764#discussion_r2217310037
Otherwise if no `NcThemeProvider` is used a runtime warning is shown in the dev tools console.
=> fix(useIsDarkTheme): provide default value to silence runtime warnings

src/components/NcAppSidebar/NcAppSidebar.vue
1. this probably was meant to center some icons within the button (22px sounds like it was the legacy 44px clickable area / 2).
2. but this breaks usage of any component within that slot.
Users of the component should rather self implement padding for their custom buttons if they need them
The problem:
=> fix(NcAppSidebar): remove slot styling for buttons in the description

CHANGELOG.md, package-lock.json, package.json
- The `usernameToColor` function is named exported instead of a default export.
This was done to have consistent export types.
* perf(NcAvatar): ensure avatar does not add mutation observer [#7157](https://github.com/nextcloud-libraries/nextcloud-vue/pull/7157) ([ShGKme](https://github.com/ShGKme))
* refactor(NcButton): remove redundant style [#7154](https://github.com/nextcloud-libraries/nextcloud-vue/pull/7154) ([skjnldsv](https://github.com/skjnldsv))
* fix(NcInputField): remove browser injected clear button [#7167](https://github.com/nextcloud-libraries/nextcloud-vue/pull/7167) ([susnux](https://github.com/susnux))
* fix(NcModal): use `--border-radius-container` [#7176](https://github.com/nextcloud-libraries/nextcloud-vue/pull/7176) ([susnux](https://github.com/susnux))
* …
=> chore: prepare release v9.0.0-rc.5

src/components/NcAvatar/NcAvatar.vue
- Add missing imports
- Regression from https://github.com/nextcloud-libraries/nextcloud-vue/pull/6749/
- <img width="473" height="166" alt="image" src="https://github.com/user-attachments/assets/1251eb9a-c74d-4dd6-9eca-8041f688828a" />
- Contacts menu is not opening
- Incorrect merge conflict resolving in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5158/
- Before | After
-- | --
- Remove redundant check on unsubscribing
- Missing backport from https://github.com/nextcloud-libraries/nextcloud-vue/pull/6780
- Do not execute a render function in a computed to check for an icon
- For Vue 3 migration
=> fix(NcAvatar): contacts menu is broken

src/components/NcActionInput/NcActionInput.vue
- Fix: https://github.com/nextcloud-libraries/nextcloud-vue/issues/7062
- Ref: https://github.com/nextcloud-libraries/nextcloud-vue/pull/4128
- Lazy load every child of `NcActionInput` with more than 50kB individual impact
- `vue` and `@nextcloud/*` libraries are not counted in the impact
| Part                     | Size, kb   |
| ------------------------ | ---------- |
| Self-size                | 10.19      |
| `NcDateTimePickerNative` | 🟩 13.25   |
| `NcTextField`            | 🟩 17.10   |
| `NcPasswordField`        | 🟩 22.23   |
| `NcSelect`               | 🟨 65.24   |
| `NcColorPicker`          | 🟨 76.54   |
| `NcDateTimePicker`       | 🟥 474.83  |
| **TOTAL**                | **543.46** |
---|---
543.46 kb | 65 kb
=> fix(NcActionInput): lazy load large children

src/components/NcButton/NcButton.vue
The correct type is the `RouteLocationRaw` which is a unresolved location - and will be resolved by the router when needed.
=> fix(NcButton): use correct type for `to` prop from VueRouter

src/components/NcContent/NcContent.vue
- Fix https://github.com/nextcloud/server/issues/48848
---|---
=> fix(NcContent): flip skip action image in rtl mode

CHANGELOG.md, src/components/NcColorPicker/NcColorPicker.vue
With #7080 we dropped the `update:open` event, but the usage of the component is different - as you can already see in the docs of it. We in-officially used the attributes passing to the underlying `NcPopover` for custom open state handling.
So instead of this we should revert that change and instead just implement it correctly by providing the 2-way binding for `open` (consistent props naming) - then we need to reverse the event removal and remove `close` (which is covered by `update:open` and for fully closed (transitions done) the proper (consistent) named event `closed`).
I would backport the `feat` commits to v8 for forward compatibility.
=> feat(NcColorPicker): add proper open-state handling

docs/app-containers.md, src/components/NcGuestContent/NcGuestContent.vue, styleguide.config.cjs
The current situation is a bit unclear, especially the guest container was not mentioned in the sidebar as a possible app container.
This PR has the goal to clarify that all apps should wrap their main view (component) within one of the app containers and provide a better discoverable list of them.
=> docs: clarify application containers and especially NcGuestContent

package.json
dependabot uses `corepack` for all updates of node dependencies. The problem here is that `corepack` breaks if the
`devEngines.packageManager` does not define a **full semantic version** meaning it does not support semantic ranges.
We can work around this by just using the array syntax with only one entry.
For reference the *corepack* bug report: https://github.com/nodejs/corepack/issues/729
=> chore: work around bug in `corepack` blocking dependency updates

src/components/NcBreadcrumb/NcBreadcrumb.vue
I am not sure how this was supposed to work, as it set a random attribute on the `li` tag - that was sometimes not even a valid HTML attribute name.
We can instead just use the ref to the li element directly.
=> fix(NcBreadCrumb): correctly pass container for `NcActions`

.github/workflows/server-styling-update.yml
Noticed this on https://github.com/nextcloud-libraries/nextcloud-vue/pull/7254
It was forgotten to also checkout the correct branch. This will then also set the correct base branch for the PR.
=> ci: use correct base branch when doing styling update on stable*

src/components/NcAvatar/NcAvatar.vue, src/components/NcUserStatusIcon/NcUserStatusIcon.vue
- Avatar has variable size
- The status icon also has a variable size (25% width)
- But the status icon still has a fixed position
- On different size avatar status has different position
- On a large avatar - too far from the avatar
- On a small avatar - outside of avatar box
- On some sizes - inside, but not in a perfect position
- Use cases
- Talk Desktop title bar (small avatar)
- Auto-complete (small avatar)
- Profile page (large avatar)
- Ref: https://github.com/nextcloud-libraries/nextcloud-vue/pull/5959
- Ref: https://github.com/nextcloud/spreed/pull/12956#pullrequestreview-2238732106
This PR makes the status icon:
- - 💫 **Orbital**: the status icon's center is positioned on the avatar circle
- - ⏹️ **Best-fit**: the status icon is as large as possible without exceeding the avatar …
=> fix(NcAvatar): orbital best-fit adaptive status icon 

build/l10n-plugin.mts, build/l10n-registration-implementation.js, build/translations.mts
Our files have names like `de_DE` but the BCP47 name is `de-DE` or `sr@latin` vs `sr-Latn`.
We need to adjust them as otherwise the language is not loaded when a language with region or script suffix is selected by the user.
This also fixed an issue where empty translations were not removed (`length > 0` vs `length > 1`), thus this also reduces the amount of bundled translations by 50% (because they were just empty).
Additionally split the injected code into a js file to make it lintable.
=> fix(l10n): correctly add languages to bundle

src/components/NcAppNavigationItem/NcAppNavigationItem.vue
This allows to have different icons if the current item is active or not. (We will use this to show the filled variant for active icons).
=> feat(NcAppNavigationItem): add `active` as slot property to the "icon"-slot

src/components/NcLoadingIcon/NcLoadingIcon.vue
- Fix flickering / height jumping when loading icon has position: static
- Although wrapping span has a consistent width/height from props.size, rotating svg is constantly changing it dimensions:
- Reproducible by checking `element.getBoundingClientRect()` or hovering over DOM element in inspector
- overflow: hidden should ignore parts that are standing out. Since spinner is round, shouldn't affect the appearance
=> fix(NcLoadingIcon): prevent height change from rotate transformation

src/components/NcAppNavigation/NcAppNavigation.vue, src/components/NcAppNavigationSearch/NcAppNavigationSearch.vue, src/components/NcDateTimePicker/NcDateTimePicker.vue, src/components/NcDialog/NcDialog.vue, src/components/NcHeaderMenu/NcHeaderMenu.vue, src/components/NcInputField/NcInputField.vue, src/components/NcPasswordField/NcPasswordField.vue, src/components/NcTextField/NcTextField.vue
Vue warns in some edge cases when a ref in a component instance and template ref key string have the same name.
- Ref: https://github.com/vuejs/core/issues/12852
- Fix https://github.com/nextcloud-libraries/nextcloud-vue/issues/7238
=> fix: `Set operation on key "value" failed: target is readonly`

src/components/NcButton/NcButton.vue, src/components/NcNoteCard/NcNoteCard.vue, src/components/NcSavingIndicatorIcon/NcSavingIndicatorIcon.vue, src/components/NcTextArea/NcTextArea.vue
- for https://github.com/nextcloud/server/pull/54439
=> refactor(NcButton, NcNoteCard): use status text color for icons and text

src/components/NcColorPicker/NcColorPicker.vue
This is somehow already resolved on main branch.
But here if no value is passed it will fail with `null cannot be iterated`.
=> [stable8] fix(NcColorPicker): fallback to zero color if no current color is set

CHANGELOG.md, package-lock.json, package.json
* The package has dropped compatibility with Nextcloud before version 32.
This mostly affects the visual appearance of components.
- `NcButton` now does no longer has `role="button"` when used as a link (passing the `href` prop or a router link (`to`)).
Instead, for accessibility and semantical correctness, has the `link` role.
- `NcColorPicker`
- The deprecated `close` event was removed in favor of the `closed` event, this was done for consistent event names.
* fix(NcDateTimePicker): adjust input padding inline end [#7208](https://github.com/nextcloud-libraries/nextcloud-vue/pull/7208) ([raimund-schluessler](https://github.com/raimund-schluessler))
* feat(NcColorPicker): add proper open-state handling [#7212](https://github.com/nextcloud-libraries/nextcloud-vue/pull/7212) …
=> chore: v9.0.0-rc.6

src/components/NcEmojiPicker/NcEmojiPicker.vue
- Missed styles scoping
- No real issue at the moment — just to prevent issues in the future
- Using the same approach as in https://github.com/nextcloud-libraries/nextcloud-vue/pull/7051
=> fix(NcEmojiPicker): scope styles

src/components/NcDateTimePicker/NcDateTimePicker.vue, src/components/NcDateTimePicker/index.js
- Regression from https://github.com/nextcloud-libraries/nextcloud-vue/pull/7195
- Styles are not loaded
- I haven't found an app where the issue is reproducable. Either webpack or vue-styleguidist issue.
- So, might be only in docs
---|---
=> [stable8] fix(NcDateTimePicker): lost styles in docs

src/components/NcAppNavigation/NcAppNavigation.vue
- Fix https://github.com/nextcloud-libraries/nextcloud-vue/issues/4937
We cannot make it required - as it could also be the labelled by variant - but we can check this.
=> fix(NcAppNavigation): warn if neither `ariaLabel` nor `ariaLabelledby` is set

build/l10n-registration-implementation.js, src/components/NcSelectTags/api.js
Those were warnings for ESLint so added proper comments (the missing types - as this is JavaScript).
=> chore: add missing docblock comments

src/components/NcButton/NcButton.vue
For Vue a prop defined as `prop?: boolean` means that `prop` is a boolean property with default `false`. But in this case we have a tri-state value: either pressed (a boolean) or undefined. So to allow such a prop to have the default value `undefined` instead of `false` we need to explicitly type it as `prop?: boolean | undefined`.
=> refactor(NcButton): use proper prop type for `pressed` to allow `undefined`

l10n/messages.pot, src/components/NcAppNavigationSearch/NcAppNavigationSearch.vue, src/components/NcHeaderButton/NcHeaderButton.vue, src/components/NcHeaderMenu/NcHeaderMenu.vue
- Added non-breaking space following:
- https://docs.nextcloud.com/server/latest/developer_manual/basics/translations.html#dos-and-don-ts
- https://github.com/nextcloud/server/wiki/Translation-knowledge-(valid-for-whole-nextcloud-project)/d45f1d248fdc6b1509337ebb0017653649a8f440#ellipsis
=> fix(NcAppNavigationSearch): add space before ellipsis

src/components/NcHeaderMenu/NcHeaderMenu.vue
- Fix #5385
- Fix https://github.com/nextcloud/spreed/issues/13062
With `is-nav` prop NcHeaderMenu doesn't start a focus-trap and therefore doesn't pause existing ones. That prevents any click in mobile state, as focus returned to AppNavigation
Alternatives for NcAppNavigation:
- release focus-trap on click outside
- toggle component to closed state on click outside
🏡 After (cherry-picked to stable8 + applied to server repo)
https://github.com/user-attachments/assets/b2e8cd28-edbb-4ea2-ad40-104c55cf86db
=> fix(NcHeaderMenu): pause trap stack on opening

webpack.config.cjs
- Continue of https://github.com/nextcloud-libraries/nextcloud-vue/pull/7331
- `namedExport` changed the default value of `exportLocalsConvention`, forcing all class names to be `camelCase`
=> chore(docs): fix css modules export names in styleguidist

src/assets/status-icons/user-status-away.svg, src/assets/status-icons/user-status-busy.svg, src/assets/status-icons/user-status-dnd.svg, src/assets/status-icons/user-status-invisible.svg, src/assets/status-icons/user-status-online.svg, src/components/NcUserStatusIcon/NcUserStatusIcon.vue
- Fix user status icon colors to be independent from server-defined pallete
```css
--color-icon-online: #2D7B41;
--color-icon-busy: #DB0606;
--color-icon-away: #C88800;
--color-icon-offline: #6B6B6B;
```
_Colors are hardcoded to SVG as a fallback, to see them in IDE and on Guthub_
=> fix(NcUserStatusIcon): adjust icon colors

src/components/NcAppNavigationSettings/NcAppNavigationSettings.vue
* follow up on https://github.com/nextcloud-libraries/nextcloud-vue/pull/7299
`nextcloud-vue` v9 still supports Nextcloud 31 thus we need to keep compatibility with the filled icons.
=> fix(NcAppNavigationSettings): bring back filled icon for Nextcloud 31

CHANGELOG.md, package-lock.json, package.json
* fix(NcUserStatusIcon): legacy 32 check by @skjnldsv in https://github.com/nextcloud-libraries/nextcloud-vue/pull/7320
* [stable8] fix(NcDateTimePicker): lost styles in docs by @ShGKme in https://github.com/nextcloud-libraries/nextcloud-vue/pull/7344
* [stable8] fix(NcPopover): scope styles to avoid leak by @backportbot[bot] in https://github.com/nextcloud-libraries/nextcloud-vue/pull/7341
* [stable8] fix(NcReferencePickerModal): scope styles by @backportbot[bot] in https://github.com/nextcloud-libraries/nextcloud-vue/pull/7347
* [stable8] fix(NcEmojiPicker): scope styles by @backportbot[bot] in https://github.com/nextcloud-libraries/nextcloud-vue/pull/7343
* [stable8] fix(NcActionButtonGroup): scope styles by @backportbot[bot] in …
=> [stable8] chore: v8.29.2

src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
=> fix(NcCheckboxRadioSwitch): Remove some leftover

src/components/NcActions/NcActions.vue, src/components/NcPopover/NcPopover.vue
* Fix #5141
---|---
B | A
- Useful when there is a custom focus control, like in `NcActions`
=> feat(NcPopover): auto return focus to trigger button on close

src/components/NcAssistantIcon/NcAssistantIcon.vue
- Companion to https://github.com/nextcloud/server/pull/54789
- For https://github.com/nextcloud/server/issues/54782
B | A
-- | --
See styleguide preview.
=> fix(NcAssistantIcon): adjust gradient for dark theme

src/components/NcPopover/NcPopover.vue
Function was renamed in
https://github.com/nextcloud-libraries/nextcloud-vue/pull/5155/commits/2ce15eb24b6b3304873399f2ee692acd4182474c#diff-0fd4de7746b137eb9b3ba7251f8c3bd9c9a066a802240c7a6bc993655ae0562fR335
=> [stable8] fix(NcPopover): regression with `this.getPopoverTriggerContainerElement is not a function`

src/components/NcCheckboxRadioSwitch/NcCheckboxContent.vue
- Fix regression from #7378
- By styleguidist, doesn't seem to affect other demo examples
- stable doesn't look affected as well
---|---
=> fix(NcCheckboxContent): limit wrapper width

src/components/NcCheckboxRadioSwitch/NcCheckboxContent.vue
When there is no visual label the checkbox / radio should be square.
---|---
=> fix(NcCheckboxRadioSwitch): ensure label less radio has proper size

src/components/NcActions/NcActions.vue, src/components/NcPopover/NcPopover.vue
- On top of: https://github.com/nextcloud-libraries/nextcloud-vue/pull/7524
- Keeping boolean props `false` by default
=> feat(NcPopover): replace `closeOnClickOutside` with `noCloseOnClickOutside`

src/components/NcAvatar/NcAvatar.vue
- Gets insights into <img width="1167" height="122" alt="image" src="https://github.com/user-attachments/assets/1f50e4e6-b620-445a-814a-3139bd3cf875" />
---|---
n/a | n/a
=> [stable8] fix(NcAvatar): log error and URL on error

CHANGELOG.md, package-lock.json, package.json
* resolves #6106 
Since we are hitting final RC of Nextcloud 32 we need to stabilize the library as also some shipped apps with make use of it and thus it must no longer include new breaking changes.
* feat(NcColorPicker): allow to clear selected value by @susnux in https://github.com/nextcloud-libraries/nextcloud-vue/pull/7363
* feat(NcPopover): replace `closeOnClickOutside` with `noCloseOnClickOutside` by @ShGKme in https://github.com/nextcloud-libraries/nextcloud-vue/pull/7525
* fix(useHotKey): use correct callback type by @susnux in https://github.com/nextcloud-libraries/nextcloud-vue/pull/7505
* perf(NcTimezonePicker): use Intl to reduce self-size from 206kb to 2kb  by @ShGKme in https://github.com/nextcloud-libraries/nextcloud-vue/pull/7522
* fix(NcPopover): revert disabling close …
=> chore: prepare stable release of v9.0.0

src/components/NcAppContent/NcAppContent.vue, src/components/NcButton/NcButton.vue, src/components/NcCollectionList/NcCollectionList.vue, src/components/NcDateTimePicker/NcDateTimePicker.vue, src/components/NcPopover/NcPopover.vue, src/components/NcRelatedResourcesPanel/NcRelatedResourcesPanel.vue, src/components/NcRelatedResourcesPanel/NcTeamResources.vue, src/components/NcRichContenteditable/NcRichContenteditable.vue, src/components/NcRichText/NcReferenceList.vue, src/components/NcRichText/NcReferencePicker/NcRawLinkInput.vue, src/components/NcSelectTags/NcSelectTags.vue, src/components/NcSelectTags/api.js, src/mixins/userStatus.js
- Fixes regressions of https://github.com/nextcloud-libraries/nextcloud-vue/pull/7418/commits/2ab8af7d619fe855531c82eb2d9ba0cd5db47e20
The logger behaves slightly different than console.*. It takes an object as second parameter for the logging context (similar to our server-side logger).
---|---
B | A
=> [stable8] fix(console): fix log context object

src/components/NcAppContent/NcAppContent.vue
☑️ Resolves
Previously if changing the pane config key the settings of the pane would not update automatically, now they do.
=> [stable8] fix(NcAppContent): add reactivity to pane config key 

CHANGELOG.md, package-lock.json, package.json
* feat(NcColorPicker): allow to clear selected value [\#7531](https://github.com/nextcloud-libraries/nextcloud-vue/pull/7531)
* feat(NcModal): add new `closeButtonOutside` prop and deprecated `closeButtonContained` [\#7553](https://github.com/nextcloud-libraries/nextcloud-vue/pull/7553) \([Antreesy](https://github.com/Antreesy)\)
* fix(useHotKey): use correct callback type [\#7511](https://github.com/nextcloud-libraries/nextcloud-vue/pull/7511)
* fix(NcRadioGroupButton): adjust hight if needed [\#7554](https://github.com/nextcloud-libraries/nextcloud-vue/pull/7554)
* fix(NcAvatar): log error and URL on error [\#7561](https://github.com/nextcloud-libraries/nextcloud-vue/pull/7561) \([ChristophWurst](https://github.com/ChristophWurst)\)
* fix(console): fix log context object …
=> chore: prepare release of v8.32.0

src/components/NcInputField/NcInputField.vue
If there is no placeholder we need still at least an empty string to make the label animation with `:placeholder-shown` work.
=> fix(NcInputField): use empty string to fix label position
