nextcloud-libraries/nextcloud-vue

webpack.dev.js

This is required in order to `npm link` this package to other apps while `npm watch`'ing it.
Ref https://webpack.js.org/configuration/devtool/.

Fix a webpack devtool that works without unsave-eval CSP

---

package.json
src/components/Avatar/Avatar.vue
src/components/Avatar/index.js
src/components/Avatar/uidToColor.js
src/components/PopoverMenu/PopoverMenuItem.vue

Fixes #14 
Example usage:
```
<avatar user="admin" displayName="Julius" />
<avatar user="anexistinguser" displayName="An existing user" />
<avatar :url="url" />
<avatar user="nonexistinguser" />
```

Add avatar component with contacts menu

---

.eslintrc.js
src/components/AppNavigation/AppNavigationItem.vue
src/components/Avatar/Avatar.vue
src/components/Multiselect/index.js
src/components/Multiselect/index.scss
src/utils/ScopeComponent.js
src/utils/ScopeElement.js
webpack.common.js

Fix #30 
``` js
/**
* Manually scope a vue component to be used with an external css file
* The external css must have the root element set with [data-v-#{$scope_version}]
* 
* e.g. .multiselect[data-v-#{$scope_version}]
* import ScopeComponent from 'Utils/ScopeComponent'
* import Multiselect from 'vue-multiselect'
* import './index.scss'
* ScopeComponent(Multiselect)
* 
* @param {Object} Component the vue component
*/
```

Multiselect style and manual scoping

---

src/components/Avatar/Avatar.vue

New try: 
I had some problems because the user of a user row was loaded asynchronous after the mounting of Avatar and so the avatar didn't get updated. Adding a watch to the username and moving the code from the mounted to a method did the job.
Additionally I got some problems, when creating an avatar for a group, which name was identically to a user's name. I added a prop to declare the user name ist not regarding a user.
I hope, I found a right way to solve the problems.

Adding avatar updates after user change and group support

---

src/components/Multiselect/AvatarSelectOption.vue
src/components/Multiselect/Multiselect.vue
src/components/Multiselect/index.js
src/components/Multiselect/index.scss

After #70 
Fix #91
Default style
``` html
<Multiselect :options="options" v-model="select" />
```
Default style multiple with auto width calculation (default option width is 150px)
You can set the min with `:tag-width="80"`
``` html
<Multiselect :options="options" v-model="select" :multiple="true" />`
```
Disable auto width calculation (always show max XXX entries)
``` html
<Multiselect :options="options" v-model="select" :multiple="true" :auto-limit="false" :limit="XXX" />`
```
Avatar select option
``` html
<Multiselect :options="options" v-model="select" label="displayName" track-by="user" :multiple="true" :user-select="true" />`
```

Wrap Multiselect

---

src/components/AppNavigation/AppNavigation.vue

Just see the template, the default has a (wrong? outdated?) structure.

Fix default items for app navigation

---

src/components/Action/Action.vue

This makes it possible to use the action component in the content list
without triggering the underlying router link handler.
Any other event handlers that rely on the propagated event still work this way.

Fix propagation of handled click event in action component

---

src/components/PopoverMenu/PopoverMenuItem.vue

This PR adds support for having an longtext and text property set besides each other in a popovermenu item.

PopoverMenu: Allow having longtext besides text item property

---

src/components/Multiselect/Multiselect.vue
src/components/Multiselect/index.scss

1. Added the support of two slots:
- option (only if `user-select` is false (since we override the option slot)
- singleLabel
2. fixed styling.
- now min-width is 160px, not the width. Adapt it to your design.
- padding fixes
- implemented the loading state like so:
- select icon switched to a triangle on single selects
@nextcloud/vue 
|![capture d ecran_2018-11-22_15-24-00](https://user-images.githubusercontent.com/14975046/48909555-e4aa1d80-ee6d-11e8-805f-6961618727f5.png)|![capture d ecran_2018-11-22_15-23-23](https://user-images.githubusercontent.com/14975046/48909560-e70c7780-ee6d-11e8-97d1-10dd940751d8.png)|

Multiselect padding loading

---

src/components/Multiselect/index.scss

- Border radius fixes
- Padding increase
- Removed triangle on single select
|![capture d ecran_2018-12-03_18-16-36](https://user-images.githubusercontent.com/14975046/49390111-4ac55900-f728-11e8-89b6-1659222bd686.png)|![capture d ecran_2018-12-03_18-17-35](https://user-images.githubusercontent.com/14975046/49390112-4ac55900-f728-11e8-8588-2ee8e77da3aa.png)|
|![capture d ecran_2018-12-03_18-19-44](https://user-images.githubusercontent.com/14975046/49390090-3ed99700-f728-11e8-893e-b98020af00ab.png)|![capture d ecran_2018-12-03_18-19-16](https://user-images.githubusercontent.com/14975046/49390093-40a35a80-f728-11e8-97d3-a06c4fcc5253.png)|
@jancborchardt I did not removed the user icon as this is actually a standard (you can use any icon you want …

Multiselect fixes

---

src/assets/arrow-left-double.svg
src/assets/arrow-left.svg
src/assets/arrow-right-double.svg
src/assets/arrow-right.svg
src/components/DatetimePicker/DatetimePicker.vue
src/components/DatetimePicker/index.scss

I dropped the use of the distant design because we had some conflict and I hate having to override design. Building our own is far better.
What I did:
1. copied the original style
2. cleaned it up
3. integrated our previous changes to it
4. increased the sizes of the buttons
5. used flex for better visual and reactivity
6. removed old buttons style so we can use nextcloud default
I took the liberty to properly implement the range picker. Even if nowhere else we use it YET, I think it looks very nice now.
This is the first step so we can then check the dark theme (we had some conflict before)
@nextcloud/designers @nextcloud/vue Any requests?
|![peek 06-12-2018 19-01-old](https://user-images.githubusercontent.com/14975046/49603092-9119f280-f98a-11e8- …

Do not use default datepicker css

---

src/components/AppContent/AppContent.vue
src/components/AppContent/index.js

This is a minimal implementation of our generic app content component, following https://docs.nextcloud.com/server/15/developer_manual/design/content.html.

Add standardized app content component

---

src/components/AppNavigationItem/AppNavigationItem.vue

This is on collapsible items in `AppNavigationItem`.
Currently, you can open a collapsible item by clicking on the triangle icon, only. With this PR, I'm introducing a default (simple) action which allows for toggling collapse state by clicking on the item's label, too. This action is only active, if there is no (other) action defined by the developer.

toggleCollapse as default action for collapsible

---

src/components/Action/Action.vue

`tabindex="1"` does not mean what you think. :wink: 
From https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex:
> - A negative value (usually `tabindex="-1"`) means that the element […] should not be reachable via sequential keyboard navigation. […]
> - `tabindex="0"` means that the element should be focusable in sequential keyboard navigation […]
> - It is not recommended to give positive values to your elements. You will end up jumping between them, and it will be confusing to manipulate between your element's tabindex attribute values. Instead, focus on writing them in a suitable DOM sequence.
So what you are looking for here is `tabindex="0"` instead. The current component resulted in any app (like the Mail app) breaking the tabbability in that it started with …

Fix action component breaking global tabbability

---

src/components/Modal/Modal.vue
src/components/Modal/index.js

Closes #210 
Okay, so I did not wanted to implement anything more because I felt that it was the app's problem to handle this:
- transitions: the modal can be use without pagination
- closing: the app should manage if the component exists or not and if it's visible
- I emit an event for each action possible (next, prev and close) and forward the event data to the parent. Do whatever you want with it :)
- Just put whatever html/component you want inside this one, the slot will manage the rest.
1. ~~Should we rely on the modal component for the show/hide zoom animation? We could do that with the beforeMount/beforeDestroy stuff as well :)~~
2. We NEED to find a solution for the translation
3. ~~the app-content  have a z-index of 1000 so it means that the modal cannot be above the header …

Modal component init

---

src/components/Avatar/Avatar.vue
src/components/Multiselect/Multiselect.vue
src/directives/Tooltip/index.js
src/directives/Tooltip/index.scss
src/directives/index.js
webpack.common.js

Implements #248 
This allows apps to use the tooltip directive included in the nextcloud-vue bundle without needing to add another v-tooltip to their bundle.

Add Tooltip directive

---

src/components/Modal/Modal.vue

- Do not emit if there is no previous or next action available
- Do not set a default width, let's leave that to the content width

Fix modal default width and previous/next event emit

---

Makefile
package.json
webpack.common.js

With this components can be imported individually and webpack can take care of just including the required code parts. 
```
import Avatar from 'nextcloud-vue/dist/Components/Avatar'
import Tooltip from 'nextcloud-vue/dist/Directives/Tooltip'
```
Unfortunately I'm not sure how compatible this is when an app doesn't use webpack, still needs some testing.
I had to remove the chunking since it didn't work properly when including it in another webpack bundle of an app, but with the current state, webpack seems to be able to deduplicate some parts of the code, even if both the full bundle and indivudal components are included at the same time.

Build separate entrypoints for each component

---

src/components/Action/Action.vue

Required for https://github.com/nextcloud/server/pull/14392.
This makes it possible to open/close the menu from the outside while also staying in sync with the internal state. This also still works without the property, just like it did before.
Usage:
```html
<Action v-if="!token.current"
:actions="actions"
v-bind:open.sync="actionOpen">
```
@skjnldsv as discussed :)

Add a two-way prop 'open' to the action component

---

src/components/Modal/Modal.vue

When clicking the next/prev buttons without moving the mouse, the event was not caught and therefore the ui was fading away despite having the user clicking the screen.

Do not hide on touchmove and click too

---

src/components/AppNavigation/AppNavigation.vue
src/components/AppNavigation/index.js
src/components/AppNavigationSpacer/AppNavigationSpacer.vue
src/components/AppNavigationSpacer/index.js
src/components/index.js

This makes it a lot easier for apps to create their own reusable navigation component.
Without this change, using an own component to make the navigation slot contents reusable resulted in an extra element wrapping the contents. This can easily break the design. I think the clean version is to just have a dedicated component as we have for many other things now.

Make the app navigation (slot) a real component and add a spacer

---

src/components/Modal/Modal.vue

I'm not sure about this, it seems a good thing to do to avoid the content to go over the header content, but in the end i might look a bit shifted to the bottom. Any thoughts?

Prevent modal to go over the title

---

src/components/AppNavigation/AppNavigation.vue

Component: `AppNavigation`
The property `navigationClass` is not needed anymore due to moving the app navigation element to it's own component. You can use `:class`, directly:
```
<app-navigation :class="{loading: loading}"> ... </app-navigation>
```
see https://github.com/nextcloud/nextcloud-vue/pull/290#discussion_r263565344

remove obsolete prop 'navigationClass'

---

src/components/Modal/Modal.vue

- Fix background
- Fix hiding transition not working with v-visible. I now override the display:none used by vue and use visibility instead (which preserve the current animation state, e.g not resetting the circle progress)
(animation is slowed up for the gif visibility purpose)

Fix header transition animation and circle reset on clear view

---

src/components/Modal/Modal.vue

- Put the arrows to flex next to the container so we can have an adaptive positioning
- Reworked the layout of the `full` size so that the arrows are absolute and over the container
Layouts:
| Normal | ![Capture d’écran_2019-03-20_10-33-10](https://user-images.githubusercontent.com/14975046/54674039-df976b00-4afb-11e9-97a7-13d6e5491f33.png) |
| Large | ![Capture d’écran_2019-03-20_10-34-08](https://user-images.githubusercontent.com/14975046/54674041-df976b00-4afb-11e9-9adb-b1d3d2880881.png) |
| Full (mobile mode) | ![Capture d’écran_2019-03-20_10-34-55](https://user-images.githubusercontent.com/14975046/54674043-df976b00-4afb-11e9-9efa-79f1595e4337.png) |

Rework the modal sizes and layout

---

src/components/AppNavigationItem/AppNavigationItem.vue

Supports both `action` and `href` in the same code snippet. However, this required a new JS-helper-method `callPreventStop` which stops the links to be processed if there is an action given.
This was done in the context of #246, which is now obsolete.

AppNavigationItem: remove duplicate code

---

src/components/AppNavigationItem/AppNavigationItem.vue

Implements the idea of #278 for the component AppNavigationItem.
Example usage: https://github.com/nextcloud/notes/pull/290/commits/d4b7c439d01e5a66d11b7129d954369500f08de1
Closes #309.

AppNavigationItem: sync property for menu's open state

---

src/components/Modal/Modal.vue

We should also prevent the events to be fired if it's disabled... :see_no_evil: 
See #322

Prevent close if disabled

---

src/components/Modal/Modal.vue

That way, if any app uses it into a child element that is within #app-content, it will still be displayed above all the UI like any other modal! :grin: 
:tada:

Force all modals to mount in body

---

src/components/AppContent/AppContent.vue
src/components/AppContent/index.js
src/components/index.js

This makes our component design a bit more aligned with the AppNavigation added in #290 (sidebar will follow shortly).
Apps can use this component to wrap their content elements. Without this change, they have to use a wrapping element (e.g. div) if they want to extract the content to a component (happened to Mail recently).

Add a component for #app-content

---

src/components/Multiselect/index.scss

It was ignored because of a css rule with bigger impact

Fix add icon when tagging in multiselect

---

src/components/Action/Action.vue
src/components/PopoverMenu/PopoverMenuItem.vue

See aria guidelines https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20161214/examples/menu-button/menu-button-1/menu-button-1.html
Added:
- visual feedback on the menu
- can navigate through popovermenu with up/down pageUp/pageDown tab/shiftTab
- can close popovermenu with escape
- can open popovermenu with space and enter
Missing?
- A-Z navigation
- `tabindex="-1"` on all menu items
@nextcloud/accessibility @nextcloud/vue thoughts and reviews? :heart:

Action and popovermenu accessibility

---

src/components/AppNavigationSettings/AppNavigationSettings.vue
src/components/AppSidebar/AppSidebar.vue
src/components/AppSidebarTab/AppSidebarTab.vue
src/components/AppSidebarTab/index.js
src/components/index.js

@nextcloud/vue 
Closes https://github.com/nextcloud/server/issues/10289
Standardisation is minimal but looks very nice and allow quite a few specificity that looks really great!
| 1 | 2 |
|:------:|:-----:|
|![dev skjnldsv com_apps_vueexample_](https://user-images.githubusercontent.com/14975046/55719337-4377ca00-59fe-11e9-9457-6a4e0dbb82a7.png)|![dev skjnldsv com_apps_vueexample_ (2)](https://user-images.githubusercontent.com/14975046/55719241-13302b80-59fe-11e9-99ba-3009e5014b21.png)|
``` vue
<app-sidebar v-show="show"
title="andy-yeo-1387151-unsplash.jpg"
subtitle="4,3 MB, last edited 19 days ago"
background="/core/preview?fileId=54&x=1880&y=993&a=true"
:actions="menu"
:tabs="tabs"
@close="closeSidebar">
<template #primary-action>
<button class="primary">Leave call</button>
</template> …
```

Implement sidebar component

---

src/components/AppNavigationSettings/AppNavigationSettings.vue

Thanks for adding the transition, @skjnldsv !
There are three things I would like to improve:

improve AppNavigationSettings slide-up transition

---

src/components/AppSidebar/AppSidebar.vue

The close button wasn't functional, because the header was on a layer on top of the button.

AppSidebar: fix sidebar close button

---

src/assets/variables.scss
src/components/Action/Action.vue
src/components/PopoverMenu/PopoverMenu.vue
src/components/PopoverMenu/PopoverMenuItem.vue
webpack.common.js

We should really change the way we do things here
We should split each action type into its own component.
QUESTIONS @nextcloud/vue :
- shall we move out from using actions objects and use slots with real components?
I feel like it would be muuuuch cleaner
```vue
<action>
<action-button :class="icon-add">Add thing</action-button>
<action-input :class="icon-user" @submit="onSubmit" @input="onInput"></action-input>
<action>
```

Center popoverby default and implement popovermenu variables

---

src/components/AppSidebar/AppSidebar.vue

There was an error when a `AppSidebar` doesn't contain any `AppSidebarTab`s and uses just the content directly.
See https://github.com/nextcloud/nextcloud-vue/pull/340#issuecomment-484798872

AppSidebar. fix error when no tabs

---

src/components/AppSidebar/AppSidebar.vue

Let the app show that the starred property is currently changed/saved/....
Example usage:
```
<AppSidebar [...] :star-loading="loading.favorite">
```

AppSidebar: Add loading property for starred icon

---

src/components/AppNavigationItem/AppNavigationItem.vue

With this, the parent component has full control over the open state of a collapsible item. See also #180.
Please note: `item.opened` is not used anymore. Hence, this is a breaking change!

AppNavigationItem: synced prop for open state

---

src/components/Actions/Actions.vue
src/mixins/actionGlobal.js

@nextcloud/vue 
Trim text and prevent action to be shown if there is no valid children :)
Also fix the default background to a translucent one.
|![Capture d’écran_2019-05-13_14-32-24](https://user-images.githubusercontent.com/14975046/57621594-251c6580-758c-11e9-8256-ad9aed0ab062.png)|![Capture d’écran_2019-05-13_14-27-04](https://user-images.githubusercontent.com/14975046/57621593-251c6580-758c-11e9-9708-f37f3371d8bb.png)|

Fix Actions empty display and text length

---

src/components/DatetimePicker/DatetimePicker.vue

See https://github.com/nextcloud/nextcloud-vue/issues/137#issuecomment-481667668
Closes #137
@nextcloud/vue

Trigger value save on year/month select

---

src/components/AppContentDetails/AppContentDetails.vue
src/components/AppContentDetails/index.js
src/components/AppContentList/AppContentList.vue
src/components/AppContentList/index.js
src/components/index.js

Implements
* https://docs.nextcloud.com/server/stable/developer_manual/design/content.html
* https://docs.nextcloud.com/server/stable/developer_manual/design/list.html (without the actual items, they will follow later)
These components were extracted from Mail. This is the bare minimum of functionality you would need.
<details>
Follow-up tasks:
- Find a common way to handle empty content lists (special `emtpy` slot, switched with prop?)
- Find a common way to display "new" items are available in a list. Maybe too specific, but we need that for mail
- Find (and hopefully enforce) a decent animation for new/removed items in the details list
- Find a common design for the details, e.g. to show a header that somewhat looks the same across all apps (with arbitrary content, of course -> slot?) …

Add AppContentList and AppContentDetails components

---

src/components/Multiselect/index.scss

When there is tags already the absolute positionned input is sent to the right.
And the click is not possible
Fix #431

Fix ie position of the multiselect input

---

src/components/AppContent/AppContent.vue

The component `AppContent` uses HammerJS for providing swipe gestures for hiding/showing the app navigation. This is only useful for (small) mobile screens, since on large screens, the app navigation is always visible.
However, HammerJS disables the user's possibility to select some text (CSS `user-select: none`) by default, which may not be intended for Nextcloud apps (i.e., it is not intended for the notes app [preview mode]).
There is a paragraph on http://hammerjs.github.io/tips/ about this:
> **“I can’t select my text anymore!”**
> Hammer is setting a property to improve the UX of the panning on desktop. Regularly, the desktop browser would select the text while you drag over the page. The `user-select` css property disables this.
> If you care about the text-selection and not so …

don't disable user-select

---

src/components/AppSidebar/AppSidebar.vue

There are two use-cases for `AppSidebar`:
1. slot contains one or more `AppSidebarTab`(s) => use tabs
2. slot contains custom element(s) => don't use tabs
With this PR, it is checked if one of those use-cases is used. It gives a warning, if they are mixed.

AppSidebar: fix tab validation: tabs are optional

---

src/components/AppSidebar/AppSidebar.vue

Reverts nextcloud/nextcloud-vue#445

Revert "AppSidebar: fix tab validation: tabs are optional"

---

src/components/Modal/Modal.vue

For https://github.com/nextcloud/server/issues/16076
> "Play" should be called "Start slideshow"

Rename slideshow play/pause

---

src/components/AppSidebar/AppSidebar.vue

Allow to trigger a ytab refresh from the parent
You can use `ref="sidebar"` and then `this.$refs.sidebar.updateTabs()` from the parent :)
I don't think we can watch over changed childrens. The `updated` method is triggered far too many times for other changes than $children change. :man_shrugging:

Add updateTabs function to appSidebar

---

src/components/ActionInput/ActionInput.vue

Was triggered even if the item was on the middle as any li could have been a far parent of the menu

Fix actionInput margins

---

src/components/Actions/Actions.vue

Fix #410 
That way, if the actions popover is the blocker for the content height, it would look better than this
|![dev skjnldsv com_settings_user_security (1)](https://user-images.githubusercontent.com/14975046/58160205-4eb94900-7c7e-11e9-87dd-c5d866b457d8.png)|![dev skjnldsv com_settings_user_security (2)](https://user-images.githubusercontent.com/14975046/58160206-4eb94900-7c7e-11e9-86da-201b4050165c.png)|

Add actions menu margin

---

src/components/ActionCheckbox/ActionCheckbox.vue
src/components/ActionTextEditable/ActionTextEditable.vue
src/components/ActionTextEditable/index.js
src/components/Actions/Actions.vue
src/components/AppNavigationCounter/AppNavigationCounter.vue
src/components/DatetimePicker/index.scss
src/components/index.js

|ActionTextEditable|ActionTextEditable with title|ActionInput type date|
|:--:|:--:|:--:|
|![Capture d’écran_2019-07-11_22-42-45](https://user-images.githubusercontent.com/14975046/61084032-6c5c9080-a42d-11e9-8b67-92c3c49e4aee.png)|![Capture d’écran_2019-07-11_22-43-41](https://user-images.githubusercontent.com/14975046/61084033-6c5c9080-a42d-11e9-8a49-8fc50c5ebd5b.png)|![Capture d’écran_2019-07-12_10-56-35](https://user-images.githubusercontent.com/14975046/61115868-bbd5a780-a493-11e9-9bb5-ea9c7ec0e347.png)|
- Design fixes
- Added `@check` and `@uncheck` event for the checkbox to speed up any integration and remove the need to implement the handlers ourselves in our apps :)

Add Datepicker to ActionInput and ActionTextEditable + design fixes and more checkbox events

---

src/components/ActionInput/ActionInput.vue

``` vue
<ActionInput
:value="share.expireDate"
icon="icon-calendar-dark"
type="date"
:not-before="new Date()" />
```

Allow to bind attributes to the ActionInput timepicker if present

---

src/components/ActionButton/ActionButton.vue
src/components/ActionCheckbox/ActionCheckbox.vue

Issue #500 :tada: 
- add value prop
- fix padding right being overrided by the previous line of padding: 0. 
this is here because of the too specific css rule in the settings: https://github.com/nextcloud/server/commit/8fb788570c449a76b4a2fdfb59842879d82e3fc9#diff-bf0066932907b556b49ffe55b209a501R615

Also allow value on checkbox

---

src/components/Actions/Actions.vue

Before we removed the focus to make sure we did not conflicted between the mouse and the keyboard navigation. But if you had a focus on an input and moving your mouse, you were losing the focus and had to click again, this is not good :)
Now we focus the nearest item and ignore if it is the currently focused item already :wink:

Focus proper action on mouse move instead of removing focus

---

src/components/Multiselect/EllipsisedOption.vue

When you are tagging a new option (users management, add new group) it happens. :man_shrugging:

Fix Cannot read property 'length' of undefined on truncated entry - multiselect

---

src/components/Actions/Actions.vue

Before that change both the .action-item as well as the .action-item__menutoggle elements had a background color defined, which leaded to a slightly different background color for the menu toggle compared to single action items.
Before:
After:

Fix duplicate bakground color on action menu toggle

---

src/components/AppSidebarTab/AppSidebarTab.vue

The AppSidebar component already checks for the order value, but the AppSidebarTab doesn't provide one, so this PR adds it as a property to easily provide an order that is different from the naturalSortCompare of the names.

Allow to provide an order for sidebar tabs

---

src/components/Actions/Actions.vue
src/utils/ValidateSlot.js

- Slow performances because all menus are hidden with v-show: switching to v-if
- We were using `$children`, so v-if don't display anything and since we create `this.actions` from `$children`, it was empty: now using `$slots.default` as the array is filled regardless of the template being shown or not.

Fix actions events and performances

---

src/utils/ValidateChildren.js

If you're passing a component as variable, you will have to wrap it in your app
Because you can import `ActionButton`, but if you do
```vue
<Actions>
<component :is="ActionButton" />
</Actions>
<script>
import ActionButton from 'nextcloud-vue/dist/components/ActionButton'
```
Then importing make no sense as you need to have your own methods, provide a click handler, etc etc.
So you will need to wrap it into your own `myComponent` that uses `ActionButton`
```vue
<template>
<ActionButton icon="icon-up" @click="copyNtoFN">
{{ t('contacts', 'Copy to full name') }}
</ActionButton>
</template>
<script>
import ActionButton from 'nextcloud-vue/dist/components/ActionButton'
name: 'myComponent',
```
```vue
<Actions>
<component :is="myComponent" />
</Actions>
<script>
import …
```

Allow wrapped children in validation script

---

src/components/Actions/Actions.vue
src/utils/ValidateSlot.js

I got this error when having children inside a `AppNavigationItem` and #486 applied:
```
21:29:58.390 [Vue warn]: Error in beforeMount hook: "TypeError: this.$slots.default is undefined"
found in
---> <Actions> at src/components/Actions/Actions.vue
<AppNavigationItem> at src/components/AppNavigationItem/AppNavigationItem.vue... (1 recursive calls)
<NavigationCategoriesItem> at src/components/NavigationCategoriesItem.vue
<NavigationList> at src/components/NavigationList.vue
<AppNavigation> at src/components/AppNavigation/AppNavigation.vue
<Content> at src/components/Content/Content.vue
<App> at src/App.vue
<Root> vue.runtime.esm.js:619
21:29:58.393 TypeError: this.$slots.default is undefined
Stack trace:
initActions@https://xxxx/apps/notes/js/notes.js:1255:103 …
```

fix undefined slot

---

src/components/ActionInput/ActionInput.vue

When moving your mouse over the datepicker actioninput, it will automatically open it. But once mouse is out, it will not close it.
Using keyboard is fine though and close accordingly.

Close the datepicker on unfocus

---

src/components/AppNavigationItem/AppNavigationItem.vue

Since  #486, `#app-navigation` has CSS class `vue` and Nextcloud server has the following style:
```
#app-navigation:not(.vue) > ul > li.active, #app-navigation:not(.vue) > ul > li a:hover, #app-navigation:not(.vue) > ul > li a:focus, #app-navigation:not(.vue) > ul > li a:active, #app-navigation:not(.vue) > ul > li a.selected, #app-navigation:not(.vue) > ul > li a.active, #app-navigation:not(.vue) > ul > li.active > a, #app-navigation:not(.vue) > ul > li a:hover > a, #app-navigation:not(.vue) > ul > li a:focus > a, #app-navigation:not(.vue) > ul > li a:active > a, #app-navigation:not(.vue) > ul > li a.selected > a, #app-navigation:not(.vue) > ul > li a.active > a {
opacity: 1;
box-shadow: inset 4px 0 var(--color-primary);
}
```
This means, that the `active` style from server is not …

AppNavigation: fix style for CSS class "active"

---

src/components/AppSidebar/AppSidebar.vue

There was still an error message when using no tabs in `AppSidebar`. Since tabs should be optional, the validation has to be changed (see https://github.com/nextcloud/nextcloud-vue/pull/447).
My approach here is to find valid tabs (a tab is valid if it has `name`, `icon` and `id`) and then check if there is either tabs only or non-tab-content only. Otherwise, a warning is given.
Please check in detail, if this is sufficient for you.

fix check for non-tab-content

---

src/components/Actions/Actions.vue

Default:
Custom icon:
fixes #618

Make "more icon" of actions customizable

---

src/components/ActionButton/ActionButton.vue
src/mixins/actionText.js

Implements #615
Since it is apparently not possible to listen for an emitted event on a slot (https://github.com/vuejs/vue/issues/4332), I just call the `closeMenu` method of the  `Actions` component directly from the `ActionButton`. I guess this is ok, since an `ActionButton` will always have an `Actions` component as parent.
Also, it is working as expected 😉

Allow to close the actions menu after click

---

src/components/Actions/Actions.vue

When you open and close an Actions menu which is on the edge of the viewport (e.g. top right) repeatedly by clicking on the action toggle button (not by clicking outside), the position of the dropdown menu is wrong for every second opening. This PR fixes it.

Fix position of actions when repeatedly opened

---

src/components/Actions/Actions.vue

With #619 the actions menu causes a parent element to have a larger height than without a custom icon (custom icon on second Actions):
This PR fixes this issue:

Fix different height of actions with custom icon

---

src/components/Multiselect/Multiselect.vue

Fixes a console error when using a multiselect with the following attributes without tagging:
:multiple="true"
:auto-limit="false"

Only set the width when tags wrap is actually available

---

package-lock.json
package.json
webpack.common.js

This PR adds the external dependencies we use to the webpack externals list, so they are not included in the bundle. Since they are part of the dependency section they will still be installed by npm when app developers install our package and webpack will take care of resolving them properly then.
Before
After
The size of the saving in the app bundles of course depends on which components are used, but when using multiple components that include the usage of v-tooltip, popper.js will only be included once with this PR.
A quick test run on the deck vue branch saved me ~300kb in duplicate dependencies.

Mark dependencies as webpack externals

---

src/components/AppNavigationItem/AppNavigationItem.vue

properly pass the exact prop to the `router-link`

🐛 FIX: exact-active-class support to not always highlight root element as active

---

src/components/Avatar/Avatar.vue
src/components/UserBubble/UserBubble.vue
src/components/UserBubble/index.js
src/components/index.js

introduces a new UserBubble component to be used e.g. for @-mentions in social or talk
it features an optional popover to e.g. display the full username-handle for remote users in social
it should also be possible to link the UserBubble to the user's profile (social), but I'd like to have this optional, but didn't manage to do this, because the `<a>` element would need to wrap the whole bubble and therefore I can't just use `v-if` on it. Any idea @skjnldsv or @ma12-co ?

UserBubble component

---

src/components/AppSidebar/AppSidebar.vue

Prevent default event for `<a href="#">`.
Currently, a `#` is added to the current URL when closing the sidebar. That's ugly. ;-)

AppSidebar: fix sidebar close (prevent default)

---

src/components/Avatar/Avatar.vue

Upload an avatar with transparency, e.g.:
Before | After
---|---
(Dont mind the icon being smaller, its from the transparent space around it.)

Remove the background on loaded images

---

src/components/ActionSeparator/ActionSeparator.vue
src/components/ActionSeparator/index.js
src/components/Actions/Actions.vue
src/components/index.js

Add new component for a separator between actions. This is already used in the talk app (see https://github.com/nextcloud/nextcloud-vue/issues/376 and https://github.com/nextcloud/spreed/blob/bc978f1d9808f898232e35c204a92985dcc25649/src/components/Navigation/ConversationsList/Conversation.vue#L50) and I would like to use it in notes. Hence, a generalization would be good.

new component: ActionSeparator

---

src/components/AppNavigationItem/AppNavigationItem.vue

AppNavigationItem: improve edit functionality

---

src/components/Multiselect/index.scss

Can be tested in Mail with the to, cc and bcc fields @skjnldsv @ChristophWurst   Otherwise there was no difference between placeholder and tag, especially cause there we remove the border.

Use regular text color for selected tag to not de-emphasize

---

src/components/AppSidebar/AppSidebar.vue

cc @jancborchardt as discussed

Adjust header elements

---

src/components/Modal/Modal.vue

Fix: #748
Here's how it looks:

Fix modal backdrop

---

webpack.common.js

Because the font name was the same over all versions, loading multiple nextcloud-vue components versions on the same page was causing conflicts.
Example: the close icon on the viewer
This is now fixed.

Fix icon font generation

---

src/components/Modal/Modal.vue
styleguide/assets/variables.css

Fix position of action elements by moving the sidebar toggle to the right, and fix title overlap on mobile screens.

Mobile fixes for Viewer header

---

src/components/UserBubble/UserBubble.vue

Fix #796 
before when you mentioned a guest or "all" in a chat you got spammed by:
```
[Vue warn]: Missing required prop: "user"
found in
---> <UserBubble> at src/components/UserBubble/UserBubble.vue
<Mention> at src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue
```

Allow non user mention bubbles

---

src/components/Actions/Actions.vue

That way we allow devs to check what triggered the close or open
Click outside, pressed escape...

Forward potential events to close and open

---

src/components/AppSidebarTab/AppSidebarTab.vue

Tab names are usually translated so they are a pretty bad id in general. This PR makes sure that the id can be set as a separate prop.

Make sure tabs can have a unique id that is not depending on the name

---

src/components/AppSidebarTab/AppSidebarTab.vue

After #833 
```
vue.runtime.esm.js:1888 TypeError: Cannot read property 'name' of undefined
at a.default (AppSidebarTab.js:formatted:1)
at vue.runtime.esm.js:1666
at Pt (vue.runtime.esm.js:1619)
at i (vue.runtime.esm.js:4665)
at vue.runtime.esm.js:4698
at gn (vue.runtime.esm.js:4639)
at a.t._init (vue.runtime.esm.js:5006)
at new a (vue.runtime.esm.js:5154)
at vue.runtime.esm.js:3283
at init (vue.runtime.esm.js:3114)
```

Fix Tab default values

---

.github/workflows/npm-build-lint.yml
.github/workflows/npm-publish.yml
.github/workflows/npm-test.yml

- So apparently CI is not really needed (not used anywhere on https://github.com/actions/setup-node)
- I moved everything to a proper matrix so we get the same syntax over our tests
- Added running on push as well when we push on master for new releases
What do you think?

Adjust tests syntax & formatting

---

src/components/DatetimePicker/index.scss

Solves https://github.com/nextcloud/nextcloud-vue/issues/859
The arrow icons in the datepicker seem to be switched.
There are two types of arrow: single and double.
Based on the length of a year and a month one would expect the "next month" arrow to be single and the "next year" arrow to be double. This was not the case, this MR fixes this.

Switch month and year arrow icons

---

src/components/AppNavigationItem/AppNavigationItem.vue

1) Open an app that uses the appnavigationitem component;
2) Click on a navigation item (the .active class should be added to the wrapping `<li>`);
The item was not highlighted in light primary color.
The item is properly highlighted.

Fix appnavigationitem's active state

---

src/components/Avatar/Avatar.vue

Closes #699 
For users without email adress `data.topAction` is `null`. Doing `[data.topAction].concat(data.actions)` then didn't result in an empty array as expected, but in an array with one entry being `null`.
I also first query the available actions before opening the menu now, otherwise a white arrow would shortly be visible for users without actions. And I adjusted the font-size of the action entry to 14px, so far it was 18 px which was to big.
@juliushaertl @georgehrke

Don't throw error for users without email adress

---

package-lock.json

``` bash
audited 1238698 packages in 8.35s
found 43239 vulnerabilities (43205 low, 34 moderate)
run `npm audit fix` to fix them, or `npm audit` for details
```
``` bash
updated 3 packages in 24.851s
fixed 41662 of 43239 vulnerabilities in 1238698 scanned packages
1575 vulnerabilities required manual review and could not be updated
2 package updates for 2 vulns involved breaking changes
```

Fix dependencies audit

---

src/components/Multiselect/index.scss

Fixes showing the multiselect value in the user management when the Multiselect is single value but taggable and searchable. The main issue is that the input always has a `position: absolute;` set, so even though the value label has a `z-index: 1;` it will never be shown on top.
Before:
After:
@skjnldsv Please have a closer look if that has any downsides, since the multiselect styling is quite complex :wink: I also cannot reproduce this in the nextcloud-vue docs so there might be some server styles interfering here, but I could not find the culprit. :see_no_evil: 
Found when testing https://github.com/nextcloud/server/pull/18818

Force single multiselect value to be shown when the input is not active

---

src/components/AppContent/AppContent.vue

Makes more sense for accessibility readers
___
> The `<main>` tag specifies the main content of a document.
> 
> The content inside the `<main>` element should be unique to the document. It should not contain any content that is repeated across documents such as sidebars, navigation links, copyright information, site logos, and search forms.
> 
> Note: There must not be more than one `<main>` element in a document. The <main> element must NOT be a descendant of an `<article>`, `<aside>`, `<footer>`, `<header>`, or `<nav>` element.
___
@nextcloud/accessibility

Use main as appContent

---

src/utils/ValidateSlot.js

The `ValidateSlot` function had two issues:
- `forEach` in combination with `splice` does not work. `splice` mutates the original array, so the `forEach` loop skips the next element after a splice occurs. Hence, some elements are not checked.
- If an array entry was not a vue component, the check if it is a forbidden component will always lead to false, since `node.componentOptions.tag` fails with `undefined`. Hence, an element which is not a html element and not a vue component would not be filtered out. This happens to e.g. text nodes which the browser sometimes renders if there is a whitespace in the markup.
This PR is necessary for #913.

Fix the validate slots function

---

package-lock.json
package.json
src/assets/iconfont/breadcrumb.svg
src/components/Breadcrumb/Breadcrumb.vue
src/components/Breadcrumb/index.js
src/components/Breadcrumbs/Breadcrumbs.vue
src/components/Breadcrumbs/index.js
src/components/index.js
styleguide.config.js
styleguide/assets/variables.css

This PR adds a breadcrumb component as it is used in the files app, closes #800.
The component resizes with the viewport and hides folders in a dropdown if the width is to small. The first (root folder) and the last folder are always shown though. The component also emits an event when something is dropped on a folder. The dropdown with the hidden folders opens on hover, so one can drop on the hidden folders as well.
Some things don't work yet on netlify, but do work locally for me:
var(--color-primary-light) doesn't seem to be available on netlify, but since it is used for other components, I guess it is fine?
@skjnldsv Do you have an idea regarding the last two problems?
I didn't test the component in the Files app. Looking at https://github.com/nextcloud/server/blob/e4948f5d86a7df2a683e …

Add breadcrumb component

---

src/components/AppNavigationItem/AppNavigationItem.vue

A bit cleaner!
Since we're only using the given prop and emitting a change we don't need this weird watch/sync mechanism.
The  Actions already contain its own separation & watcher so you can modify the state without triggering a `[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "open"`

We don't need an intermediate data & watcher for Actions open state

---

src/components/Breadcrumbs/Breadcrumbs.vue

On Firefox ESR 68.6.0 you have to set `event.dataTransfer.setData()` to enable dragging and element. In other browsers the example worked already.

Fix breadcrumbs drag example for Firefox ESR

---

package-lock.json

Regarding the messages:
```js
// Requires jest 26 https://github.com/facebook/jest/issues/5815
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN jsdom@16.2.1 requires a peer of canvas@^2.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN jsdom@15.2.1 requires a peer of canvas@^2.5.0 but none is installed. You must install peer dependencies yourself.
// Requires jsdom@16, crossing the jest issue above
npm WARN ws@7.2.3 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.3 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.3 …
```

Fix audit and lockfile

---

package-lock.json
package.json
src/components/AppContent/AppContent.vue
src/components/AppNavigation/AppNavigation.vue
src/components/AppNavigationToggle/AppNavigationToggle.vue

fix https://github.com/nextcloud/server/issues/15831
___
@ma12-co, @skjnldsv & @ChristophWurst on a nice beer programming session on a sweet Friday afternoon :beers:

Allow to toggle sidebar and always show the toggle

---

src/components/Breadcrumbs/Breadcrumbs.vue

Due to vues inplace patching strategy comparing the crumbs was not reliable, so it could happen, that the hidden class was not applied to a crumb that should be hidden. Checking by the index is more reliable, as it only compares Integers.

Check by index if hiding breadcrumbs is necessary

---

l10n/messages.pot
src/components/Actions/Actions.vue
src/components/AppContent/AppContent.vue
src/components/Breadcrumbs/Breadcrumbs.vue

```vue
<Actions ref="actions" @open="log" @close="log">
<ActionButton>Test</ActionButton>
<ActionButton>Test</ActionButton>
<ActionButton>Test</ActionButton>
</Actions>
```
~~Allows us to do `this.$refs.actions.toggleMenu(true)`~~
Cleaner than having to always pass an open property or do `this.$refs.actions.opened = true` 
What do you think @nextcloud/vuejs ?
~~We cannot use close/open methods name as `this.open` is already used by the prop~~
Fixed differently by properly passing the open prop through the children
___
This also fixes a missing close event when clicking the menu icon to close

Cleanup code and properly toggle Breadcrumb menu

---

src/components/AppNavigation/AppNavigation.vue

The `navigation-toggled` event was emitted to soon, before the animation finished. Hence, the breadcrumb component would get the wrong width and hide breadcrumbs although not necessary. On hovering the actions menu, a resize would be triggered and the crumbs would be visible (correctly) now.
Giving a bit more time to finish the animation fixes the issue.
Follow-up to #975 @skjnldsv 
Before:
After:

Finish toggle animation before emitting event

---

src/components/AppContent/AppContent.vue
src/components/AppNavigation/AppNavigation.vue
src/components/AppNavigationToggle/AppNavigationToggle.vue
src/components/AppSidebar/AppSidebar.vue
src/components/Content/Content.vue

:warning: breaking! If you added some css to make sure the content was not overflowing to the right, please remove it, the content will now be shrink properly alongside the app-nav & app-sidebar with flex (like it should have been since the beginning!)

Move away from containers server styling

---

package-lock.json
package.json
src/components/Highlight/Highlight.vue
src/components/Highlight/index.js
src/components/Multiselect/AvatarSelectOption.vue
src/components/Multiselect/EllipsisedOption.vue
src/components/Multiselect/Multiselect.vue
src/utils/FindRanges.js

This PR adds a `Highlight` directive, which highlights a substring with `<strong>`. It allows us to get rid of the currently used `v-html` directive and fixes some bugs in the current implementation.
Closes #1031.
Problems fixed compared to the current solution:
- The casing of the searched term is now correctly maintained. Before, if you searched for `opt`, `Option 1` would've become `option 1`
| master | PR | 
| ------------- |:-------------:|
| ![master_casing](https://user-images.githubusercontent.com/2496460/79697319-57e1da00-8282-11ea-902b-598ec87b1b4e.gif)     | ![pr_casing](https://user-images.githubusercontent.com/2496460/79697376-b9a24400-8282-11ea-85bc-95466acc81b4.gif) |
- In the ellipsised multiselect search terms are now correctly highlighted even if they span both parts
| …

Replace v-html directive for Multiselect highlighting

---

src/components/Avatar/Avatar.vue

Avatars of people in unread mails had the letter of the avatar placeholder bolded too. This didn’t look very good, so now it’s forced to normal font weight always:
cc @nextcloud/mail for review

Force normal font weight for avatar letter placeholder, even for unread mails

---

src/components/ActionInput/ActionInput.vue

For addressing nextcloud/server#20520
`vue2-datepicker` expects a v-model with a `Date` but the value type checks for string only.

Pass Date object for Action Input Value

---

src/components/Avatar/Avatar.vue

Avatars with transparency have the generated color from the letter placeholder shine through. This of course should not happen and looks all kinds of weird with logos:
Now there is always white background. Also in the dark theme, as images with transparency usually expect white as background.
Please review @nextcloud/vuejs and cc @ChristophWurst @GretaD because this is very visible in Mail.

White background for avatars with transparency, also in dark theme

---

tests/OC.js
tests/setup.js

This fixes the `No OC found` warnings from l10n: https://github.com/nextcloud/nextcloud-vue/pull/1081/checks?check_run_id=661403687#step:5:11

Fix No OC found test warnings

---

src/components/ActionRouter/ActionRouter.vue
src/components/ActionText/ActionText.vue
src/components/ActionTextEditable/ActionTextEditable.vue

While the ActionRouter should provide the `@click`-event according to docs, it didn't emit on click. So i looked through the actions, comparing docs to actual behavoiur resp. the click-event.
- This PR includes now to emit the Click-event on `ActionRouter`, `ActionText` and `ActionTextEditable` as given on Docs.
- The `ActionSeparator` also should emit the event according to docs. In this case i would rather remove the event on docs, as i don't see this as use-case of the separator. I just didn't find the place to edit the doc.
- Concerning the `ActionTextEditable` i'm not sure, which way would be more reasonable - emit the event as i did here, or better remove the event from docs?

Fix click event on actions

---

src/components/AppNavigation/AppNavigation.vue

There are quite many li-items on app-navigation, that need a ul-container to be properly shown on sidebar (esp. if many items need a scrollbar). The container was already thought to be used, but as far as i understand from vue-coding it's better code-style to provide the slot as proposed here, instead of letting users manually add the ul-tag within the app-navigation.
Makes the Code of the list-items a bit more meaningful connected to the AppNavigation (here on forms app).

Provide Navigation list as slot

---

src/components/index.js

Export of EmptyContent is missing 
* import { EmptyContent} from 'nextcloud/vue' 
* import { EmptyContent } from '@nextcloud/vue/dist/Components/EmptyContent'
didn't work
* import EmptyContent from '@nextcloud/vue/dist/Components/EmptyContent'
worked

Export EmptyContent

---

src/components/AppNavigation/AppNavigation.vue

Just saw, that the navigation overrides the Nextcloud-Header-Bar.
The header has a z-index of 2000, vue-body of 1000 and sidebar of 1500. Therefore i propose a z-index for navigation of 1800, to still override the sidebar in case, but appear below the NC-Header.
**Before:**
**After:**

Avoid Navigation to overflow NC-Header

---

src/components/AppNavigation/AppNavigation.vue

Sorry, seems like i need to fix my own PR #1107.
Just recognized, that to maintain compatibility to 'old' systems, that include the `ul` on their own, the 100% height needs to be removed. Otherwise, the two `ul` concur, resulting in two 50% `ul`-lists.
Tested now the cases of manual ul, the new template ul and list-items without ul. They should all work now.

Fix Provide Navigation List

---

src/components/AppNavigationItem/AppNavigationItem.vue

On forms, @jancborchardt recognized, that the actions-menu of navigationItems shows the form-title on mouseover.
This PR now shifts the title-attribute, into the Title-span, so it is only visible there. Actions-Menu as well as counter do not show the title anymore.
**Before** (imagine a cursor above the small label):
**After**:

Only show mouseover-title on text in navigationItem

---

l10n/messages.pot
src/components/ActionButton/ActionButton.vue
src/components/ActionCheckbox/ActionCheckbox.vue
src/components/ActionInput/ActionInput.vue
src/components/ActionLink/ActionLink.vue
src/components/ActionRadio/ActionRadio.vue
src/components/ActionRouter/ActionRouter.vue
src/components/ActionSeparator/ActionSeparator.vue
src/components/ActionText/ActionText.vue
src/components/ActionTextEditable/ActionTextEditable.vue
src/components/Actions/Actions.vue

Related and partially fixes the issue by @jancborchardt at forms https://github.com/nextcloud/forms/issues/416
- First commit changes to only prevent default key-events, if the action-menu is opened. Like this, navigating through content does not get killed. If closed, navigation works as usual, if opened, navigation is caught into action-menu.
- Second commit allows to focus the three-dot actionmenu-button, to be able to close the menu again on space by keyboard. Further, the keyboard navigation overflows, so people can navigate through the actionmenu in a round.
- Special change in second commit, is not to focus the first element, when opening the menu. First looks a bit unfamiliar, as we know the menu until now with always the blue bar. The reason behind this change is that in order to …

Fix actions navigation by keyboard

---

src/components/Actions/Actions.vue

Actions did only check the out-of-bottom, if the actionmenu was aligned as center, so e.g. on App-Navigation, it didn't check and ran out of view.
- The out of bottom (y-dir) should be checked independent of right/left align (x-dir).
**Before:**
**After:**

Check actions out of bottom independent of left/right aligned

---

src/components/AppNavigation/AppNavigation.vue

It's a pity, and i'm really sorry for that back & forth. But the fix to avoid the breaking-change makes the actions-menu on navigation hiding within the small ul, instead of flipping or showing above.
Easiest way to solve this, is now to revert the mentioned commit, unfortunately then making the already announced breaking change really a change, that breaks the manual usage of ul, but forces to use the slot.
For reference: 
- The navigation-list PR, released as breaking change: #1107
- The PR, that wanted to avoid the navigation-PR to be breaking, also within current release: #1123
- This PR: Now becoming itself a breaking change, as the first one looked like not braking anything (see vue-public talk)? 😟 
**Before**
**After**

Revert "Fix Provide Navigation List" & provide footer-slot

---

src/components/UserBubble/UserBubble.vue

If `avatarImage` was not set, it was throwing all over the place

Fix Avatar URL check in UserBubble

---

src/components/AppNavigationItem/AppNavigationItem.vue

Signed-off-by: Holger Dehnhardt <holger@dehnhardt.org>
Fixes: https://github.com/nextcloud/nextcloud-vue/issues/1140
The indention of a sublevel now starts with the right edge of the parent.
From the second level on, :hover previously displayed the arrow icon and the navigation icon on top of each other.
The navigation icon is now also hidden for lower levels. 
Unfortunately, :hover fades out all the navigation icons of the same branch. But I don't know what to do about that;-)

reduce indentation of the sub-levels

---

src/components/Actions/Actions.vue

|![Capture d’écran_2020-07-23_16-20-44](https://user-images.githubusercontent.com/14975046/88297723-931bfb00-cd00-11ea-8d6b-da93344f4c9f.png)|![Capture d’écran_2020-07-23_16-20-35](https://user-images.githubusercontent.com/14975046/88297720-92836480-cd00-11ea-8d14-b99a63d7d13a.png)|
Buttons have a border-radius from server, so it does it when you try with ActionLink for example
```vue
<Actions>
<ActionLink icon="icon-external" href="https://nextcloud.com">
Nextcloud website
</ActionLink>
</Actions>
```

Fix actions single border radius

---

src/components/Avatar/Avatar.vue

When testing with Axe, Wave or Lighthouse there’s a bunch of errors before. Now fixed. :)
See https://www.w3.org/TR/UNDERSTANDING-WCAG20/text-equiv-all.html (since avatars are decorative and next to names)

Avatar: Add empty alt attribute for accessibility

---

l10n/messages.pot
src/components/AppNavigationSettings/AppNavigationSettings.vue
src/mixins/excludeClickOutsideClasses.js
src/mixins/index.js

fixes #862 
Example: https://github.com/nextcloud/calendar/pull/2155

Allow to add exclude list for v-click-outside

---

src/components/Avatar/Avatar.vue

fix height of avatar icon

---

src/components/ColorPicker/ColorPicker.vue

I spotted an issue downstream that I can replicate with firefox, which shows an active checkbox being at the top of the color picker, rather than the vertical center: https://github.com/nextcloud/deck/issues/2102
I'm not sure if `align-content` was a typo or not, so I left it there.
Using `align-items: center;` will vertically align children in a flex container to the middle of said container when combined with `justify-content: center;`

vertically align active checkmark to center

---

src/components/AppSidebar/AppSidebar.vue
src/components/AppSidebarTabs/AppSidebarTabs.vue
tests/OC.js
tests/setup.js
tests/unit/components/AppSidebar/AppSidebarTabs.spec.js

This PR allows to show an empty sidebar and assures to correctly check for mixing AppSidebarTab with other content in the default slot. The PR partially implements #1090 and closes #733.
Here is how it looks.
After:
Before:
I decided against converting the tabs part to a render function, because it seemed quite a lot of effort for just "doing it right". The template solution seems to work fine. The only thing which seems a bit dubious to me is watching `this.$children` for changes, but it was like that before and works, so 🤷‍♂️

Allow empty sidebar, correctly check mixed content

---

src/components/AppSidebar/AppSidebar.vue

I overlooked a "```" in the docs, sorry for the hassle.
Closes #1284.

Fix broken netlify docs

---

src/mixins/excludeClickOutsideClasses.js

This fixes the warning:
```
[Vue warn]: Invalid default value for prop "excludeClickOutsideClasses": Props with type Object/Array must use a factory function to return the default value.
found in
---> <AppNavigationSettings> at src/components/AppNavigationSettings/AppNavigationSettings.vue
<AppNavigation> at src/components/AppNavigation/AppNavigation.vue
<AppNavigation> at src/components/AppNavigation/AppNavigation.vue
<Content> at src/components/Content/Content.vue
<App> at src/App.vue
<Root> vue.runtime.esm.js:619
```

Use factory function to return default value

---

package-lock.json
package.json
src/assets/iconfont/user-status-away.svg
src/assets/iconfont/user-status-dnd.svg
src/assets/iconfont/user-status-invisible.svg
src/assets/iconfont/user-status-online.svg
src/components/Avatar/Avatar.vue
src/components/Multiselect/AvatarSelectOption.vue
src/components/UserBubble/UserBubble.vue
src/mixins/index.js
src/mixins/userStatus.js

| | |
|![61D15EEB-050C-4EB4-B565-CAA7DBC3B8D6](https://user-images.githubusercontent.com/1250540/89434753-35e26980-d744-11ea-8949-ebacd32dc74e.png)|![170CA5A4-4621-4ED2-A833-027CFF03A2F8](https://user-images.githubusercontent.com/1250540/89443387-81027980-d750-11ea-8017-fd4819251ad4.png)|
|![76349057-CF32-405F-9DFA-D66C3197A138](https://user-images.githubusercontent.com/1250540/90263194-9b72dc00-de4f-11ea-9005-f956d1a59698.png)||

Add user-status to Avatar component

---

src/mixins/userStatus.js

Didn't report in the original PR, but is reporting here: https://github.com/nextcloud/nextcloud-vue/pull/1303/files#file-src-mixins-userstatus-js-L46

Fix linting error introduced by #1259

---

src/components/AppSidebar/AppSidebar.vue

This PR allows to show the title input field by clicking on the title. Also it makes sure that the title input is rendered in the same style as the title itself:
Partially implements #1090.

Allow to toggle editable title by click

---

src/components/AppSidebar/AppSidebar.vue

This PR allows to specify a custom action instead of the star icon in the sidebar. Useful e.g. for the Tasks app to toggle the completed state of a task.
Since #1288 introduced quite some changes to the structure, I implemented it on top of #1288. The important commit is f1ea31adc8fa131a96d4bdd9609bc9848c70edfe. I will rebase this PR here once #1288 is in.

Allow to specify a custom action instead of the star

---

src/assets/action.scss

If an icon is passed as a url, it can have no icon-* class
Signed-off-by: Kirill Dmitriev <dk1a@protonmail.com>

Add background-repeat:no-repeat to icons

---

src/components/AppSidebar/AppSidebar.vue
src/directives/Linkify/index.js

Implement first part of #1336.

Allow to toggle linkification by prop

---

src/components/AppSidebar/AppSidebar.vue

Fixes the sidebar layout in compact mode, implements the second part of #1366:
@skjnldsv Since there are many valid combinations of options (compact, with-star, with-header-figure, with-secondary-actions), it needs a good test to find any possibly remaining issues.

Fix sidebar layout in compact mode

---

src/components/Actions/Actions.vue

Allow to choose boundariesElement for actions' popover

---

cypress/plugins/index.js

This should disable the spell check for cypress, preventing false negatives for the visual regression tests.
@juliushaertl Please check whether this fixes https://github.com/nextcloud/nextcloud-vue/pull/1359#issuecomment-682497474 the issue for you.

Disable spell checking for cypress

---

src/components/AppSidebar/AppSidebar.vue

Maybe I missed something and there is a new way to do that but it seems to be a bug. AppSidebar used to emit "update:active" event to let its parent know when active tab is changed.
"update:active" event is not emitted by AppSidebar anymore. It is emitted by AppSidebarTabs but not caught. So it just needs to be forwarded imho.

Forward update:active event in AppSidebar

---

src/components/AppNavigationItem/AppNavigationItem.vue

Just forwarding the "menu-placement" prop to the underlying Actions component. Default is the same as Actions's placement.
It can be useful, for example, to avoid hiding what's below the AppNavigationItem when showing the menu.

New prop for AppNavigationItem to set actions/menu placement

---

src/mixins/userStatus.js

The user status endpoint is not available for guests, [only for logged in users](https://github.com/nextcloud/server/blob/0fad921840eb801492522af6ef795231163cff20/apps/user_status/lib/Controller/StatusesController.php#L71). As the request will always fail if the current user is a guest there should be no need to perform it.
Note, however, that this will prevent user statuses to be shown on the avatars in public share pages, even if the current user is actually logged in. [Public share pages are opened in incognito mode](https://github.com/nextcloud/server/blob/217a69ebf9cd766c23b6f69037cbbe07cb00b7ce/apps/files_sharing/lib/Controller/ShareController.php#L310), so `getCurrentUser` returns null. However, if the current user is logged in requests to the API would work without problems, so …

Do not fetch user status if current user is a guest

---

src/components/Avatar/Avatar.vue

Before the user status was always fetched when the component was mounted,
even if "showUserStatus" was false. If the avatar was never meant to
show the user status that caused unneeded requests (for example, in the
chat view of Talk).

Fetch user status in avatar only if it is going to be shown

---

src/components/ActionInput/ActionInput.vue

Noticed in Calendar. See https://nextcloud-vue-components.netlify.app/#/Components/Actions?id=actioninput

Fix ActionInput label height

---

src/components/Actions/Actions.vue

This allows to select the popover container. The default is still `body` so nothing will break here 😉 Helps fixing #1384.
See https://github.com/nextcloud/nextcloud-vue/issues/1384#issuecomment-687573004 for details.

Allow to set popover container

---

src/components/UserBubble/UserBubble.vue

Regression from bd7bc35917e8a5150f1142565c47e3d169864444
It inverted the logic from `isUserAvatar` to `isCustomAvatar` but forgot to invert the bool operator on this 2 usages

Fix customer avatar handling in userbubble

---

src/components/Avatar/Avatar.vue

1. Go to any page that uses the Avatar component to show your own avatar, e.g. a Talk conversation participant tab
2. Change your status
3. Wait until your avatar shows the new status :skull_and_crossbones: 
Relevant event is emitted in server:
https://github.com/nextcloud/server/pull/22801
I kept the event neutral from `getCurrentUser` so it will automatically update statuses of other users when e.g. Talk emits their status updates in the future (since it fetches it with the 30s participant list update it makes sense)

Listen to user status events to update the status on avatars

---

src/components/Avatar/Avatar.vue

How it looks in talk ([note that the duplicate icon needs a fixing there](https://github.com/nextcloud/spreed/pull/4253)):
I played around a bit with a circled white background but this might look odd depending on the emoji. 
@jancborchardt Feel free to play around with the styles if needed

Show icon instead of status if not in do not disturbe mode

---

src/components/AppSidebar/AppSidebarTabs.vue

Fixes a regression in 2.6.x where a tab would not be shown if the name contains a space. Found in deck where some translations add a space to the tag name.

Allow spaces in the name of a AppSidebarTab

---

src/components/AppSidebar/AppSidebar.vue
src/components/AppSidebar/AppSidebarTabs.vue
src/components/AppSidebarTab/AppSidebarTab.vue

- Added loading prop to AppSidebar
- Removed non-working slot v-bind
- Moved active show/hide to the css instead of relying on v-show to avoid conflicts

Add loading state on AppSidebar and remove unwanted slot bind

---

src/components/Modal/Modal.vue

The Modal component might freeze completely if it gets destroyed when its parent is destroyed. This is caused by the forced mount to body. To fix this I added a lifecycle hook that cleans up the injected html element after the component has been destroyed.
Additionally, I noticed that the modal code uses the lifecylce hook `unmounted` which is not existing in vue v2 ([see the documentation](https://vuejs.org/v2/api/#Options-Lifecycle-Hooks)). The dead code was moved to the corresponding hook `beforeDestroy`.
Found the bug while developing nextcloud/mail [#3591](https://github.com/nextcloud/mail/pull/3591).

Fix modal freeze

---

l10n/messages.pot
src/components/RichContenteditable/AutoCompleteResult.vue
src/components/RichContenteditable/MentionBubble.vue
src/mixins/richEditor/index.js

Bubble icon and autocomplete icons are always overridden by the background-image, even if there is no avatar URL (because it's not a user or there is no id).
This is an attempt to fix that :grin:.
refs #1433

Fix suggestion for RichContenteditable component

---

l10n/messages.pot
src/components/AppSettingsDialog/AppSettingsDialog.vue
src/components/AppSettingsDialog/index.js
src/components/AppSettingsSection/AppSettingsSection.vue
src/components/AppSettingsSection/index.js
src/components/index.js

App Settings Dialog

---

README.md

Signed-off-by: Cyrille Bollu <cyrpub@bollu.be>

Adds information to README.md file how to use vue-devtools

---

package.json

Remove hide-modules from webpack production command
Without this fix, `npm run build` fails with an error as this argument was removed in webpack 4 and https://github.com/nextcloud/nextcloud-vue/pull/1452 just upgraded to that version

Fix npm run build by removing obsolete command

---

l10n/messages.pot
package-lock.json
package.json
src/components/RichContenteditable/AutoCompleteResult.vue
src/components/RichContenteditable/RichContenteditable.vue

Add submit, multiline and maxlength support

---

package-lock.json
package.json
src/components/Avatar/Avatar.vue

This is a crude POC that shows that when we save the "does this user has an avatar call", performance improves.
Possible solution for https://github.com/nextcloud/spreed/issues/4284
Maybe this should be stored in a store or something, but as I understand, Vue components in the library don't really have a store available.
Another approach would be to supply an optional property "hasAvatar" and the caching could be done from the outside in situations where the caller thinks it makes sense.

Cache hasAvatar info in sessionStorage to avoid flicker

---

src/components/Avatar/Avatar.vue

Pretty much does the same, just a code cleanup!

Cleanup avatar fetching methods

---

src/components/RichContenteditable/RichContenteditable.vue

Fix https://github.com/nextcloud/nextcloud-vue/issues/1483

Fix multiLine prop

---

src/components/Multiselect/index.scss

🐛 FIX: allow proper linebreak in multiselect for narrow mobile screens

---

src/components/Avatar/Avatar.vue

- Do not cache if the user is not defined
- Added debug level
- Fallback to letters if the url is invalid
```vue
<Avatar
:disable-menu="true"
:disable-tooltip="true"
display-name="Hello User"
:is-no-user="true"
:size="40"
url="http://this.is.a.fakeUrl.jpg"
class="app-content-list-item-icon" />
```

Fix avatar caching for non-user rendering

---

src/components/AppSidebar/AppSidebar.vue
src/components/AppSidebar/AppSidebarTabs.vue
src/components/AppSidebarTab/AppSidebarTab.vue

Joas told me recently they had to rely on hacks to make the sidebar inner scrollable.
The AppSidebar needs to be as simple as possible, so I made the inner tabs scrollable by default and integrated two new events:
- `scroll`, the tab is being scrolled
- `bottomReached`, the tab is scrolled to the bottom
I also fixed some variables on the css

Make appSidebar scrollable inside

---

src/components/AppNavigationItem/AppNavigationItem.vue

If you want to mount a Modal for an item in the navigation it becomes
tricky to mount the (virtual or not in-place) modal component from the
navigation. To avoid more complexity itwold be convenient to just mount
the component inside the navigation with the intention that it shouldn't
really render anything in-place.
For https://github.com/nextcloud/mail/pull/3569

Allow an "extra" slot for the AppNavigationItem

---

src/components/Avatar/Avatar.vue

|![dev skjnldsv com_apps_contacts_ (3)](https://user-images.githubusercontent.com/14975046/96685571-982f2b80-137d-11eb-986f-3c519e68e49d.png)|![dev skjnldsv com_apps_contacts_ (2)](https://user-images.githubusercontent.com/14975046/96685569-96fdfe80-137d-11eb-8ada-bdf388ebbee8.png)|
|![Capture d’écran_2020-10-21_09-05-28](https://user-images.githubusercontent.com/14975046/96685603-a54c1a80-137d-11eb-8c38-a4213eac24dd.png)|![Capture d’écran_2020-10-21_09-05-34](https://user-images.githubusercontent.com/14975046/96685616-a8dfa180-137d-11eb-9231-61d9fc891505.png)|
@nextcloud/vuejs

Do not show letter if we have an icon and keep image ratio

---

src/components/AppSettingsDialog/AppSettingsDialog.vue

Solves the first part of this comment: https://github.com/nextcloud/spreed/pull/4195#pullrequestreview-511633941

Fix setting navigation item blur

---

package.json
src/components/DatetimePicker/DatetimePicker.vue

We are getting vue2-datepicker 3.7.0 and since 3.6.3, the `format` prop not a string/object anymore. It's now just a string and there is a new `formatter` object prop.
As there is no default for this prop in vue2-datepicker, I wonder if it's better to have `{}` or `null` as default in `@nc/vue`

Adapt to new vue2-datepicker format props

---

src/components/Modal/Modal.vue

For viewer, to automatically contain the image, we need a specific css pattern that rely on a combination of max and height/width.
If only one is defined the chaining is broken.
|![dev skjnldsv com_apps_contacts_All%20contacts_adb58ef0-8850-4f41-8afa-6b6144ca894b_contacts (1)](https://user-images.githubusercontent.com/14975046/97162606-b763f980-177f-11eb-8a34-f1fda00d8e27.png)|![dev skjnldsv com_apps_contacts_All%20contacts_adb58ef0-8850-4f41-8afa-6b6144ca894b_contacts](https://user-images.githubusercontent.com/14975046/97162599-b632cc80-177f-11eb-981f-a3fe55cd0473.png)|

Also set Modal height/width to allow children to define their height/width and not only max-height/width

---

src/components/AppSettingsDialog/AppSettingsDialog.vue

Fixes https://github.com/nextcloud/spreed/pull/4195#pullrequestreview-514124732
Plus makes sure that the settings are scrolled to the top each time they're opened

Fix settings blur 2 

---

package-lock.json
package.json
src/components/EmojiPicker/EmojiPicker.vue

Solves constant CPU usage and energy impact when used in Talk app.
Also updated to 7.0.7.
See https://github.com/nextcloud/spreed/issues/4501 for context about the performance issue and some research about it.
Note: not reproducible on the demo page with the emoji picker, so it might be due to some layout configuration.

Use static emoji picker

---

src/assets/action.scss

Long ActionTexts have a weird margin.
This effectively reverts #688. However, the bug mentioned there is not present after applying this PR. I guess there were other improvements that fixed the button issue.
Before:
After:

Fix action text margin for long texts

---

.github/workflows/cypress.yml

Fixes 
``` js
Error: The `set-env` command is deprecated and will be disabled soon.
Please upgrade to using Environment Files.
For more information see: github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands
```

Bump cypress github-action to v2

---

l10n/messages.pot
src/components/RichContenteditable/RichContenteditable.vue
src/mixins/richEditor/index.js

- Do not render an unknown mention
- Fix default value if any and fix pasting with custom data

Fix RichEditor rendering of unknown mention, undefined checks and fix default value init

---

src/components/AppSidebar/AppSidebar.vue

Added nicer looking tooltip for the close button.
Added optional tooltip for the app sidebar header.
Tested with Talk where I locally set the titleTolltip property to the same value as the title:
And the close button:
I didn't want to make it default to the title as it might not always look good depending on use case.
In the case of the Talk app, the title is a user defined room name.
For other apps it might be static text that doesn't ellipsize nor needs a tooltip.

Add tooltips in app sidebar header

---

src/components/Modal/Modal.vue

Reverts nextcloud/nextcloud-vue#1518
As @ma12-co mentionned, this was a wrong approach, as the modal should wrap the flow instead.
It make more sense to keep capping the height/width instead.
Sorry about the noise! :(

Revert "Also set Modal height/width to allow children to define their height/width and not only max-height/width"

---

src/components/RichContenteditable/RichContenteditable.vue

Make sure the default localValue is initialised and refactor duplicate method
Avoid stuff like those as localVaue is used to detect if the editor is empty (stupid ff bug)

Fix rich-contenteditor default value init and small code cleanup

---

src/components/AppSidebar/AppSidebarTabs.vue
tests/unit/components/AppSidebar/AppSidebarTabs.spec.js

Hi,
I added unit tests on already tested component to familiarize myself with the code.
I also fix some warning on the passing tests of the current code (stub of console does not work as expected)
During this phase I found a bug with the key listener.
According to the documentation, we can use the kebab-case standard even if it’s not a defined shortcut.
https://vuejs.org/v2/guide/events.html#Key-Modifiers
But it doesn’t seem to work on every system.
Other events seems to trigger the listeners ‘keydown.page-up’ and ‘page down’.
You can try it with the written tests.
According to Vue-test-utils the key to trigger it in tests are ‘pageup’ and ‘pagedown’.
https://vue-test-utils.vuejs.org/guides/dom-events.html
May it be an issue in Vuejs listener process on some engines?
For now I fixed it …

Improve testability + small code changes of AppSideBarTabs

---

src/components/AppSidebarTab/AppSidebarTab.vue

The aria-labelledby must contain the id of an element that contains the
label and not a direct text. This fixes it by pointing back to the
matching tab heading element.
As an additional bonus, this will semantically link this "tabpanel" to
the matching "tab".
Tested with Talk and a screen reader: the screen reader now says "Participants region" or "Settings region" when clicking inside the tab.

Fix labelledby in tab section

---

src/components/AppSidebar/AppSidebar.vue

Needed to fit talk's description in the header slot.

Remove sidebar actions slot max height

---

src/components/RichContenteditable/RichContenteditable.vue

Fixes a bug in which the `<div contentaditable>` would be `contenteditable = true` even if the `contenteditable` prop was set to false.

Fix contenteditable state ad first load

---

src/assets/action.scss

Fix action button text for long translations

---

src/components/AppNavigationItem/AppNavigationItem.vue
src/components/AppNavigationItem/AppNavigationNewItem.vue
src/components/AppNavigationItem/InputConfirmCancel.vue

@jancborchardt and I decided to create a new mode for the AppNavigationItem, to add something similar to the editable mode, but without the editing part, just a inline input box that apperas when the logo is clicked and a event when the new input gets acccepted.
We will need this for the News App Vue Rewrite.
I think @jancborchardt can explain this much better than me.
when clicked:

AppNavigationItem improved editing mode and AppNavigationNewItem component

---

src/components/Avatar/Avatar.vue

Hide clickability from screen reader by not registering the click event when not clickable.

Allow disabling the avatar menu

---

src/components/UserBubble/UserBubble.vue

This will prevent screen readers to say "Heading level 6" + the
contents instead of just reading the contents.
Tested with Orca and Firefox.

Remote semantics of h6 in user bubble

---

src/components/AppNavigation/AppNavigation.vue

Makes it possible for screen readers to say the text of aria label
followed by the term "navigation" when entering that region.
Also added an optional arial label for the toggle.
In the talk app I've set the aria label to "Conversation list" so when entering the left sidebar (or jumping to any element inside) the screen reader says "Conversation list navigation".

Set navigation role and aria label on app navigation

---

src/components/RichContenteditable/RichContenteditable.vue

Useful to dismiss an edit from the parent.  

Richcontenteditable: bind event listeners

---

src/components/Actions/Actions.vue
src/components/AppNavigationToggle/AppNavigationToggle.vue

When setting the boolean to false, the DOM attribute "aria-expanded"
disappears.
For screen readers to be able to say "Actions push button collapsed" instead of just "Actions push button" the
attribute must be present and set to the string "false" instead of
absent.
Discovered this by comparing screen reader behavior with the example from https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20161214/examples/menu-button/menu-button-1/menu-button-1.html

Aria-expanded must be a false string, not absent

---

.gitignore
CHANGELOG.md
README.md

Copied entries from Github Releases up to 2.6.0.
Because I heard that we're doing changelogs also in other repos like https://github.com/nextcloud/nextcloud-dialogs
For some reason CHANGELOG.md was in gitignore, maybe there were plans to automate this ?
Anyway, let me know if down to 2.6.0 is enough or whether it's useful to have even older entries.
I've adjusted the README to mention that whoever does a release needs to update the changelog as well.

Add changelog file

---

src/components/ListItemIcon/ListItemIcon.vue
src/components/Multiselect/Multiselect.vue
src/components/Multiselect/index.scss

To review before: https://github.com/nextcloud/nextcloud-vue/pull/1578
Switched to standard positioning to make sure the container take the content's height.
Allows design like this

Fix default multiselect height

---

package-lock.json
package.json
src/assets/action.scss
src/components/ActionButton/ActionButton.vue

When using a material design icon in the icon slot, this fix will
properly align it vertically.
We need it because the ActionButton consumer cannot override the styles with `::v-deep` since the popover itself might be in the document body
When testing the docs you might need to scroll up or down to see the dropdown because of https://github.com/nextcloud/server/issues/23872 which also occurs in the docs...

Quickfix for action button and material design icon

---

src/components/AppNavigationItem/AppNavigationItem.vue
src/components/AppNavigationNewItem/AppNavigationNewItem.vue
src/components/AppNavigationNewItem/index.js
src/components/index.js

It was forgotten in the exports in https://github.com/nextcloud/nextcloud-vue/pull/1277
cc @powerpaul17

Add AppNavigationNewItem

---

src/components/ActionInput/ActionInput.vue

Ref https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/email
See #1662

Allow ActionInput type=email

---

src/components/ActionInput/ActionInput.vue

Straight forward implementation: simply passes all attributes and events from/to multiselect component.
Closes #774
Preview of documentation: https://deploy-preview-1250--nextcloud-vue-components.netlify.app/#/Components/Actions?id=actioninput

add multiselect type to ActionInput

---

src/components/Avatar/Avatar.vue
src/components/Popover/Popover.vue
src/components/PopoverMenu/PopoverMenuItem.vue

fix https://github.com/nextcloud/server/issues/18634

Use the popover component for the avatar menu

---

src/components/PopoverMenu/PopoverMenu.vue
src/components/PopoverMenu/PopoverMenuItem.vue

Required in https://github.com/nextcloud/server/pull/25229 for overrides like for example dark mode stylesheets.
Otherwise the rules would be too generic.

Make the popover menu more easily addressable

---

src/components/Avatar/Avatar.vue
src/components/PopoverMenu/PopoverMenuItem.vue

Use longtext with the avatar menu as it will mostly contain user names
and email addresses which can become long.
The longtext mode automatically triggers wrapping by default.
However, in the case of long email addresses we can't wrap on spaces, so
an ellipsis has been added as well.
(note, there is no white-space mode that can break in the middle of a string, so this is the best we got)
For https://github.com/nextcloud/spreed/pull/4976#issuecomment-763517914

Fix longtext appearance for avatar popover menu

---

src/assets/action.scss

Allows for longer German words which cannot be wrapper when they don't
contain spaces.
In case a longer text if present that doesn't fit and cannot wrap, like
an email address, an ellipsis will now be shown.
Before:
After:

Increase max width of action button

---

package.json
src/mixins/richEditor/index.js

Linkify-urls is redundant as we already had a library.
Linkify-urls is not compatible with Safari as it's designed to be used
on Node JS and it uses non-polyfillable regexp features.
@nickvergessen please test this with Safari, also with Talk.

Replace linkify-urls with linkifyjs

---

src/components/Popover/Popover.vue

Revert the workaround that existed to dodge popper.js glitch where the
popover appeared in the wrong position first and a few milliseconds
later in the right place.
This fixes a regression where the regular Popover wasn't working any
more.
Fixes https://github.com/nextcloud/nextcloud-vue/issues/1681
The glitch will be addressed in https://github.com/nextcloud/nextcloud-vue/issues/1683

Revert workaround for popper glitch, fix regression

---

src/components/AppNavigationItem/AppNavigationItem.vue

All unwrapped HTML in the documentation section are now wrapped with backticks, allowing them to be render as code in markdown
1. Example and codes for "Usage" > "Simple Element" > spinning loader did not render
| :-- | :-- |
| ![image](https://user-images.githubusercontent.com/8733840/107154766-b2822900-69af-11eb-864e-94c599ce765b.png) | ![image](https://user-images.githubusercontent.com/8733840/107154768-b4e48300-69af-11eb-8cee-403f3beaf017.png)
2. Documentation for "Usage" > "Element with counter" renders incorrectly
| :-- | :-- |
| ![image](https://user-images.githubusercontent.com/8733840/107154821-e9583f00-69af-11eb-94e6-7165c78e4a17.png) | ![image](https://user-images.githubusercontent.com/8733840/107154822-eb220280-69af-11eb-81d2-78aede5609aa.p …

Fix documentation issue for AppNavigationItem due to unwrapped HTML

---

src/assets/action.scss

As discussed with @jancborchardt 

Update action hover feedback

---

src/components/AppSettingsDialog/AppSettingsDialog.vue

fix #1629 
https://user-images.githubusercontent.com/26852655/107752618-e98d6d00-6d16-11eb-9670-47ac9c2e0b42.mp4

Improve settings dialog layout

---

src/components/AppSettingsDialog/AppSettingsDialog.vue

Don't ellipsize caption if there's available space.

Fix settings navigation layout

---

src/mixins/excludeClickOutsideClasses/index.js

Fix https://github.com/nextcloud/nextcloud-vue/issues/1689
See https://github.com/nextcloud/files_pdfviewer/issues/281

Make sure we can check the classList on the node

---

src/components/Actions/Actions.vue

Add slot for Material design icons to the actions 
https://user-images.githubusercontent.com/26852655/108392906-0f30df80-720b-11eb-873a-a0421f994390.mp4

Add support for material design icons

---

src/components/Actions/Actions.vue

Allow to disable the main action button (either single action or menu toggle)
Example:
https://user-images.githubusercontent.com/26852655/109001436-dc6c6880-769c-11eb-9754-dc55aa178881.mp4

Add disabled state to actions

---

src/components/AppNavigationItem/InputConfirmCancel.vue

Currently there is a bug in the `AppNavigationItem` component: When an item is editable, the user can open the edit form but that is always empty. This can easily be seen on the [styleguide site](https://nextcloud-vue-components.netlify.app/#/Components/App%20containers/AppNavigation?id=appnavigationitem). Just click on the edit icon and the text field is going to be empty.
This change will avoid that by avoiding duplication of the value in the subcomponent.
As I am a first-time contributor, I hope this is going to meet your requirements. If not, please tell me so.

Use data of parent component in InputConfirmCanel subcomponent

---

src/components/Avatar/Avatar.vue

Fix #1428 
Improves talk loading (by skipping 40+ status requests) when the status is preloaded already

Allow to inject preloaded user statuses

---

src/components/AppSettingsDialog/AppSettingsDialog.vue
src/components/Avatar/Avatar.vue
src/components/EmojiPicker/EmojiPicker.vue
src/components/Modal/Modal.vue

Added container property for Modal, AppSettingsDialog, EmojiPicker and
the menu of the Avatar component.
These are needed to make it possible to use them in fullscreen mode.
See https://github.com/nextcloud/spreed/issues/5027

Add a container property to popup components

---

src/components/Multiselect/index.scss

When we select an item from the multiselect dropdown, the item it is not shown in the input field while the dropdown is active. This bring a lot of confusion to users as they are not sure if they selected smth or not. This PR fixes that.

Improve multiselect tag

---

src/components/Actions/Actions.vue
styleguide.config.js

Render the first action icon slot if single action

---

src/components/Actions/Actions.vue

Whenever the trigger of a single action item or the trigger of an action
menu is focussed or blurred, re-emit the event on the Action component
for outside processing.
Fixes https://github.com/nextcloud/nextcloud-vue/issues/1617
Can be seen in use in https://github.com/nextcloud/spreed/pull/4666 where we need to track whether a button is focussed to prevent removing the hover and preventing to hide the buttons there.

Actions forward focus and blur events on trigger

---

src/components/Actions/Actions.vue
src/components/Popover/Popover.vue

Because "@after-show" is still happening too early due to v-tooltip's
use of "requestAnimationFrame" we can't rely on its events to tell us
when the popover is actually visible.
This workaround introduces an additional Popover event "after-show" and
"after-hide" that are based on monitoring the inner "isOpen" property
which is the one toggling the CSS visibility.
The Actions popover logic now uses "after-show" to reliably apply the
focus on the first action element.
Fixes https://github.com/nextcloud/nextcloud-vue/issues/1760
See https://github.com/Akryum/v-tooltip/issues/661 for the upstream issue.

Fix actions dropdown focus timing

---

src/components/Breadcrumb/Breadcrumb.vue
src/components/Breadcrumbs/Breadcrumbs.vue

This PR allow the last breadcrumb in the breadcrumbs bar to shrink, in case all other breadcrumbs are already hidden. This prevents the breadcrumb from overflowing on narrow screens (e.g. iPhone 8).
Before:
After:

Allow last crumb to shrink if all crumbs collapsed

---

src/components/SettingsSection/SettingsSection.vue

Under the assumption it is a bug and not a new design feature, this fixes:
- SettingsSection was missing the separating border at the bottom
- Distance of Header and desciption adapted:
Settings before Vue:
Settings currently on Vue-Components:
Settings after this PR is merged:

Fix Settings css

---

src/l10n.js
webpack.common.js

On Password-Policy the usage of _SettingsSection_ instead of a simple _div_ blew up the package-size from `100 KiB` to `330 KiB` of which `140 KB `are the `l10n.js` of vue-Components. So i thought about how to reduce this.
The current implementation inserts the pot-file as json, and packs this within the bundle. However, there is a huge overhead on that kind of storing. So the idea was to reduce the overhead by storing only necessary data.
As model i initially used the json-format as translations are stored within apps.
- Unfortunately i didn't find a npm-package/a way to store in the desired format, the recommended package (po2json) seems to be unmaintained and breaks on plural-translations.
- Therefore this approach now manually transforms/compresses the format and decompresses it …

Minimize bundled translations

---

src/components/AppSidebar/AppSidebar.vue

This is the backport of #1767 to stable2.
Interestingly, the cypress screenshots didn't change, but that should be fine, since the issue was due to a server rule interfering.

Fix compact sidebar subtitle not visible, backport to stable2

---

build/extract-l10n.js
l10n/messages.pot
src/components/AppSidebar/AppSidebar.vue
src/components/SettingsInputText/SettingsInputText.vue
src/components/SettingsSection/SettingsSection.vue

Two small things:
- As plural-translations have a format of `n('%n Action', '%n Actions', n)` the extraction needs to use parameters 0 and 1. Didn't get recognized, as there are currently no plural-translations on this repo.
- Currently, translations do not get extracted if they are directly written within a html-property. Normally that should be fixed on extraction, however, the author seems to be on a bigger rewrite (since two years? https://github.com/lukasgeiter/gettext-extractor/issues/31 🤔), so this is a quick and simple workaround to put them on new lines.

Fix translation extraction

---

src/components/Breadcrumbs/Breadcrumbs.vue

In some cases, breadcrumbs which should be hidden would not have the correct class set, causing them to still be visible. This was because the breadcrumbs were not rendered yet, when the class was applied. Hence `crumb.elm` was `undefined` and the class could not be applied. In case a rerender was triggered (e.g. by opening the Dropdown menu), the correct class was then set and the crumbs were correctly hidden.
I changed the code to now double check after the render function was called and has finished (in the `updated` hook), that the correct class is set for the crumbs to hide.
This PR also fixes a small papercut introduced by #1771 where the `min-width` would cause the last crumb to be wider than necessary if the content was narrow. In some cases this caused the crumbs to be completely …

Ensure that crumbs to hide have correct class

---

src/components/Actions/Actions.vue

Only a very narrow set of attributes were passed to the element if only one action were displayed.
Example (the download is NOT applied to the action without this PR):
```vue
<ActionLink
download="123456"
icon="icon-download"
:close-after-click="true"
:href="currentFile.davPath">
{{ t('viewer', 'Download') }}
</ActionLink>
```

Make sure to pass all props and attributes to single-action Actions

---

src/assets/action.scss

Once again, just two small css-fixes:
- Longtext-actions had a fixed width, which was a bit unhandy in case the text length was just close above the switching-length
- Longtext-actions were a bit misaligned in height.
Left **before**, right **after:**

Fix Actions css

---

src/components/Avatar/Avatar.vue
src/components/ListItemIcon/ListItemIcon.vue

Because we `v-bind="$attrs"` to the avatar component, declaring id pass it to the `$props` and make sure we are not having a duplicate ID on the page

Add id prop to ListItemIcon to prevent v-binding to the Avatar

---

src/components/AppNavigationToggle/AppNavigationToggle.vue

This is another approach to https://github.com/nextcloud/nextcloud-vue/pull/1843. We simply use `ActionButton` for the `AppNavigationToggle` now and let it do the heavy lifting.
hover/focus feedback after:

Use ActionButton for AppNavigationToggle

---

src/components/AppNavigation/AppNavigation.vue
src/components/ListItem/ListItem.vue
src/components/ListItem/index.js
src/components/index.js
styleguide.config.js

This component will be used for talk's conversations, mail's envelopes and contact's list items. The goal here is to have a unified 'layout component' that you can wrap with your custom one and add your own logic on top of it.

Create ListItem component

---

src/components/ActionCaption/ActionCaption.vue
src/components/ActionCaption/index.js
src/components/Actions/Actions.vue
src/components/index.js

Upstreaming talk's `actioncaption`, as per the original @jenniferpiperek design

Create ActionCaption component

---

src/components/ListItemIcon/ListItemIcon.vue

Needed to make sure the events listeners we apply to the parent are forwarded
You can test on the docs, on master, adding a `@click=` does not work.
Here, it does :)
```vue
<template>
<ListItemIcon title="User 1" @click="alert" />
</template>
<script>
methods: {
alert() {
alert(...arguments)
}
}
}
</script>
```

Fix ListItemIcon listeners

---

src/components/CheckboxRadio/CheckboxRadio.vue
src/components/CheckboxRadio/index.js
src/components/index.js

- Uses the Material design icons
- Supports simple, sets and single-set checkboxes + radio (see docs)
- Supports indeterminate state
- Very straightforward! :rocket: 
A few examples:

Add CheckboxRadio component

---

src/components/ListItem/ListItem.vue

Add slot for third line in listitem component

---

src/components/Actions/Actions.vue

This fixes the alignment of the material design icon in a single action.
Before:
After:
Closes #1884.

Fix alignment of md icons in single action

---

src/components/CheckboxRadio/CheckboxRadio.vue

Add loading state to CheckboxRadio

---

src/components/CheckboxRadioSwitch/CheckboxRadioSwitch.vue
src/components/CheckboxRadioSwitch/index.js
src/components/index.js

Implement switch mode to CheckboxRadioSwitch

---

src/components/DatetimePicker/DatetimePicker.vue
src/components/DatetimePicker/index.scss

This is the trivial but imperfect fix for #998. We allow to attach the datepicker to body instead of the parent DOM element, so that the datepicker is not cropped by the AppSidebar.
The good thing about this solution is that the probability of breaking anything is quite low, since the default behaviour is unchanged (the change to the CSS is only necessary, because the datepicker attached to body has no `.mx-datepicker` container anymore).
The bad thing is, that the datepicker will scroll with body when attached to it (but it re-opens at the right position):
I have a more sophisticated solution in #1881 which solves the scrolling problem and works very nicely, but it requires changes to AppSidebar and to the datepicker library we use. I will provide a separate PR for it.

Allow to append datepicker to body

---

src/components/AppNavigationItem/AppNavigationItem.vue

Fix #1868 and adds 4px padding on top and bottom too so that the actions hover circle doesn't intersect with the boundary of the element

Fix appnavigationitem layout

---

src/components/AppNavigationItem/AppNavigationItem.vue
src/components/CounterBubble/CounterBubble.vue
src/components/CounterBubble/index.js
src/components/ListItem/ListItem.vue
src/components/index.js

Because we need a more generic bubble, like in this example:
This is from https://github.com/nextcloud/spreed/pull/5534
Keep the old file to not break existing imports.
I've tested it with some local Talk code that is using AppNavigationCounter and it properly redirects the component.
The only issue I see is that the style guide doesn't show the deprecation notice and replaces the component with the name:

Replace AppNavigationCounter with CounterBubble

---

src/components/AppNavigationItem/AppNavigationItem.vue

This was a trick to differentiate the pinned to the non-pinned entries, but other elements does not have this `pinned` order feature (like the AppNavigationCaption), and therefore gets stuck all in the top.

Remove AppNavigationItem flex order for AppNavigationCaption

---

src/components/DatetimePicker/DatetimePicker.vue
src/components/DatetimePicker/index.scss

This PR fixes the width of the datepicker when `show-week-number` is `true`.
Closes #1014.

Fix datepicker overflow when week numbers are shown

---

src/components/RichContenteditable/RichContenteditable.vue

In order: normal, `contenteditable=false`, `disabled=true`

Add disabled state to RichContenteditable and clean not-working v-model

---

src/components/AppSidebar/AppSidebar.vue

Because sometimes we need to wait for the sidebar to really be opened, let's add proper events.
Will help fix viewer tests that waits for the Sidebar to finish open
_____
Example (animation duration changed for this screencast)

Add proper opening/opened/closing/closed events & fix events docs

---

src/assets/action.scss

This fixes the alignment of the icon slot of the ActionRouter component in case the `router-link` renders to an `a` tag.
Before:
After:

Correctly align md icon in ActionRouter component

---

src/components/AppNavigationItem/AppNavigationItem.vue

fix #1868
Bringing back only the counter fix.

Fix counter margin

---

src/components/ActionButton/ActionButton.vue

This moves the icon span into the icon slot for the `ActionButton` component. This aligns it with the other Actions ~and prevents setting a background icon *and* providing an material design icon via slot.~ Nevermind, I just realized you can still provide a material design icon *and* have an icon set at the background.
But at least, this PR aligns it with how the other Action components handle it.
Closes #1925

Wrap icon span in icon slot for ActionButton

---

src/components/Breadcrumb/Breadcrumb.vue
src/components/Breadcrumbs/Breadcrumbs.vue

This PR adds support for a material design icon in the breadcrumb bar.
Closes #1928.

Allow material design icon in breadcrumb

---

src/components/AppSidebar/AppSidebar.vue
src/components/AppSidebar/AppSidebarTabs.vue
src/components/AppSidebarTab/AppSidebarTab.vue

This PR implements material design icons in the AppSidebarTabs header. The icon is not gray anymore when focused, which I think makes sense, as the text is black as well.
Before
After (sharing icon is provided by string):
Closes #1859.

Allow material design icons in AppSidebarTab

---

src/assets/action.scss

This prevents the ActionLink component from overflowing the dropdown menu in Firefox, which caused a scrollbar if the Actions were close to the viewport edge.
Before:
After:
Closes #1887.

Prevent overflow of action-link in Firefox

---

src/components/RichContenteditable/RichContenteditable.vue
src/mixins/richEditor/index.js

The user bubble is broken when there is a space in the username.
This was due to the parsed value being sanitized before applying regexp on it.
I simply changed the regexp to match `&quot;` instead of `"`.
This should fix: https://github.com/nextcloud/server/issues/26861
Before | After
-- | --

Fix user bubble when username contains a space

---

l10n/messages.pot
src/components/Avatar/Avatar.vue

Fixes https://github.com/nextcloud/nextcloud-vue/issues/613
This makes the avatar component focussable with the keyboard and also hitting the enter key will open the menu.
However the menu is not navigable and I'm not sure if we want to reimplement arrow navigation there.
Also, I heard that there will be a revamp of that popover, so the interaction in that popover would be different

Make avatar menu focusable with keyboard

---

src/components/ActionInput/ActionInput.vue

This fixes the size of the material design icon in the ActionInput component.
Before:
After:

Fix md icon size in ActionInput

---

src/components/ActionInput/ActionInput.vue

This fixes the padding of the ActionInput in case it is the first or last entry. The currently set margin lead to a gap between the popover arrow and the input element.
Before:
After:
In case one switches from ActionButton to ActionInput like it happens in Calendar, this will still lead to a "jumping" of the popover menu, since the ActionButton has a different height than the ActionInput with the additional padding (see https://github.com/nextcloud/calendar/pull/3016). But the gap is not there anymore.
On a side note: I would say the additional padding is not really necessary (or at least to high). But since this is supposed to be a bug fix PR, I didn't remove it, but instead made it work properly 😉. @jancborchardt maybe to check if this is really what it is supposed to look like.

Fix first and last action input padding

---

src/directives/Tooltip/index.js

Adds a slight delay to our tooltips, which at the moment appear immediately upon hovering elements.
Didn´t manage to capture the pointer in the gif, but you can get a sense of the timing of it by looking at the mouseover feedback

Delay all tooltips

---

src/components/AppSidebar/AppSidebar.vue

When the sidebar is animated with a v-if, the closed `event` will not be received by the parent's event listeners as the `AppSidebar` is destroyed before the end of the transition.
This PR adds a `beforeDestroy` hook in `AppSidebar` to emit the `closed` event before the destruction.

Ensure the closed event is dispatched in AppSidebar 

---

src/components/AppNavigationItem/AppNavigationItem.vue

If there are other actions or a counter in an AppNavigationItem and the edit mode is activated, the close button was not accessible:

AppNavigationItem: hide utils if edit mode is active

---

.eslintrc.js
package-lock.json
package.json
src/components/AppContent/AppContent.vue
src/components/AppContent/AppDetailsToggle.vue

Hi! So this is the new counterpart to a Pull Request originally made in https://github.com/nextcloud/mail/pull/4123. 
It was suggested to move the implemention into the global component, so that other apps are able to use this as well. Here are some details about the implementation:
This is (still) using the [splitpanes](https://antoniandre.github.io/splitpanes/) package to do the heavy lifting. We've got two columns: `main` and `aside`. These two columns have `min`, `max` and default `size` widths defined [here](https://github.com/nextcloud/nextcloud-vue/compare/master...dotplex:enhancement/resizable-columns?expand=1#diff-937d3d5f5c1cfb86c454474540a49bc24a57cdabe0876f60e4e0aa018a5b9223R79-R90).
`splitpanes` fires an event called `resized` after a resize has occurred, which triggers a …

Resizable columns

---

src/components/Avatar/Avatar.vue

Adjusts position of loading spinner to be the same as the three dots
icon.
This also indirectly fixes the location where the menu will appear which
was shifted before this fix.
This is a **regression** that was introduced in master/4.0.0
For https://github.com/nextcloud/spreed/issues/5492
Screenshots from testing in the Talk app:
Before:
(randomly shifted due to spinner position)
After:

Fix alignment of loading spinner in avatar menu

---

src/components/AppNavigationCaption/AppNavigationCaption.vue

```vue
<AppNavigationCaption
title="Your caption goes here" />
```
|![image](https://user-images.githubusercontent.com/14975046/121481093-12bfc080-c9cc-11eb-8d10-38ddb258c26d.png)|![image](https://user-images.githubusercontent.com/14975046/121480983-f4f25b80-c9cb-11eb-8a9e-d66675e28fc8.png)|

Fix flex order of AppNavigationCaption

---

src/components/AppContent/AppContent.vue

Variable is set -> default is used, developers *can* overwrite the prop value
Variable is not set -> prop become required
Right now you can't use the AppContent without the global variable, because the code that sets the default is always evaluated and will throw a ReferenceError before the developer can even specify their own value. Ref https://github.com/nextcloud/mail/pull/5165#issuecomment-858724634.
Then we can avoid hacks like https://github.com/nextcloud/spreed/commit/c6627446672379bf1913ffe898df460d1776b4af
The code is untested because neither @GretaD nor I can build this library at the moment.

Safely check the global appName and handle its inexistence

---

src/components/AppContent/AppContent.vue

Initial somehow fallback to `inline`, For proper sizing and people using virtual scrollers, let's go back to traditional `block`
Also, because this is a high-level scoped selector, !important is not needed and will allow apps to override this if needed :shrug: 
Fixes contacts + circles

Fix AppContent mobile display

---

src/components/ActionButton/ActionButton.vue
src/components/Actions/Actions.vue
src/components/AppNavigationItem/AppNavigationIconCollapsible.vue
src/components/AppNavigationNew/AppNavigationNew.vue
src/components/AppNavigationSettings/AppNavigationSettings.vue
src/components/ColorPicker/ColorPicker.vue
src/components/Modal/Modal.vue
src/components/PopoverMenu/PopoverMenuItem.vue

Closes #2068 
Button elements which have explicit `type` attributes have been left unchanged.

Add type=button attribute to buttons

---

README.md

- Pull the latest changes from `master` or `stableX`;
- Checkout a new branch with the tag name (e.g `v4.0.1`): `git checkout -b v<version>`;
- Run `npm version patch --no-git-tag-version` (`npm version minor --no-git-tag-version` if minor). This will return a new version name, make sure it matches what you expect;
- Commit, push and create PR;
- Add the change log content from the 'Changelog' action on Github to `CHANGELOG.md`;
- Commit and push;
- Get your PR reviewed and merged;
- Create a release on github with the version as tag (e.g `v4.0.1`) and add the changelog content as description (https://github.com/nextcloud/nextcloud-vue/releases);

Simplify release process

---

src/components/Modal/Modal.vue

In some aspect ratios the videoplayer controls are hidden behind the prev and next divs. This PR makes sure that the videoplayer controls are always usable.
https://user-images.githubusercontent.com/42591237/125089325-973a5780-e0ce-11eb-8671-de043990f7bc.mp4
https://user-images.githubusercontent.com/42591237/125089347-9acdde80-e0ce-11eb-82a6-ca2f5228e5c9.mp4

Fix videoplayer controls in viewer

---

src/components/Modal/Modal.vue

3000 ms is a bit short for most images, imho. Hence I propose increasing it to 5000 ms.

Set default slideshowdelay to 5000 ms

---

src/components/RichContenteditable/RichContenteditable.vue

Otherwise the error is shown in the console:
```
[Vue warn]: Failed to resolve directive: tooltip
(found in <RichContenteditable>)
```

Add a hint about the tooltip directive

---

src/mixins/userStatus.js

We have to check that the userId is defined before we run a request.
Closes #2155.

Check that userId is defined before querying

---

src/components/ActionButton/ActionButton.vue
src/components/Actions/Actions.vue
src/components/AppContent/AppContent.vue
src/components/AppNavigationCaption/AppNavigationCaption.vue
src/components/AppNavigationIconBullet/AppNavigationIconBullet.vue
src/components/AppNavigationItem/AppNavigationItem.vue
src/components/AppNavigationToggle/AppNavigationToggle.vue
src/components/AppSidebar/AppSidebar.vue
src/components/Avatar/Avatar.vue
src/components/Breadcrumbs/Breadcrumbs.vue
src/components/DatetimePicker/DatetimePicker.vue
src/components/Multiselect/Multiselect.vue
src/components/MultiselectTags/MultiselectTags.vue
src/components/Popover/Popover.vue
src/components/SettingsSelectGroup/SettingsSelectGroup.vue
src/components/UserBubble/UserBubble.vue

This PR makes sure we don't use the deprecated named / scoped slot syntax in the library anymore, see https://vuejs.org/v2/guide/components-slots.html#Deprecated-Syntax
This is a necessary preparation for migrating to vue@3 and is supported in vue@2.6 already, so nothing will break. See https://v3.vuejs.org/guide/migration/migration-build.html#preparations
Related to #2154.

Use new named slot syntax

---

src/components/Modal/Modal.vue

Currently, there are many open points regarding modal sizes that each developer needs to decide and implement. This leads to unecessary code duplication, maintenance effort and inconsistent UI because each developer implements the sizing differently. Hence here is my proposal to standardize the modal sizes completely.
It also includes always using full screen modal on mobile which is the superior experience on mobile, imho.

standardize modal sizes

---

src/components/AppNavigationSettings/AppNavigationSettings.vue

This PR replaces the current settings icon with the material design equivalent and also fixes the settings label alignment to the `AppNavigationItem` component. Supersedes #2210, closes #2138 and fixes the second part of #2199.
After:
Before:

Use material design icon for settings icon

---

src/components/EmptyContent/EmptyContent.vue

Please note that in english it seems centered. **Switch language** to observe left-aligned content.
Before
After

Center align text

---

src/components/ListItem/ListItem.vue

fixes: https://github.com/nextcloud/mail/issues/5484
before
after

Make timestamp of unread msg not bold

---

src/components/Actions/Actions.vue

If there is only one Action and it is disabled, the whole Actions component gets disabled now. Before, the Action would still be enabled.
After:
Before:
Closes #1904.

Disable actions when the only action is disabeld

---

src/components/Highlight/Highlight.vue
src/utils/FindRanges.js
tests/unit/components/Highlight/Highlight.spec.js
tests/unit/utils/FindRanges.spec.js

This ensures that we do not duplicate characters in the Highlight component, even if the user supplies overlapping ranges. And that we only match the first occurence of overlapping matches when the user supplies a string to search for.
I also added some unit tests to check for the correct functioning.
After:
Before:
Closes #2191.

Do not duplicate character in Highlight directive, only highlight first match occurence

---

docs/index.md
l10n/messages.pot
src/components/AppContent/AppDetailsToggle.vue
src/components/AppNavigationItem/InputConfirmCancel.vue
src/components/AppNavigationToggle/AppNavigationToggle.vue
src/components/AppSettingsDialog/AppSettingsDialog.vue
src/components/DatetimePicker/DatetimePicker.vue
src/components/RichContenteditable/RichContenteditable.vue
src/components/SettingsSelectGroup/SettingsSelectGroup.vue
styleguide/global.requires.js

This removes the necessity to bind `window.t` to `Vue.prototype.t`. This makes using the components a bit less error prone on first usage and cleans up the Vue instance. The Netlify build still looks fine and e.g. the Calendar app works well.
We should furthermore not use `this.t(...)` (i.e. the `l10n` mixin) as it breaks the l10n extraction. The mixin is fine if we need `t` for the template though.
Closes #586.

Don't rely on Vue.prototype.t and properly extract all strings

---

src/components/UserBubble/UserBubble.vue
src/components/UserBubble/UserBubbleDiv.vue
styleguide.config.js

Fixes #2200. Supersedes #2234.
The problem was that we use a `div` in case the default slot is empty and then `<template #trigger>` is simply not rendered anymore.
I introduced a component which just renders a `div` as a wrapper for the #trigger slot in case the default slot is empty.
UserBubble without default slot on netlify:

Fix empty user bubble

---

package-lock.json
package.json

Revert #2245 after accidental merge, adjustments need to be made due to breaking changes

Revert "Bump linkifyjs from 2.1.9 to 3.0.0"

---

src/components/Actions/Actions.vue

https://github.com/nextcloud/server/pull/28835

Stop filtering Actions in $slots

---

src/components/ActionLink/ActionLink.vue
src/components/ActionRouter/ActionRouter.vue
src/components/Actions/Actions.vue
src/components/PopoverMenu/PopoverMenuItem.vue
src/mixins/richEditor/index.js

Links passed to components are not necessarily endorsed so this adds `nofollow` onto the existing `noopener noreferrer`
As detailed in https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types :)

Add nofollow to tell search engines that links are not endorsed

---

l10n/messages.pot
src/components/AppNavigationItem/AppNavigationItem.vue
src/components/AppNavigationSettings/AppNavigationSettings.vue
src/components/AppSidebar/AppSidebar.vue

This allows material design icons for the AppNavigationItem menu and replaces the ActionButton icons with md icons as well.
Closes #2198.
| | Before | After |
|-|-|-|
| Custom Icon |![Screenshot 2021-09-07 at 22-24-16 Week 36 of 2021 - Calendar - Nextcloud](https://user-images.githubusercontent.com/2496460/132406460-355871fe-950c-418c-9724-955c31ee520e.png)|![Screenshot 2021-09-07 at 22-24-42 Week 36 of 2021 - Calendar - Nextcloud](https://user-images.githubusercontent.com/2496460/132406469-c5f1fb71-4950-4b33-a1ee-ed8b6b511f02.png)|
| Editable |![Screenshot 2021-09-07 at 22-27-35 Nextcloud Vue Style Guide](https://user-images.githubusercontent.com/2496460/132406589-e2f6b251-ac87-406d-afa8-6954767a8467.png)|![Screenshot 2021-09-17 at 21-20-51 Nextcloud Vue Style …

Allow material design icons for appnavigationitem

---

package-lock.json
package.json
src/components/AppSidebar/AppSidebar.vue
src/directives/Linkify/index.js
src/mixins/richEditor/index.js
src/utils/Linkify.js

This unifies the linkify-string usage (we had this function in two places) and switches to the linkify-string package which replaces linkifyjs/string since the latest major release of linkifyjs.
Supersedes https://github.com/nextcloud/nextcloud-vue/pull/2257.
Closes https://github.com/nextcloud/nextcloud-vue/issues/1488.

Unify linkify usage, move to linkify-string

---

src/components/AppNavigationItem/AppNavigationItem.vue
src/components/AppNavigationSettings/AppNavigationSettings.vue

there's a lot of space between the icon and the label. On mail app that doesnt look good when we have more than one level submailbox. Even though we removed the option to add more than one level submailbox, the people who added more than one level before we removed it, have problem reading the name of their mailboxes. 
**before**
**after**

Fix the space between navigation icon and label

---

src/components/PopoverMenu/PopoverMenuItem.vue

Before:
After:
Signed-off-by: Carl Schwan <carl@carlschwan.eu>

Remove whitespace from PopoverMenuItem when displaying emoji

---

src/components/AppSidebar/AppSidebarTabs.vue

The style was applied to the containing element instead of the icon element.
Don't know why the `background-position: center 8px;` was needed, so I removed it. It was also shifting icons toward the bottom when applied to the icon.
Tested in `styleguide`.
Fix: https://github.com/nextcloud/activity/issues/669
Problem introduced here: https://github.com/nextcloud/nextcloud-vue/pull/1939

Change background style target for tab icons

---

src/components/Multiselect/Multiselect.vue

Currently the `closeOnSelect` property of vue-multiselect is just overwritten by `!multiple`.
This PR aims to make `closeOnSelect` independently usable. If it is not set by the user, it will still fall back to `!multiple`.

Free closeOnSelect

---

src/components/AppNavigationItem/AppNavigationItem.vue

This is the alternative to #2406. We increase the padding-right of `AppNavigationItem` to 8 px here.
The result is the same, the `ActionsMenu`s of `AppNavigationItem`, `AppNavigationCaption` and `ListItem` are nicely aligned, they just all have a right-padding of 8 px here:
Make your choice between #2406 and this one and approve the PR you like better 😉

Increase padding right of AppNavigationItem to 8 px

---

package-lock.json
src/components/DatetimePicker/DatetimePicker.vue

First step towards properly defined translations.
The only thing missing is translating nice strings in the input, for that we need to use the `formatter` prop with moment, so far this can be done in the app directly:
https://github.com/mengxiong10/vue2-datepicker/tree/v3.10.0#formatter
```js
formatter: {
stringify: (date) => {
return date ? moment(date).format('LL') : ''
},
},
```
Supersede: https://github.com/nextcloud/nextcloud-vue/pull/146

Automatically use Nextcloud translated months, days and years

---

src/components/Breadcrumbs/Breadcrumbs.vue

This replaces the folder icons of the hidden crumbs actions dropdown with a material design icon.
Before:
After:
Part of fixing #2410.

Use MD icon for hidden crumbs action button icons

---

src/components/Breadcrumb/Breadcrumb.vue
src/components/Breadcrumb/breadcrumb-light.svg
src/components/Breadcrumb/breadcrumb.svg
src/components/Breadcrumbs/Breadcrumbs.vue

First step to fix #2410.
The breadcrumb now uses `ChevronRight` as a separator and has a background as hover feedback.
For a live example, please have a look at the docs:
https://deploy-preview-2411--nextcloud-vue-components.netlify.app/#/Components/Breadcrumbs?id=breadcrumbs-1
I had to rename the component class to `vue-crumb` since the server CSS kept interfering. If we want to use `crumb` instead, we will have to explicitly overwrite all interfering server rules.
Still todo see https://github.com/nextcloud/nextcloud-vue/issues/2410#issuecomment-998298730

Adjust breadcrumb appearance

---

src/components/Breadcrumb/Breadcrumb.vue

This fixes dragging stuff onto crumbs that are hidden. Before the menu would immediately close after leaving the three-dots-menu, since the dropdown was attached to body, thus triggering the dragLeave handler when hovering over the dropdown.
I wanted to show a screencast, but peek doesn't work with Wayland anymore, so you gotta trust me with this one :wink:  :see_no_evil:

Fix dragging onto hidden crumbs

---

src/components/Breadcrumb/Breadcrumb.vue
src/components/Breadcrumbs/Breadcrumbs.vue

This PR implements to customize the menu icon for the `Actions` menu of each breadcrumb. We can now e.g. use `MenuDown` for the actions menu of the last breadcrumb. I adjusted the docs to demonstrate this:

Allow custom action menu icon for breadcrumb

---

src/components/ListItem/ListItem.vue

fixes #2340
Added new prop that allows developers to always show the actions to the right of details and counter. See second item in the list.
https://user-images.githubusercontent.com/26852655/147488721-bdec8b86-c327-41a7-87a2-0dc5369ea88f.mov

Add option to always show actions

---

src/components/Actions/Actions.vue

This changes the behavior of the `Actions` component so that if a `menu-title` is provided, it can be shown for single Actions as well by setting the `forceTitle` prop to `true`. This is necessary for the changes to the Breadcrumbs component requested in #2416 so that the breadcrumb title of the last crumb is also shown if only a single Action is given. In case of multiple Actions, i.e. with a dropdown, or when `menu-title` or `force-title` is not set, nothing changes.
Before:
After:
~@skjnldsv @nextcloud/vuejs In the current form this is a breaking change, since `menu-title` will be shown if it is set, which it was not before for single actions. Do you prefer that I keep the previous behavior and make showing the title for single actions optional by a new prop?~
Edit: I decided to make …

Show menu title for single Action

---

src/components/Actions/Actions.vue

For Actions with menu-title showing a material design icon, the icon position was off.
Before:
After:

Fix md icon position for Actions with title

---

src/components/Breadcrumbs/Breadcrumbs.vue

In order to show an `Actions` or `Button`component (or actually anything else you put into the slot) directly adjacent to the right of the last crumb, the element needs to be a child of the breadcrumbs container. So I added a slot and take the elements width into account when hiding the overflowing crumbs.
This is how it looks now with a button:
And an Actions component:
This is the last step (maybe 🙂) in order to make it look like @nimishavijay mockup:

Implement showing global crumb actions

---

src/components/Breadcrumbs/Breadcrumbs.vue

As per https://github.com/nextcloud/nextcloud-vue/pull/2411#discussion_r772871567 this adds a constant to store the `vue-crumb` class prefix.
This is only a minor code cleanup and does not bring any design or functional changes.

Add variable for crumb class name

---

src/components/ActionInput/ActionInput.vue

resolve https://github.com/nextcloud/calendar/issues/3932
ActionInput has been extended with attribute "aria-label"
Signed-off-by: julia.kirschenheuter <julia.kirschenheuter@nextcloud.com>

Add aria label to the ActionInput component

---

src/components/AppNavigationItem/AppNavigationItem.vue

fixes https://github.com/nextcloud/mail/issues/5987
this.$slots will be updated in created() and beforeUpdate() lifecycle-hooks

AppNavigationItem.vue: updating of this.$slots

---

src/components/Breadcrumb/Breadcrumb.vue
src/components/Breadcrumbs/Breadcrumbs.vue

After the major changes to the breadcrumb bar in #2411 and #2444 the last breadcrumb does not shrink anymore on small screens. This PR fixes it.
| | Before | After |
| ------------- |:-------------:| -----:|
| Without Actions      | ![before_without](https://user-images.githubusercontent.com/2496460/153669608-15b372ce-46e7-4344-b3f8-176320bbe4d9.gif)  | ![after_without](https://user-images.githubusercontent.com/2496460/153670377-49c9a68b-ae9c-43af-80e4-a64a5b6dd109.gif) |
| With Actions      | ![before_with](https://user-images.githubusercontent.com/2496460/153669696-9c79b9e5-b68c-4818-85b4-50c547a9e44a.gif) | ![after_with](https://user-images.githubusercontent.com/2496460/153670440-355ff073-ff5b-4b0c-a862-988a1a459873.gif) |

Fix shrinking of last breadcrumb for narrow width

---

src/components/AppNavigationItem/AppNavigationItem.vue

change appearance of the slot "icon": instead of removing the icon-slot from DOM the icon-slot will be hidden. This is needed to keep the focus on the element inside of slot.
Required for https://github.com/nextcloud/calendar/pull/3960

Change appearance of the slot "icon" at AppNavigationItem

---

src/functions/emoji/emoji.js

No need to import from src. These are exported fine in the dist.
Importing from src also caused issues in jest tests in the text app
as they do not transform the src import:
https://github.com/nextcloud/text/runs/5315732664?check_suite_focus=true#step:7:85

fix: imports from emoji-mart-vue-fast

---

src/components/Breadcrumb/Breadcrumb.vue

Matching the API https://v3.router.vuejs.org/api/#to

Allow Breadcrumbs "to" prop to be an object

---

src/components/Modal/Modal.vue

increase the small modal width

---

src/components/Button/Button.vue

Allows to have `<Button native-type="submit">Send</Button>` in a form and listen on the `@submit` event instead of the `@click` one.

Add button native type prop on <Button>

---

src/components/Actions/Actions.vue

🐛 (#2529): fix missing firstAction

---

src/components/Button/Button.vue

Was broken again by this suggestion:
https://github.com/nextcloud/nextcloud-vue/pull/2540#discussion_r821644569
I didn't notice it as npm link is broken with the vue lib and I seem to not have recompiled all levels

Fix error spam of icon only buttons part2

---

src/components/Popover/Popover.vue

This PR *tries* to takes a further step towards the standardization of border radii. Currently, border radii are not uniform. Among other things, buttons have a very high border-radius, while Popovers are only allowed a 3px border-radius, and lists have none.
In the current state of this PR, here are some examples:
| --- | --- |
| ![check-1](https://user-images.githubusercontent.com/12123721/159508163-76da304c-cf1d-4282-b604-a33478683ca1.png) | ![check-2](https://user-images.githubusercontent.com/12123721/159508210-29b3747f-21a9-42e1-a124-05ba3ee7ffed.png) |
| ![menu-1](https://user-images.githubusercontent.com/12123721/159508280-2b7558d9-26d0-4df9-bce3-b58de3d3681a.png) | ![menu-2](https://user-images.githubusercontent.com/12123721/159508292-62382943-39a0-4213-8a81-e3ff …

Use large corner radius for the Popover component

---

src/components/ProgressBar/ProgressBar.vue

The ProgressBar component was not shown in the documentation.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>

Fix the ProgressBar display in the documentation

---

src/components/Button/Button.vue

Add proper hover feedback to tertiary buttons whose icon aren't affected by the color css rule. e.g. emojis
https://user-images.githubusercontent.com/26852655/160430239-a1436f2d-9059-4b5d-821c-371f4d9bea41.mov

Fix tertiary buttons hover feedback

---

src/components/Button/Button.vue

Up till now now the icon only button we've been using almost always had a background "highlight" when hovered. This is fine for most buttons unless they have not enough white-space around them (within an input, a bar). So far the button component didn't offer this option. **This pr introduces tertiary buttons with background and makes them default.**  
So to summarise we'd have:
- **Default `tertiary` use case**: there's enough white-space around the button, so having background feedback is ok. This is what Actions currently have
https://user-images.githubusercontent.com/26852655/160655629-3453a25a-15ca-4f37-86f8-e9e38c5dfc9c.mov
- **`tertiary-no-background` use case**: the button has not enough space around it so we rely on opacity to provide the hover feedback. …

Add tertiary buttons with background and make them the default

---

src/components/RichContenteditable/RichContenteditable.vue

Fix https://github.com/nextcloud/server/issues/31781
|---|---|
| ![image](https://user-images.githubusercontent.com/42591237/161540538-ae32f017-4a9e-4c94-b441-f229994eab70.png) | ![image](https://user-images.githubusercontent.com/42591237/161540492-85addf55-e802-4d9c-9fa3-03f800962748.png) |

fix positioning of content text

---

.github/workflows/l10n.yml

Before the l10n check would run with npm 6 which is not what is specified in `package.json`.

Ensure l10n check uses right node and npm version

---

package-lock.json
package.json
webpack.prod.js

This updates webpack to the latest major version 5. I additionally only updated the really necessary dependencies to allow `npm install` to run correctly even without an existing `package-lock.json` (not sure if that's necessary, but I thought it's better).
I opted to do really small steps and not push `nextcloud/eslint-config` to the latest version yet, so that the PRs are easier to review and the history is cleaner. I would welcome this PR to be merged soon, because there are several dependencies to be updated still (I would like to test migrating an app to vue 3 and nextcloud/vue blocks this with its outdated dependencies).

Update to webpack 5

---

src/components/Popover/Popover.vue
src/directives/Tooltip/index.scss

This cleans up the CSS code for the popover and tooltip. Before the CSS code was a bit illogical. Before e.g. the `border-color` was set to a color on all sides in the general rule, and then overwritten to be transparent on three sides. Now it's the other way around, transparent everywhere and only one side is overwritten. This reduces complexity.
Since it does not visually change anything, I didn't attach any screenshot here. Just have a look at the docs and check that tooltip and popover (i.e. Actions) look the same.

Cleanup tooltip and popover CSS

---

package-lock.json
package.json
tests/visual/components/AppSidebar/AppSidebarMixin.js

This migrates to `@fontsource/roboto`. This does not bring any visual or functional changes, just updated the dependency to its new home.

Migrate to @fontsource/roboto

---

package-lock.json
package.json
src/components/Actions/Actions.vue
src/components/AppSidebar/AppSidebarTabs.vue
src/components/VNodes/VNodes.vue

For some reason `vue2-jest` does not like the functional component for rendering `VNodes` to be defined directly in the parent component. So I moved it to a separate file. The nice thing is, it reduces code duplication as well.

Migrate to @vue/vue2-jest

---

src/components/Breadcrumb/Breadcrumb.vue

This is a minor cleanup of the breadcrumbs bar. The Actions menu is now only rendered if Actions are actually present. Before, they were just hidden.
This does not change any functionality or appearance, just cleans up the HTML code and probably renders a bit faster.

Only show actions if actions given for breadcrumbs

---

src/components/Highlight/Highlight.vue
src/components/Multiselect/EllipsisedOption.vue
src/utils/GenRandomId.js
webpack.common.js

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.

Replace deprecated String.prototype.substr()

---

package-lock.json
package.json

This removes `vue-visible` which was not used.

Remove unused dependency vue-visible

---

src/components/ProgressBar/ProgressBar.vue

This fixes the `border-radius` of the `ProgressBar` component. I introduced a CSS variable to dynamically set the height. Since the variable is scoped to the respective element, it does not pollute the global scope and multiple progress bars can exist with different heights / border radii on the same page.
See this screenshot from the docs in Firefox (I temporarily increased the height with the dev tools to make it obvious):
And in Chrome:
Closes #2569.

Fix border radius for small progress bar

---

src/components/Button/Button.vue

Fix button disable state and reactivity

---

src/components/Modal/Modal.vue

Fix https://github.com/nextcloud/server/issues/31854

don't give normal and large modals a fixed height

---

package-lock.json
package.json
styleguide.config.js

Due to a problem of vue-styleguidist with webpack 5, we have to manually work around if for now. Fix is from https://github.com/vue-styleguidist/vue-styleguidist/pull/1308 and can be removed once the upstream fix is merged and released.

Fix styleguide serve

---

package-lock.json
package.json
styleguide.config.js

With the really quickly released new version of vue-styleguidist merged in https://github.com/nextcloud/nextcloud-vue/pull/2632 our adjustments from #2628 to make `npm run styleguide` work again are not necessary anymore. This PR removes them.

Cleanup styleguide config

---

src/components/Modal/Modal.vue

small cleanup of small modal size

---

src/components/Avatar/Avatar.vue

The life cycle hook `beforeDestroyed` is actually called `beforeDestroy`.

Fix lifecycle hook name in Avatar

---

src/components/AppNavigationNewItem/AppNavigationNewItem.vue

The `isMobile` mixin is unused in this component and can be removed.

Remove unused `isMobile` mixin from AppNavigationNewItem

---

package.json
src/components/Modal/Modal.vue

add focus-trap (https://github.com/focus-trap/focus-trap) for accessibility
https://user-images.githubusercontent.com/38529028/165922863-7cb781d4-2b3c-4a93-9c5f-06d6b26ba6c6.mp4
Signed-off-by: Vanessa Pertsch <vanessa.pertsch@posteo.de>

add handle keyboard focus for accessibility

---

src/components/EmojiPicker/EmojiPicker.vue

- on open : Search is in focus 
- if search is in focus, emojis are selectable by arrow keys  
- Categories and emojis are selectable by tab
Is this the behavior we want to see?

Make emojis selectable by tab

---

src/components/DatetimePicker/DatetimePicker.vue
src/components/DatetimePicker/index.scss

Also see nextcloud/calendar/pull/4105 for the discussion.
In this pr i fixed the missing margin on the buttons. I also widened the popup to fit all the controls aswell as made the text in those buttons centered.
Also i added color to the confirm button to match the 'primary' style of nextcloud. 
Here is an example of the fixes:

Update the css for the datepicker

---

src/components/AppSidebarTab/AppSidebarTab.vue
src/components/EmojiPicker/EmojiPicker.vue

Breaking change.
Follow-up of https://github.com/nextcloud/nextcloud-vue/pull/2594

Comply with eslint for event name

---

src/components/DashboardWidgetItem/DashboardWidgetItem.vue

This PR adds an `action` slot to the `DashboardWidgetItem` so that it's possible to provide different actions for each dashboard widget item. This also allows to provide material design icons for each action, which was not possible before. Closes #2685.
See https://github.com/nextcloud/tasks/pull/2017 for an example how this works.
In Tasks, we can now prevent showing actions for read-only tasks:
Before:
After:

Add actions slot to dashboard widget item

---

src/components/AppSettingsDialog/AppSettingsDialog.vue
src/components/AppSettingsSection/AppSettingsSection.vue

..Also gets rid of the annoying title without top margin when scrolling into view  
https://user-images.githubusercontent.com/26852655/171647817-72448a07-33bc-40ba-b0a1-9592e9ee1044.mov

Add title section to settingsdialog

---

src/components/ColorPicker/ColorPicker.vue

Necessary since Popover component got border-radius. Otherwise it feels a bit tight
| --- | --- |
| ![cp-before-](https://user-images.githubusercontent.com/12123721/159894498-d972ad43-0e5b-4208-b389-c39204531f2d.png) | ![cp-after-](https://user-images.githubusercontent.com/12123721/159894510-b31a2750-eb12-4feb-bb37-07201715b91e.png) |
| ![cp-before](https://user-images.githubusercontent.com/12123721/159894568-33d29508-3bc6-4cca-89c5-d0b4cf0b356e.png) | ![cp-after](https://user-images.githubusercontent.com/12123721/159894585-2cf12651-9ac0-4ddc-965b-d352b419dfa2.png) |

Increase padding of ColorPicker

---

src/components/ColorPicker/ColorPicker.vue

Not my most useful change, but feels more reactive.
https://user-images.githubusercontent.com/12123721/159895809-09569d4c-9044-4b7d-b107-c776985c8625.mov
https://user-images.githubusercontent.com/12123721/159895880-2b641a3d-0cd3-44be-a646-ee01e049ae70.mov

Add ColorPicker feedback on selection

---

src/components/AppNavigationNew/AppNavigationNew.vue

This replaces the simple button element in the `AppNavigationNew` component with the `Button` component and exposes an icon slot to add a material design icon. I also added a documentation example.
Implements part of #2707.

Add icon slot to AppNavigationNew component

---

l10n/messages.pot
src/components/Modal/Modal.vue

fix #2737
https://user-images.githubusercontent.com/26852655/172405851-89a1910d-9daa-4455-ba62-5f134145e07d.mov

Move close button within modal boundaries

---

src/assets/variables.scss
src/components/AppContent/AppContent.vue
src/components/AppNavigationToggle/AppNavigationToggle.vue

...Upstreaming more talk v-deeps
Before: 
After:

Properly align appnavigationtoggle

---

src/components/Modal/Modal.vue

reason behind this: as noticed in the accessibility workshop, the action buttons of the modal should always visible. Changing the default to -1 will allow to opt-in into the hiding of the action buttons which is in my opinion the better way to do this.

show the action buttons on top of the modal always by default

---

src/components/DashboardWidgetItem/DashboardWidgetItem.vue

Add padding 8px to DashboardWidgetItem actions

---

src/components/AppNavigation/AppNavigation.vue
src/components/AppSidebar/AppSidebar.vue

Close https://github.com/nextcloud/calendar/issues/4161
|---|---|
| ![image](https://user-images.githubusercontent.com/42591237/172866993-a75fba49-c86a-4a48-8be0-79e341551577.png) | ![image](https://user-images.githubusercontent.com/42591237/172866881-d7c7f6c6-8444-46c8-ba0d-729f41cd3027.png) |

make the sidebare full-width on small screens

---

src/components/Avatar/Avatar.vue

This PR adds a material design icon slot to the avatar component. Implements the second part of and closes #2707.
I also added an example for an avatar with a md icon.

Add md icon slot to Avatar component

---

src/components/AppNavigationItem/InputConfirmCancel.vue

This replaces the native buttons of `InputConfirmCancel` with the Button component from nextcloud-vue.
Before:
After:
Closes #2746.

Use button component for InputConfirmCancel

---

src/components/CheckboxRadioSwitch/CheckboxRadioSwitch.vue

This improves the `CheckboxRadioSwitch` accessibility as described in #2708.
No visual changes of the component result.
Closes #2708.

Improve CheckboxRadioSwitch accessibility

---

src/components/AppNavigationItem/AppNavigationItem.vue
src/components/AppNavigationNewItem/AppNavigationNewItem.vue
src/components/AppSidebar/AppSidebar.vue
src/components/Avatar/Avatar.vue
src/components/CheckboxRadioSwitch/CheckboxRadioSwitch.vue
src/components/Multiselect/Multiselect.vue
src/components/Multiselect/index.scss

| Component        | Before           | After  |
| ------------- |:-------------:| :-----:|
| `AppSidebar`      | ![Sidebar_before](https://user-images.githubusercontent.com/2496460/174159948-ceafb511-be96-46c6-b168-76105f8c4760.gif) | ![Sidebar_after](https://user-images.githubusercontent.com/2496460/174159984-0c33167d-f2bc-4657-9e73-55b680f48881.gif) |
| `AppNavigationItem` | ![AppNavigation_before](https://user-images.githubusercontent.com/2496460/174157474-ec5aca0d-ab7d-4a7b-a0f9-62895855887f.gif) | ![AppNavigation_after](https://user-images.githubusercontent.com/2496460/174157539-2f6964c6-7566-423f-ab60-cca4cecb37c4.gif) |
| `AppNavigationNewItem` | ![AppNavigationNew_before](https://user-images.githubusercontent.com/2496460/174157192-18216c0d-d3cf-4ef3-96a8-b035d1c45d92.gif) | …

Use loading icon everywhere

---

l10n/messages.pot
src/components/AppNavigationItem/AppNavigationIconCollapsible.vue

This replaces the native button in `AppNavigationItemCollapsible` with a vue button and adjusts the icons used to `ChevronRight` and `Chevron Down`.
Before:
After:
Closes #2783.

Use button-vue and chevron for appnavigation collapse

---

src/components/CheckboxRadioSwitch/CheckboxRadioSwitch.vue

This was inspired by https://github.com/nextcloud/server/issues/26691
A new boolean prop `buttonVariant` toggles between the classic style and this one. It can be used with all types.
If the CheckboxRadioSwitch elements are displayed next to each other vertically, their borders are "merged".
https://user-images.githubusercontent.com/11291457/174578908-5616d945-6ad4-4c9c-89fc-5cda32732f2f.mp4

Alternative style for CheckboxRadioSwitch (radio type)

---

src/components/ActionButton/ActionButton.vue
src/components/ActionInput/ActionInput.vue
src/components/ActionTextEditable/ActionTextEditable.vue
src/components/Actions/Actions.vue
src/components/AppNavigationItem/AppNavigationIconCollapsible.vue
src/components/AppNavigationItem/AppNavigationItem.vue
src/components/AppNavigationItem/InputConfirmCancel.vue
src/components/AppNavigationNew/AppNavigationNew.vue
src/components/AppNavigationSettings/AppNavigationSettings.vue
src/components/AppNavigationToggle/AppNavigationToggle.vue
src/components/AppSidebar/AppSidebar.vue
src/components/Avatar/Avatar.vue
src/components/Breadcrumbs/Breadcrumbs.vue
src/components/CheckboxRadioSwitch/CheckboxRadioSwitch.vue
src/components/ColorPicker/ColorPicker.vue
src/components/Modal/Modal.vue
src/components/SettingsSection/SettingsSection.vue

Since v5.0.0 of the lib, the property decorative has been removed.
This means the "decorative" is added to the span element, causing the
HTML validation to fail:
> Attribute decorative not allowed on element span at this point.
Upstream commit
https://github.com/robcresswell/vue-material-design-icons/commit/c65d8ea786ea49210193cb3129c12a68ed6c0baf
> This patch also removes the default title, encouraging better
> accessibility by removing unhelpful titles that dont indicate usage. The
> `decorative` prop has been removed and any icons that do not have a
> meaningful title will be hidden from screen readers.
Signed-off-by: Joas Schilling <coding@schilljs.com>

Fix vue material design icons HTML validation

---

src/components/ActionButton/ActionButton.vue
src/components/Actions/Actions.vue

- add `role=menu` to `Actions`
- add `role="presentation"` and `role="menuitem"` to `ActionButton`
Related: 
- #2502 
- https://github.com/nextcloud/text/pull/2715
Refs: 
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/menu_role

Actions - small a11y adjusts

---

src/components/Modal/Modal.vue

Signed-off-by: Vanessa Pertsch <vanessa.pertsch@posteo.de>

Change Prev/next links to buttons

---

src/components/AppSettingsDialog/AppSettingsDialog.vue
src/components/AppSettingsSection/AppSettingsSection.vue

Section titles were used before, but those are translated and can therefor
contain non-asci characters which are not allowed in HTML IDs.
Stripping them out is not possible as the remaining string might not be unique
anymore or even empty in case of languages with other charactersets like japanese
---
* This is a "save to backport" solution.
* For 5.4 or 6 we should consider making the ID non-optional to enforce good handling
* Sample PR for an app https://github.com/nextcloud/spreed/pull/7615
Fix  #2854

Fix invalid setting section IDs

---

src/components/Button/Button.vue

Add a button style for being used on primary like in the header

---

src/components/SettingsInputText/SettingsInputText.vue

This PR improves the style of the `SettingsInputText` component (and to see what I'm doing, add examples to the documentation).
While fixing the style, I removed some SCSS that seems unused (?)

Improve SettingsInputText component

---

src/components/Button/Button.vue

Follow-up to #2864. When `to` is provided, the button will act as a `router-link`.
Required for https://github.com/nextcloud/nextcloud-vue/issues/2768.

Turn the button into router-link when to is there

---

src/components/Button/Button.vue

Follow up to #2871
Before:
After:

Fix box shadow colour of "tertiary-on-primary" button

---

src/components/EmptyContent/EmptyContent.vue

Close https://github.com/nextcloud/nextcloud-vue/issues/2500
- Icons use inline `svg` markup https://github.com/robcresswell/vue-material-design-icons/blob/5.1.2/build.ts#L20-L28
- Icons have `role="img"` https://github.com/robcresswell/vue-material-design-icons/blob/5.1.2/build.ts#L18
- Icons are [decorative](https://www.w3.org/WAI/tutorials/images/decorative/) so they have the `aria-hidden` attribute https://github.com/robcresswell/vue-material-design-icons/blob/5.1.2/build.ts#L15
- Allow more flexibility in component usage without a title e.g https://github.com/nextcloud/nextcloud-vue/blob/498364d197c5257d758a48853abf87f71ba1d8d2/src/components/DashboardWidget/DashboardWidget.vue#L143-L149

Accessible EmptyContent component

---

src/components/Multiselect/EllipsisedOption.vue
src/components/Multiselect/index.scss

Fix step 3 of https://github.com/nextcloud/nextcloud-vue/issues/2891
1. ❌ Error: Element div not allowed as child of element span in this context. (Suppressing further errors from this subtree.)
2. Loading icon background color issue
Before | After
---|---

Fix issues with Multiselect component

---

src/components/AppContent/AppDetailsToggle.vue

This PR migrates the `AppDetailsToggle` to use a vue button and a material design icon, and explicitly imports the `tooltip` directive which at the moment needs to be imported by the app dev via `Vue.use()` which is error prone.

AppDetailsToggle uses Button, MD icon, directive

---

src/components/AppNavigationToggle/AppNavigationToggle.vue

This brings back the tooltip on `AppNavigationToggle` which got lost with #2846. Closes #2876.

Bring back AppNavigationToggle tooltip

---

src/components/LoadingIcon/LoadingIcon.vue

This PR adjusts the style of the vue loading icon to the old style of the loading icon:
It also replaces the `fillColor` with an `appearance` prop. This prevents the usage of arbitrary colors, and allows to select whether the icon adjusts its color to the Nextcloud color scheme, or always shows as `light` or `dark`, independent of the color scheme.
At the moment, the colors for the `light` and `dark` mode are hard-coded, since I didn't find any color variables that don't change with the color scheme. Any hints here are welcome.
Follow-up to #2727.

Adjust loading icon style, replace `fillColor` prop

---

l10n/messages.pot
src/components/AppSidebar/AppSidebar.vue

To make sure that a screen reader user has some context on what the button actually does

Add more explicit title to the sidebar close button

---

src/components/Actions/Actions.vue
src/components/AppNavigationItem/AppNavigationItem.vue

Add aria-expended attribute to link
Correct aria-expended attribute of button in Actions.vue
Fixes https://github.com/nextcloud/nextcloud-vue/issues/2755

Add aria-expended attribute

---

src/components/ListItem/ListItem.vue

This fixes two things:
- The ListItem was not really usable without subtitle but with counter. Different line heights and a completely messed up design were the result. This now brings that case onto one line, when only title and counter are available and fixes the ListItem height, so all ListItems are the same height. 
|--|--|
[Full odd looking gif](https://user-images.githubusercontent.com/47433654/164996305-9cd5c448-f1bd-45de-8328-f6dd66b8ab91.gif)||
|![old](https://user-images.githubusercontent.com/47433654/180499784-e387bef4-5746-4321-9d81-bf6769664443.png)|![non_compact](https://user-images.githubusercontent.com/47433654/180499906-98170bf2-fe4e-4d2d-8687-5b1edf8a1402.png)|
- In connection to the fixed height, it introduces a compact-mode for the list item. Once …

Fix ListItem css

---

src/components/Actions/Actions.vue

Fixes a missing icon in the actions component docs.
Before:
After:

Fix missing icon in actions custom icon slot

---

src/components/ActionButton/ActionButton.vue
src/components/ActionLink/ActionLink.vue
src/components/Actions/Actions.vue

In an effort to encourage the usage of material design icons, I replaced the old icon classes in the Actions component docs with material design icons.

Use material design icons in actions docs

---

src/components/ActionTextEditable/ActionTextEditable.vue

This adds a material design icon slot to the `ActionTextEditable` component and adjusts the icons used in the docs.
Before (with icon classes):
After (with material design icons):

Add md icon slot to ActionTextEditable

---

src/components/AppSettingsDialog/AppSettingsDialog.vue
src/components/AppSettingsSection/AppSettingsSection.vue

Enforce setting section ids

---

src/components/Multiselect/EllipsisedOption.vue

Backport of #2895 
The second commit was not necessary unless https://github.com/nextcloud/nextcloud-vue/pull/2774 is being backported

[stable5] Fix issues with Multiselect component

---

src/components/Avatar/Avatar.vue

An avatar is treated as a button that toggles its contact menu, except when the menu was explicitly disabled. However, a menu may not be available even if it was not explicitly disabled (for example, if the avatar is for the current user). As no menu can be toggled in that case the avatar should not be treated as a button either.
Note that the menu is lazily loaded, so after you try to open the menu it could happen that there is actually no menu (that scenario can be tested by always returning a 404 in [ContactsMenuController](https://github.com/nextcloud/server/blob/232322fe062031d5fe5b5297ca60b22bc1da1d30/core/Controller/ContactsMenuController.php#L61)). In that case the avatar stops being a button after the user explicitly triggered it, is it needed to signal that to screen readers? Or …

Do not treat an avatar as a button if there is no menu

---

src/components/Modal/Modal.vue

Makes sure that "this" is the right scope so that deactivate is called
on the correct element.
Doesn't seem to affect the current behavior.
Discovered while adding a modal example in https://github.com/nextcloud/nextcloud-vue/pull/2953 to prove https://github.com/nextcloud/nextcloud-vue/issues/2816
I tested locally with the example PR that this change here doesn't affect anything, the focus still returns to the correct element.

Fix focus trap init function

---

src/components/Actions/Actions.vue

This PR fixes focusing the last action with page-down, which is currently broken. Closes #2958.
I also cleaned up two unused icon classes that I missed to remove in #2927.

Fix focusing last action with page-down

---

src/components/MultiselectTags/MultiselectTags.vue

Required to migrate behaviour like this
https://github.com/nextcloud/files_retention/blob/dcb68844ab563c261d3f8f8be5c90d2e3c9c8407/js/admin.js#L140-L143
to the Vue component.

Allow to filter the available tags

---

src/components/Actions/Actions.vue

This adds a default `aria-label` with the value of the tooltip to the single action button, fixing the `You need to fill either the text or the ariaLabel props in the button component.` warning that currently occurs in the docs for single actions if the `ActionButton` has no `aria-label` set. Follow-up of #2911.

Add aria-label to single action button

---

src/components/Modal/Modal.vue

This fixes the broken styleguide after #2953. `Button` was renamed to `ButtonVue` in #2980 because eslint complained. So importing it as `Button` does not work anymore and breaks the styleguide.

Fix button import in modal example

---

src/components/AppNavigationItem/AppNavigationItem.vue

Running `npm run stylelint` locally happens to complain about the minor issue being fixed with this PR. No idea why the GH action stylelint does not complain about it :shrug:

Fix stylelint

---

src/components/Actions/Actions.vue
src/components/AppSettingsDialog/AppSettingsDialog.vue
src/components/Breadcrumbs/Breadcrumbs.vue
src/components/ColorPicker/ColorPicker.vue
src/components/Content/Content.vue
src/components/EmojiPicker/EmojiPicker.vue
src/components/Modal/Modal.vue
src/components/Popover/Popover.vue

This PR replaces all usages of the normal HTML `button` with the `ButtonVue` from nextcloud/vue. Fixes half of #2988.
Before:
After:

Use ButtonVue everywhere in the docs

---

src/components/Actions/Actions.vue
src/components/Breadcrumb/Breadcrumb.vue

This fixes (and simplifies) the styling of the `Actions` component in the `Breadcrumbs` component, which is broken due to #2911. To allow to re-use the `ButtonVue` styling, I allowed to forward the `type` prop from the `Actions` to the `ButtonVue` component.
Closes #2988.
Before:
After:

Fix Actions styling in Breadcrumbs

---

src/components/RichContenteditable/RichContenteditable.vue
src/directives/Tooltip/index.scss

This PR fixes two regressions from the migration to floating-vue in #2600. The `RichContenteditable` tooltip open variable name was not adjusted and the tooltip top arrow style was broken.
Before (tooltip only shown on hover):
After (tooltip automatically shown):

Fix regressions from floating-vue migration

---

src/components/RichContenteditable/RichContenteditable.vue

This changes the `RichContenteditable` component to locally import the `tooltip` directive. Hence, a global import by the app developer is not necessary anymore.

Import tooltip directive only locally

---

src/directives/Tooltip/index.js

This adds an export of the tooltip `options` object, so one can customize the tooltips if necessary.
Works like this:
```js
import { options as TooltipOptions } from '@nextcloud/vue/dist/Directives/Tooltip'
TooltipOptions.container = '#content-vue'
```
Closes #2993.

Also export tooltip options

---

src/components/Multiselect/Multiselect.vue

Pretty much all the slots are passed down to Vue-Multiselect except `noResult` which is hardcoded. This is a naive way to pass it down and keep the default value if not defined. Maybe there's a more elegant way.

[MultiSelect] pass the #noResult slot to the underlying component

---

CHANGELOG.md
package-lock.json
package.json

* [#2980](https://github.com/nextcloud/nextcloud-vue/pull/2980) Bump @nextcloud/eslint-config from 8.0.0 to 8.1.2 ([@dependabot[bot]](https://github.com/apps/dependabot))
* [#2911](https://github.com/nextcloud/nextcloud-vue/pull/2911) Use render function in Actions component ([@raimund-schluessler](https://github.com/raimund-schluessler))
* [#2929](https://github.com/nextcloud/nextcloud-vue/pull/2929) Bump vue from 2.6.14 to 2.7.8 ([@raimund-schluessler](https://github.com/raimund-schluessler))
* [#2923](https://github.com/nextcloud/nextcloud-vue/pull/2923) Enforce setting section ids ([@nickvergessen](https://github.com/nickvergessen))
* [#2998](https://github.com/nextcloud/nextcloud-vue/pull/2998) Import tooltip directive only locally …

6.0.0-beta.1

---

src/components/ActionButton/ActionButton.vue
src/components/Actions/Actions.vue

Actual:
Expected:
The icon should appear.
It already works with this format when inside the popover, it's only when there's only a single action that it doesn't.
The component is used that way in many places in the server, see https://github.com/nextcloud/server/pull/33508#issuecomment-1212357494

Fix single button action icon attribute

---

package.json
src/components/MultiselectTags/MultiselectTags.vue
tests/unit/components/MultiselectTags/MultiselectTags.spec.js

Like discussed in https://github.com/nextcloud/nextcloud-vue/pull/2973

Add docs and tests for #2973

---

src/components/Actions/Actions.vue

This brings back the support for a `default-icon` and fixes the support of `icon` for the `Actions` component.
Follow-up to #3006, fixes #3016.
Please test this well, I only checked in in the docs.

Fix icon-class, re-add default-icon support for Actions

---

CHANGELOG.md
package-lock.json
package.json
src/components/Actions/Actions.vue

contains https://github.com/nextcloud/nextcloud-vue/pull/3006 which moves https://github.com/nextcloud/nextcloud-vue/pull/2911 from "breaking" to "enhancement".
note: the regressions were just a misunderstanding about whether we wanted to keep or break icon attr: https://github.com/nextcloud/nextcloud-vue/pull/3006#issuecomment-1212422191

V6.0.0 beta.2

---

README.md

Signed-off-by: Julius Härtl <jus@bitgrid.net>

Add note about pre-releases to the readme

---

src/components/Modal/Modal.vue

This PR addresses two issues that are not directly visible in the components but with the way how our apps use them.
- Allow click outside even if the focus trap is set
- Allow apps (like viewer) to pass additional focus trap elements (like the sidebar) which will then be added to the trap so it can be accessed
Corresponding viewer commit: https://github.com/nextcloud/viewer/pull/1319/commits/a2fb11097d8a3a81c4f666edfc038b7b5c6aafef

Fix issues with focus trap on modal

---

src/components/Popover/Popover.vue

Similar to #3020 this fixes an issue with the Popver/Actions focus-trap which was added in https://github.com/nextcloud/nextcloud-vue/pull/2941 and prevented directly opening another Actions menu, when one was already open. Before, you would need two clicks on the second Actions menu trigger to open the other Actions menu, one for closing the first one, one for actually opening the second one.
Try this example code by copying into the docs:
```vue
<template>
<div>
<Actions>
<ActionButton @click="actionDelete">
<template #icon>
<Delete :size="20" />
</template>
Delete
</ActionButton>
<ActionButton @click="actionDelete">
<template #icon>
<Delete :size="20" />
</template>
Delete
</ActionButton>
</Actions>
<Actions>
<ActionButton @click="actionDelete">
<template #icon>
<Delete :size="20" /> …
```

Allow click outside for Popover focus trap

---

src/components/Popover/Popover.vue

Otherwise the trap is kept active while the component is being destroyed e.g. on unshare of a link

Dismis focus trap when component gets destroyed

---

src/components/Popover/Popover.vue

This PR disabled the focus trap for Popovers by default for the moment. Reason is, that focusing other elements from within an Actions menu does not work anymore. E.g. here: https://github.com/nextcloud/tasks/blob/master/src/components/TaskBody.vue#L583-L588 the call to `focus()` has no effect.
Also see this example (copy into docs):
```vue
<template>
<div>
<input ref="input" />
<Actions>
<ActionButton @click="focusInput" :close-after-click="true">
<template #icon>
<Delete :size="20" />
</template>
Focus input
</ActionButton>
<ActionButton @click="actionDelete">
<template #icon>
<Delete :size="20" />
</template>
Delete
</ActionButton>
</Actions>
</div>
</template>
<script>
import Delete from 'vue-material-design-icons/Delete'
components: {
Delete,
},
methods: { …
```

Disable focus-trap for Popover by default

---

src/components/DashboardWidget/DashboardWidget.vue

This implements two slots for populating the empty icon and half-empty icon slots of the empty content component. This closes #3033.
I also fixed the rule to overwrite the empty-content top-margin in the dashboard widget.

Implement empty content icon slot in DashboardWidget

---

src/components/AppSettingsDialog/AppSettingsDialog.vue

This ensures that the app-settings modal style is correctly overwritten and takes precedence over the modal style.
Ref https://github.com/nextcloud/nextcloud-vue/pull/3025.

Correctly overwrite app-settings modal style

---

src/components/Actions/Actions.vue

Fixes #2842 
The `aria-controls` attribute must point to an element in the same document. When the menu is closed it is removed from the DOM, so the `aria-controls` attribute should be set only when the menu is open.
According to MDN [_The `aria-controls` only needs to be set when the popup is visible_](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-controls), so I guess it is fine to remove it if the menu is not there rather than always having it in the DOM but hidden, although I do not really know.

Fix reference to closed menu in "aria-controls"

---

src/components/ActionButton/ActionButton.vue
src/components/Actions/Actions.vue
src/components/Popover/Popover.vue
src/mixins/actionText.js

As alternative to #3028, I would like to propose a less complex solution for the `Actions` component focus-trap problem in #3021. When an `Action` has the `close-after-click` prop set, the focus is not returned to the initial element after closing. This enables programmatically focusing another element (e.g. an input element)  after the `Actions` menu is closed. Checkout the example added. 
In difference to #3028 it does not introduce a scoped slot, hence is not a breaking change, but just keeps the current behaviour intact, without changes to the app.
On the other hand, It is a bit less flexible, since the dev cannot configure whether the focus is returned or not at the moment. But if one really needs this option, it could be implemented by simply adding a prop for it.

Don't return focus after close-after-click

---

src/components/Breadcrumb/Breadcrumb.vue

This fixes the alignment of the actions menu icon in the `Breadcrumbs` component.
Before:
After:

Fix breadcrumbs dropdown icon alignment

---

src/components/ListItem/ListItem.vue

Closes #3039
I didn't do anything UI-wise to distinguish external links (which use `target="_blank"`, but we could change that).

Allow ListItem components to link to external links

---

src/components/Actions/Actions.vue
src/components/Modal/Modal.vue
tests/unit/components/Actions/Actions.spec.js

Currently, it's hardcoded, meaning we are not hecking the available space and changing the inline accordingly.
Might come later, but this is a good enough starting point

Allow to render x items outside an Actions menu

---

.github/workflows/changelog-generate.yml
CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud/nextcloud-vue/compare/v6.0.0-beta.2...v6.0.0-beta.3)
- Add Nc prefix to all components [\#3058](https://github.com/nextcloud/nextcloud-vue/pull/3058) ([raimund-schluessler](https://github.com/raimund-schluessler))
- Allow to render x items outside an Actions menu [\#3060](https://github.com/nextcloud/nextcloud-vue/pull/3060) ([skjnldsv](https://github.com/skjnldsv))
- Allow ListItem components to link to external links [\#3040](https://github.com/nextcloud/nextcloud-vue/pull/3040) ([tcitworld](https://github.com/tcitworld))
- Fix breadcrumbs dropdown icon alignment [\#3059](https://github.com/nextcloud/nextcloud-vue/pull/3059) ([raimund-schluessler](https://github.com/raimund-schluessler))
- Add missing trailing comma …

6.0.0-beta.3

---

src/components/NcModal/NcModal.vue

All the other actions (slideshow, close...) have a proper margin
|![Peek 18-08-2022 19-35](https://user-images.githubusercontent.com/14975046/185458818-a9cf18db-f9fb-4cc8-9462-ca501cc48718.gif)|![Peek 18-08-2022 19-34](https://user-images.githubusercontent.com/14975046/185458820-bd7fba1d-4356-4f5c-a72a-556ed2f22236.gif)|

Fix margin for Modal inline actions

---

src/components/NcAppSettingsDialog/NcAppSettingsDialog.vue

This changes the `NcAppSettingsDialog` to always show the title element, independent of whether a title is set or not.
This allows to click the modal close button even if no title is given. Before it was visible, but not clickable, since it was hidden behind the dialogs content. Closes #3029.
Check by removing the `title` prop of `NcAppSettingsDialog`.

Always show NcAppSettingsDialog title

---

src/components/NcListItem/NcListItem.vue

Spotted this while porting the functionality to AppNavigationItem

Fix listitem tabbed navigation

---

src/components/NcAppNavigationItem/NcAppNavigationItem.vue

Regression of #3058 where I missed adding the prefix to some components in the docs.

Fix NcAppNavigationItem docs

---

src/components/NcInputField/NcInputField.vue

overrides a box shadow rule that effectively makes the border of
the input field 4px thick instead of 2.

Fix InputField focus state

---

src/components/NcTextField/NcTextField.vue

The added `ref` simplifies programmatically focusing the `input` field of `NcInputField` when using `NcTextField`.
This will be used e.g. here:
https://github.com/nextcloud/tasks/pull/2086/files#diff-c8bcf2830b5032bb1455ee25738dd6fa8cdb38b7c4e00ea59e69e577aaac973fR402

Add ref to NcInputField in NcTextField

---

src/components/NcInputField/NcInputField.vue

Depending on how the bundler packs together the CSS rules of nextcloud/vue, it would happen that the style of `NcButton` takes precedence over the custom adjustment to the button in `NcInputField`, leading to a wrongly positioned button.
This PR ensures that the custom adjustment to the button in `NcInputField` always apply.

Make input field button style take precedence

---

src/components/NcListItem/NcListItem.vue

ListItem Design update

---

src/components/NcEmptyContent/NcEmptyContent.vue

Restore the missing comments icon

Fix EmptyContent comments example in docs

---

src/components/NcEmptyContent/NcEmptyContent.vue

Adding a slot to NcEmptyContent to put a button below.
There is however still a problem with reactivity, when using multiple NcEmptyContent 'after' each other.
If i first show an EmptyContent with LoadingIcon only, and after finished loading i want to show an EmptyContent with icon and text, then the text is not shown. Same applies to Icon (Action, Desc), if a slot is not used on the first usage, but should be shown on the second. (Example in https://github.com/nextcloud/forms/pull/1308)
@raimund-schluessler @skjnldsv @Pytal Any idea, how to fix the emptyContent reactivity here? Seems like there was some attempt to fix reactivity in https://github.com/nextcloud/nextcloud-vue/pull/2867, but did this maybe introduce the problem? :see_no_evil:

Allow more than text on EmptyContent description

---

src/components/NcAppNavigationItem/NcAppNavigationItem.vue

Show actions on hover/focus/active

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud/nextcloud-vue/compare/v6.0.0-beta.3...v6.0.0-beta.4)
- Allow more than text on EmptyContent description [\#3082](https://github.com/nextcloud/nextcloud-vue/pull/3082) ([jotoeri](https://github.com/jotoeri))
- Add ref to NcInputField in NcTextField [\#3078](https://github.com/nextcloud/nextcloud-vue/pull/3078) ([raimund-schluessler](https://github.com/raimund-schluessler))
- 📰 Update AppNavigationItem design [\#3056](https://github.com/nextcloud/nextcloud-vue/pull/3056) ([marcoambrosini](https://github.com/marcoambrosini))
- ListItem Design update [\#3055](https://github.com/nextcloud/nextcloud-vue/pull/3055) ([marcoambrosini](https://github.com/marcoambrosini))
- Make input field button style take precedence …

6.0.0-beta.4

---

src/components/NcEmptyContent/NcEmptyContent.vue

So - this fixes Reactivity for me.
|Before|After|
|:---:|:---:|
|<video autoplay src="https://user-images.githubusercontent.com/14975046/186139154-c80a6692-f09f-4ff3-9e24-c9fd30990b75.mp4" />|<video autoplay src="https://user-images.githubusercontent.com/14975046/186138687-09c17a52-1b52-4600-887f-19bd2b4c9ffa.mp4" />|
(With this code: https://github.com/nextcloud/forms/pull/1308/files)
@Pytal can you remember, why you introduced that reactivity stuff in #2867 ? Any place, where i can/need to test it?
@raimund-schluessler As you mentioned https://github.com/nextcloud/tasks/blob/0611f1b897c4681035b7e6541247dd4dcc9cea44/src/components/TaskCreateDialog.vue#L77-L85 - Does this work for you on current master? Do you see similar issues as me above (Not seeing the description on second …

Fix EmptyContent Reactivity

---

src/components/NcModal/NcModal.vue

Fix https://github.com/nextcloud/nextcloud-vue/issues/2954
Before | After
--- | ---

Fix contrast of next/prev modal buttons

---

src/components/NcAppNavigation/NcAppNavigation.vue
src/components/NcAppNavigationSettings/NcAppNavigationSettings.vue
styleguide/assets/variables.css

🥛 Make app navigation semi-transparent

---

src/components/NcCounterBubble/NcCounterBubble.vue
styleguide/assets/variables.css

tested manually on mail, i cannot connect to nc/vue 
fixes #3054

Make unread counter primary colour

---

src/components/NcDashboardWidget/NcDashboardWidget.vue
src/components/NcEmptyContent/NcEmptyContent.vue

- Now went back to the action slot, so action and description can be properly formatted here on the component.
- The description also became a prop, thus beeing consistent with the title.
- Adapting resp. docs
- Adapting Usage within DashboardWidget
I considered alternatively to make the old description slot a flex-element for centering items, that however didn't allow me to put some margin between text and action here on the component. So apps would have needed to separately style the distance between.
|Before|After|
|---|---|
|![Screenshot from 2022-08-26 09-03-28](https://user-images.githubusercontent.com/47433654/186843112-0bd269c6-9d53-4466-bf09-18916cc85c3c.png)|![Screenshot from 2022-08-26 08-50-34](https://user-images.githubusercontent.com/47433654/186841095-3d28cd6d-a1d4-4886-a7e8 …

Fix emptyContent once more

---

src/components/NcModal/NcModal.vue

Assuming that all NcModal are actually modal.
Was reported when reviewing the user status dialog: https://github.com/nextcloud/server/issues/33745

Add aria-modal to Modal dialog

---

src/components/NcMultiselect/NcMultiselect.vue
src/components/NcMultiselect/index.scss

- Add focus effect for better accessibility
- Increase font size to be 15px like the other component
- Update style to be more like the NcInputField
There are still some remaining issues that are not fixed by this PR,
notably the width of the multiselect component change when clicking
on it. This is a preexisting issue :(

Improve multiselect

---

styleguide/assets/variables.css

Related to: #3095
Just update `styleguide/assets/variables.css` using the script below in preparation to automate this process.
```sh
NEXTCLOUD=http://nextcloud.local
TARGET=/tmp/vars-temp
TARGET_OUTPUT=styleguide/assets/variables.css
printf "\n\n/* Plain */\n" > $TARGET
curl $NEXTCLOUD/index.php/apps/theming/theme/default.css?plain=1 >> $TARGET
printf "\n\n/* Light */\n" >> $TARGET
printf "@media (prefers-color-scheme: light) {" >> $TARGET
curl $NEXTCLOUD/index.php/apps/theming/theme/light.css?plain=1 >> $TARGET
printf "}" >> $TARGET
printf "\n\n/* Dark */\n" >> $TARGET
printf "@media (prefers-color-scheme: dark) {" >> $TARGET
curl $NEXTCLOUD/index.php/apps/theming/theme/dark.css?plain=1 >> $TARGET
printf "}" >> $TARGET
cat $TARGET | sed -E "s/\-\-[^:]*:\s*url[(]'[^;]+'\);//g" > …
```

Update variables.css from nextcloud server

---

src/components/NcListItem/NcListItem.vue

Required for https://github.com/nextcloud/mail/issues/6982
Screenshots:

Add slot for dot indicator in NcListItem.vue

---

src/components/NcListItem/NcListItem.vue

Since the `NcListItem` component has no `#counter` slot, the templates in the docs are misleading and useless. This PR removes them.
No visual changes.

Remove unused #counter template from ListItem docs

---

src/components/NcAppContent/NcAppContent.vue

200px is very narrow. Too narrow for the apps that use the resizeable column.
Tagging as enhancement. Not breaking. And no backports.
Ref https://github.com/nextcloud/mail/issues/6973

Make the app content list 300px min

---

src/components/NcInputField/NcInputField.vue
src/components/NcPasswordField/NcPasswordField.vue
src/components/NcTextField/NcTextField.vue

- Fix random name being used since it makes sending form cumbersome and
also doesn't provide the label hover effect
- Expose more properties from the underlying <input> element
Required for https://github.com/nextcloud/server/pull/33781

Improve text fields

---

src/components/NcAppContent/NcAppContent.vue
src/components/NcAppNavigation/NcAppNavigation.vue
src/components/NcAppSidebar/NcAppSidebar.vue
src/components/NcContent/NcContent.vue

Vue components implementation of https://github.com/nextcloud/server/pull/33568

Implement new container layout

---

CHANGELOG.md
package-lock.json
package.json

Migration guide is likely to be extended with the next beta releases
[Full Changelog](https://github.com/nextcloud/nextcloud-vue/compare/v6.0.0-beta.6...v7.0.0-beta.0)
- This component library release requires Nextcloud 25 or later
- We changed the container layout to adapt to the design changes with Nextcloud 25
- The body is no longer the main scroll area but instead the app content
- Please do careful testing of your user interface, especially in regards to the following components and scroll behaviour:
- NcContent
- NcAppNavigation
- NcAppContent
- NcAppSidebar
- Scroll listeners need to be adapted to watch for the scroll on the NcAppContent container instead of the main document
- If you are using sticky headers in your app you might need to adjust the css top property as the app …

7.0.0-beta.0

---

src/components/NcListItem/NcListItem.vue

It is the wrapper that receives the .active class from Vue router, not
the .list-item sub element. Therefore the S(C)SS selector didn't match.
Found in and reported at https://github.com/nextcloud/mail/issues/7098.

Fix .active state of app list items

---

src/components/NcPopover/NcPopover.vue

This cleans up the `NcPopover` component and makes use of the events provided by floating-vue. This way we can remove the workaround of using the watcher.

Use events provided by floating-vue

---

src/components/NcAppNavigation/NcAppNavigation.vue
src/components/NcAppNavigationNew/NcAppNavigationNew.vue
src/components/NcAppNavigationSettings/NcAppNavigationSettings.vue

Adds proper spacing to the app navigation entries and moves the settings to pill style

Fix spacing in app navigation and make the setting pill style

---

src/components/NcListItem/NcListItem.vue

Fix what @marcoambrosini mentioned at https://github.com/nextcloud/nextcloud-vue/pull/3055#issuecomment-1225273555
44px avatar size / 2 + 8px padding, and 2px for better visual quality
The avatar size and padding should ideally be taken from variables but I couldn’t see the relevant ones in the variables file. `--default-grid-baseline: 4px;` is added by @juliushaertl in another pull request.
Unfortunately can’t do screenshots as I can’t see how to add the third line to the component in the docs.

Fix for border-radius being too large for 3-line entries like in Mail

---

l10n/messages.pot
src/components/NcRelatedResourcesPanel/NcRelatedResourcesPanel.vue
src/components/NcRelatedResourcesPanel/NcResource.vue
src/components/NcRelatedResourcesPanel/index.js
src/components/index.js

Add new component for https://github.com/nextcloud/server/issues/28320
@ArtificialOwl since this component will be used in other apps how do we fetch the related resources of a Talk conversation, Deck board, Calendar event, et cetera?

Add related resources panel component

---

src/components/NcAppNavigationItem/NcAppNavigationItem.vue

This PR fixes all issues I described in https://github.com/nextcloud/nextcloud-vue/issues/3094#issuecomment-1236092609:
- The actions and counter are now visible when the `AppNavigationItem` is active
- The actions are now visible when the `AppNavigationItem` has the undo state
- The actions now appear on hover if the `AppNavigationItem` is editable
- The actions and counter do not overflow anymore
I had to switch from JS to CSS and hover/focus/active classes, because the active state is applied by `router-link` and not easily accessible in JS (one could switch to a scoped slot, but that creates different trouble). However, I think handling the hover/focus in CSS is anyway more performant and creates less issues (I saw some weird glitches with the JS implementation, probably the mouseover …

Fix AppNavigationItem actions visibility

---

src/components/NcAppNavigationItem/NcAppNavigationItem.vue

This fixes the docs of the `AppNavigationItem` with actions menu. Since we now (after #3157) attach the actions menu for the `AppNavigationItem` component to `#app-navigation-vue`, the menu would not open anymore in the docs, as the component is used there without the correct parent component, i.e. `AppNavigation`. This fixes the issue and allows the actions menu to also open in the docs.
For a real life app, no adjustment is necessary, of course.

Fix docs of NcAppNavigationItem with actions menu

---

src/components/NcAppNavigationSettings/NcAppNavigationSettings.vue

This adjust the border radius of the appnavigation settings button to the look of the appnavigation items. This was fixed in master already, so this only targets stable6.

Adjust appnavigation settings border radius

---

src/components/NcSettingsSection/NcSettingsSection.vue

This option only apply to the title and description by default and is opt-in for the content.

Limit max width of the settings

---

src/components/NcAppNavigationItem/NcAppNavigationItem.vue

Pass a dom element to the boundaries-element prop of NcActions.
closes #3187

Fix NcAppNavigationItem, pass correct boundaries-element NcActions

---

src/components/NcAvatar/NcAvatar.vue

See https://github.com/nextcloud/server/pull/33752 for screenshots

Use dark themed avatar on dark theme

---

l10n/messages.pot
src/components/NcDatetimePicker/NcDatetimePicker.vue

This fixes an issue in Forms where the placeholder for NcDatetimePicker cannot be overwritten by passing some text to the property: https://github.com/nextcloud/forms/issues/1296 
Signed-off-by: Christian Hartmann <chris-hartmann@gmx.de>

Fix overwriting placeholder property in NcDatetimePicker

---

src/components/NcInputField/NcInputField.vue

Server has the same rules but excludes with a :not() selector the vue component

Fix active and focus frame

---

src/components/NcPopoverMenu/NcPopoverMenu.vue
src/components/NcPopoverMenu/NcPopoverMenuItem.vue

This just overwrites some style from the server
Before 
After: some spacing between the items and not a ridiculously big border-radius

Fix the NcPopoverMenu component

---

src/components/NcActions/NcActions.vue

The detection relies on the tag we use in our compontent instead of the "real" component name. In calendar we did not change every tag to `NcAction...` but just changed imports instead. As a result the detection is broken and the `...` menu is always shown.
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1479486/189345086-e127fa07-df67-4d68-adfe-9e118d6b1bc5.png) | ![image](https://user-images.githubusercontent.com/1479486/189344853-ff06b733-22f5-46ab-b170-d56219651c38.png) |

Fix single action detection

---

l10n/messages.pot
src/components/NcDashboardWidget/NcDashboardWidget.vue

Instead of having a prop that allows customizing one part of a sentence, use a prop to allow changing the full sentences.
Part of the fix for https://github.com/nextcloud/activity/issues/919
This an API break so only for nc-7

Fix a word puzzle in NcDashboardWidget component

---

src/components/NcDateTimePickerNative/NcDateTimePickerNative.vue

Resolves https://github.com/nextcloud/nextcloud-vue/issues/3182
Provide inheritAttrs with ```false``` value for NcDateTimePickerNativ.vue
Extend types for ```min``` and ```max``` props

Improve using of native datetime picker

---

src/components/NcPasswordField/NcPasswordField.vue

Use case: 
LoginForm.vue set focus to password field when username is already given via url.

Add ref=inputField to NcPasswordField

---

src/components/NcMultiselect/index.scss

If you put the multiselect somewhere other than an element with the main background color, it looked weird.
|---|---|
| ![Bildschirmfoto vom 2022-09-14 11-50-55](https://user-images.githubusercontent.com/1374172/190123460-7b398a9f-68ad-4c27-a335-7a6e0852abbf.png) | ![Bildschirmfoto vom 2022-09-14 11-53-22](https://user-images.githubusercontent.com/1374172/190123505-78c78b90-c045-4608-bfbb-e41373779763.png) |

Fix multiselect background color spilling outside the component

---

src/components/NcEmptyContent/NcEmptyContent.vue

Fix NcEmptyContent used inside NcModal

---

l10n/messages.pot
src/components/NcRelatedResourcesPanel/NcRelatedResourcesPanel.vue
src/components/NcRelatedResourcesPanel/NcResource.vue
styleguide/global.requires.js
tests/OC.js

Before | After
--- | ---
`coreApps` and `appswebroots` data was added to resolve some console errors in the styleguide

Update design of related resources panel

---

src/components/NcModal/NcModal.vue

In order for it to be on top of whatever is passed into the component's slot

Move the close button to the end of the content

---

src/assets/variables.scss
src/components/NcAppNavigationSettings/NcAppNavigationSettings.vue

Contributes to https://github.com/nextcloud/nextcloud-vue/issues/3184.
Follow-up to https://github.com/nextcloud/nextcloud-vue/pull/3158.
* Make settings button same with as other nav elements
* Make sure scrolled menus don't look cut at the bottom
| Description | Before | After |
|---|---|---|
| General | ![Bildschirmfoto vom 2022-09-14 14-45-35](https://user-images.githubusercontent.com/1374172/190158056-1d27437e-f528-4b70-8c2d-f239bf4fca98.png) | ![Bildschirmfoto vom 2022-09-14 14-43-38](https://user-images.githubusercontent.com/1374172/190158094-b2fb5490-af79-4ac8-952c-c897995f5a39.png) |
| Matching width | ![Bildschirmfoto vom 2022-09-14 14-45-51](https://user-images.githubusercontent.com/1374172/190158048-3a21cc66-9de4-4330-ab06-c450db3b92ad.png) | ![Bildschirmfoto vom 2022-09-14 …

Make app navigation settings pixel perfect-ish

---

src/components/NcPasswordField/NcPasswordField.vue
src/components/NcTextField/NcTextField.vue

Make it possible to set the `autofocus` attribute on on TextField and PasswordField

Forward the autofocus attribute to input field component

---

src/components/NcModal/NcModal.vue

Automatic remounting behaviour of NcModal is not always desired so we allow passing `null` to prevent this and to keep NcModal mounted at the initial mount point on the DOM
More context in https://github.com/nextcloud/nextcloud-password-confirmation/pull/387

Allow opting out of automatic NcModal remounting

---

src/components/NcAvatar/NcAvatar.vue

Close https://github.com/nextcloud/nextcloud-vue/issues/2975
Listen to avatar https://github.com/nextcloud/server/blob/b9c002df0a3ab80c1612206cfb1f724d90e0da3a/apps/settings/src/components/PersonalInfo/AvatarSection.vue#L268 and displayname https://github.com/nextcloud/server/blob/b9c002df0a3ab80c1612206cfb1f724d90e0da3a/apps/settings/src/components/PersonalInfo/DisplayNameSection.vue#L66 update events to automatically refresh the image or displayname based avatar

Live refresh image and displayname based avatar on update

---

src/components/NcAvatar/NcAvatar.vue

My sneaky demo that the `NvAvatar` renders letters different than Nextcloud 25 server-side generated avatars :smiling_imp:

Add styleguide example for non-user avatar

---

src/components/NcAvatar/NcAvatar.vue

Ref https://github.com/nextcloud/mail/issues/7294
Ref https://github.com/nextcloud/server/pull/33752
|---|---|
| ![Bildschirmfoto vom 2022-09-20 08-48-29](https://user-images.githubusercontent.com/1374172/191189809-995b9440-e516-40da-83ef-7ab8d86546a0.png) | ![Bildschirmfoto vom 2022-09-20 09-00-32](https://user-images.githubusercontent.com/1374172/191189444-1f7d5947-011b-4021-b91c-fd4d95700899.png) |
(Demo requires https://github.com/nextcloud/nextcloud-vue/pull/3270)

Fix initials color of new non-user avatars

---

src/components/NcAvatar/NcAvatar.vue

Discovered in https://github.com/nextcloud/contacts/pull/2726
Due to the 0.1 alpha channel of the new avatars, the background potentially shows through. This is not expected nor does it look any good.
|---|---|
| ![Bildschirmfoto vom 2022-09-20 09-16-31](https://user-images.githubusercontent.com/1374172/191196233-11771230-19f7-4333-94fa-6ea9e6f5e6a0.png) | ![Bildschirmfoto vom 2022-09-20 09-53-45](https://user-images.githubusercontent.com/1374172/191200088-142151f6-f4d7-41d6-9d33-987d1bc22869.png) |

Fix non-user avatar on complex background

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud/nextcloud-vue/compare/v6.0.0-beta.8...v7.0.0-beta.5)
- Add styleguide example for non-user avatar [\#3270](https://github.com/nextcloud/nextcloud-vue/pull/3270) ([ChristophWurst](https://github.com/ChristophWurst))
- Live refresh image and displayname based avatar on update [\#3266](https://github.com/nextcloud/nextcloud-vue/pull/3266) ([Pytal](https://github.com/Pytal))
- Forward the autofocus attribute to input field component [\#3245](https://github.com/nextcloud/nextcloud-vue/pull/3245) ([kesselb](https://github.com/kesselb))
- Allow 'search' as type prop for NcTextField [\#3190](https://github.com/nextcloud/nextcloud-vue/pull/3190) ([artonge](https://github.com/artonge))
- Fix non-user avatar on complex background …

Release v7.0.0-beta.5

---

src/components/NcAppContent/NcAppContent.vue

Currently the assignment of the `topbar-margin` css variable does not work, it gets compiled to:
```css
--topbar-margin: $topbar-margin
```
See also https://sass-lang.com/documentation/breaking-changes/css-vars

Fix SCSS to CSS variable assignment

---

src/components/NcAppNavigationCaption/NcAppNavigationCaption.vue

Fix https://github.com/nextcloud/calendar/issues/4536
This was discussed in the design chat and we agreed to left align the headers.
| --- | --- |
| ![before](https://user-images.githubusercontent.com/1479486/192498704-396ced20-bddf-4216-8fd0-116397930e60.png) | ![after](https://user-images.githubusercontent.com/1479486/192498320-264ff6ea-c0c5-4905-b1cc-15fa17a1c166.png) |

Fix alignment of NcAppNavigationCaption

---

src/components/NcMultiselect/index.scss

Fix https://github.com/nextcloud/calendar/issues/4550
In most cases, the correct `box-sizing` is already set on some parent and inherited down to the Multiselect (e. g. Calendar sidebar editor). In some instances it isn't and the Multiselect is too big.
| --- | --- |
| ![box-sizing-before](https://user-images.githubusercontent.com/1479486/193026509-3133baf0-2146-4336-a2be-47bacf93eadc.png) | ![box-sizing-after](https://user-images.githubusercontent.com/1479486/193026518-28fe12bf-73d2-4d26-83ec-f2e547c90aaf.png) |

Fix NcMultiselect height

---

src/components/NcInputField/NcInputField.vue
src/components/NcTextField/NcTextField.vue

Necessary for vue3 as the old syntax is removed.

Use new slot syntax everywhere

---

src/components/NcAppContent/NcAppContent.vue

Fix https://github.com/nextcloud/mail/issues/7323

Fix app content growing too wide

---

src/components/NcDateTimePickerNative/NcDateTimePickerNative.vue

Necessary for vue3 and doesn't hurt to have for vue2.7.

Add emits property to NcNativeDatetimePicker

---

src/components/NcColorPicker/NcColorPicker.vue

Before | After
--- | ---
<details>
<summary>RGB and HSL</summary>
RGB
HSL
</details>

Add advanced fields to color picker

---

src/components/NcAppNavigationItem/NcAppNavigationItem.vue

Fix https://github.com/nextcloud/calendar/issues/4574
The open class should be added when `menuOpenLocalValue` or the prop `menuOpen` is true.

Also use menuOpen state in NcAppNavigationItem

---

src/components/NcEmojiPicker/NcEmojiPicker.vue
src/components/NcPopover/NcPopover.vue

See https://github.com/Akryum/floating-vue/pull/894
Because the Popover always focuses after the event is emitted, we need to make sure to wait after the render (nextTick) to properly focus on another element.
Also implementing a way around the library to mitigate the focus priority until the new PR above is merged
fix https://github.com/nextcloud/nextcloud-vue/issues/3332

Fix emoji picker and Popover no-Auto-Focus

---

src/components/NcAppNavigation/NcAppNavigation.vue
src/components/NcListItem/NcListItem.vue

Fix https://github.com/nextcloud/nextcloud-vue/issues/3198
Light theme before/after in https://github.com/nextcloud/nextcloud-vue/issues/3198
Before (`#8C8C8C`) | After (`#919191`)
--- | ---
> Minimum 4.5 contrast ratio
Requires variables added in https://github.com/nextcloud/server/pull/34299

Fix contrast of maxcontrast text on blurred background

---

src/components/NcDashboardWidget/NcDashboardWidget.vue

Use padding instead of margin
Fix https://github.com/nextcloud/server/issues/34582

Fix empty content height in NcDashboardWidget in N in N in N

---

src/components/NcColorPicker/NcColorPicker.vue

Also added a light border. Otherwise we cannot see very bright colour :)

Allow to provide a custom palette to the ColorPicker

---

src/components/NcPasswordField/NcPasswordField.vue
src/components/NcTextField/NcTextField.vue

Add `minlength` and `maxlength` to be forwarded to the input by `v-bind="$props"`
The part which adds the `autofocus` prop definition is an addendum to https://github.com/nextcloud/nextcloud-vue/pull/3245
Before this change `autofocus` wasn't contained in `$props` so it wasn't automatically forwarded by `v-bind="$props"`, adding the explicit definition now makes it get forwarded by the `v-bind` and also makes the prop show up in the docs

Add minlength and maxlength to text field

---

src/components/NcTextField/NcTextField.vue

Add an `"undo"` icon in addition to the `"close"` and `"arrowRight"` icons

Add undo trailing icon

---

src/components/NcActions/NcActions.vue

This forwards a ref of an action to the respective inline action.
This allows to do something like this now:
```vue
<template>
<NcActions ref="actions">
<NcActionButton @click="actionDelete" ref="actionbutton">
<template #icon>
<Delete :size="20" />
</template>
Delete
</NcActionButton>
</NcActions>
</template>
<script>
import Delete from 'vue-material-design-icons/Delete'
components: {
Delete,
},
methods: {
actionDelete() {
alert('Delete')
console.debug(this.$refs.actions.$refs.actionbutton) // Not defined before this PR.
},
},
}
</script>
```
However, the use case in https://github.com/nextcloud/server/pull/34288 won't work anymore without adjustments, because we use a render function now, and the ref is not available in the context of the current component anymore.

Forward ref of actions to inline actions

---

src/components/NcDashboardWidget/NcDashboardWidget.vue

Regression from https://github.com/nextcloud/nextcloud-vue/commit/8705a051b08dce466d4ed28023f30ef25c4b44d6#diff-3d47e5014667a3933f462ef227ec4965133bf0b3fb67e26bbd164fdda46dc006
Found while working on https://github.com/nextcloud/spreed/pull/8260
Also added it to the docs:
https://deploy-preview-3407--nextcloud-vue-components.netlify.app/#/Components/NcDashboard?id=ncdashboardwidget

Fix missing half-empty dashboard empty content view

---

l10n/messages.pot
src/components/NcDatetimePicker/NcDatetimePicker.vue

Fix https://github.com/nextcloud/nextcloud-vue/issues/3403
Preview: https://deploy-preview-3405--nextcloud-vue-components.netlify.app/#/Components/NcPickers?id=ncdatetimepicker
Regression of https://github.com/nextcloud/nextcloud-vue/pull/3202

Fix DateTimePicker example and translation

---

src/components/NcPasswordField/NcPasswordField.vue

The defined fallback is only affecting when no core=>capabilities is there. But that is pretty unlikely while the password_policy entry can be missing often (app not installed, unit tests, ...)
Also null vs. undefined gives different results:
https://github.com/nextcloud/nextcloud-vue/blob/0204f6dd86ad16e9b57d8c5915ee15672d4a5e5a/src/components/NcPasswordField/NcPasswordField.vue#L354-L359
Fixes the failing JS unit test in: https://github.com/nextcloud/spreed/pull/8213

Fix password_policy fallback handling

---

src/components/NcRelatedResourcesPanel/NcRelatedResourcesPanel.vue

Query for resources with the item id as a query string parameter instead of a URL path segment to allow for complex ids
For https://github.com/nextcloud/related_resources/pull/124

Allow querying for resources with complex item ids

---

src/components/NcAppSidebar/NcAppSidebarTabs.vue

Fix https://github.com/nextcloud/server/issues/34777
|---|---|
| ![image](https://user-images.githubusercontent.com/42591237/200553310-4103776c-5d8b-4562-9d39-eef1e19cb1c7.png) | ![image](https://user-images.githubusercontent.com/42591237/200553225-6b4816d1-a5b2-456a-814e-1bf9775c056a.png) |
Signed-off-by: Simon L <szaimen@e.mail.de>

fix sidebar scrolling for small displays

---

l10n/messages.pot
src/components/NcRichContenteditable/NcRichContenteditable.vue

Signed-off-by: Jérôme Herbinet <33763786+Jerome-Herbinet@users.noreply.github.com>
Signed-off-by: Jérôme Herbinet <33763786+Jerome-Herbinet@users.noreply.github.com>

Comment placeholder wording fix

---

src/components/NcActions/NcActions.vue

Fix https://github.com/nextcloud/server/issues/33839
|---|---|
| ![image](https://user-images.githubusercontent.com/42591237/200556494-e1627a0b-300a-4aec-838d-85323dc9cdd7.png) | ![image](https://user-images.githubusercontent.com/42591237/200556425-d9119181-7f8f-421a-80bf-83b79ab0fd09.png) |
Signed-off-by: Simon L <szaimen@e.mail.de>

fix the size of the popper element

---

src/components/NcActions/NcActions.vue
src/components/NcAvatar/NcAvatar.vue
src/components/NcEmojiPicker/NcEmojiPicker.vue

Fixes type validation errors in the console
From https://github.com/Akryum/floating-vue/blob/v1.0.0-beta.18/packages/floating-vue/src/components/Popper.ts#L146-L147

Widen container prop type passed to NcPopover

---

src/components/NcAppContent/index.js
src/components/NcAppContentDetails/index.js
src/components/NcAppContentList/index.js
src/components/NcAppNavigationNew/index.js
src/components/NcAppNavigationSettings/index.js
src/components/NcAppSidebar/index.js
src/components/NcContent/index.js
src/components/NcEmojiPicker/index.js
src/components/NcGuestContent/index.js
src/utils/logger.js

Dont't ask, all the other files follow the same `**` syntax :see_no_evil: 
Sometimes this single `*` creates weird syntax highlighting bugs

Fix comments headers

---

src/components/NcActionInput/NcActionInput.vue
src/components/NcActionTextEditable/NcActionTextEditable.vue
src/components/NcAppNavigationItem/NcInputConfirmCancel.vue
src/components/NcAppSidebar/NcAppSidebarTabs.vue
src/components/NcButton/NcButton.vue
src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
src/components/NcListItemIcon/NcListItemIcon.vue
src/components/NcNoteCard/NcNoteCard.vue
src/components/NcRichContenteditable/NcAutoCompleteResult.vue
src/components/NcRichContenteditable/NcRichContenteditable.vue
src/components/NcSettingsInputText/NcSettingsInputText.vue

**Replace deprecated --color-text-lighter with --color-text-maxcontrast** & **Replace deprecated --color-text-light with --color-main-text**
We should never ever use `--color-text-lighter` (or "light") anymore.
- `color-text-light` → `color-main-text`
- `color-text-lighter` → `color-text-maxcontrast`
Could we fully deprecate the old variables?
---
**Progressive enhancement for outdated --color-primary-element-lighter**
The --lighter does not exist in new versions anymore, so currently a button with `type=""` (empty, as opposed to no type property or `type="secondary"` actually does not show any background. This fixes that.

Fix outdated variables

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud/nextcloud-vue/compare/v7.0.1...v7.0.2-beta.0)
- Widen container prop type passed to NcPopover [\#3462](https://github.com/nextcloud/nextcloud-vue/pull/3462) ([Pytal](https://github.com/Pytal))
- Allow querying for resources with complex item ids [\#3404](https://github.com/nextcloud/nextcloud-vue/pull/3404) ([Pytal](https://github.com/Pytal))
- Allow to provide a custom palette to the ColorPicker [\#3384](https://github.com/nextcloud/nextcloud-vue/pull/3384) ([skjnldsv](https://github.com/skjnldsv))
- Export NcMentionBubble and NcAutoCompleteResult [\#3373](https://github.com/nextcloud/nextcloud-vue/pull/3373) ([vinicius73](https://github.com/vinicius73))
- Add guest content component …

7.1.0-beta.0

---

src/components/NcInputField/NcInputField.vue
src/components/NcPasswordField/NcPasswordField.vue
src/components/NcTextField/NcTextField.vue
src/components/index.js
styleguide.config.js

https://deploy-preview-3485--nextcloud-vue-components.netlify.app/#/Components/NcFields
Fix https://github.com/nextcloud/nextcloud-vue/issues/3479

Extend NcInputField props and forward $attrs to NcPasswordField and NcTextField

---

src/components/NcDateTimePickerNative/NcDateTimePickerNative.vue

Fix https://github.com/nextcloud/nextcloud-vue/issues/3403

Fix value type for DateTimePickerNative

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud/nextcloud-vue/compare/v7.1.0-beta.0...v7.1.0-beta.1)
- Extend NcInputField props and forward $attrs to NcPasswordField and NcTextField [\#3485](https://github.com/nextcloud/nextcloud-vue/pull/3485) ([skjnldsv](https://github.com/skjnldsv))
- Move loadState to data for better mockability [\#3502](https://github.com/nextcloud/nextcloud-vue/pull/3502) ([skjnldsv](https://github.com/skjnldsv))
- Fix value type for DateTimePickerNative [\#3491](https://github.com/nextcloud/nextcloud-vue/pull/3491) ([skjnldsv](https://github.com/skjnldsv))

7.1.0-beta.1

---

src/components/NcMultiselect/index.scss

See https://github.com/nextcloud/server/issues/34148

Fix multiselect checkmark and plus icon

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud/nextcloud-vue/compare/v7.1.0-beta.1...v7.1.0-beta.2)
- Fix multiselect checkmark and plus icon [\#3513](https://github.com/nextcloud/nextcloud-vue/pull/3513) ([skjnldsv](https://github.com/skjnldsv))
- Make gap in NcAppNavigation consistent in nested lists [\#3506](https://github.com/nextcloud/nextcloud-vue/pull/3506) ([juliushaertl](https://github.com/juliushaertl))
- Finish emoji focus cleaning [\#3504](https://github.com/nextcloud/nextcloud-vue/pull/3504) ([skjnldsv](https://github.com/skjnldsv))

release v7.1.0-beta.2

---

.github/workflows/changelog-generate.yml
CHANGELOG.md
package-lock.json
package.json

No additions needed in release notes since `v7.1.0-beta.2` https://github.com/nextcloud/nextcloud-vue/compare/v7.1.0-beta.2...master

Release v7.1.0

---

src/components/NcAppNavigationItem/NcAppNavigationItem.vue

I don't really understand how no one experienced this before...
EDIT: ah, ok.
Some icons do not start with `icon-`
|![2022-12-02_12-04](https://user-images.githubusercontent.com/14975046/205278950-aa3705a4-8c5e-46cc-a0c3-1aadcb659714.png)|![2022-12-02_12-04_1](https://user-images.githubusercontent.com/14975046/205278954-a6ce83a9-7a86-4453-b602-1aac5fecbbf2.png)|

Fix icon repeat and position for AppNavigationItem

---

src/components/NcGuestContent/NcGuestContent.vue

Fix #3534 
I also improved the documentation of `NcGuestContent` to clarify its usages and caveats.
Observe the bottom margin that was incorrectly applied to all pages before. Now, it's only applied when `NcGuestContent` is actually used.
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1479486/205250320-3d905f0e-a62b-46f5-abd7-7856db5518dc.png) |![image](https://user-images.githubusercontent.com/1479486/205250395-1d39ea1d-3370-4fa9-9125-e928fd92edc9.png) |
The global styling still works with my patch applied. Otherwise, there would be weird margin between the bottom and the scrollable area.
[nc-guest-content-after.webm](https://user-images.githubusercontent.com/1479486/205250838-52e8e036-dd2b-4203-a7d3-844427a8cc7d.webm)

Scope global #content styles via extra class

---

src/components/NcButton/NcButton.vue

Attribute `role="button"` added for anchor element in NcButton with `href` and fixed the invalid `type="button"` attr being added to the DOM when using NcButton as a link https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-type
`router-link` is rendered as a button element https://v3.router.vuejs.org/api/#tag

Add button role for NcButton with href

---

src/components/NcHeaderMenu/NcHeaderMenu.vue
src/components/NcHeaderMenu/index.js
src/components/index.js

Since we're positioning it fixed on nextcloud the live example is not as great as this example, but it works out.
From https://github.com/nextcloud/server/blob/abaa3ef61b9a6177ca3fe965e837e6e9bca16a4b/core/src/views/UnifiedSearch.vue

Add NcHeaderMenu

---

src/components/NcActions/NcActions.vue
src/components/NcPopover/NcPopover.vue

Fix focused element when tabbing after reaching the last actions menu item
https://nextcloud-vue-components.netlify.app/#/Components/NcActions?id=ncactions-1 (Scroll down to "Multiple actions")
Focus returns to the top of the page
https://deploy-preview-3530--nextcloud-vue-components.netlify.app/#/Components/NcActions?id=ncactions-1 (Scroll down to "Multiple actions")
Focus returns to the actions menu toggle button

Fix focus returning to top of page instead of actions toggle button

---

src/components/NcBreadcrumb/NcBreadcrumb.vue
src/components/NcBreadcrumbs/NcBreadcrumbs.vue
src/components/NcListItem/NcListItem.vue

Added some missing documentation for events.
(This is a cherry pick from https://github.com/nextcloud/nextcloud-vue/pull/3529 as that PR is still WIP)

Fix jsdoc: Add missing documentation for events

---

src/components/NcActionInput/NcActionInput.vue

Brought over from NcInputField and switched `labelVisible` default to `true`
https://github.com/nextcloud/nextcloud-vue/blob/1dc8ed09c47d482a7a9cf8ae89babbd15f209aee/src/components/NcInputField/NcInputField.vue#L147-L155
https://github.com/nextcloud/nextcloud-vue/blob/1dc8ed09c47d482a7a9cf8ae89babbd15f209aee/src/components/NcInputField/NcInputField.vue#L167-L175
https://github.com/nextcloud/nextcloud-vue/blob/1dc8ed09c47d482a7a9cf8ae89babbd15f209aee/src/components/NcInputField/NcInputField.vue#L370-L382

Allow accessible labels for NcActionInput

---

src/components/NcSettingsSection/NcSettingsSection.vue

Resolves https://github.com/nextcloud/server/issues/35886
A11y issue: Create `aria-label` for icon link in SettingsSection

Create `aria-label` for icon link

---

src/components/NcRichContenteditable/NcRichContenteditable.vue
src/mixins/richEditor/index.js

By default Tribute does not allow spaces when autocompleting mentions, so as soon as a space was pressed the autocompletion list was closed, even if some candidate mentions had a space (either in the id or in the display name of the user).
As I found no explicit mention about why spaces should not be allowed when autocompleting mentions in `NcRichContenteditable` this pull request enables them (but if there is a good reason not to enable them please shout :-) ).
Note that now the autocompletion does not end until _Enter_ is pressed (or an item is selected in the list); even if space is pressed and nothing else matches the autocomplete will still be active, even if the list is hidden.
This pull request also fixes an existing bug: if _Enter_ was pressed when the current mention did not …

Allow spaces when autocompleting mentions

---

src/components/NcAppNavigationItem/NcAppNavigationIconCollapsible.vue

Upstream fix for https://github.com/nextcloud/mail/pull/7856
Fixes https://github.com/nextcloud/deck/issues/4352
Fixes https://github.com/nextcloud/mail/issues/7095
This makes sure that the NcAppNavigationIconCollapsible styles always take precendence over the NcButton ones as for the mail/deck app the loading order seems to be different compared to the vue component docs. Before this the NcButton relative positioning was applied within the apps instead of the absolute one.
Tested and works with deck.

fix(NcAppNavigationItem): Make sure that icon-collapse styles take precendense over NcButton styles

---

.eslintrc.js
src/components/NcMultiselect/NcMultiselect.vue
src/components/NcMultiselectTags/NcMultiselectTags.vue
tests/setup.js
webpack.config.js

As discussed https://github.com/nextcloud/nextcloud-vue/issues/2951#issuecomment-1351963646
For developers in addition to the existing deprecation badges in the docs

Add console warning messages for deprecated multiselect components

---

src/components/NcProgressBar/NcProgressBar.vue

This is very subtle, check the gif below where I toggle the overflow rule on and off
EDIT: Also fixed the background variable
|![image](https://user-images.githubusercontent.com/14975046/210620582-c3c51544-8c96-44a1-b005-511d37823dff.png)|![image](https://user-images.githubusercontent.com/14975046/210620637-5103b280-e5df-43f3-9374-671d2834a789.png)|

fix(ProgressBar): Fix progress rounded corners

---

src/components/NcAvatar/NcAvatar.vue

[aria-label](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label) should only be present when the element is interactive

Do not add aria-label when avatar is not interactive

---

src/components/NcListItemIcon/NcListItemIcon.vue

This simplifies the `NcListItemIcon` component a bit, so it does not rely on checking `this.$slots` anymore. This makes the move to vue3 a tiny bit easier.

Simplify NcListItemIcon default slot usage

---

src/components/NcActionButton/NcActionButton.vue
src/components/NcActionInput/NcActionInput.vue
src/components/NcAppNavigationCaption/NcAppNavigationCaption.vue
src/components/NcAppNavigationItem/NcAppNavigationItem.vue
src/components/NcAppNavigationNewItem/NcAppNavigationNewItem.vue
src/components/NcAppSidebar/NcAppSidebar.vue
src/components/NcContent/NcContent.vue
src/components/NcListItemIcon/NcListItemIcon.vue

This PR replaces all legacy icon classes in the docs with material design icons. It only affects the docs, not the components itself. See e.g. here:
Before:
After:

Use material design icons in documentation everywhere

---

l10n/messages.pot
src/components/NcIconSvgWrapper/NcIconSvgWrapper.vue
src/components/NcIconSvgWrapper/index.js
src/components/NcListItemIcon/NcListItemIcon.vue
src/components/index.js

Unnecessary SVG title element addition is dropped as screenreaders will read the `aria-label` on `span` so we also reduce system resource usage

Add NcIconSvgWrapper to public API

---

src/components/NcContent/NcContent.vue

This fixes a little typo in the `NcContent` docs.

Fix minor typo in NcContent docs

---

src/components/NcRichContenteditable/NcRichContenteditable.vue

Fixes #3635 by adjusting the border
Signed-off-by: Chartman123 <chris-hartmann@gmx.de>

Adjust border thickness of NcRichContenteditable

---

src/components/NcAppNavigationItem/NcAppNavigationItem.vue

From nc25 (not vue):
Since we're moving away from tooltips libraries.
```
<NcAppNavigationItem name="My title" icon="icon-category-enabled" />
<NcAppNavigationItem name="My title" title="My custom title" icon="icon-category-enabled" />
```

feat(AppNavigationItem): Allow native title attribute control

---

package-lock.json
package.json
styleguide.config.js
webpack.config.js

This PR introduces the common webpack config.
However, `npm run styleguide` is broken (see #3634), which needs to be fixed before we can decide how to proceed here.

Use common webpack config

---

src/components/NcActions/NcActions.vue
src/components/NcAppNavigationItem/NcAppNavigationItem.vue
src/components/NcBreadcrumb/NcBreadcrumb.vue
src/components/NcBreadcrumbs/NcBreadcrumbs.vue
src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
src/components/NcDateTimePickerNative/NcDateTimePickerNative.vue
src/components/NcHighlight/NcHighlight.vue
src/components/NcTimezonePicker/timezoneDataProviderService.js
src/components/NcVNodes/NcVNodes.vue
src/utils/GetParent.js

This fixes most lint warnings.
Some related to the typescript types I couldn't figure out how to solve.

Fix lint errors

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud/nextcloud-vue/compare/v7.3.0...v7.4.0-beta.0)
- Use common webpack config [\#3633](https://github.com/nextcloud/nextcloud-vue/pull/3633) ([raimund-schluessler](https://github.com/raimund-schluessler))
- Add NcIconSvgWrapper to public API [\#3630](https://github.com/nextcloud/nextcloud-vue/pull/3630) ([Pytal](https://github.com/Pytal))
- feat\(AppNavigationItem\): Add href support [\#3612](https://github.com/nextcloud/nextcloud-vue/pull/3612) ([skjnldsv](https://github.com/skjnldsv))
- Add `NcSavingIndicatorIcon` [\#3575](https://github.com/nextcloud/nextcloud-vue/pull/3575) ([susnux](https://github.com/susnux))
- feat\(AppNavigationItem\): Allow native title attribute control [\#3617](https://github.com/nextcloud/nextcloud-vue/pull/3617) …

7.4.0-beta.0

---

webpack.config.js

I was right to do a beta lol 
https://github.com/nextcloud/nextcloud-vue/pull/3633/files#r1066789921

Revert webpack output file name

---

CHANGELOG.md
package-lock.json
package.json

See https://github.com/nextcloud/nextcloud-vue/pull/3644

7.4.0-beta.1

---

src/components/NcBreadcrumb/NcBreadcrumb.vue

- Add exact prop for vue router
- Fix styling
|![Capture d’écran_2023-01-13_16-31-35](https://user-images.githubusercontent.com/14975046/212357762-ddefda66-a0dd-4b96-8b7a-e79e7784e60f.png)|![Capture d’écran_2023-01-13_16-31-41](https://user-images.githubusercontent.com/14975046/212357774-e25169a3-befb-4731-bcd1-66628361a738.png)|

Breadcrumb: add exact prop and fix style

---

package-lock.json
package.json
src/components/NcSelect/NcSelect.vue

Allow setting the placement of the dropdown to open above the input in addition to the default of opening below
This also updates the dropdown position automatically to keep the element within the viewport when e.g. scrolling
Before | After
--- | ---

Set placement of select dropdown

---

webpack.config.js

Add https://github.com/nextcloud/nextcloud-vue/blob/83b054e15af5be35c8709098f485612bd5ae74e5/webpack.config.js#L127-L128 back after https://github.com/nextcloud/nextcloud-vue/pull/3633
| | Screenshot |
--- | ---
**Before** | ![image](https://user-images.githubusercontent.com/24800714/213319190-63df51c4-1b7a-45e4-a70f-e84a29b940ca.png)
**After** | ![image](https://user-images.githubusercontent.com/24800714/213319197-08705278-82c1-4581-8cc8-716d06df04d9.png)

Fix invalid svg errors in styleguide

---

src/components/NcActionButtonGroup/NcActionButtonGroup.vue
src/components/NcActionButtonGroup/index.js
src/components/index.js

This adds a component to inline `NcActionButton` within a action menu, e.g. see this example from https://github.com/nextcloud/text/pull/3544
Submitting this as suggested by @skjnldsv in https://github.com/nextcloud/text/pull/3544#discussion_r1044630774

Add `NcActionButtonGroup` to inline `NcActionButton`s within the action menu

---

l10n/messages.pot
src/components/NcColorPicker/NcColorPicker.vue

This fixes the missing text / aria-labels warnings from the NcColorpicker.

Add aria-labels to colorpicker buttons

---

README.md

Readme update:
___
This library uses translated strings.
When you edit/create a translated string, you need to run `npm run l10n:extract` to update the source files.
Our awesome translation community will then be notified and a bot will sync those changes automatically.
Nonetheless, it requires a bit of caution.
When you implement a translated string, import the `translate` or `translatePlural` and add it in your methods like so:
```vue
<template>
<element>
{{ t('Choose') }} 
</element>
</template>
<script>
import { translate as t } from '@nextcloud/l10n'
methods: {
t,
},
}
</script>
```
Please note that using a translated string as an attribute will _NOT_ work.
But it will work if it's within an element (like the example above)
```vue
<template>
<element :prop="t('This …
```

chore(l10n): update l10n readme

---

src/components/index.js

Otherwise importing with `import { NcHighlight } from ‘@nextcloud/vue'` fails

fix: Export NcHighlight through default package export

---

src/components/NcButton/NcButton.vue

Solution to prevent overriding transition styles for NcButton component.
Fix #3689. Please see issue for details.
Signed-off-by: Maksim Sukharev <antreesy.web@gmail.com>

Fix: update transition styles for NcButton

---

src/components/NcModal/NcModal.vue

We handle keydown events on the global window object
https://github.com/nextcloud/nextcloud-vue/blob/58b5c435979784c5143c1b539e52c9ada826981f/src/components/NcModal/NcModal.vue#L536
and click events on the previous and next arrow buttons
https://github.com/nextcloud/nextcloud-vue/blob/58b5c435979784c5143c1b539e52c9ada826981f/src/components/NcModal/NcModal.vue#L264
https://github.com/nextcloud/nextcloud-vue/blob/58b5c435979784c5143c1b539e52c9ada826981f/src/components/NcModal/NcModal.vue#L296
So when keyboard focus is on the previous or next button and we hit `Enter`, the click handler of either previous or next will fire and the global handler will always call `this.next()`
Focused element | Result
--- | ---
Previous button | Back then forward to the same slide
Next button | Forward two …

Fix keyboard navigation of modal slides

---

src/components/NcAppNavigationItem/NcAppNavigationItem.vue

This fixes an undefined variable bug in the `NcAppNavigationItem` component.
`this.editing` is undefined, but since the function returns `true` in only one case, it worked nevertheless. I took the chance to simplify this conditional a bit as well.

Fix NcAppNavigationItem hasUtils computed

---

src/components/NcDashboardWidget/NcDashboardWidget.vue

Fix https://github.com/nextcloud/spreed/issues/8611
25 | 26 Before | 26 After
---|---|---

Fix dashboard padding with half-empty content view

---

src/components/NcPasswordField/NcPasswordField.vue

This fixes setting the `trailingButtonLabel` (which is the `aria-label` of the trailing button in the `NcInputField` component) from the `NcPasswordField` so that the password toggle button gets the correct label.
This also fixes the `You need to fill either the text or the ariaLabel props in the button component.` warning currently visible in the docs when looking at the `NcPasswordField` component.

Fix setting trailingButtonLabel for PasswordField

---

src/components/NcAvatar/NcAvatar.vue

Fixes https://github.com/nextcloud/nextcloud-vue/issues/3677
| ![Screenshot from 2023-01-25 15-26-14](https://user-images.githubusercontent.com/6078378/214589158-df9bbc66-6d97-4497-9929-2933abd83da1.png) | ![Screenshot from 2023-01-25 15-22-51](https://user-images.githubusercontent.com/6078378/214589190-5bb0c378-10d0-4063-829b-4edfa6ff6a3b.png) | 
| ![Screenshot from 2023-01-25 15-25-58](https://user-images.githubusercontent.com/6078378/214589187-77817eec-677f-4e5a-97a1-c3f59a32c931.png) |  ![Screenshot from 2023-01-25 15-23-03](https://user-images.githubusercontent.com/6078378/214589161-e507604e-3ff5-49f6-ba67-59e85c87372c.png) |

Replace custom toolip with native one on Avatar component

---

src/components/NcAppNavigationCaption/NcAppNavigationCaption.vue
src/components/NcIconSvgWrapper/NcIconSvgWrapper.vue

This fixes a warning `You need to fill either the text or the ariaLabel props in the button component` triggered in the docs because the `NcActionButton` component has no title. Just cleanup of the docs, no effect on the component itself.
Edit: I added a commit fixing the same warning for buttons used in the `NcIconSvgWrapper` docs.

Add aria-labels to example buttons in docs

---

l10n/messages.pot
src/components/NcListItem/NcListItem.vue

We currently overwrite the `aria-label` of the `NcActions` component used in the `NcListItem` component with an empty string, which leads to a `You need to fill either the text or the ariaLabel props in the button component.` triggered by `NcListItem` by default. This PR sets the default aria-label in `NcListItem` to the same value as used in `NcActions`.

Use proper default actions aria label in `NcListItem`

---

src/components/NcBreadcrumbs/NcBreadcrumbs.vue

This simplifies the render function of `NcBreadcrumbs` a bit. We need less `if` and less `concat` now. The behaviour stays the same, no visual changes.

Simplify the render function of NcBreadcrumbs

---

src/components/NcSelect/NcSelect.vue

* Border should be primary color on hover
* Border should be stay primary color if active
* Unify the style of the `no-options` slot with `NcMultiselect`

Adjust style of NcSelect to match other input elements

---

src/components/NcButton/NcButton.vue

This moves the `NcButton` component to use a render function. This gets rid of the reactivity caveat of using `$slots` outside the template or render function. With this, the button now also properly warns if text and aria-label become undefined during runtime and not only during mount. There are no visual changes resulting.
This changes also prepares for the migration to vue 3.
Closes #3231.

Move NcButton to render function

---

src/components/NcSelect/NcSelect.vue

Explicitly set the `z-index` to ensure the select is visible in instances where the container would otherwise overlap it i.e.
https://github.com/nextcloud/nextcloud-vue/blob/f2d3d9994e4cc6fba8a5026aaedd35cc15834b03/src/components/NcModal/NcModal.vue#L710
https://github.com/nextcloud/server/blob/b765a227052300ac76daaecaf37f8e48e77dedec/apps/files/src/views/Sidebar.vue#L523

Fix hidden select

---

src/components/NcHeaderMenu/NcHeaderMenu.vue

Fix focus trap error throw "Your focus-trap must have at least one container with at least one tabbable node in it at all times" with `fallbackFocus` option documented in https://github.com/focus-trap/focus-trap#createoptions
This occurs e.g. when opening the notifications menu when there are no notifications

Fix throw when header menu contains no tabbable nodes

---

src/components/NcButton/NcButton.vue

Nextcloud server has a CSS rule `span { cursor: default; }` that would sometimes (depending on the order in which the bundle is loaded) overwrite the button cursor style. This should make it more explicit so it takes precedence over the server style.

Fix `NcButton` cursor style

---

src/components/NcSelect/NcSelect.vue

We can not set variables referencing themeable variables on the `:root` as currently the theme variables are applied on the `body` element. Meaning `var()` will be evaluated with the context of the `:root` element, which does not apply the user selected theme.
We neither can set this variables on the `select`, because the some of the variables are used to style the dropdown list which is a modal so not a child of the select.
This fixes issues like this:
https://github.com/nextcloud/forms/pull/1471#pullrequestreview-1277505842
See also https://github.com/nextcloud/server/pull/36462

fix(ncselect): Fix styling if a custom theme is applied

---

src/components/NcMultiselect/NcMultiselect.vue

This adds a missing space in the ternary expression which messed up the syntax highlighting in my editor.

Add missing space in NcMultiselect ternary expression

---

src/components/NcActions/NcActions.vue

This removes the background for open `NcActions` of type `tertiary-no-background`.
Closes #3720.
| Type | Before | After |
|-|-|-|
| `tertiary` | ![Screenshot 2023-02-06 at 10-09-44 Nextcloud Vue Style Guide](https://user-images.githubusercontent.com/2496460/216931135-95766b49-b247-4fb3-bb5d-489d589c0669.png) | ![Screenshot 2023-02-06 at 10-06-51 Nextcloud Vue Style Guide](https://user-images.githubusercontent.com/2496460/216930781-f7aca7fd-bc9f-4aa4-a3ba-a2e0808389a9.png) |
| `tertiary-no-background` | ![Screenshot 2023-02-06 at 10-10-43 Nextcloud Vue Style Guide](https://user-images.githubusercontent.com/2496460/216931280-a49c2c45-551c-4ad0-8770-06e2102d00a8.png) | ![Screenshot 2023-02-06 at 10-07-20 Nextcloud Vue Style Guide](https://user-images.githubusercontent.com/2496460/216930830-8 …

No background for `tertiary-no-background` `NcActions`

---

src/components/NcDashboardWidgetItem/NcDashboardWidgetItem.vue
src/components/NcListItem/NcListItem.vue

This removes the outdated `menu-align` prop that has no effect anymore. The menus are automatically positioned since a while already, since the prop simply was ignored. I think it works very well that way.
Supersedes #2847.

Remove outdated and unused menu-align attributes

---

src/components/NcSelect/NcSelect.vue
src/components/NcSelectTags/NcSelectTags.vue

Fix https://github.com/nextcloud/nextcloud-vue/issues/3662 and make minor updates to `vue-select` prop handling
The `limit` prop is now used instead of `optionsFilter` to limit the available tags
Previously only 5 tags were being passed as options to `VueSelect`, since `VueSelect` handles searching internally any tag after the 5th one could not be searched for
Before | After
--- | ---

Fix tag search

---

webpack.config.js

* Resolves: #3753 
This should probably go into the webpack config project, but until it is fixed there, we should fix it here.
Somewhere in a module js (ESM) file, probably by webpack-node-polyfills, `process/browser` without the required `.js` extension is imported. We do not use babel-loader on the node_modules and the default loader defaults to `resolveFullySpecified = true`, so this causes an issue. See also https://webpack.js.org/configuration/module/#resolvefullyspecified

fix: Add a webpackrule to resolve module js files in `node_modules`

---

src/components/NcRichContenteditable/NcRichContenteditable.vue

Since we don't need autocompletion on forms, we would just pass an empty function (as talk does btw., too :wink:). So why not doing this here.

RichContent autocomplete not required

---

src/components/NcAppContent/NcAppContent.vue

* In IsMobileState.js we treat viewports smaller 1024px as mobile.
* In NcAppContent.vue we treat viewports starting with 1024px as mobile.
This results in weird behaviour with screens that have exactly 1024px width. E.g., on three-pane apps, NcAppContentList is hidden but the NcAppDetailsToggle button is not displayed yet.
This commit changes NcAppContent.vue to treat viewports smaller 1024px as mobile, to be in sync with IsMobileState.js.
This PR accompanies https://github.com/nextcloud/server/pull/36751.
Both are required to fix https://github.com/nextcloud/nextcloud-vue/issues/3758.
Fixes: #3758

Don't regard 1024px width viewport as mobile

---

src/components/NcPopover/NcPopover.vue

Fixed the wrong JSDoc comment :
> Syntax error in type: import('focus-trap').Options['setReturnFocus'] eslint [jsdoc/valid-types](https://github.com/gajus/eslint-plugin-jsdoc#eslint-plugin-jsdoc-rules-valid-types)
Also added a default value to make eslint happy (even if undefined) and added the missing type information:
> Prop 'setReturnFocus' requires default value to be set. eslint: [vue/require-default-prop](https://eslint.vuejs.org/rules/require-default-prop.html)
> Prop "setReturnFocus" should define at least its type. eslint: [vue/require-prop-types](https://eslint.vuejs.org/rules/require-prop-types.html)

NcPopover: Fix `setReturnFocus` property

---

package-lock.json
package.json

Add node-polyfill-webpack-plugin

---

src/components/NcBreadcrumb/NcBreadcrumb.vue
src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
src/components/NcUserBubble/NcUserBubble.vue

Vue3 limits the use of the custom elements `:is` special attribute to the reserved `<component>` tag only, see https://v3-migration.vuejs.org/breaking-changes/custom-elements-interop.html#customized-built-in-elements
Vue2 does not care. So we migrate already to keep #3692 simpler.

Use component with :is

---

src/components/NcHeaderMenu/NcHeaderMenu.vue
src/components/NcListItem/NcListItem.vue

No effect for vue2, required for vue3. Makes the migration in #3692 a tiny bit shorter.

Adjust emits option

---

src/components/NcActionInput/NcActionInput.vue

Working on #3785 I noticed that the `NcActionInput` native datepicker has no background-color effect on hover. This PR fixes this.
|-|-|
| ![Bildschirmaufzeichnung vom 2023-02-19, 13-26-42](https://user-images.githubusercontent.com/2496460/219947963-d87b30ba-8af2-4238-ab68-de653422ed1b.gif) | ![Bildschirmaufzeichnung vom 2023-02-19, 13-30-20](https://user-images.githubusercontent.com/2496460/219948037-34770d2e-4ffc-4d74-b83d-23f8b4fd8400.gif) |

Fix hover for ActionInput datepicker native

---

src/components/NcEmptyContent/NcEmptyContent.vue

For accessibility we sometimes need an empty content with an h1.
Fixes #3672.

enh(NcEmptyContent): allow customizing the title

---

styleguide.config.js

This PR slightly adjusts the docs config to show the `NcDateTimePickerNative` in the `NcPickers` section where it belongs.

Show NcDateTimePickerNative in NcPickers section

---

src/components/NcButton/NcButton.vue

Seems with #3726 I broke the `NcButton` component of type `router-link`.
This PR brings back the correct `button` tag. `NcButton` will need a migration to the `router-link` slot later on, as the `tag` prop is decprecated.

Fix NcButton router-link

---

src/components/NcActionInput/NcActionInput.vue

This PR adds more examples for different types of `NcActionInput`. I added the types `password`, `color` and `date native`. No functional changes, only documentation.
See here:

Add examples for more ActionInput types

---

src/components/NcButton/NcButton.vue

This fixes the warning
```
[Vue warn]: The .native modifier for v-on is only valid on components but it was used on <button>.
```
which is triggered for `NcButton` currently. This is a problem due to #3726.

Fix nativeOn is only valid on components error, make rootElement computed

---

src/components/NcAppNavigationIconBullet/NcAppNavigationIconBullet.vue

This only affects the docs, no functional changes, just silenced the warning.

Migrate from deprecated `title` to `name` prop in docs

---

src/components/NcModal/NcModal.vue

This PR allows to toggle the modal visibility by setting the `show` prop of the modal, which will keep the modal in the DOM.
It also fixes the transition animation of the modal-wrapper when showing/hiding the modal with `v-if`.
Checkout the docs https://deploy-preview-3769--nextcloud-vue-components.netlify.app/#/Components/NcModal and enjoy a smooth modal wrapper animation 😉 
@susnux I think this is the best version of the solution now, as it allows to use `v-show / :show.sync="modal"` or `v-if`, fixes the transition animations for both and requires no watcher.
Fixes #497.

Allow using v-show for `NcModal`, fix modal-wrapper transition

---

src/components/NcDatetimePicker/NcDatetimePicker.vue

The background of the DatetimePicker input field is clipped to `content-box` which gives the wrong background color on the left and right. As long as the background-color of the parent is white, it's not visible, but e.g. in the `NcActionInput` component you see a problem.
I added a bright color with the devtools to make this visible:
Before:
After:

Fix clipped background color for NcDatetimePicker

---

src/components/NcActionInput/NcActionInput.vue

This PR makes the datetimepickers in `NcActionInput` the full width.
|-|-|
| ![Screenshot 2023-02-20 at 13-32-36 Nextcloud Vue Style Guide](https://user-images.githubusercontent.com/2496460/220109074-cf26b4c5-b4cb-4b0c-9367-0df0652cbd3a.png) | ![Screenshot 2023-02-20 at 13-36-17 Nextcloud Vue Style Guide](https://user-images.githubusercontent.com/2496460/220109813-baf655f0-513e-4370-bac5-ed7424edfe5b.png) |

Make datetimepicker full width in NcActionInput

---

src/components/NcActionInput/NcActionInput.vue

This replaces the deprecated `NcMultiselect` with the new `NcSelect` component for the `NcActionInput` component of type multiselect.
~Although it got better (the dropdown wasn't visible at all before),~ Like before, there currently still is a `z-index` issue for the select dropdown. This is because the `NcActions` component has a `z-index: 100000` and the select dropdown only got `9999`. Fixing this is tricky at the moment, because the dropdown gets appended to body without a custom class that could be targeted, which means we can only set the `z-index` for all select dropdowns globally, which I don't know whether we want this. The proper solution would be to enhance `NcSelect` to allow to set a custom dropdown class, but that needs an upstream fix.
| | Before | After |
|-|-|-|
| select …

Use `NcSelect` for `NcActionInput` type multiselect

---

src/components/NcActions/NcActions.vue

The scrollbar in an `NcActions` component makes the right top and bottom corners square. This PR fixes it.
|-|-|
| ![Screenshot 2023-02-20 at 14-03-36 Nextcloud Vue Style Guide](https://user-images.githubusercontent.com/2496460/220117175-cf43135a-99e3-4e26-9c00-ac52e08c2b30.png) | ![Screenshot 2023-02-20 at 14-09-32 Nextcloud Vue Style Guide](https://user-images.githubusercontent.com/2496460/220117919-4dd2917b-6b8e-4537-8974-c466295c7e97.png) |

Show round corners for scrolling NcActions

---

src/components/NcAppNavigationToggle/NcAppNavigationToggle.vue

Closes #3688 
Changed icon for NcAppNavigationToggle in open state with more visually and semantically appropiate icon
Before | After
--- | ---

NcAppNavigation - change toggle icon for opened sidebar

---

src/components/NcPopover/NcPopover.vue

This fixes the invalid prop type check for `NcPopover` `setReturnFocus`. As per the focus-trap docs, allowed values are
`HTMLElement | SVGElement | string | Boolean`, see
https://github.com/focus-trap/focus-trap/blob/4cbbef5e971bcdadcc07c3cbb08d0fccfc001809/index.d.ts#L4-L5
Fixes #3801.

Fix prop type check for NcPopover setReturnFocus

---

src/components/NcTimezonePicker/NcTimezonePicker.vue

This PR moves `NcTimezonePicker` from using `NcMultiselect` to `NcSelect`. Since `NcSelect` does not support grouping, I had to work around this a bit, but the outcome is the same as when using `NcMultiselect`. I additionally enhanced the search function a bit, so one can now also search for the continent name and see all timezones e.g. in Europe, and searching for "Europe London", will give the correct timezone.
The styling probably needs a bit of adjustment still, because it currently uses the default `NcSelect` style with a gray/blue border, whereas the current timezone picker has no border. But maybe we want to update the style here and match with the other pickers, so I left it for now.
|-|-|
| ![image](https://user-images.githubusercontent.com/2496460/219797388-f8e …

Use `NcSelect` for `NcTimezonePicker`

---

src/components/NcTimezonePicker/NcTimezonePicker.vue

Adds a missing trailing comma in the timezone picker. Regression of #3781.

Add missing trailing comma

---

src/components/NcActionInput/NcActionInput.vue

For the `NcActionInput` type multiselect, we need to allow the `value` of type `array` in case on passes an object as the options. Otherwise we will get an invalid prop type check.
Follow-up of #3760.

Allow value of type array for NcActionInput

---

src/components/NcActionInput/NcActionInput.vue
src/components/NcDateTimePickerNative/NcDateTimePickerNative.vue

This adds the `inputClass` prop to the `NcDateTimePickerNative` component. This is necessary so the input field gets correctly focused when the datepicker is used in the `NcActionInput` component. With this PR, the datepicker gets the focus when you use the keyboard to navigate through the actions. Before, there was no way of focusing the datepicker with the keyboard only.

Allow to add class to native datepicker input

---

l10n/messages.pot
package-lock.json
package.json
src/components/NcRichContenteditable/NcRichContenteditable.vue
src/functions/linkPicker/index.js

This integrates the vue-richtext's link picker in RichContentEditable with TributeJS. The trigger is "/". The item list is obtained from a vue-richtext function call.
The workflow:
* type /
* choose a link provider
* this opens a modal which contains either
* a generic search (using one or multiple unified search providers)
* a custom picker element
* user does the work which results in getting a link
* the link is inserted in the RCE content
As picking a link is asynchronous, I used a trick to make it work with Tribute:
A dummy invisible element is inserted immediately when opening the link picker (when selecting a tribute dropdown item). Once the picker returns the link (with a promise), the dummy element is replaced by the link.
:warning: For the link picker to get the provider list, …

Add link picker in RichContentEditable with tribute

---

src/components/NcSelect/NcSelect.vue

If the selected option is longer than the element it should not overflow the NcSelect but use ellipsis.
before | with `min-width: 0` | with hidden disabled search
---|---|---
As you can see currently the option overflows the select, note the actions (dropdown toggle) are missing because they are placed outside the select underneath other elements on the right.
After fixing the overflow there is still this weird height issues, which happens because `.vs__selected-options` have `flex-wrap` set and contain the search input even if it is disabled (`searchable=false`).
This can be fixed by removing the search input from the visible dom when not used.
I already submitted a upstream PR, but I doubt that it will be merged soon.

`NcSelect`: Selected options should not overflow the container

---

src/components/NcActionInput/NcActionInput.vue
src/components/NcInputField/NcInputField.vue

This PR introduces the `NcTextField` and `NcPasswordField` to the `NcActionInput` component to unify the appearance.
|-|-|
| ![Screenshot 2023-02-22 at 10-42-12 Nextcloud Vue Style Guide](https://user-images.githubusercontent.com/2496460/220582279-5f2f27e2-9fea-413e-806a-2df150cfd5fe.png) | ![Screenshot 2023-02-22 at 10-43-10 Nextcloud Vue Style Guide](https://user-images.githubusercontent.com/2496460/220582490-9eeaf2a0-bb85-492b-91fd-13a4a266ec86.png) |
I had to enhance the `NcInputField` component a bit, to allow type `number` and enable adding a class to its input field.
@jancborchardt @nimishavijay Could you especially have a look at the color picker please? Before we used an input field of type color which gave the native colorpicker, now we use the colorpicker …

Use `NcTextField` for `NcActionInput`

---

src/components/NcSelect/NcSelect.vue

* Resolves: #3808 
I think this resolves the issue, does this looks like you would expect it to look with `no-wrap` set?
before | after
---|---
https://user-images.githubusercontent.com/1855448/220661348-1ed78048-cb97-49f3-ac1e-8bb8a04b47f7.mp4

fix(NcSelect): Do not squash selected items with `no-wrap` set

---

src/components/NcActionInput/NcActionInput.vue

The `date` type of the `NcActionInput` component didn't have it's opacity reduced when not hovered. This PR unifies this.
|-|-|
| ![Screenshot 2023-02-23 at 14-49-11 Nextcloud Vue Style Guide](https://user-images.githubusercontent.com/2496460/220926449-d6eb15c5-8f3d-47eb-904a-2f415ffb70df.png) | ![Screenshot 2023-02-23 at 14-49-29 Nextcloud Vue Style Guide](https://user-images.githubusercontent.com/2496460/220926485-b55e4efa-fdcc-438f-962c-591016ca6b6e.png) |

Unify datetimepicker opacity in NcActionInput

---

src/components/NcDatetimePicker/NcDatetimePicker.vue
src/components/NcDatetimePicker/index.scss

This PR adjust the `NcDatetimePicker` styling to bring it inline with the other picker and input styles. It also replaces the icons used with material design icons.
|-|-|
| ![Screenshot 2023-02-23 at 13-52-58 Nextcloud Vue Style Guide](https://user-images.githubusercontent.com/2496460/220912141-b082aa46-397e-44bf-850a-a091c6db6de7.png) | ![Screenshot 2023-02-23 at 13-53-23 Nextcloud Vue Style Guide](https://user-images.githubusercontent.com/2496460/220912167-1e88b73d-5c3c-44c4-a47c-111f6e035b01.png) |
| <img width="265" alt="ActionInputBefore" src="https://user-images.githubusercontent.com/2496460/220912201-5b232a6a-3cfa-492d-b11d-29e7932c53d1.png"> | <img width="266" alt="ActionInputAfter" src="https://user-images.githubusercontent.com/2496460/220946493-01ca7284-e037-4c …

Adjust `NcDatetimePicker` styling

---

src/components/NcVNodes/NcVNodes.vue

Functional components are not supported anymore with vue 3, so we make the `VNodes` component non-functional already. The performance impact should be negligible, since the component is only used to show the appsidebartabs icons.

Make `NcVNodes` component non-functional

---

src/components/NcAppNavigation/NcAppNavigation.vue
src/components/NcAppNavigationItem/NcAppNavigationItem.vue
src/components/NcListItem/NcListItem.vue

* Resolved: #3351 
Add the missing right border on the app navigation (high contrast mode). Unify design with settings view where the app navigation has a border on the right on high contrast mode.
Changed the background color of the active element on high contrast mode, as the highlighting was barley visible.
Also applied the styles for the NcListItem to have a common styling across apps, as some apps, like the forms app, use list items instead of app navigation items (to allow a second title within the item).
Normal | High-contrast before | High-contrast now|
---|--- | ---

fix: High contrast mode optimization

---

src/components/NcButton/NcButton.vue

This fixes a runtime warning if the `default` slot of `NcButton` does not contain text only, e.g. `<p>Test</p>`.
Closes #3824.

Don't fail if `NcButton` default slot contains not only text

---

src/components/NcDateTimePickerNative/NcDateTimePickerNative.vue

This PR adjusts the icon position of `NcDateTimePickerNative` to align with the other input and datepicker components.
After:

Adjust native datepicker icon position

---

src/components/NcRichContenteditable/NcRichContenteditable.vue

This fixes the position of the cursor in the `NcRichContenteditable` component after one types text and deletes it again. I also adjusted the padding a bit, to bring the text to the center. Closes #3828.
Before:
After:

Fix rich content placeholder position

---

src/components/NcSelect/NcSelect.vue

This fixes a regression where the placeholder text is not shown if `NcSelect` is configured to be not searchable, in this case the input element was hidden but this also hides the placeholder.

NcSelect: Only hide search input if disabled and an element was selected

---

package-lock.json
package.json

Use `@nextcloud/vue-richtext` 2.1.0-beta.6 which fixes the circular dependency by including `@nextcloud/vue` in its rollup package.
This made it impossible to import both `@nextcloud/vue` and `@nextcloud/vue-richtext` in the same script and caused rendering issues of  `@nextcloud/vue-richtext` when used in `@nextcloud/vue`.
This is a temporary fix for things to work until `@nextcloud/vue-richtext` is merged in here.
refs #3812

Fix circular dependency with `@nextcloud/vue-richtext`

---

src/components/NcRichContenteditable/NcRichContenteditable.vue

* Resolves: https://github.com/nextcloud/forms/issues/1536
Currently the previous content of the `NcRichContentEditable` is replaced when pasting behind a newline.
This fixes this by emitting the full content after a paste event.
https://user-images.githubusercontent.com/1855448/221934330-dc88f086-d8b7-48f9-b907-5780f82219c7.mp4
https://user-images.githubusercontent.com/1855448/221934362-04bd934b-fbce-4bea-98f3-e84d54f5d7fc.mp4

`NcRichContentEditable`: Emit correct rich content on paste

---

package.json

This white-lists only the packages necessary for jest to run the tests without transforming all packages in `node_modules`. I think this speeds up the test run a bit, but it's difficult to say, as jest (or babel?) kind of seems to cache the transformation result.

Only transform necessary packages for jest

---

src/components/NcRichText/NcReferencePicker/NcSearch.vue

This migrates the usage of the deprecated `v-deep` directive in `NcSearch`.

Don't use deprecated v-deep

---

src/components/NcRichText/NcReferencePicker/NcReferencePicker.vue

This is just a little cleanup which removes the empty `beforeDestroy` block.

Remove empty beforeDestroy block in `NcReferencePicker`

---

src/components/NcRichText/NcReferencePicker/NcRawLinkInput.vue

The close/clear icon in the `NcRawLinkInput` component is not registered. However, since the default close button icon is already `close`, providing it is anyway superfluous. So this PR just removed the useless template. No visual or functional changes.

Remove superfluous input close icon template

---

l10n/messages.pot
src/components/NcRichText/NcReferencePicker/NcProviderList.vue
src/components/NcRichText/NcReferencePicker/NcRawLinkInput.vue
src/components/NcRichText/NcReferencePicker/NcSearch.vue
src/components/NcRichText/NcReferencePicker/providerHelper.js

This translates some yet untranslated strings.

Translate strings in `NcRich*` components

---

src/components/NcRichText/autolink.js

The second parameter of the `parseUrl` function is not used, so I removed it. It was called without it anyway already here:
https://github.com/nextcloud/nextcloud-vue/blob/d36b3f694405e49a34ec1ac0422c1657c8908cac/src/components/NcRichText/placeholder.js#L39

Remove unused parseUrl parameter

---

src/components/NcRichText/autolink.js

Vue3 does not support functional components anymore. Performance decrease should be negligible here. Similar to #3816.

Make NcLink non-functional

---

src/components/NcAppNavigationItem/NcAppNavigationItem.vue
src/components/NcButton/NcButton.vue
src/components/NcListItem/NcListItem.vue
src/components/NcVNodes/NcVNodes.vue

This PR migrates the `NcAppNavigationItem`, `NcButton` and `NcListItem` components from using the dreprecated `tag` prop of `router-link` to the `v-slot` API introduced with `vue-router@3.1.0`, see https://v3.router.vuejs.org/api/#v-slot-api-3-1-0. This is required to make the library compatible with `vue-router@4` for vue 3 in #3692.
There are no functional changes and the markup stays the same. For the dev, nothing should change, besides that the corresponding warning from `vue-router` is gone.
The PR is best viewed as https://github.com/nextcloud/nextcloud-vue/pull/3775/files?diff=unified&w=1

Migrate from `router-link`'s `tag` prop to `v-slot`

---

src/components/NcAppNavigationItem/NcAppNavigationItem.vue

With my last "cleanup" commit 4ce516e959d5ca2c180e178c54e5433af134aa00 in #3775 I introduced a little bug by not providing the `$event` to the `navigate` handler. This makes the navigation fail and gets fixed by this PR.

Fix navigate handler call

---

src/components/NcRichText/NcReferencePicker/NcSearchResult.vue

For https://github.com/nextcloud/spreed/pull/9053
Before | After
---|---

feat(NcRichText): Support icon class for smart picker integrations

---

l10n/messages.pot
src/components/NcRichContenteditable/NcRichContenteditable.vue
src/components/NcRichText/NcReferencePicker/NcReferencePickerModal.vue
src/components/NcRichText/NcReferencePicker/providerHelper.js

Call the link picker "smart picker" and translate more strings

---

src/components/NcActions/NcActions.vue
tests/unit/components/NcActions/NcActions.spec.js
tests/unit/components/NcActions/TestCompositionApi.vue

* Resolves: #3719
The setup function of the composition API does not pass components by name but by instance to the vue render function `h`.
This results in `componentOptions.tag` being undefined, so for this case we need to check the `Ctor` instead.

fix: Render actions when using the composition API

---

l10n/messages.pot
src/components/NcRelatedResourcesPanel/NcRelatedResourcesPanel.vue
src/components/NcRelatedResourcesPanel/NcResource.vue

| | Screenshot |
--- | ---
**Before (Top-right toast + empty panel area)** | ![image](https://user-images.githubusercontent.com/24800714/222816642-6529c237-c268-4a36-b237-751a492297b9.png) ![image](https://user-images.githubusercontent.com/24800714/222816603-5dd80c88-2ca0-42b2-b237-b94a90c02826.png)
**After** | ![image](https://user-images.githubusercontent.com/24800714/223221743-926c6387-b04d-4c8d-b291-7680e65657f8.png)

Display related resources error message in panel

---

src/components/NcListItem/NcListItem.vue

@raimund-schluessler When using `NcListItem` in https://github.com/julien-nc/integration_miro/blob/main/src/components/talk/SendModal.vue#L31-L49 we get this error:
This appeared with `@nextcloud/vue` 7.8.1.
If I'm right about the fix, this PR might need some more changes to deal with the undefined `router-link` in `<component :is="to ? 'router-link' : 'NcVNodes'"`

Fix missing NcVNodes import in NcListItem

---

src/components/NcPopover/NcPopover.vue

`NcPopover` is a wrapper around `floating-vue`'s `Dropdown` component. It proxies all attrs and listeners to the wrapped Dropdown. It allows setting any `Dropdown`'s props for customization.
But Vue inherits all attrs on the root node by default. It makes all attrs, passed as Dropdown prop, set as HTML attrs of root div.
This PR adds the required `inheritAttrs: false`.
ESLint rule helping with this problem: https://eslint.vuejs.org/rules/no-duplicate-attr-inheritance.html
- **Add an example with passing props to the `Dropdown`**
- **Fix Popover positions in docs**
- Before:
- After: 
- **Fix typos in docs**
See commits for details 🦖

Fix doubling attrs in `NcPopover` and improve docs

---

src/components/NcRichContenteditable/NcRichContenteditable.vue

Fix #3264 
Fix https://github.com/nextcloud/spreed/issues/9104

fix(NcRichContenteditable): Fix pasting XML and HTML content

---

src/components/NcRichContenteditable/NcRichContenteditable.vue

Tribute is listening to keyup, but we don't need this.
1. Start writing a completion `@al`
2. Cancel with Escape
3. Paste a sentence starting with a space ` Lorep Ipsum`
4. See the tribute opening on the top left of the screen
1. Paste some string starting with a valid mention like `@all lorem ipsum`
4. See the tribute opening on the top left of the screen
- The tribute popup does not opens

fix(NcRichContenteditable): prevent tribute from opening on keyup

---

src/components/NcRichContenteditable/NcRichContenteditable.vue

* Fix #3825 
Opposed to #3923 I fixed it in `NcRichContenteditable` so that other components like the emoji picker itself are not interfered and still operate normally.

fix(NcRichContenteditable): Fix tribute emoji complete interfering unexpectedly aka. 🇨🇨 

---

src/functions/emoji/emoji.js

See https://github.com/nextcloud/nextcloud-vue/pull/3924#issuecomment-1482504034 for more details

feat(Emoji): Suggest emojis based on text smiles

---

src/components/NcAppNavigationItem/NcAppNavigationItem.vue
src/components/NcListItem/NcListItem.vue

This brings back the correct `href` for the link in `NcListItem` and `NcAppNavigationItem` that got erroneously removed with #3775. Closes #3921.
Tested with Talk master and the links show up again.

Bring back correct href for router-link links

---

src/components/NcAvatar/NcAvatar.vue

Fix #3877 and fix https://github.com/nextcloud/spreed/issues/8625
Apply similar solution to what we have in https://github.com/nextcloud/nextcloud-vue/pull/3707: at the moment of mounting component we can't rely on styles, generated by `this.$el`, so it's better to refer to `document.body`, where we have rules for dark / light themes

Fix styles inheritance in `NcAvatar` when being mounted

---

src/components/NcEmptyContent/NcEmptyContent.vue

Fixes https://github.com/nextcloud/server/issues/37325
No visual changes. Add `aria-hidden="true"` to icon slot because an icon have only decorative purposes in all cases.

Add `aria-hidden` to icon of empty content

---

src/components/NcRichContenteditable/NcRichContenteditable.vue

1. Open http://localhost:6060/#/Components/NcRichContenteditable
2. Paste `@Test01 or inserting emoji` into the input
3. Check that there is no dangeling Tribute in the top left
Seems there was yet another event triggering the tribute.
With the given modification the problem does not occur anymore.
Seems that preventDefault() (from vue `.prevent`) is not enough.

fix(NcRichContenteditable): Completely stop event propagation for keyup events

---

src/components/NcRichText/NcRichText.vue
src/components/NcRichText/helpers.js
tests/unit/components/NcRichText/NcRichText.spec.js

Fix https://github.com/nextcloud/spreed/issues/9187
Before | After
---|---

fix(NcRichText): Match IP addresses as links

---

src/components/NcRichText/NcRichText.vue
src/components/NcRichText/placeholder.js

@juliushaertl We missed something when moving `RichText` in here as `NcRichText`.
The `richtext.scss` file is not used anymore. It had to be imported separately when `RichText` was used.
We could now simply import it in `NcRichText`.
@raimund-schluessler No problem with importing it, right?
Another problem raised in https://github.com/nextcloud/spreed/issues/9163 is that links have the `rich-text--component` class and they apparently used to have the `rich-text--external-link` (with `useMarkdown` set to false). This leads to them not being underlined anymore.
@juliushaertl Apparently this appeared after `@nextcloud/vue-richtext` v2.0.4. Does it ring a bell? Any intentional change in the link class?
Fix nextcloud/spreed#9163

Fix NcRichText style

---

src/components/NcAppSidebar/NcAppSidebar.vue
src/components/NcAppSidebar/NcAppSidebarTabs.vue
src/components/NcAppSidebarTab/NcAppSidebarTab.vue
tests/unit/components/NcAppSidebar/NcAppSidebarTabs.spec.js

Fixes: #3461
Currently, `NcAppSidebarTabs` gets content passed slot, goes throw all nodes, and detects `NcAppSidebarTab` instances. But it happened once on mounted and does not support tabs update.
In this solution:
1. `NcAppSidebarTabs` provides:
- `registerTab` method
- `unregisterTab` method
- `activeTab` property (replacement for `$parent`), could be reverted
2. All `NcAppSidebarTab` register and unregister themself on `created` and `beforeDestroy`
3. After registration `NcAppSidebarTabs` has the tab's data directly from the `NcAppSidebarTab`s
Sorting works the same way it was before. But there is no warnings if a user passes not-tabs as content.
This solution is fully compatible with Vue 3 as it is and Composition API.

Fix dynamic tabs registration and a11y in NcAppSidebarTabs with provide/inject

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud/nextcloud-vue/compare/v7.8.4...v7.8.5)
- fix\(NcRichContenteditable\): Completely stop event propagation for keyup events [\#3937](https://github.com/nextcloud/nextcloud-vue/pull/3937) ([nickvergessen](https://github.com/nickvergessen))
- fix\(NcRichText\): Match IP addresses as links [\#3935](https://github.com/nextcloud/nextcloud-vue/pull/3935) ([nickvergessen](https://github.com/nickvergessen))
- fix\(NcRichText\): Fix NcRichText style [\#3932](https://github.com/nextcloud/nextcloud-vue/pull/3932) ([julien-nc](https://github.com/julien-nc))

chore(release): Bump version to 7.8.5

---

src/components/NcButton/NcButton.vue

|![Capture d’écran_2023-03-28_13-17-25](https://user-images.githubusercontent.com/14975046/228220069-1f5ae8f5-453b-4ee3-b99d-4816994c3811.png)|![Peek 28-03-2023 13-16](https://user-images.githubusercontent.com/14975046/228220089-f55b9faa-427c-492d-9d57-ad358af670ae.gif)|

fix(NcButton): ellipsis text on small width

---

src/components/NcActionButton/NcActionButton.vue
src/components/NcActionInput/NcActionInput.vue
src/components/NcActionLink/NcActionLink.vue
src/components/NcActionText/NcActionText.vue
src/components/NcActions/NcActions.vue
src/components/NcButton/NcButton.vue
src/mixins/actionText.js

**Accessibility issue**
Fixes https://github.com/nextcloud/server/issues/36909
Add `aria-hidden` attributes for decorative icons for all components from weather menu:

Add `aria-hidden` to icons of different components

---

src/components/NcDatetimePicker/NcDatetimePicker.vue

Required for https://github.com/nextcloud/calendar/issues/4259
This allows to overwrite the locale configuration of the upstream date picker library. Some apps (e.g. Calendar) overwrite some of the default values which are specified here.
https://github.com/nextcloud/calendar/blob/90f4f29204a95a49daa3961e33addf80f5720e7e/src/components/Shared/DatePicker.vue#L24

enh(NcDatetimePicker): convert lang computed value to prop

---

src/components/NcAppSettingsDialog/NcAppSettingsDialog.vue

In the photos app the file picker inside of NcAppSettingsDialog loses focus because it's appended to the body
reproduction: 
1. open the photos app
2. go to photos settings 
3. try changing the photos directory 
4. Navigate with tab or try adding a new folder

Add additionalTrapElements prop to settingsDialog

---

src/components/NcAppContent/NcAppContent.vue

* Resolves: https://github.com/nextcloud/server/issues/36911
Add a possibility for providing a heading for `NcAppContent`.
Move `<h1>` heading in the <main> landmark instead of the `<header>`.
By jumping directly to the h1 heading the user would be able to navigate through the main content of the page immediately.
See https://github.com/nextcloud/server/issues/36911#issuecomment-1492439336
| ![Screenshot from 2023-04-05 10-47-51](https://user-images.githubusercontent.com/6078378/230030511-7eb2b4a4-dbe3-4732-b4f8-ac58e674a3db.png) |![Screenshot from 2023-04-05 10-42-58](https://user-images.githubusercontent.com/6078378/230029271-35e8dc5 …

Add placeholder for heading inside of app content

---

src/components/NcAppNavigationItem/NcAppNavigationItem.vue
src/components/NcListItem/NcListItem.vue

`Ctrl+Click`, `Shift+Click` and etc. on a link in `NcListItem` and `NcAppNavigationitem` opens the link in a new tab.
Nothing happened
In `NcListItem` and `NcAppNavigationitem` when the item is a `RouterLink`, navigation after a click is handled manually, while default behavior stops with `event.preventDefault()`.
It breaks a native web-browser behavior - the ability to open a link in a new tab by combining a Click with a modifier key, for example, `Ctrl+Click`.
This PR checks if modifiers are pressed before the manual navigation and preventing default behavior.
Regression of: https://github.com/nextcloud/nextcloud-vue/pull/3775
Continue of: https://github.com/nextcloud/nextcloud-vue/pull/3922
Related: https://github.com/nextcloud/talk-desktop/issues/104

Fix native open in a new tab in components with a custom router link

---

l10n/messages.pot
src/components/NcRichText/NcReferencePicker/NcProviderList.vue
src/components/NcRichText/NcReferencePicker/NcReferencePickerModal.vue

Adjust some smart picker strings

---

src/components/NcActions/NcActions.vue

Since #3927 the tooltip directive is unused in the `NcActions` component, but was not removed entirely. This is done here now.

Remove unused tooltip directive

---

src/components/NcRichText/NcReferencePicker/NcReferencePickerModal.vue
src/components/NcRichText/NcReferencePicker/NcSearch.vue

* Remove it to let custom picker components set it if needed.
* Adjust the padding of the generic search.
* Make one class more explicit
This allows, for example, custom picker components that have infinite scrolling (like the Giphy integration one) to remove bottom padding/margin which looks better.
As we can't make sure nextcloud/vue is updated everywhere at once and all the providers are adjusted (I'll make sure most of them are :grin: ), we might temporarily have:
* double padding with adjusted providers displayed in apps using an old nextcloud/vue release
* no padding at all for old providers displayed in apps using a nextcloud/vue release which includes those changes
Not that bad IMO.

Remove the smart picker modal padding

---

src/components/NcBreadcrumb/NcBreadcrumb.vue

We currently wrongfully overwrite the `href` attribute of the `router-link` in `NcBreadcrumb` with the default `href` prop value. This makes the link rendered by `router-link` to not have its `href` attribute correctly set, which prevents the default link behavior. Navigating still works though, so I guess this is why we didn't notice yet. This PR fixes it by only setting the `href` attribute from the prop if it's not a `router-link`.

Don't overwrite router-link href in NcBreadcrumb

---

src/components/NcHeaderMenu/NcHeaderMenu.vue

- This was here for legacy menus that were still using icon classes
- Because this is a vue component, it means apps using it are already using svg (notifications, settings menu, contacts menu, search... etc) 
This also fixes the weird avatar invert bug
Fix https://github.com/nextcloud/server/issues/37379

fix(NcHeaderMenu): fix unnecessary filter invert

---

src/components/NcSelectTags/NcSelectTags.vue

Add opt-in props to disable internal v-model and options handling for NcSelectTags

feat(NcSelectTags): Disable internal v-model and options handling

---

src/directives/Tooltip/index.scss

Equivalent of https://github.com/nextcloud/server/pull/35485 for nextcloud-vue
Bootstrap 3.3.5 has XSS vulnerabilities and some security scanners report that Nextcloud is using a vulnerable dependency. However, this is a false positive, as only some SCSS from that version is included ([originally in server](https://github.com/nextcloud/server/commit/1c128e93913caa350be3c4274c73b28eaddc6a90), then [in nextcloud-vue](https://github.com/nextcloud/nextcloud-vue/commit/026a5f05fe616bb8dbc5d21b41aa1eba06bd270e#diff-d176069cb5022ae4bd2f74e41e25845de1291330544cb0c335bdd71a36b9135d)) and nothing can be exploited.
It seems that the scanners [just look for the version string instead of actually checking the vulnerability](https://www.tenable.com/plugins/was/112373), so the version reference was …

Split Bootstrap version reference in Tooltip .scss

---

src/components/NcInputField/NcInputField.vue

The `NcInputField` component currently warns about a missing label only if a label is provided and if the label changes during the lifetime of the component (which probably is the reason why no one noticed this yet). This PR fixes the inverted logic and runs the check on component creation as well. This might spawn quite a few warnings in the apps using this component, but I guess that's what this warning is for :shrug: 
As a side note, I would propose to change from `throw new Error` to `Vue.warn`, but that's a matter of taste, I guess.

Fix inverted validate label check in NcInputField

---

src/components/NcRichContenteditable/NcAutoCompleteResult.vue

- Required for https://github.com/nextcloud/spreed/issues/9188
- Talk PR to show it in action https://github.com/nextcloud/spreed/pull/9332

feat(NcRichContenteditable): Allow to pass in an icon URL

---

src/components/NcAppSidebar/NcAppSidebar.vue
src/components/NcAppSidebar/NcAppSidebarTabs.vue
src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
tests/unit/components/NcAppSidebar/NcAppSidebarTabs.spec.js

* Resolves #603
I split this into separate commits to make reviewing easier as the PR is quite huge.
The first part adjusts the styling of the checkbox radio switch to be used with for the sidebar tabs (adjust borders and add an icon slot).
The hover colors are confusing, primary color is applied to multiple elements, the border is only applied to not-selected elements.
https://user-images.githubusercontent.com/1855448/229255077-560d4054-8cbf-4207-a4e5-4902bf887f8d.mp4
<details>
The border is applied around the whole group, the hover color is fixed to be primary on the checked element and default hover color otherwise.
https://user-images.githubusercontent.com/1855448/229255140-24e1603a-c0cf-436c-83f8-053bfbe85533.mp4
</details>
The border is applied around the whole group, the hover …

Improve `NcCheckboxRadioSwitch` and use for `NcAppSidebarTabs`

---

src/components/NcAppSidebar/NcAppSidebar.vue

`NcMultiselect` is deprecated, we should not use it in the lib. No functional changes here, it only affects the docs. Ref #3743.

Use NcSelect in NcAppSidebar example

---

src/components/NcSelect/NcSelect.vue

Before | After
--- | ---
Keep the `input` and selected option on a single line

Disable wrap on overflow

---

src/components/NcAppSidebar/NcAppSidebarTabs.vue

Fix: https://github.com/nextcloud/spreed/issues/9345
1. Add tabs `A`, `C` to `NcAppSidebarTabs`
2. Set active `B` add add tab `B`
New tab is added, but not active.
New tab is added and active.
Local `activeTab` should be updated on each new tab registration. Previously it was updated only if it wasn't set before (I have no ideas, why).
It's a bit specific, I decided not to add it to the documentation.
```vue
<template>
<div>
<button @click="active = 'settings-tab', showTabs[1] = true">Activate settings and add settings-tab</button>
<NcCheckboxRadioSwitch :checked.sync="showTabs[0]">Show search tab</NcCheckboxRadioSwitch>
<NcCheckboxRadioSwitch :checked.sync="showTabs[1]">Show settings tab</NcCheckboxRadioSwitch>
<NcCheckboxRadioSwitch :checked.sync="showTabs[2]">Show sharing …
```

NcAppSidebarTabs: fix activating the tab being added

---

src/components/NcActionInput/NcActionInput.vue
src/components/NcPasswordField/NcPasswordField.vue

This would allow to not show the eye icon on sharing password field.
Before | After
-- | --

Allow to override showTrailingButton from an NcAction

---

src/components/NcBreadcrumbs/NcBreadcrumbs.vue

This adjusts the CSS of the `NcBreadcrumbs` component to the new HTML structure changed in #3990. After #3990 the breadcrumbs would not shrink correctly anymore on small screens, this PR fixes it.
Before (overlaps the `NcActions` on the right):
After (no overlap, correctly shrinks):

Adjust breadcrumb CSS to new html structure

---

src/components/NcAppNavigation/NcAppNavigation.vue

Fix an old sidebar navigation on server.
This fix is only for (where `app-navigation-vue` is used):
* Fixes: https://github.com/nextcloud/server/issues/36990
* Fixes: https://github.com/nextcloud/server/issues/36926
The goal of this fix: don't allow screen reader navigation through a sidebar if sidebar is closed. No visual changes.
After:

Add aria-hidden attr to the whole navigation depending on a sidebar state

---

src/components/NcRichContenteditable/NcMentionBubble.vue
src/mixins/richEditor/index.js

This is e.g. the case with guests and user groups in talk.
It's the follow up to the removal of the quotes in talk from https://github.com/nextcloud/spreed/pull/9420 which previously caused double quoting for users and groups with a space. But now groups and guests without a space are no longer quoted.

fix(NcRichContenteditable): Also quote ids containing a slash

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud/nextcloud-vue/compare/v7.11.0...v7.11.1)
- fix\(NcRichContenteditable\): Also quote ids containing a slash [\#4031](https://github.com/nextcloud/nextcloud-vue/pull/4031) ([nickvergessen](https://github.com/nickvergessen))
\* *This Changelog was automatically generated by [github_changelog_generator](https://github.com/github-changelog-generator/github-changelog-generator)*

Release 7.11.1

---

src/components/NcAppNavigation/NcAppNavigation.vue

See https://github.com/nextcloud/nextcloud-vue/pull/4016#discussion_r1185014371

fix(NcAppNavigation): fix flex element styles causing resizing sidebar

---

src/components/NcRichText/NcReferenceList.vue

Fixes https://github.com/nextcloud/text/issues/3824
When there is no result for the references we should hide the container and also not fail early on trying to access an undefined object.

fix: Avoid showing the reference list if no results were found

---

src/components/NcRichText/NcReferenceList.vue

Turns out I messed up testing of #4036 with the case to show references, this is the follow up fix to actually still show the link preview when expected
Before this change the link preview was only shown if the data was provided through the prop, not if it was dynamically fetched from the provided text.

fix: Fix regression to still display references

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud/nextcloud-vue/compare/v7.11.1...v7.11.2)
- fix: Fix regression to still display references [\#4039](https://github.com/nextcloud/nextcloud-vue/pull/4039) ([juliushaertl](https://github.com/juliushaertl))
- fix: Avoid showing the reference list if no results were found [\#4036](https://github.com/nextcloud/nextcloud-vue/pull/4036) ([juliushaertl](https://github.com/juliushaertl))
- fix\(NcAppNavigation\): fix flex element styles causing resizing sidebar [\#4035](https://github.com/nextcloud/nextcloud-vue/pull/4035) ([ShGKme](https://github.com/ShGKme))

release: v7.11.2

---

src/mixins/clickOutsideOptions/index.js

There is a regression since we switched to `@vueuse` for the click outside trigger, as the option for ignored selectors is not called `ignored` but `ignore`.
So currently the `exclude-click-outside-selectors` option does not work.

Fix regression of click-outside-options mixin not working since using `@vueuse`

---

src/components/NcActionButton/NcActionButton.vue
src/components/NcActionLink/NcActionLink.vue
src/components/NcActionRouter/NcActionRouter.vue
src/components/NcActionText/NcActionText.vue
src/components/NcActionTextEditable/NcActionTextEditable.vue
src/components/NcAppNavigationItem/NcAppNavigationItem.vue
src/components/NcBreadcrumb/NcBreadcrumb.vue
src/components/NcBreadcrumbs/NcBreadcrumbs.vue
src/mixins/actionText.js

Since master is `8.0.0` now, we can merge all breaking changes scheduled for the next major.
This PR removes the `nameTitleFallback` and makes the `name` prop required for `NcActions*`, `NcAppNavigationItem` and `NcBreadcrumb*`.

Migrate from deprecated title prop

---

src/assets/action.scss
src/components/NcActionCheckbox/NcActionCheckbox.vue
src/components/NcActionInput/NcActionInput.vue
src/components/NcActionRadio/NcActionRadio.vue
src/components/NcActionTextEditable/NcActionTextEditable.vue
src/components/NcActions/NcActions.vue

Before | After
--- | ---
> `--color-background-hover` is `#f5f5f5`
`#222222` on `#ffffff` is 15.9:1
`#222222` on `#f5f5f5` is 14.59:1
`#949494` on `#ffffff` is 3.03:1
`#006aa3` on `#f5f5f5` is 5.36:1

enh(NcActions): Readability

---

src/components/NcActionInput/NcActionInput.vue
src/components/NcSelect/NcSelect.vue

Regression from https://github.com/nextcloud/nextcloud-vue/pull/3760
Fix NcActions focusable functionality with NcSelect

fix(NcSelect): Action input usage

---

src/components/NcAppContent/NcAppContent.vue

The upper context sometimes needs to know when the list pane is resized. If, for example, the content of the NcAppContent's default slot needs to be re-rendered or needs to adjust its layout/size.
Concrete use case: GpxPod displays a Maplibre map that:
* reacts if the window is resized :tada: 
* does not react if its container size changes :disappointed: We need to explicitly tell the map component to resize when this happens.
Suggestion: Emit `resize:list` in NcAppContent when Splitpanes (the 'list' slot) is resized by the user.
What do you think?

Emit event when NcAppContent list pane is resized

---

styleguide.config.js
styleguide/global.requires.js

https://nextcloud.com/wp-content/themes/next/assets/img/common/nextcloud-square-logo.png is 404 since the website redesign.

fix(styleguide): Fix URL replacement to not be 404

---

src/components/NcActions/NcActions.vue
src/components/NcAvatar/NcAvatar.vue

This PR migrates the `NcAvatar` component from using the deprecated `NcPopoverMenu` to `NcActions`.
|-|-|
| ![Screenshot 2023-04-29 at 13-06-41 Tasks - Nextcloud](https://user-images.githubusercontent.com/2496460/235299601-a3822697-3a39-4dac-b9b4-d0731b03f8ee.png) | ![Screenshot 2023-04-29 at 13-09-07 Tasks - Nextcloud](https://user-images.githubusercontent.com/2496460/235299604-4bbfd33d-6ce0-410b-96b4-f5f0f13f9511.png) |
Closes #1683, closes #1762

Use `NcActions` component for `NcAvatar`

---

src/components/NcListItem/NcListItem.vue

Because
https://github.com/nextcloud/nextcloud-vue/blob/14e2c5bd0593cf87568c92acc01f898b55b8fe7f/src/components/NcListItem/NcListItem.vue#L710-L717

Fix NcListItem wrong bold class

---

src/components/NcRichText/NcReferencePicker/NcReferencePickerModal.vue
src/components/NcRichText/NcReferencePicker/customPickerElements.js

Design review outcome: Some custom picker components don't look good in a "large" `NcModal`.
This allows to pass the desired modal size when registering a custom picker component.
This size is then used by `NcReferencePickerModal`.

Allow setting modal size when registering a custom picker component

---

src/components/NcSelect/NcSelect.vue

Before | After
---|---
Background is not our background color and therefor also used in dark mode | background is our color variable so perfectly fine in dark mode

fix(NcSelect): Fix disabled state of NcSelect with dark mode

---

src/mixins/clickOutsideOptions/index.js

This removes the deprecated `excludeClickOutsideClasses` from the `clickOutsideOptions` mixin.

Remove excludeClickOutsideClasses from clickOutsideOptions

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud/nextcloud-vue/compare/v7.11.3...v7.11.4)
- feat\(NcActions\): Improve readability of action menu entries [\#4049](https://github.com/nextcloud/nextcloud-vue/pull/4049) ([Pytal](https://github.com/Pytal))
- feat\(NcReferencePickerModal\): Allow setting modal size when registering a custom picker component [\#3866](https://github.com/nextcloud/nextcloud-vue/pull/3866) ([julien-nc](https://github.com/julien-nc))
- fix\(NcListItem\): Fix wrong bold class [\#4083](https://github.com/nextcloud/nextcloud-vue/pull/4083) ([julien-nc](https://github.com/julien-nc))
- fix\(NcSelect\): Fix disabled state of NcSelect with dark mode [\#4079](https://github.com/nextcloud/nextcloud-vue/pull/4079) ([nickvergessen](https://github.com/nickvergessen))
- …

chore(release): Bump version to 7.11.4

---

src/components/NcSettingsSection/NcSettingsSection.vue

open external documentation in new window; the link should not pass any referrer information to the linked page, and should not be followed by search engine bots for the purpose of indexing

target=_blank in NcSettingsSection.vue

---

src/components/NcAppNavigationItem/NcAppNavigationIconCollapsible.vue
src/components/NcAppNavigationItem/NcAppNavigationItem.vue

* Resolves:  [#38155](https://github.com/nextcloud/server/issues/38155)
(from @Clementine46)
**/!\ Testing is welcome in order to make sure it's not doing side effects elsewhere in the UI.**
[before.webm](https://github.com/nextcloud/nextcloud-vue/assets/33763786/653d4208-0dd7-4d4f-a32c-0177ce6988e3)
[after.webm](https://github.com/nextcloud/nextcloud-vue/assets/33763786/d5a919ca-28ce-49ec-9106-28dbccf317e6)

Files : Left panel dropdown improvement for NC 26

---

src/components/NcAppSidebar/NcAppSidebarTabs.vue
src/components/NcAppSidebarTab/NcAppSidebarTab.vue

Partial backport of https://github.com/nextcloud/nextcloud-vue/pull/4111
Second problem is not relevant to `stable7` and cannot be backported.

NcAppSidebarTabs: fix rendering tabs with CSS icon in `OCA.Files.Sidebar`

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud/nextcloud-vue/compare/v7.11.4...v7.11.5)
- fix\(NcAppSidebarTabs\): Fix rendering tabs with CSS icon in OCA.Files.Sidebar [\#4112](https://github.com/nextcloud/nextcloud-vue/pull/4112) ([ShGKme](https://github.com/ShGKme))
- fix\(NcAppNavigationItem\): Left panel dropdown improvement [\#4105](https://github.com/nextcloud/nextcloud-vue/pull/4105) ([Jerome-Herbinet](https://github.com/Jerome-Herbinet))
- fix\(NcSettingsSection\): Add target blank and no ref info [\#4100](https://github.com/nextcloud/nextcloud-vue/pull/4100) ([Rello](https://github.com/Rello))
- fix: Use the color-primary-element* variables in components [\#4098](https://github.com/nextcloud/nextcloud-vue/pull/4098) ([szaimon](https://github.com/szaimon))

Release v7.11.5

---

src/components/NcRelatedResourcesPanel/NcRelatedResourcesPanel.vue
src/components/NcRelatedResourcesPanel/NcResource.vue

Since https://github.com/nextcloud/nextcloud-vue/pull/3236 the `subtitle` and `tooltip` prop and the `tooltip` directive of `NcResource` are unused. This PR removes them completely now.

Remove unused props and directives of NcResource

---

src/components/NcAppSidebar/NcAppSidebarTabs.vue
src/components/NcAppSidebarTab/NcAppSidebarTab.vue

This PR resolves two different problems in `NcSidebarTab` with CSS icon. I combined them together into 1 PR because they both required to be fixed to resolve the problem.
Fixes: https://github.com/nextcloud/server/issues/38229
Regression of: https://github.com/nextcloud/nextcloud-vue/pull/3891
The icon is rendered by `NcAppSidebarTab.renderIcon()` in `NcAppSidebarTabs`. It seems to me when it is used with `OCA.Files.Sidebar` (and maybe `LegacyView`), `Tabs` and `Tab` components are rendered by different Vue copies on the page (on my instance [24 different copies of Vue are bundled](https://github.com/nextcloud/server/assets/25978914/8177014c-cfe6-453c-8b80-937168c204ce)). 
As a result, when `NcAppSidebarTab.renderIcon()` is called in `NcAppSidebarTabs`'s rendering, it doesn't know about …

NcAppSidebar: fix tabs with css icon

---

src/components/NcRelatedResourcesPanel/NcResource.vue

Before | After
--- | ---
Alignment changed after https://github.com/nextcloud/nextcloud-vue/pull/3936

fix(NcResource): Alignment

---

l10n/messages.pot
src/components/NcAppNavigationSettings/NcAppNavigationSettings.vue

Mark settings button that triggers the expand/collaps of the side nav settings with aria-expanded attribute to improve accesibility.
Resolves : https://github.com/nextcloud/server/issues/37136

Add aria-expanded to settings accordion button

---

src/components/NcAppSidebar/NcAppSidebarTabs.vue
src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue

* Resolves: https://github.com/nextcloud/nextcloud-vue/pull/4064#issuecomment-1538775180
For button style:
Removed some leftover margins which caused the icons slot to be not properly centered.
Also fixed the icon for vertically aligned buttons to be on the same line as the label text.
before | after
---|---

fix(NcCheckboxRadioSwitch): Align icon slot properly

---

src/components/NcInputField/NcInputField.vue
src/components/NcPasswordField/NcPasswordField.vue
src/components/NcRichContenteditable/NcRichContenteditable.vue
src/components/NcTextField/NcTextField.vue

`NcInputField`, `NcTextField`, and `NcPassowrdField` are wrappers on native `input` proxying native attributes and events. But native `HtmlInputElement` also has public methods. At least 2 of them are commonly used: [focus](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus) and [select](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/select).
Currently, it is possible to use them only by DOM selectors or long path throw formally internal properties by `$refs` (they are not part of publicly documented API).
This PR:
- Adds `focus` and `select` public methods to all `Nc*Field` with documentation
- Adds `focus` public method to `NcRichContentEditable` with documentation
Before 😭                                                  | After 😸 …

Input Fields and RichContenteditable: add focus and select methods

---

src/components/NcNoteCard/NcNoteCard.vue

This is a proposal for #4020 and linked to https://github.com/nextcloud/server/pull/37953
I am net in any way experienced with this, so feel free to point out any errors. I am also not set on the colors, it's just what felt kinda right (but again, I am not a frontend dev)

Add info NoteCard

---

src/components/NcAppNavigation/NcAppNavigation.vue

Padding was only applicable to the list, but should apply to the footer too.
---|---

Fix alignment of nav contents

---

src/components/NcEmptyContent/NcEmptyContent.vue

* Follow up on #3791
Like the `title` this allows to override the default behavior of the description by providing a slot for it.
This way you could pass in formatted content (e.g. using emphasis / strong emphasis ...).
Note: Maybe move the slot inside the paragraph element?

feat: Add slot for description of `NcEmptyContent`

---

src/components/NcAppNavigationItem/NcAppNavigationIconCollapsible.vue
src/components/NcAppNavigationItem/NcAppNavigationItem.vue

Fix https://github.com/nextcloud/nextcloud-vue/pull/4103#issuecomment-1551128985

fix toggle overlapping other stuff

---

styleguide.config.js

Problem: currently all sections are uncollapsed by default which makes each page very long and you cannot filter easily with your eyes without having to scroll a lot. Solution: collapse all sections by default which allows for easier filtering and scrolling. Then you can still view the sections that you are interested in by clicking the buttons.
One example:
|---|---|
| ![nextcloud-vue-components netlify app_](https://github.com/nextcloud/nextcloud-vue/assets/42591237/a9fbced9-7110-4c54-abc1-93326061659b) |  ![deploy-preview-4152--nextcloud-vue-components netlify app_](https://github.com/nextcloud/nextcloud-vue/assets/42591237/092e97e7-ed65-4a14-84a9-34ab22f345d7) |

collapse sections by default to make the styleguide a bit lucid

---

src/components/NcCounterBubble/NcCounterBubble.vue

When choosing e.g. black as primary color in dark mode:
|---|---|
| ![image](https://github.com/nextcloud/nextcloud-vue/assets/42591237/e9492360-4014-4be0-8fd3-44f8e2e2abca) | ![image](https://github.com/nextcloud/nextcloud-vue/assets/42591237/0c72f1c7-bfbb-4860-9018-5e42dfee4747) |

fix visibility of default counterbubble

---

src/components/NcActions/NcActions.vue

Automatically remove attributes that are incompatible with accessible navigation when all action links are website navigation links
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/menu_role
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-haspopup
- https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/examples/disclosure-navigation/

enh(NcActions): Navigation link actions

---

src/components/NcAppNavigationItem/NcAppNavigationItem.vue
src/components/NcAppNavigationNewItem/NcAppNavigationNewItem.vue

`NcAppNavigationNewItem` performs an on-page action and so the correct sematic tag is button.
* Fix https://github.com/nextcloud/nextcloud-vue/issues/4108
---|---

Implement app menu new-item action as button not link

---

CHANGELOG.md
package-lock.json
package.json

Prepare new beta for version 8 (for testing purpose).
I also updated the changelog to reflect all changes up to current master ad9e43cce49e7df19ec07b72781bf985302decec

Prepare new beta: `v8.0.0-beta.1`

---

src/components/NcAppNavigation/NcAppNavigation.vue

When the navigation is closed, add "inert" attribute to prevent tabbing
into the sidebar.
Note: I didn't test this but tied the attribute to the `open` value. I verified in the Talk app that the `open` attribute is properly updated when swiping, resizing the window, etc. So setting `inert` under the same conditions should work.

Prevent tabbing into closed navigation

---

src/components/NcAppContent/NcAppContent.vue

We already use `display: flex` for app-content-list if not on mobile, see `core/css/apps.scss` in server repository.
This is necessary for using `position: sticky` and `bottom: 0` inside `app-content-list`.

Use `display: flex` in app-content-list on mobile as well

---

src/components/NcRichText/NcReferencePicker/NcProviderList.vue

Since the padding on the modal itself was removed it should still be added to the provider list when opening the picker with `getLinkWithPicker` 
---|---

fix(NcProviderList): Add padding around provider list

---

src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue

Improve accesibility by making focus indicator visible.
Resolves : https://github.com/nextcloud/photos/issues/1671
---|---

Add focus-visible style for NcCheckboxRadioSwitch

---

src/components/NcSelect/NcSelect.vue

- Fix https://github.com/nextcloud/nextcloud-vue/issues/4119
---|---

fix(NcSelect): Hide clear and deselect when disabled

---

src/components/NcSelect/NcSelect.vue

- Regression from https://github.com/nextcloud/nextcloud-vue/pull/4079
- Fix styles with placement set to top and hover color when disabled
---|---

fix(NcSelect): Styles on state change

---

src/components/NcSelect/NcSelect.vue

- Regression from https://github.com/nextcloud/nextcloud-vue/pull/4106
- Adapt to new `NcListItemIcon` API changes
---|---

fix(NcSelect): Adapt to NcListItemIcon

---

src/components/NcAppNavigation/NcAppNavigation.vue
src/components/NcModal/NcModal.vue

```
[Vue warn]: Error in beforeDestroy hook: "TypeError: this.mc is null"
```
This code was used by hammerJS but is not required anymore since we migrated to vueuse.

fix: Remove leftovers of hammerJS

---

src/components/NcInputField/NcInputField.vue

Allow custom aria-describedby in NcInputField

Append custom aria-describedby to input field

---

src/components/NcModal/NcModal.vue

* Fix #2405
As it sets the background color it should also set the foreground color as it can not assume the default will match the contrast criteria.
---|---

Fix NcModal does set the background color but not the text color

---

src/components/NcAppNavigationCaption/NcAppNavigationCaption.vue

NcAppNavigationCaption: Align actions with other navigation action

---

package-lock.json
package.json

* Reverts: https://github.com/nextcloud/nextcloud-vue/pull/4178
`Intl.Segmenter` is not supported by Firefox (113) and only planned for later 2023, there is also no easy polyfill available. Blocked by Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=1423593
You can test this by opening the documentation on master using firefox, it wont load.

fix: Revert updating `string-length` to v6

---

src/components/NcSelect/NcSelect.vue

- Lighten the disabled background and text colors slightly to distinguish the disabled state from the regular state
---|---

fix(NcSelect): Disabled colors

---

README.md

Reference the stable builds of the documentation in the README file.
* Fix https://github.com/nextcloud/nextcloud-vue/issues/4177

docs: Add stable documentation links to the readme

---

src/components/NcProgressBar/NcProgressBar.vue

Close https://github.com/nextcloud/nextcloud-vue/issues/4199
| Browser | Before | After |
|---|---|---|
| Chromium | ![image](https://github.com/nextcloud/nextcloud-vue/assets/42591237/10d857df-98f8-4b3b-9590-d1c115ae2650) | ![image](https://github.com/nextcloud/nextcloud-vue/assets/42591237/e40a703d-1782-4d5b-a0b4-e48e0c645949) |
| Firefox | ![image](https://github.com/nextcloud/nextcloud-vue/assets/42591237/d96d6591-3334-45ce-81ea-a232b28437cd) | ![image](https://github.com/nextcloud/nextcloud-vue/assets/42591237/ea7ba5ad-3dbc-4344-b32d-c26878875c78) |

fix progress-bar on chromium browsers

---

src/components/NcSettingsSelectGroup/NcSettingsSelectGroup.vue
styleguide/global.requires.js

Adding documentation, move to NcSelect and drop unused property
* Moved from deprecated `NcMultiselect` to `NcSelect` (Ref: https://github.com/nextcloud/nextcloud-vue/issues/3743 )
* Debounce search API calls (200ms) to prevent spamming the API while typing
* Cache empty search groups (the ones loaded when the search dropdown is opened) for current page
* Load display names of initial groups (those which were given through the `value` property).
* Removed unused `hint` property
* Added `placeholder` property and added a hidden label element
The `label` property is still used for the placeholder for backwards compatibility.
* Added documentation for the events and added an example (Add axios mocking so we can emulate querying for groups on the netlify docs)

Improve `NcSettingsSelectGroup` - Convert to `NcSelect`

---

src/components/NcRichText/NcRichText.vue

The style part is written as scss but the language attribute was missing.

Fix missing language for scss style

---

src/components/NcRichText/NcReferencePicker/NcRawLinkInput.vue

The surrounding Smart Picker modal does not have padding anymore.

Fix padding in the 'any link' preview component (smart picker)

---

l10n/messages.pot
src/components/NcRichText/NcReferencePicker/NcProviderList.vue
src/components/NcRichText/NcReferencePicker/NcSearch.vue

refs #3743 
Switch to `NcSelect` in `NcProviderList` and `NcSearch` from `NcRichText`.
I couldn't figure out a way to avoid an issue with NcSearch. When selecting a "Load more..." item, even if we actually select the item while searching for more results, the selection jumps to the top and then back to the "more" item.
Not so pretty...but not so bad.
https://github.com/nextcloud/nextcloud-vue/assets/11291457/90b2c16c-3789-4a07-af7d-5e265d01711c

Use NcSelect in NcRichtext

---

package-lock.json
package.json
src/components/NcSelect/NcSelect.vue

- Bump to https://github.com/nextcloud-deps/vue-select/releases/tag/v3.23.0
- Document new prop
- Fix styles

chore(deps): Bump @nextcloud/vue-select from 3.22.2 to 3.23.0

---

package-lock.json
package.json
src/components/NcModal/NcModal.vue

Fix #4265 
Sometimes the content is empty or not ready yet.
> `fallbackFocus` {HTMLElement | SVGElement | string | () => HTMLElement | SVGElement | string}: By default, an error will be thrown if the focus trap contains no elements in its tab order. With this option you can specify a fallback element to programmatically receive focus if no other tabbable elements are found. For example, you may want a popover's <div> to receive focus if the popover's content includes no tabbable elements. Make sure the fallback element has a negative tabindex so it can be programmatically focused. The option value can be a DOM node, a selector string (which will be passed to document.querySelector() to find the DOM node), or a function that returns any of these.

fix(NcModal): fix focus-trap fallback

---

l10n/messages.pot
src/components/NcDatetimePicker/NcDatetimePicker.vue

* Resolves #2701
Currently not all strings are extracted (and can not be extracted).
This happens because `this.t(...)` does not work just `t(...)` work for extracting strings.

NcDatetimePicker: Make sure all l10n strings are extracted

---

package-lock.json
package.json
src/components/NcModal/NcModal.vue

Backport of https://github.com/nextcloud/nextcloud-vue/pull/4266

[stable7] fix(NcModal): fix focus-trap fallback

---

docs/index.md
package-lock.json
package.json
styleguide.config.js

* Fix #3374
Adds links to documentation for older versions on the styleguide, also fixes the dead badges on the index of the styleguide page (we do not use travis anymore).

fix(docs): Add links to documentation for older versions

---

build/extract-l10n.js
l10n/messages.pot
package-lock.json
package.json

* Resolves #2062 
There are still some (two at this moment) string which can not be extracted because they are used within properties like `:aria-label="t(...)"`.
To resolve this we need to use the HTML extractor on vue SFC files.
The huge diff is from applying our code style rules (tab vs spaces).
*BTW I tried `gettext-extractor-vue` written by the gitlab team, but that does not work as it converts all `t()` calls to `_t()` or different (compile the SFC), so the extractor does not know which strings to extract.*

fix: Ensure `extract-l10n` extracts strings from properties

---

CHANGELOG.md
src/components/NcRichContenteditable/NcAutoCompleteResult.vue
src/components/NcRichContenteditable/NcRichContenteditable.vue
src/mixins/richEditor/index.js
tests/unit/mixins/richEditor.spec.js

* Resolves #1825
* First commit is a follow up on #4106 
The first commit solves some issues / leftovers where the property was renamed but the example code was not changed.
The second commit solves an issues were mentioning users with `@` in there userid was not possible (`@` was removed).
Also added a note about the property renaming on the changelog previously only `name` -> `title` was mentioned and not `label` -> `title`.
New tests included.
---|---

Fix: Leftovers of `name` prop migration + fix `@` in user ids (richEditor)

---

package-lock.json
package.json

* Add focus-visible style for NcCheckboxRadioSwitch by @Fenn-CS in https://github.com/nextcloud/nextcloud-vue/pull/4176
* adjust border-radius of ncpopover by @szaimen in https://github.com/nextcloud/nextcloud-vue/pull/4237
* Append custom aria-describedby to input field by @Pytal in https://github.com/nextcloud/nextcloud-vue/pull/4225
* Automated styling update from server by @nextcloud-command in https://github.com/nextcloud/nextcloud-vue/pull/4186
* chore: update node engines to next LTS by @nextcloud-command in https://github.com/nextcloud/nextcloud-vue/pull/4244
* chore: update workflows from templates by @nextcloud-command in https://github.com/nextcloud/nextcloud-vue/pull/4172
* docs: Add stable documentation links to the readme by @juliushaertl in …

8.0.0-beta.2

---

src/components/NcActionLink/NcActionLink.vue
src/components/NcButton/NcButton.vue

* Fix #4262 
To reproduce:
* Link vue-lib to Viewer app
* Left only Download button (NcActionLink) in `Viewer.vue` file https://github.com/nextcloud/viewer/blob/master/src/views/Viewer.vue#L95 
* Compile JS code
* Open NC instance
* Create a text file in Talk app chat
* Try to download it
| 🏡 After
|---| 
| ![image](https://github.com/nextcloud/nextcloud-vue/assets/93392545/9018a6ae-c701-4b60-ba56-ddd6fb5cba04) |

`NcActionLink` - provide download attributes for single action button in `NcAction`

---

src/components/NcRichContenteditable/NcRichContenteditable.vue

All component's event handlers were set as native event handlers with by `v-on="$listeners"`.
It allows using event handlers without the `.native` modifier for native events.
But the component also raised custom events manually by `$emit`, including corresponding native events. As a result, it triggers such handlers twice.
Related issue: https://github.com/nextcloud/spreed/issues/9004
1. Set paste event handler:
```html
<NcRichContenteditable @paste="handler" />
```
2. Paste anything
`handler` is called twice:
- Once `handler` will be called by `$emit('paste')`
- One more time, `handler` will be called by `v-on="$listeners"`.
`handler` is called once.
In this PR with the `v-on="listeners"` directive only proxied native event handlers are set, without custom events.
There is a simple …

Remove doubling proxied event handlers in `NcRichContenteditable`

---

src/components/NcDashboardWidgetItem/NcDashboardWidgetItem.vue

* Fix https://github.com/nextcloud/server/issues/36978
* Fix https://github.com/nextcloud/server/issues/39064
| ![image](https://github.com/nextcloud/activity/assets/6078378/2aca6e5f-6b77-46b2-8348-0056854e7529) | ![Screenshot from 2023-06-29 11-04-42](https://github.com/nextcloud/activity/assets/6078378/e4c77bd2-88fb-4802-9f51-c850d9047cbb)
| ![user status](https://github.com/nextcloud/server/assets/6078378/ac67292a-28cf-455a-b337-82398c6c465d) | ![user status2](https://github.com/nextcloud/server/assets/6078378/005b3581-6808-4b99-86a2-6e26bf999388)

Replace `<p>` with `<span>` to ignore unneeded margin below

---

jest.config.js
src/components/NcRichContenteditable/NcRichContenteditable.vue
tests/unit/components/NcRichContenteditable/NcRichContenteditable.spec.js

Confirm entering during composition session in IME on Mac OSX is considered by `<NcRichContenteditable>` as <kbd>Enter</kbd> and emits `submit` during the input.
Reproducible on Safari and Chromium on Mac.
Not reproducible on Linux or Windows.
* Related issues: 
- https://github.com/nextcloud/spreed/issues/9145
- https://github.com/nextcloud/spreed/issues/3268
---|---

NcRichContenteditable: fix IME support on Mac OSX

---

src/components/NcButton/NcButton.vue

Same as https://github.com/nextcloud/nextcloud-vue/pull/4319 (but for master)

Set double outline to buttons in focus state

---

jest.config.js
package-lock.json
package.json
src/components/NcRichContenteditable/NcRichContenteditable.vue
tests/unit/components/NcRichContenteditable/NcRichContenteditable.spec.js

Manual backport of https://github.com/nextcloud/nextcloud-vue/pull/4294
This backport includes backporting of https://github.com/nextcloud/nextcloud-vue/pull/4283/commits/730dcb7e2d1bf771c108c592515fdfbd81ea2d12

[stable7] NcRichContenteditable: fix IME support on Mac OSX

---

src/components/NcSettingsSelectGroup/NcSettingsSelectGroup.vue

* Fixes the error `this.getValueObject is not a function`
The value object is a computed property, so do not use parenthesis. The name was quite misleading and only used for the `inputValue` so just merged it.

[stable7] fix(NcSettingsSelectGroup): Fix `this.getValueObject is not a function`

---

cypress/support/component.ts

Fixes this error thrown when running cypress:
```
ERROR in nextcloud-vue/cypress/support/component.ts
./cypress/support/component.ts 33:21-28
[tsl] ERROR in nextcloud-vue/cypress/support/component.ts(33,22)
TS2345: Argument of type '"mount"' is not assignable to parameter of type 'keyof Chainable<any>'.
```

fix(cypress): Add declaration for `mount` command

---

package-lock.json
package.json
styleguide.config.js
vite.config.mts
webpack.config.js

* Follow up on #4276 
This uses vite also for the CommonJS module entry point (index).
* Much faster build time (18% faster)¹
* Much smaller output asset: 400kB (vite) vs 1'020kB (webpack)
I tested it with the *text* app, looks good, the js assets of the text app will shrink in total by 254kB with the vite version.
¹ Run time on my system (using `time npm run build`):
```
before:  npm run build  131,93s user 7,69s system 29,180 total
after:   npm run build  117,00s user 6,73s system 23,918 total
```

Migrate building CommonJS module entrypoint to vite

---

package.json

Currently cypress reports a warning because the glob pattern in the update script is not escaped, this simply fixes the warning. No logic / functional changes.

fix(cypress): Escape glob pattern in cypress script to remove warning

---

src/components/NcListItem/NcListItem.vue

* Fix #3889 
* I've noticed, that we may render two NcActions component in one NcListItem, but hide one of them with `display: none`
* Because of that, and because of behaviour of `handleTab()` method in NcListItem, we couldn't focus one of the two available action menus
* Not sure, that behaviour now is align with a11y requirements, but at least actions are accessible
🏚️ Before
https://github.com/nextcloud/nextcloud-vue/assets/93392545/8ea06a24-f030-438a-b0c7-1bdb02e23a53
🏡 After
https://github.com/nextcloud/nextcloud-vue/assets/93392545/e54af34f-64d2-4b15-ae18-4c8fb5072b08

fix(NcListItem) - define a single place for NcActions to render

---

l10n/messages.pot
src/components/NcEmojiPicker/NcEmojiPicker.vue

In collectives pages optionally have an emoji set. Once this is set there is currently no way to remove it.
Enhance the emoji picker to show the currently selected emoji and enable unselecting it to clear the previous selection.
See also:
* https://github.com/nextcloud/collectives/issues/422
* https://github.com/serebrov/emoji-mart-vue/issues/253#issuecomment-1585978632
[Bildschirmaufzeichnung vom 31.07.2023, 20:40:58.webm](https://github.com/nextcloud-libraries/nextcloud-vue/assets/97337118/52743678-8512-4f2d-9e27-4d4e9cf931a8)

enh(emoji-picker): allow unselecting set emoji
